### PR TITLE
Update pt-BR translation of portal.json

### PR DESCRIPTION
**Pull request by Lekler**
Update pt-BR translation of portal.json 

Following commit #21042, the following updates were made:

- Filled in 6 missing translations and made style corrections to existing translations to improve clarity and consistency.

### CODE REVIEW

**Comment by cathysarisky** [comment]
This appears to be a duplicate of https://github.com/TryGhost/Ghost/pull/21100  ?

**Comment by Lekler** [comment]
@cathysarisky This pull adds translations to fields you added in #21042 in portal.json. 
The #21100 adds translations to the search.json file you created in #21055.

The pull requests were made on different days.

**Comment by cathysarisky** [comment]
> @cathysarisky This pull adds translations to fields you added in #21042 in portal.json. The #21100 adds translations to the search.json file you created in #21055.
> 
> The pull requests were made on different days.

Sorry, @Lekler , I may have looked at too many pull requests today, and I guess I was confused! :)  Thanks for all your contributions!  Obrigado!

**Review by cathysarisky — APPROVED** [review]
Looks good to me and my AI assistant.  Thanks so much for your work on this!

**Pull request merged**
