### PR TITLE
Implementing multiple changes in API posts.browse method

### LINKED ISSUE #5152: API: Add `featured` filter option to posts.browse
Currently the `api.posts.browse` endpoint takes the [following options](https://github.com/TryGhost/Ghost/blob/master/core/server/api/posts.js#L48):

> page, limit, status, staticPages, tag

There is an open issue to swap [`page` for `offset`](https://github.com/TryGhost/Ghost/issues/5093)

And another issue to swap [`staticPages` for `page`](https://github.com/TryGhost/Ghost/issues/5151) as well as add generally better support for querying pages.

It would also be good to be able to filter posts by whether or not they are featured: 

`api.posts.browse({featured: true})` or `api.posts.browse({featured: false})` 

Making this work involves adding this as an allowed option in the model.

### PR DESCRIPTION
**Pull request by edsadr**
```
Closes #5152, #5093, #5151

- Adds `featured` filter option to posts.browse method modifying the model to take it too
- Implements offset pagination method to posts.browse method modifying the model to work with it too but still supporting the `page` parameter
- Removes `staticPages` parameter in options filter to allow using the `page` parameter with options `all` `true` or `false
```

### CODE REVIEW

**Comment by ErisDS** [comment]
Moving this comment here as it's relevant to the PR more than the issue:

@edsadr said:

> @ErisDS here is what I would like to propose, with #5093 you are requesting to stop using page with an integer to get a page, but I implemented to support the current format and also to support the offset/limit format pager, however if page is a boolean then it will get just static pages replacing staticPages parameter.

> I wanted to do it this way as I think is a way more flexible and will also support the new offset limit approach ... if you guys don't like this then I will change to any other approach you decide =)

A parameter for the API really needs to have one meaning / job. The problem with mixing up what page does depending on type is not only that it's confusing because it's not clear what the `page` parameter means (trying to explain this in [documentation](https://github.com/TryGhost/Ghost/pull/5185/files#diff-bdcddc304f43d5639517a20c8b5d6308R48) is way too difficult) but also because of JavaScripts tendency to use 0 and 1 as booleans.

**Comment by edsadr** [comment]
Ok so.. are you willing to deprecate the old use for page parameter for good? I did this thinking in current Ghost themes or apps implementations using this pattern, this change will break them all... just confirm this and I will move to this approach of just using limit and offset for paging

**Comment by ErisDS** [comment]
The API is not public or considered stable yet, anyone depending on it should be doing so in full knowledge that changes are expected.

It's fab that you're working on a couple of different issues, we definitely need people working on getting the API more polished, however it would be really helpful if you could do each issue separately. For example this discussion about `page` is preventing the feature stuff being ready to merge, and also having multiple changes lumped together makes it harder to test and verify each change is complete. If you wouldn't mind splitting them up, that'd be fantastic :+1:

**Comment by edsadr** [comment]
Ok no problem... but as I see it the `page` parameter and the `offset` and `limit` are pretty close and  related, so not really sure if you would to split all those then... I am working on it tonight... please try to let me know before so I can speed up things get this merged and move to another fix :)

**Comment by ErisDS** [comment]
Each issue is a separate piece of work and ought to be treated that way in my opinion.

**Comment by ErisDS** [comment]
Hey @edsadr if you have a minute would love to hear how you're getting on with this

**Pull request closed without merging**
