### PR TITLE
experiment 

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ErisDS** [comment]
Master is merged into stable when we release.

This is the 3rd one of these PRs we've had recently - is there a reason for this that I'm not aware of?

**Comment by fmarier** [comment]
> This is the 3rd one of these PRs we've had recently - is there a reason for this that I'm not aware of?

I've also received a number of these in Lightbeam. I think it's because of https://hacktoberfest.digitalocean.com/

**Comment by DanielTamkin** [comment]
Sucks to see this, Kinda defeats the purpose of "Hacktoberfest" if people are just blindly making pull requests :unamused:

**Comment by joel-delong** [comment]
Honestly had never made a pull request on an open-source project before. I was trying to figure out what I was doing.

Chill out and stop emailing me.

**Comment by ErisDS** [comment]
No one is emailing you - these are comments on the pull request you created. I understand that you didn't realise what you were doing, but the effect is that you started a conversation with ~960 people. If you don't want email notifications, then you will need to unsubscribe :wink:

**Pull request closed without merging**
