### PR TITLE
Remove unnecessary role attributes from main element

### PR DESCRIPTION
**Pull request by zce**
Source: https://validator.w3.org/nu/#textarea

- [ ] There's a clear use-case for this code change
- [ ] Commit message has a short title & references relevant issues
- [x] The build will pass (run `npm test`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by kirrg001** [comment]
@kevinansfield You are assigned and PR is almost 3 month old. Could you pls review, reassign or close? Thanks 🙂

**Comment by kirrg001** [comment]
@kevinansfield

**Comment by kevinansfield** [comment]
In principle this is fine, the main issue I can see is the possibility of it being breaking change because the `role` attribute can be used in CSS selectors and JS.

I've had a quick look through some of the more prominent open source themes and couldn't see any problems the change would cause so I guess this is fine to go but probably deserves a mention on the themes changelog.

**Comment by allouis** [comment]
@kevinansfield What do you reckon about this - shall we merge?

**Comment by kirrg001** [comment]
> being breaking change because the role attribute can be used in CSS selectors and JS.

Hmm yeah, maybe let's track this change for Ghost 3.0? I am not sure it's a good idea to just remove it now.

**Pull request closed without merging**
