### PR TITLE
[WIP] No more CodeMirror

### LINKED ISSUE #4368: Drop CodeMirror from the Editor
With reference to the [Split Screen Editor Epic (#1294)](https://github.com/TryGhost/Ghost/issues/1294)

--- 

The Ghost editor undeniably needs some :heart:. No matter how you consider what the editor might look like in the future, there is one underlying problem - to ship improvements like spellcheck, we need to build a completely custom editor, that's an enormous undertaking, and it would detract from all the other features we want to ship :-1:.

That is, unless we drop formatting/syntax highlighting from the left side of the editor :boom: 

**yep**... I'm talking about dropping CodeMirror in favour of a plain textarea.

CodeMirror currently has two main jobs: 1) it formats/syntax highlights the markdown and 2) provides an API for interacting with the entered text. However, what it does under the bonnet is generate a completely custom representation of the document which is neither markdown or HTML. This breaks the [browser spellcheck](https://github.com/TryGhost/Ghost/issues/1240), doesn't work reliably [on mobile/touch](https://github.com/TryGhost/Ghost/issues/960) (which meant we had to remove it from mobile/touch devices), and the way it interprets markdown is quite different to our HTML conversion, which causes [weird](https://github.com/TryGhost/Ghost/issues/959) [bugs](https://github.com/TryGhost/Ghost/issues/1909) and adds complexity.

If we strip out CodeMirror, we will lose formatting, but what we get instead will be an editor with working **spellcheck**, working **mobile uploads** and significantly reduced complexity: because we only have two document representations - markdown and HTML, and we are in control of them both. This means we can focus on making the conversion between them better (i.e. adding advanced markdown features).

In the future, we'll be able to bring back formatting if we want it using contenteditable, but in the meantime we can more easily focus on the features we want to bring to the editor, the markdown we want to support, and creating our own way of modelling documents - because the editor is so significantly less complicated.

I've been working on a prototype testing out how to interact with selections in the textarea to make sure that image uploads will still work (on ALL devices) etc and to me this feels like taking back control, and I'm REALLY, _**ridiculously**_ excited about it.

### PR DESCRIPTION
**Pull request by ErisDS**
:boom: :fireworks: :boom: :tada: :boom:

This PR needs SIGNIFICANT cross browser and device testing
## Please help test this PR!!

There are two easy ways to do this - the first is to set yourself up so that you're able to quickly and easily test [any Ghost PR with these instructions](http://dev.ghost.org/easy-git-pr-test/).

<a name="demo"></a>
### Live Demo

Alternatively, you can visit http://editordemo.ghost.io and login with the following credentials: 
email: demo@ghost.org
pass: test1234

Hopefully I don't have to ask that people keep the demo content clean and respectful :) I will login and clear it out on a regular basis. 

---

This PR contains a complete reimplementation of the existing functionality we had with codemirror with a few exceptions:
- the new, simpler image upload code no longer uses markers to map between the left and right panes, and instead does a quick lookup, which should work equally well on all devices
- it may be necessary to change the image upload code to make sure that the event which re-enables the textarea is fired after the processing is complete, rather than after the image upload is complete (this is a maybe TODO)
- now that we don't have awkward markers to keep track of, the image upload regex can be updated in both the `ghostimagepreview.js` and `image-manager.js` to be a much more powerful regex which properly supports [image titles](https://github.com/TryGhost/Ghost/issues/985) (this is a TODO)
- the shortcodes have been reimplemented to be slightly smarter about where the cursor goes after, and whether or not they require a newline (more to be done here to make the list shortcut better) 
- the textarea does not capture TAB. This can be added, but I'm not 100% whether it's a blessing or a curse - so lets do some testing without before adding it (this is a maybe TODO)
- [x] Finish up link and image shortcuts
- [x] Get the editor scrolling as you type
- [ ] Improve the image regex
- [ ] Maybe add TAB handling
- [ ] Maybe change image upload events
- [x] Fix existing tests
- [ ] Add new tests

closes #4368, fixes #1240 (spellcheck) and more
- Drop CodeMirror in favour of a plain text area
- Use rangyinputs to handle selections cross-browser
- Create an API for interacting with the textarea
- Replace marker manager with a much simpler image manager
- Reimplement shortcuts, including some bug fixes
- Rename components include editor-route-base

### CODE REVIEW

**Comment by xori** [comment]
Windows 8.1
Chrome 39 - Flawless
IE 9 fails but 10+, works fine with spellcheck, image uploading works but is buggy. If you drag in a file that isn't a supported picture then drag in a valid picture it didn't work for me, and just shows the loading cat over the background forever (trying to upload with a 32kb jpg for IE11)

**Comment by ErisDS** [comment]
Ghost is only expected to work in the current version, and previous version of major browsers. Therefore IE9 failing is fine ;)

Sorting out the lack of indent is definitely on my radar - not sure what the right solution for it is yet, but I think we probably need something.

**Comment by ErisDS** [comment]
I have rebased this PR against latest master. I've updated the rangyinputs library now that it has been released (this fixes undo/redo on everything except IE) and I've also added `spellcheck="true"` to the editor.

All of these updates have been pushed to the Live demo @ http://editordemo.ghost.io (email: demo@ghost.org, pass: test1234).

There are definitely other improvements to be had: finding a solution for tabs, cleaning up some of the upload events and other things, but the base functionality is here and I think, providing we're happy this is working nicely cross-browser, it would be preferable to get this merged into master ahead of the next release and make any further adjustments as separate PRs.

@PaulAdamDavis rebasing had a lot of conflicts in CSS - it might be worth you going through and checking that I didn't screw it up (I probably did). 

Pending getting the tests passing, a review of the CSS by @PaulAdamDavis and further cross-browser testing of the updated PR, I'm going to take the [WIP] tag off of this :)

**Comment by PaulAdamDavis** [comment]
I've looked over the CSS, tested in Chrome, Safari & Firefox. All the styles are as expected. :+1:

Quick note for those testing in Firefox: It doesn't properly handle padding in textareas. What the Editor does now is as good as it gets. See [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1099204) for more.

**Comment by chevex** [comment]
This fixes the spell check issues right? Is there an ETA on when this will appear in the stable branch?

**Comment by ErisDS** [comment]
I have rebased this against the new ember-cli client structure, and made some improvements. Re-raised as #5031, closing this PR in favour of that one.

**Pull request closed without merging**
