### PR TITLE
Added visible column to products table

### PR DESCRIPTION
**Pull request by allouis**
refs https://github.com/TryGhost/Team/issues/1387

We are moving away from the portal_products setting to instead store
each tiers visiblity on the Tier itself. This column will be used for
that data.

Both of the default Tiers should be visible, but newly created tiers
should not be.

### CODE REVIEW

**Comment by allouis** [comment]
A second migration will handle updating the `visible` column for existing Tiers, based off of the `portal_products` setting.

**Review by matthanley — COMMENTED** [review]
I can see why you've implemented it that way, but having a different default behaviour in the schema vs the model feels like it could be super confusing later on.

Does it make more sense to default to false everywhere, and then flip them back to true in the second migration for each tier currently enabled in the setting?

**Comment by allouis** [comment]
> Does it make more sense to default to false everywhere...

Yes it does :) Will update

**Review by matthanley — APPROVED** [review]
lgtm once the integrity test has been updated 👍🏼

**Review by rshbhgrg — APPROVED** [review]

**Review by daniellockyer — APPROVED** [review]

**Comment by ErisDS** [comment]
Can we _please_ call this column `visibility`? We have a pattern for that, and none for `visible`.

**Pull request merged**
