### PR TITLE
Logout on pass change

### LINKED ISSUE #6384: Should not keep user logged in, if password was changed on his account.
# Ghost should not keep user logged in, if password was changed on his account.
### Issue Summary

When one human changes password for specific user, any other people, who are logged in that user aren't logged out but still logged in and can still do anything.
### Steps to Reproduce (2 humans)
1. One person logs in your website with your account, which is powered by Ghost,
2. You change your password,
3. Another person who has logged in is still there and can do any kind of stuff.

Because of that, I think, ghost needs to log out all people, who are logged in one account, where password was changed, except of the one who changed password.
### Technical details:
- Ghost Version: 0.7.5
- Client OS: Windows 8.1
- Server OS: Ubuntu 15.10, with nginx that adds SSL and some custom error pages, inside Microsoft Azure
- Node Version: 0.10.40
- Browser: Google Chrome Version 48.0.2564.82 m
- Database: SQLite

### PR DESCRIPTION
**Pull request by ramiel**
When the user change the password, every other session belonging to that user is disconnected.
Resolve #6384

### CODE REVIEW

**Comment by acburdine** [comment]
Hey @ramiel, thanks for contributing!

First thing, can you squash your commits (see [here](https://github.com/TryGhost/Ghost/wiki/Git-workflow#clean-up-history)), and then rewrite your commit message to look something more like [this](https://github.com/TryGhost/Ghost/wiki/Git-workflow#commit-messages)?

Second (and this is me being super nitpicky so feel free to ignore it), there's a couple of lines changed that are missing a space after a comma or colon. (I feel like the linter should have flagged it but idk)

Lastly, would it be possible to add tests for this behavior? I see that you pass the headers correctly but didn't see any specific tests :smile: 

I'll test this behavior in a bit and verify it, but on first glance it looks good :+1:

**Comment by sebgie** [comment]
Hey @ramiel,
welcome to Ghost! Thank you for taking on this issue.

It seems a bit overkill to pass around the headers of every request to make this feature work. I would like to suggest to store the `id` of the token on the request during authentication  (https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/auth-strategies.js#L47). This object is then used to create the context object (https://github.com/TryGhost/Ghost/blob/master/core/server/api/index.js#L196). The context object could be modified to also hold the token id to make this feature work. Maybe there are further use cases where the token or its associated client could be used?

It would also be great if you could have a quick look at our [contributing guide](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#pull-requests) for formatting commit messages and squashing commits :).

**Comment by ramiel** [comment]
I was wondering the same thing, if I could have a reference to the token of the current request. Not finding one, I passed all the headers. Ok, just my ignorance on Ghost code. I'll change the code accordingly and make another PR.

**Comment by acburdine** [comment]
You don't need to make another PR necessarily, just add the changes to this one :)

**Comment by ramiel** [comment]
I'd want to write a test but I'm a bit unsure on where you are expecting the test for this behaviour. Probably adding a test in the integration tests is the best...

**Comment by ramiel** [comment]
PS: `disallowTrailingWhitespace` disallow spaces after comma or colon.

**Pull request closed without merging**
