### PR TITLE
Make Ghost compatible with showdown latest

### LINKED ISSUE #2093: Markdown issues with new lines.
Line breaks are not always working. It's hard to describe what is happening, therefore I made a gif. I would expect the formatted (right) being the same as the input (left).

markdown

I narrowed it down and changed a regular expression. I thought I got it working until I did a `grunt validate`. It starts failing at https://github.com/TryGhost/Ghost/blob/master/core/test/unit/client_showdown_int_spec.js. This is rather strange because if I [reconstruct that output manually in JSfiddle](http://jsfiddle.net/F4ZJP/23/), it perfectly matches the provided regular expression.

Take https://github.com/TryGhost/Ghost/blob/master/core/test/unit/client_showdown_int_spec.js#L75 for example. It fails with

```
6) Showdown client side converter should not treat pre blocks with pre-text differently:
   AssertionError: expected '<pre>\nthis is `a\\_test` and this\\_too and finally_this_is\n</pre>  ' to match /^<pre>\nthis is `a\\_test` and this\\_too and finally_this_is\n<\/pre>$/
```

Putting said input line that in my [modified JSFiddle](http://jsfiddle.net/43cNX/1/), the output of _Haunted Markdown_ and _Fixed Haunted Markdown_ is exactly the same. Also the [regular expression}(http://regex101.com/r/yP1gS7) matches.

I hope I didn't write this too complicated.

### LINKED ISSUE #4627: "==" in multiple image url translated to "<mark></mark>"
e.g.

```
"![](http://xxx.com/==20131118/2)\n$$\\x_s$$\nfdsaf\n![](http://xxx.com/==20131119/2)"
```

in markdown which will be translated to 

```
<p><img src="http://xxx.com/<marker>20131118/2" alt="" />
$$\x_s$$
fdsaf <br />
<img src="http://xxx.com/</marker>20131119/2" alt="" /></p>
```

### LINKED ISSUE #5039: Github flavoured Markdown can't handle Github flavoured Markdown
Whenever you place certain markdown inside triple back-tick fences, GFM (both in editor and on front-end) still tries, and fails, to render it.

So far for me it breaks spectacularly when placing the following inside code-fences:
- Images
- Code fences
- Strikethrough text (doesn't work with 4 spaces, either)

---

image

Works fine when 4 spaces used

image

### LINKED ISSUE #5237: Bug: Inline code in link title in footnotes is broken
The following markdown 

``` md
[^1]: [`Something`](http://example.com)
```

renders as this HTML:

``` html
<li class="footnote" id="fn:1"><p>[</p>

<p>undefined](http://example.com) <a href="#fnref:1" title="return to article">↩</a></p></li>
```

Example:

I'm using Ghost v0.6.2

### LINKED ISSUE #5587: inline script in the editor has problems with ==
Put this in the editor (Ghost v0.6.4)

```
<script>
var x = 0;
if ( x === 0 ) {
    alert("yay");
}
</script>
```

then publish.

View the blog post in a web browser.
Would expect an alert box saying 'yay'.
However, we get a javascript error.

Inspecting the rendered HTML/JS code and we see

```
<script>
var x = 0;
if ( x <mark>= 0 ) {
    alert("yay");
}
</script>
```

It looks like some macro replacement magic is taking place, replacing any `==` characters with `<mark>`.

### LINKED ISSUE #5632: Support fenced code block in list.
It would be great if we can do something like this:
- A list item with some code sample
  
  ```
  console.log('hello, world.');
  ```

### LINKED ISSUE #5939: <pre> and <code> replaced within code blocks by {gfm-js-extract-pre-1}
Writing a code block containing the following:

```
<pre>test</pre>

<code>test</code>
```

Will produce:

```
{gfm-js-extract-pre-1}

{gfm-js-extract-pre-2}
```

Screenshot

### LINKED ISSUE #7536: Certain uses of backticks break code block rendering
### Issue Summary

When backticks are used in certain ways it can break code block rendering
### Steps to Reproduce
1. Create a new post
2. Add the following content:
   
   ``````
   `` code+` ``
   
   ```second code block```
   
   `third code block`
   ``````
3. Note that the second and third code blocks in the preview both show `second code block`.
4. Remove the very last backtick
5. Note that the second code block shows `undefined`
6. Replace the backtick removed in step 4 and remove the single backtick after the `+` from the first code block
7. Note that all code blocks now render

backtick-issue
### Technical details:
- Ghost Version: 0.9.0
- Node Version: 6.6
- Browser/OS: macOS, Chrome
- Database: Sqlite3

I try in safari, it is all the same.

### PR DESCRIPTION
**Pull request by tivie**
Related to https://github.com/TryGhost/Ghost-Editor/pull/7
Related to https://github.com/TryGhost/Ghost-Admin/pull/516

Closes #3398
 - Ghost is now compatible with showdown main

Closes #7536
 - backticks are now parsed correctly in the situations mentioned

Closes #5632
 - Fenced code blocks are now supported in lists

Closes #5587
 - Highlight extension ignores code blocks

Closes #5237
 - Inline code in link title in footnotes is now parsed properly

Closes #5039
 - GFM fenced code blocks can handle markdown code properly

Closes #4627
 - highlight ignores == in urls

Closes #2093
 - simpleLineBreaks option in showdown fixes this issue

Closes #5939
 - `<pre><code>` blocks are working properly now

Issue #5028
 - This should no longer be an issue

### CODE REVIEW

**Comment by tivie** [comment]
It seems building is failing on this test (**unrelated with Showdown**, as far as I can tell):

```
1) Post Model Single author posts add can add, defaults are all correct:
AssertionError:
expected '<h2 id="testing">testing</h2>\n<p>mctesters</p>\n<ul>\n<li>test</li>\n<li>line</li>\n<li>items</li>\n</ul>'
actual:  '<h2 id="testing">testing</h2>\n\n<p>mctesters</p>\n\n<ul>\n<li>test</li>\n<li>line</li>\n<li>items</li>\n</ul>'
```

**Comment by kevinansfield** [comment]
I'm assuming this will only be relevant to the LTS branch as the Ghost-Editor module should handle it for the alpha?

I was also thinking that rather than duplicating the showdown config in Ghost and [Ghost-Admin](https://github.com/TryGhost/Ghost-Admin/pull/516) it may make sense to have this set up as a configuration key so that the admin client can read the options from the API or is that over-complicating something that will likely disappear with 1.0?

**Comment by tivie** [comment]
I read somewhere that you were planning of moving the editor logic to your new Ghost-editor and keep the "legacy converter" option as a way to ease the transition, for users, to 1.0.
As a Ghost user, I reckon that makes sense and it's a must for me, as I've built some custom tools for auto publishing around the old editor that would probably need to be totally reworked with the new mobile-doc editor.

@kevinansfield Regarding showdown config, I'm open to "create" a Ghost flavor in showdown core, if you feel the options I choose are appropriate.
This would remove the need to create complex coupling between `Ghost-admin` and `Ghost core` since setting up showdown would be a "one liner", something like this.

```js
var legacyConverter = new showdown.Converter({extensions: [sdGhostExtra, footnotes, highlight]});
legacyConverter.setFlavor('ghost');
```

What do you think?

**Comment by tivie** [comment]
Regarding the failing test, **it is related to showdown after all**.

Since showdown now cleans up the output (removing superfluous extra newlines between HTML tags), the expected output in the database fetch doesn't match what was hard written in the testcase.

New showdown removed a newline between the heading `<h2 id="testing">testing</h2>` and the paragraph `<p>mctesters</p>`.

I will push a fix to the test as soon as possible

**Comment by kirrg001** [comment]
Hey @tivie 👋

Thanks for your effort on this.
This is only relevant for the `LTS` branch, as @kevinansfield pointed out.

We will remove the markdown field and the legacy converter from the master branch (for `1.0`) soon, see #8479. The migration path from `LTS` to `1.0` will contain a transformation from markdown field to mobiledoc field, see #8141.

Furthermore, `1.0` is using markdown-it instead of showdown, see https://github.com/TryGhost/Ghost/commit/5d868d14ad6adc386a65f8f806154bed0fc24e6c.

This PR needs to be re-created against the `LTS` branch, closing.

**Pull request closed without merging**
