### PR TITLE
fix db migrations problem

### PR DESCRIPTION
**Pull request by king6cong**
Hi, 

This is a fix for a db config issue. looks like being caused by some code refactoring.

Maybe using db.knex.client.dialect will be better.

### CODE REVIEW

**Comment by ErisDS** [comment]
Hi there @king6cong!

> This is a fix for a db config issue

Can you please take some time to describe the problem including full reproduction steps (if you hit "new issue" there's a bug report template). Without any details it's impossible to verify whether your code fixes the issue or know why this should be merged :wink:

**Comment by king6cong** [comment]
### Steps to Reproduce

when db migration is triggered, like changing the db version

```
--- a/core/server/data/schema/default-settings.json
+++ b/core/server/data/schema/default-settings.json
@@ -1,7 +1,7 @@
 {
     "core": {
         "databaseVersion": {
-            "defaultValue": "004"
+            "defaultValue": "005"
         },
         "dbHash": {
             "defaultValue": null
```

this error will be produced

```

Migrations: Database upgrade required from version 004 to 005
Migrations: Creating database backup

ERROR: Cannot read property 'client' of undefined

 TypeError: Cannot read property 'client' of undefined
    at Object.getTables (/home/vagrant/repos/Ghost/core/server/data/schema/commands.js:82:39)
    at exporter (/home/vagrant/repos/Ghost/core/server/data/export/index.js:31:67)
    at backupDatabase (/home/vagrant/repos/Ghost/core/server/data/migration/index.js:46:12)
    at Object.migrateUp (/home/vagrant/repos/Ghost/core/server/data/migration/index.js:164:12)
    at Runner_SQLite3.<anonymous> 
```

I hope this helps :smile:

**Comment by ErisDS** [comment]
> I hope this helps :smile:

Sorry but nope! I'm actively working on our migrations system at the moment and have been testing it quite a lot. I've not seen this error. What were you doing when this happened? What is your db config?

**Comment by king6cong** [comment]
Sorry, my fault. 
After a rerun of npm install, everything is ok. 
The version of knex I used was old.

```
-    "knex": "0.7.3",
+    "knex": "0.9.0",
```

Thanks for your time :kissing_cat:

**Pull request closed without merging**
