### PR TITLE
Minified images files using Trimage

### PR DESCRIPTION
**Pull request by flip111**
| size before | size after | reduction | filename |
| - | - | - | - |
| 3681  | 3297 | 10.43 | core/server/public/404-ghost.png |
| 7958  | 5609 | 29.52 | core/server/public/404-ghost@2x.png |
| 6792  | 2351 | 65.39 | core/test/utils/fixtures/images/favicon.png |
| 3386  | 2419 | 28.56 | core/test/utils/fixtures/images/favicon_not_square.png |
| 247144 | 222466 | 9.99 | core/test/utils/fixtures/images/favicon_size_too_large.png |
| 79774 | 78423 | 1.69 | core/test/utils/fixtures/images/favicon_too_large.png |
| 1470  | 640 | 56.46 | core/test/utils/fixtures/images/favicon_too_small.png |
| 8638  | 6806 | 21.21 | core/test/utils/fixtures/images/ghost-logo.png |
| 2499  | 1825 | 26.97 | core/test/utils/fixtures/images/ghosticon.jpg |

### CODE REVIEW

**Comment by flip111** [comment]
Docs [say](https://docs.ghost.org/docs/contributing#section-submitting-pull-requests) `Pull requests are awesome`, sucks that this one is closed without motivation :angry:

**Comment by kevinansfield** [comment]
There was nothing in the PR description to indicate this wasn't one of the frequent bots opening PRs without any consideration to what's being changed. This PR is only making modifications to images used as test fixtures which also raises suspicions as it's not actually doing anything meaningful.

**Comment by kevinansfield** [comment]
Considered PRs are most definitely appreciated. Running an automated tool without reviewing it's output is not really a considered PR, in the future I would suggest reviewing the changes to see if they are meaningful to the project. If you have an automated tool maybe suggest ways it could be incorporated into workflows rather than opening a PR with no context.

**Comment by flip111** [comment]
It's not an automated tool, i spend one hour reading contribution guide, finding manual tools, minifying and checking if pictures were not corrupted. `Output of automated tool`, not sure what tool you are talking about. I didn't check travis output before but i updated my branch to make changes in test cases. In the future i suggest you check github account of person before dismissing them as bot.

This PR is not important for me, you can leave it closed.

**Pull request closed without merging**
