### PR TITLE
Updated permissions service to handle api keys

### PR DESCRIPTION
**Pull request by allouis**
:wave: refs #9865 :wave:  
:information_source: This is split out from https://github.com/TryGhost/Ghost/pull/9869/ :information_source: 

This PR contains the updates to the permissions service to be able to handle api_key permissions. it does _not_ include updates to the models which have their own permission logic - that will come in a separate PR.

### CODE REVIEW

**Comment by allouis** [comment]
Updated this to use `api_key_id` rather than `api_key`

**Comment by kirrg001** [comment]
The PR is for the admin key feature or?
If yes, can we make this PR HOLD for now? Nobody actively works on this feature currently as far as i know.

**Comment by allouis** [comment]
We can put it on hold - but this PR is complete and can be merged

**Comment by kirrg001** [comment]
@gargol I've looked at this one. All the logic is optional. As long as the auth layer does not accept api_key authentication, we can just merge this into master for now.

I would probably think about renaming `context.api_key_id` to `integration`, but that is a tiny detail.

Feel free to merge into master if you are ready 👍

**Comment by gargol** [comment]
Added the renaming of `api_key_id` to `integration` (or maybe something else :man_shrugging:) to our "go live checklist" so we do it once we have more context around actual use of this permission. Merging now :tada:

**Pull request merged**
