### PR TITLE
Fix nav regressions in admin client

### PR DESCRIPTION
**Pull request by kevinansfield**
issue #5841
- fix relative link checks in navlink url input component
- fix navlink url input component sending absolute URLs instead of relative URLs to action handler
- remove URL manipulation in navigation settings controller (url input handles URL manipulation, validator flags anything that's still incorrect)
- capture `cmd-s` in url input to ensure changes are actioned before save
- automatically add `mailto:` to e-mail addresses
- add `gh-validation-state-container` component so `.error`/`.success` validation classes can be applied to any container element
- add `validation-state` mixin that can be mixed in to any other component to give it access to validation status (used in `gh-navitem` component to keep alignment when inline error message elements are added)
- validate and display inline errors on save
- improve ember test coverage for navigation settings related controller and components

---

Ember todos:
- [x] fix CMD-S not saving current value if input has focus
- [x] add inline validation for invalid URLs
  - [x] add NavItem validator
  - [x] implement a more generic container component than `gh-form-group`
  - [x] display errors when saving navigation
- [x] cleanup controller so we have a single location for URL manipulation
- [x] add tests and fix for errors when `baseUrl` has a path element
- [x] improve ember test coverage
- [x] fix last item not marked as last
- [x] fix validation of e-mails in URLs
- [x] automatically add `mailto:` if we detect a valid URL
- [x] fix auto-encoding of URL characters for relative URLs

### CODE REVIEW

**Comment by ErisDS** [comment]
@kevinansfield Just a headsup, I took this for a spin to see if it fixes the current helper (it does :+1:), and each time I focus-out from a field I'm seeing my subdirectory getting added to the URL like this:

**Comment by kevinansfield** [comment]
That's very odd. I haven't been able to replicate it so far, does this only happen if you have Ghost installed on a subdirectory?

**Comment by ErisDS** [comment]
Yeah - I always use a subdirectory `/blog/` in my dev env as it's one of those things that easily regresses :)

**Comment by ErisDS** [comment]
Save & validation seem to be working much better. The email handling doesn't seem to be quite right just yet - it adds mailto when you press enter or focus out, but then adds the full URL again on save - not sure if that's because #5864 is needed?

Also noticed we've lost the behaviour which added the trailing slash at the end of a relative URL and can't remember if that was done on purpose to fix another issue or not. I don't *think* so. Without adding the slash to genuine relative URLs, the current helper will probably still not work - but might be something to fix separately to this already pretty epic PR?

**Pull request merged**
