### PR TITLE
🏗  Dropped apps related tables

### PR DESCRIPTION
**Pull request by naz**
refs https://github.com/TryGhost/Ghost/issues/12565

- Dropped apps_* tables which were not used since the concept of "apps" has been abandoned
- Uses newly introduced "dropTables" migration utility

Note to reviewers, would pay a special attention to dropTables which I've introduced with [earlier commit](https://github.com/TryGhost/Ghost/commit/b5b65b3a60e87df03e906a53ea723493e5b7d0ca).

### CODE REVIEW

**Comment by naz** [comment]
@daniellockyer the CI is failing because it tries to rollback to v3. Is that intentional? Why would we want to do this?

**Comment by daniellockyer** [comment]
@naz The test was for v3 to make sure we could roll back to any of the previous versions. I'll update it to ignore v4 for now

**Review by tpatel — CHANGES_REQUESTED** [review]
I think `dropTables` should use `createIrreversibleMigration` because it's only implementing `up` and not `down`. That way the migration will be `irreversible` so that it's compatible with the CLI!

**Review by tpatel — APPROVED** [review]
Just seen that the issue I've mentioned got fixed in https://github.com/naz/Ghost/commit/80481d4076b147858b9d45fe86fa2a39ca3317a7

**Review by daniellockyer — APPROVED** [review]

**Comment by daniellockyer** [comment]
@naz The test was updated - feel free to rebase again 🙂

**Review by allouis — APPROVED** [review]
so smol!!

**Comment by naz** [comment]
Thanks guys! Merged into main as 606212d

**Pull request closed without merging**
