### PR TITLE
File storage

### PR DESCRIPTION
**Pull request by phated**
This is an initial implementation based on the discussion in #4600.  I added config tests, but I wasn't sure where tests would go for testing a custom storage engine was loaded and used correctly.  I also had to update timestamps in the importer tests because they were failing on fresh clone.

Please let me know what you think and how we can get this merged.  Thanks!

### CODE REVIEW

**Comment by ErisDS** [comment]
Hi @phated I'm REALLY excited that someone has taken on the file storage challenge! I'll take a closer look at your PR a little later on, but wanted to quickly provide a bit of feedback about the timestamps issue.

The timestamps should not need changing, and as you can see changing them has caused the tests to fail on Travis. There seems to be some environment based problem here, I'd guess that it might be timezone related. The tests may need to be updated to work more generally across timezones, but changing the timestamps isn't the right fix here.

**Comment by halfdan** [comment]
Maybe this does the trick? https://github.com/TryGhost/Ghost/pull/4822

**Comment by phated** [comment]
@ErisDS I rebased out the timestamp changes.

**Comment by phated** [comment]
Is there anything blocking this?

**Comment by ErisDS** [comment]
@phated, sorry for letting this one sit for such a long time, totally my bad. I finally had time today to sit down and properly play with this and get a feel for it with a real replacement storage layer.

It seems to work really well - I managed to build a custom module inside of the /content/storage folder with local dependencies and require stuff from Ghost core. We can certainly improve on it (moving storage/base.js to it's own requirable npm module with all the tools you're likely to need would be nice), but it works for now and means hacking core is totally unnecessary, so a big win on that front :+1:.

I have just one minor change - I think this is likely to be useful to quite a small number of people, and those people are going to need to read some pretty detailed documentation to get this working (which is fine). With that in mind I don't think there's any need to have `/content/storage/` be a folder with a readme in every Ghost install like the other `/content/` folders - it's consistent, but it's just unnecessary.

If you're up for updating your PR, I'd appreciate it if you could also update your commit message to match the [preferred format](https://github.com/TryGhost/Ghost/wiki/Git-workflow#commit-messages). If you've moved on, I'll be more than happy to fixup and merge manually :)

Sorry again for the delay.

**Comment by phated** [comment]
@ErisDS thanks for following up.  I've updated the PR as per your instructions.

**Comment by benwoodward** [comment]
Awesome! How do I use this?

**Comment by ErisDS** [comment]
Documentation will be made available when this is released ;)

**Comment by joeyespo** [comment]
@ErisDS Any chance you could ping this thread when the associated release goes out?

**Comment by ErisDS** [comment]
Will drop the docs here at that time yep.

**Comment by ErisDS** [comment]
0.6.0 is available, docs here: https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module

**Comment by benwoodward** [comment]
Nice work people! Thank you.

jwkg5bw

**Pull request merged**
