### PR TITLE
✨  ghost auth: sync email

### PR DESCRIPTION
**Pull request by kirrg001**
refs #7452

- sync email changes in background (every hour right now)
- sync logged in user only!
- no sync if auth strategy password is used
- GET `/users/me` is triggered on every page refresh
- added **TODO** to support or add long polling for syncing data later
- no tests yet on purpose, as i would like to get a basic review first

### CODE REVIEW

**Comment by ErisDS** [comment]
I am not sure about the concept of doing this in middleware.

A couple of problems I see is that it's hard-wired into a very specific, but not necessarily related part of the system, it's a bit like the update check firing on the admin index. 

Two other options would be:
- use an event - perhaps make a special event for when users/me is requested?
- use the scheduler to schedule updates

**Comment by kirrg001** [comment]
> it's a bit like the update check firing on the admin index.

^ This blocks the request. My approach listens on an express event to wait that the /users/me request finished successfully.

> use an event - perhaps make a special event for when users/me is requested?

For this approach we would trigger an event here, https://github.com/TryGhost/Ghost/blob/master/core/server/api/users.js#L90
e.g. `read:user:me` and listen on it in the auth module. This is also great 👍

**Comment by kirrg001** [comment]
ready to merge 🚀

**Comment by ErisDS** [comment]
I am leaning very heavily towards using events much more in Ghost, especially for any actions which are async and we don't need to care about waiting for their outcome.

There are some cool benefits:
- it allows you to decouple pieces of a system, which is particularly handle for avoiding circular dependencies, aaaaaand for getting Ghost to be more modular internally
- searching the codebase for things that listen to an event is quite nice
- any event we add can in future be hooked into by apps, meaning we're building out our app system at the same time by accident

The downside is going to be, I think, that we will loose track a bit of what fires which event and when exactly (e.g. with this event, does it happen before or after the query) and find it hard to know what is listening to an event. However, I think by the time we encounter those problems we'll be able to leverage new bits of the events API in Node v6 to help us solve them, and that's IF we even find that 😁

**Pull request merged**
