### PR TITLE
Added theme helper changes for `tiers` 

### PR DESCRIPTION
**Pull request by rshbhgrg**
refs https://github.com/TryGhost/Team/issues/1004

- Added tiers data for posts with non tiers visibility
- Fixed include option not working for fetching tiers via #get helper
- Added new {{tiers}} theme helper

### CODE REVIEW

**Review by matthanley — COMMENTED** [review]
We have test cases for `visibility: public|members|paid` but we're missing the case when `visibility: tiers`

**Comment by matthanley** [comment]
@rishabhgrg could you also make sure that the related docs changes are tracked/PR'd, as well as a GScan change to deprecate the `{{products}}` helper

**Comment by rishabhgrg** [comment]
@matthanley Extended with test cases for `tiers` visibility [here](https://github.com/TryGhost/Ghost/pull/14259/commits/c3e5305a8c3827a0f7ccae48e35e6fe4b5d4c922) with similar pattern as other visibility.

**Comment by rishabhgrg** [comment]
Added an issue [here](https://github.com/TryGhost/Team/issues/1407) to track docs and deprecation changes.

**Review by matthanley — APPROVED** [review]

**Pull request merged**
