### PR TITLE
Ensure cors check happens for /authentication/token route 

### PR DESCRIPTION
**Pull request by kirrg001**
no issue

- otherwise external browser clients run into cors problems

### CODE REVIEW

**Comment by kirrg001** [comment]
@kevinansfield 

I think this is not so easy to implement for all cases.

1. configuration endpoint can't be used for external clients, because we expose the admin credentials. we can't do the cors check, because it relies on the client credentials, which fetches the trusted domains.

2. For the authentication setup routes the admin client currently does not send the client credentials.

Should we only enable the cors check for `/authentication/token` for now? But i doubt you can then fully implement an external client, because you can't setup a blog. You can only talk to existing blogs. Probably related to https://github.com/TryGhost/Team/issues/39.

**Comment by gazpachu** [comment]
> You can only talk to existing blogs

@kirrg001 That's fine, at least external clients will be able to interact with the existing blog.

**Comment by kirrg001** [comment]
Updated the PR to only do a cors/trusted domain check for /authentication/token.

**Comment by gazpachu** [comment]
Hi folks, I've just tried it with a clean Ghost install of 1.19.0 but I still get this:

```
Failed to load http://localhost:2368/ghost/api/v0.1/authentication/token: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
```

Although I still get the token

**Comment by gazpachu** [comment]
Well, it seems I didn't get the latest commits. Any idea of how can I install them using the CLI?

**Comment by kirrg001** [comment]
@gazpachu Sorry, you have to wait for the next release. Will happen this week 🙃

**Comment by gazpachu** [comment]
All working well now :)

**Pull request merged**
