### PR TITLE
Added locale for Bengali Language (bn) Just modified signup form for …

### PR DESCRIPTION
**Pull request by newazsvn**
Added Bengali (bn) Locale.

- Only modified signup form for now
- Soon the other files will be translated

### CODE REVIEW

**Comment by newazsvn** [comment]
Translation Complete

**Comment by amirsaam** [comment]
you need to add your locale code to ghost/i18n/lib/i18n.js too.

p.s. to devs, please remember to release a new version for portal and comments-ui after merging.

**Comment by newazsvn** [comment]
> you need to add your locale code to ghost/i18n/lib/i18n.js too.
> 
> p.s. to devs, please remember to release a new version for portal and comments-ui after merging.

Done. Thanks.

**Comment by cathysarisky** [comment]
Hello @newazsvn , thanks so much for your work on these! Sorry to see they haven't been merged yet.  Do you a few moments more to pick up the newly added strings, including the ones that support the search app?  To do that, you'll need to sync your fork.  Here are directions if you need them:  https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork .  If you can get your changes updated, I'll put this PR on the list of PRs I'm reminding the dev team about. :)

**Review by cathysarisky — APPROVED** [review]
Looks good to my AI helper!

**Pull request merged**
