### PR TITLE
Removed lib/members in favour of packages

### PR DESCRIPTION
**Pull request by allouis**
This replaces the `core/server/lib/members` directory with two new dependencies, [`@tryghost/members-auth-pages`](https://github.com/tryghost/members/tree/master/packages/members-auth-pages) and [`@tryghost/members-api`](https://github.com/tryghost/members/tree/master/packages/members-api)

The auth pages module gives us a `dist` directory of static files, which we serve using `express-static`. The members-api gives the same interface as before and is simply replaced by switching `require` targets.

### CODE REVIEW

**Review by rshbhgrg — APPROVED** [review]

**Comment by jxw125** [comment]
There are some references to lib/members in the grunt file - is it safe to just remove these now this directory does not exist?

**Comment by ImranKhan-dev** [comment]
Its breaking when I do 
> yarn setup

Receiving below error 

Running "subgrunt:init" (subgrunt) task
Warning: The "core/server/lib/members/static/auth" directory is not valid, or does not contain a Gruntfile. Use --force to continue.

Let me know how to fix

**Comment by lmuzquiz** [comment]
Same for me. Also if i run grunt build i get this: 

```
 Running "subgrunt:prod" (subgrunt) task
Warning: The "core/server/lib/members/static/auth" directory is not valid, or does not contain a Gruntfile. Use --force to continue.

Aborted due to warnings.
➜  Ghost git:(gconfort) Running "shell:ember:prod" (shell) task
```

**Comment by allouis** [comment]
@jxw125 @ImranKhan-dev @lmuzquiz I've updated the Gruntfile to remove all the references! Thanks for the catch :fishing_pole_and_fish:

**Comment by lmuzquiz** [comment]
Thanks @jxw125

**Pull request merged**
