### PR TITLE
Tests: Renamed `unit/server_helpers` to `unit/helpers`

### PR DESCRIPTION
**Pull request by kirrg001**
no issue

- nothing to explain 😁

### CODE REVIEW

**Comment by ErisDS** [comment]
This is not passing. I can merge #9141 first and rebase on top (which I think is the easier way around) if you can get the build passing

**Comment by kirrg001** [comment]
@ErisDS Should pass now. 
Let's merge #9141 first - more important.

**Comment by ErisDS** [comment]
This needs rebasing

**Review by ErisDS — CHANGES_REQUESTED** [review]
Needs rebasing then it's ready to go

**Review by ErisDS — APPROVED** [review]

**Pull request merged**
