### PR TITLE
✨ knex-migrator v2

### PR DESCRIPTION
**Pull request by kirrg001**
refs #7489 
After this PR there is only one TODO left: see https://github.com/TryGhost/Ghost/issues/7489.

Please see the PR in `knex-migrator` repo:
See https://github.com/TryGhost/knex-migrator/pull/11

This PR shows the usage of running migrations within Ghost. (added an example migration)
This PR integrates the usage of resetting the database within Ghost.
You can checkout this branch and play with it.
### current versioning
- using knex-migrator requires a .knex-migrator file
- this must contain a current version your project is on
- so when Ghost is on 1.0.X, we expose 1.0
- knex-migrator won't run any migrations newer then this version
### hooks

We can hook into the whole process of knex-migrator.
For example:
Before migrations start, initialise the models.
After migrations, destroy database connection.
### TODO
- [x] final test
- [x] 1.0, 1.1, 1.2 exists, then i import a database - what happens? -> Right now: when importing a JSON database file, Ghost would set the current Ghost version to the database version. Because we don't import the database version (see importer). I've added a task to #7489 to test importing/exporting databases and change behaviour if needed
- [x] replace package.json knex-migrator tarball (when knex-migrator is released)
- [x] remove example migration before merge

### CODE REVIEW

**Comment by kirrg001** [comment]
This is ready for a review. Happy about any feedback 🕵🏻

**Comment by ErisDS** [comment]
I have reviewed this and TryGhost/knex-migrator#11, although that PR broke GitHub for me 😂 

This is all looking amazing 🎉 , the code is maturing really nicely and I'm excited about how much this solution has evolved and grown up 👍  I especially like the details around being able to exclude some migrations & the flexibility in the commands, I think this is going to help us to move a lot faster! 💯 

I have only 3, small pieces of feedback.
1. The name of the config file is not ideal, due to npm ignoring dotfiles, as [discussed here](https://github.com/TryGhost/Ghost/pull/7591)
2. I think the behaviour of the reset needs [further consideration](https://github.com/TryGhost/knex-migrator/pull/11#discussion_r84471339).
3. The message currently output on the CLI doesn't mention how to install knex-migrator or where to go to get help with the error. I think that we can improve that error message to provide more guidance and reduce contributor friction.

**Comment by kirrg001** [comment]
> 1. The name of the config file is not ideal, due to npm ignoring dotfiles, as discussed here

Agreed!
PR is coming to knex-migrator repo and to Ghost.

> 2. I think the behaviour of the reset needs further consideration.

Will look into your comment in the PR https://github.com/TryGhost/knex-migrator/pull/11
👍 


> 3. The message currently output on the CLI when you need to run init doesn't mention how to install knex-migrator or where to go to get help with the error. I think that we can improve that error message to provide more guidance and reduce contributor friction.

Yeah good feedback. 
Added an issue, see https://github.com/TryGhost/knex-migrator/issues/13

**Comment by kirrg001** [comment]
Added knex-migrator 0.1.0
I would like to merge this for alpha.8.
Just ping me here and i will remove the example migrations folder 👍

**Comment by kirrg001** [comment]
Travis is red, but it does not show any logs right now. Maybe a bug. Will try to rebuild tomorrow.

**Comment by kirrg001** [comment]
Ok travis is green now!

**Comment by kirrg001** [comment]
Please review for `alpha.8`. Ghost-CLI is already using knex-migrator `0.2.0` as local dependency. And Ghost master is using `0.7.x`.

**Pull request merged**
