### PR TITLE
[Spike] New mobiledoc based editor

### PR DESCRIPTION
**Pull request by kevinansfield**
prereq for TryGhost/Ghost-Admin#6

Spike/prototype to test out new editor functionality based around https://github.com/bustlelabs/mobiledoc-kit

no issue
- adds server-side mobiledoc rendering
- adds support for demo SimpleMDE markdown card

### CODE REVIEW

**Comment by halfdan** [comment]
Do I understand this correct as a step away from Markdown? Or is there a plan to allow the new editor to handle Markdown? Or in other words - how does Ghost looks like after this PR?

**Comment by ErisDS** [comment]
This is an experiment that aims to answer all of those questions. As I said to you in Slack the other day, we're planning right now - and that comes with some experimenting. It's a chicken-and-egg kinda situation.

**Comment by kevinansfield** [comment]
> Do I understand this correct as a step away from Markdown? Or is there a plan to allow the new editor to handle Markdown?

There are a couple of immediate options:

1. The mobiledoc editor already recognizes some markdown and automatically converts the text (such as lists etc) as you type and it's easy to extend with other text expansions so it would still be possible to type markdown to some extent
2. There is support for "cards" that are like editable sections with a HTML/text/dom renderer - it should be fairly simple to have a "markdown" card that ingests markdown formatted text and uses an existing markdown converter for it's HTML renderer. In this way there could even be multiple community markdown cards that use different markdown libraries

Although markdown should still be easy to support, the idea with the new editor is to move away from the restrictions that markdown imposes and open up a new level of flexibility/extensibility. However as @ErisDS said there's still a lot of experimentation to be done in that regard :smile:

**Comment by nuclearpengy** [comment]
Sounds interesting.

**Comment by kevinansfield** [comment]
Closing as this is now located on the [Ghost-Admin](https://github.com/TryGhost/Ghost-Admin/issues/6) repo.

**Comment by kevinansfield** [comment]
Oops, I was a little over-zealous with the PR closing earlier. Re-opening as this as it contains the server-side component of the new editor spike, the client-side part of this lives [here](https://github.com/TryGhost/Ghost-Admin/issues/6).

**Comment by kevinansfield** [comment]
Closing as this has served it's purpose and we're now working on a new mobiledoc implementation.

**Pull request closed without merging**
