### PR TITLE
add Bulgarian translation for search

### PR DESCRIPTION
**Pull request by StanTraykov**
Add initial translation for Bulgarian for the search interface.

### CODE REVIEW

**Comment by StanTraykov** [comment]
@cmraible 👋 Just added a Bulgarian translation for the search interface.

**Comment by yovko** [comment]
I would suggest to translate tags as "етикети" ("тагове" is not yet an accepted word in the official dictionary, if I'm not mistaken - and perhaps it's better not to impose it) :-)

**Comment by StanTraykov** [comment]
@yovko thanks, changed it to етикети to sound more natural (or maybe old-fashioned to the new generation? I don't know :D).

**Comment by ronaldlangeveld** [comment]
Thank you for submitting translations to Ghost! 🙏🏻 We really appreciate every string you’ve added. There might be a few new strings that need translation in Bulgarian. If you spot any untranslated or missing strings, let us know, and we’ll fix them ASAP! 🎉

**Pull request merged**
