### PR TITLE
Reorganise & Rename server/data/ folder internals

### PR DESCRIPTION
**Pull request by ErisDS**
This is the start of a proposal to reorganise and rename a sizeable amount of what's inside `/server/data/` as part of #6301:
- In the migration folder, `commands.js`  changes to `builder.js` to resolve conflict with the 'commands' inside `data/utils/clients/`.
- a new `data/schema/` folder has been added to hold all the code related to the database schema
- `data/utils/clients` have been moved to `data/schema/clients` 
- `data/utils/index.js` has become `data/schema/commands.js`
- `data/schema.js` has been split, the definition of the DB schema stays put, the additional checks have moved to `data/schema/checks.js`

Moving forward, I think it makes sense to also move the `migration/`, `fixtures/` & `versioning/` folders underneath the 'schema' folder as well as the default-settings.json, which is really a `fixtures` file.

That way all the code which is purely to do with the database table definition (schema), the data inside (fixtures), and how we move between versions (migration, versioning) is all sectioned up inside a top-level schema folder.

I'm raising this super early to give an opportunity for anyone to comment or suggest something different before I get too far down the rabbit hole. Ideas very welcome!

---

Note 1: The export and import (+importer, which is part of the import) functionality is clearly separate, these are tools for moving data in and out of the database. They have a dependency on being able to ask questions about the schema, but the new structure doesn't affect this.

Note 2: The validation functionality is related and probably ok where it is. The meta and xml folders are full of tools for generating various types of meta data about a blog: rss, sitemaps, html meta data for the `<head>` and doing xmlrpc pings which are vaguely related. This functionality probably belongs all together in some sort of 'meta data' section.

### CODE REVIEW

**Comment by sebgie** [comment]
:+1:

**Comment by ErisDS** [comment]
In the interest of not blocking #6301, this can be merged as-is, I think, and any further moves can be done later.

**Comment by ErisDS** [comment]
I've done an extra piece to move `data/versioning/index.js` to be `data/schema/versioning.js` - that fits neatly.

I tried out moving `fixtures` and `migration` underneath `schema`, but it didn't feel right - the requires feel like they're going in the wrong direction and dangerously close to getting circular.

I *think* `fixtures` needs to move under migration. Then the top level things are effectively 'schema', 'migration', 'import', 'export'. The `xml` and `meta` folders will be moved from here when the channel stuff is finished and the serverside blog rendering all becomes a bit clearer I think.

Only question left in  my mind is, where should `default-settings.json` live? Next to schema.js  or inside fixtures?

**Comment by ErisDS** [comment]
So, I've now also moved `fixtures/` into `migrations/`, and moved the stray `default-settings.json` into `schema/`

The result is a folder that looks like this:



Given that meta & xml both need a new home, so ignoring those, I think this is more sane?

**Pull request merged**
