### PR TITLE
🐛Fix generic 500 response

### LINKED ISSUE #10948: v2 API throws a 500 error for malformed query param
Malformed query params can cause a 500 error. E.g.

https://demo.ghost.io/ghost/api/v2/content/posts?format=json&include=tags&key=&key=22444f78447824223cefc48062

The malformed part is that there's an empty key, and then a correct key.

### To Reproduce

1. Click on https://demo.ghost.io/ghost/api/v2/content/posts?format=json&format=json&include=tags&include=tags&key=&key=22444f78447824223cefc48062
2. Notice the generic 500

IMO this should throw a 400, not a 500, the same as if you provide other incorrect params:

https://demo.ghost.io/ghost/api/v2/content/posts/?format=json&include=&key=22444f78447824223cefc48062

### Technical details:

* Ghost Version: master

### PR DESCRIPTION
**Pull request by pbmiguel**
closes #10948 

- Throws 400 when request has multiple key-query values

### CODE REVIEW

**Comment by pbmiguel** [comment]
@ErisDS, for fixing the #10948 issue I here proposed throwing 403 instead of throwing 400 as you had suggested.

- Nevertheless, do you think a 403 for this situation is reasonable?

I welcome comments, suggestions and corrections. Thanks.

**Comment by ErisDS** [comment]
In this case, there may be a correct key present, the reason the error is happening is because the query params are malformed = it's a bad request, not because the key is wrong.

We're not denying the user access, we're just not able to read what they've sent us. Therefore 400 is the correct response code IMO.

**Comment by pbmiguel** [comment]
Yup, It makes sense your perspective... the problem lies on a bad request and not the fact that the authentication is wrong.

Thanks! I'm going to change it as you've suggested.

**Comment by pbmiguel** [comment]
@ErisDS, changed as suggested. 
It's now ready to be reviewed.
👍

**Comment by ErisDS** [comment]
Merged 🎉 Thank you 👍

**Pull request merged**
