### PR TITLE
Improved pagination misusage error and reattach error to request object

### PR DESCRIPTION
**Pull request by kirrg001**
Please merge both commits!
See commit descriptions.

You can reproduce an error if you add a custom error template and add the `{{pagination}}` helper on top.

### CODE REVIEW

**Comment by kevinansfield** [comment]
I see this output for a 404 page when it's using the `{{pagination}}` helper outside of a context, is that expected or should we see a proper 500 error page?

```
Oops, seems there is an error in the error template.

Encountered the error:

[error-404.hbs] You are misusing the pagination helper.

whilst trying to render an error page for the error:

400
[error-404.hbs] You are misusing the pagination helper.
```

I can see in the logs that there's a link to the pagination helper docs but it's not present on the error page, is there a way we can output it on the error page too so that users are more likely to see it?

```
ERROR [2017-11-28 12:22:47] "GET /unknown/" 500 26ms

NAME: IncorrectUsageError
MESSAGE: [error-404.hbs] You are misusing the pagination helper.

level:normal

https://themes.ghost.org/docs/pagination
IncorrectUsageError: [error-404.hbs] You are misusing the pagination helper.
```

**Comment by kirrg001** [comment]
The thing is that you originally request a page which does not exist, but while rendering a problem occurred in **this page**. That's why it shows "...whilst trying to render an error page for the error:"

**Comment by kevinansfield** [comment]
I'm also not sure `You are misusing the pagination helper.` is much more helpful than `pagination data is not an object or is a function`.

Can we change it to something like `The {{pagination}} helper was used outside of a paginated context. See https://themes.ghost.org/docs/pagination`?

**Comment by kirrg001** [comment]
> Can we change it to something like The {{pagination}} helper was used outside of a paginated context. 

Yeah sure :)

> See https://themes.ghost.org/docs/pagination?

Thought about this. Yeah let's add it also to the translation.

**Comment by kirrg001** [comment]
updated 👍

**Comment by kevinansfield** [comment]
Hmm, I tried putting the `{{pagination}}` helper in the `post.hbs` file in Casper right before `{{content}}`:

```
            <section class="post-full-content">
                {{pagination}}
                {{content}}
            </section>
```

When I view a post I see the error in my logs but there's no error shown to the user, just a blank screen. Is that expected?

screen shot 2017-11-28 at 13 02 19

**Comment by kirrg001** [comment]
No not expected, probably it fails because of a syntax error. Looking.

**Comment by kirrg001** [comment]
Ah it needs a rebase with master, this was fixed in my previous PR. Second

**Comment by kirrg001** [comment]
I rebased, can you try again? :)

**Comment by kevinansfield** [comment]
👍 looking good now 😄

**Pull request merged**
