### PR TITLE
Add member's email status on member page

### PR DESCRIPTION
**Pull request by lenabaidakova**
closes TryGhost/Team#2270
- Show emails status depending on the reason email was blocked (spam/fail)

### CODE REVIEW

**Comment by moreofmorris** [comment]
Hey @lenabaidakova, I could get this working when there was two newsletters but I can't seem to get it working when there was only one?

CleanShot 2022-11-17 at 10 28 45@2x

CleanShot 2022-11-17 at 10 27 18@2x

I added details about this feature over in the [Design Specification](https://www.notion.so/ghost/Design-Specification-150e1800c6764937a230f09b62cd0ad3#8ddaa922d6a04b7293e2206a65157854). There may be some room here to improve aspects of this page generally but details in there 🙂

**Comment by moreofmorris** [comment]
Hey @lenabaidakova, I rewrote some bits in the [Design Spec](https://www.notion.so/ghost/Design-Specification-150e1800c6764937a230f09b62cd0ad3#8ddaa922d6a04b7293e2206a65157854), so hopefully it's a bit more clearer. It feels like a good opportunity to make how we show single and multi newsletters more consistent which provides us a better way to show the suppression notice.

**Comment by lenabaidakova** [comment]
> Hey @lenabaidakova, I rewrote some bits in the [Design Spec](https://www.notion.so/ghost/Design-Specification-150e1800c6764937a230f09b62cd0ad3#8ddaa922d6a04b7293e2206a65157854), so hopefully it's a bit more clearer. It feels like a good opportunity to make how we show single and multi newsletters more consistent which provides us a better way to show the suppression notice.

@moreofmorris , icons updated :)

**Comment by moreofmorris** [comment]
@lenabaidakova loving this Elena!

Let's reduce the opacity even more for these disabled states (just for this area, no where else). As they are still technically on, but disabled with an opacity of `0.5` it still looks quite clickable. Let's reduce the opacity down even further to `0.1` like in the screenshot below 👍 Aside from that, looks great!

CleanShot 2022-11-18 at 09 56 49@2x

**Review by moreofmorris — APPROVED** [review]
Looks great, thanks Elena!

**Pull request merged**
