### PR TITLE
Ignore yarn-error.log

### PR DESCRIPTION
**Pull request by limichange**
Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!
- [x] Commit message has a short title & issue references
- [x] Commits are squashed 
- [x] The build will pass (run `npm test`).

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by kirrg001** [comment]
Hey @limichange 👋

Thanks for your PR!

Could you please update your PR and add the yarn debug log file as well?

e.g https://github.com/facebookincubator/create-react-app/pull/1507/files#diff-a084b794bc0759e7a6b77810e01874f2R9

**Comment by limichange** [comment]
I think we can remove all log files by `*.log`.
e.g https://github.com/vuejs/vue/blob/dev/.gitignore

**Comment by limichange** [comment]
Maybe i need close this PR, and create a PR for remove all log files ?

**Comment by limichange** [comment]
Sorry, we don't need this PR.
https://github.com/TryGhost/Ghost/blob/master/.gitignore#L3

**Pull request closed without merging**
