### PR TITLE
Use v4 instead of v1 uuids

### PR DESCRIPTION
**Pull request by ctavan**
I'm a co-author of the [uuid npm module](https://github.com/kelektiv/node-uuid) which is being used in some places within the code base of Ghost.

I'm currently trying to understand real-world use cases of [time-based UUIDs ("v1 UUIDs")](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_(date-time_and_MAC_address)).

I found three occurrences where v1 UUIDs were being used instead of v4 UUIDs and I was wondering if any of these cases really require the semantically much more complex v1 UUIDs or whether we could live equally well with purely random v4 UUIDs?

At least the test suite still passes after my changes, so apparently this doesn't seem to introduce any known regressions.

I'd be really curious to understand the motivation for choosing v1 over v4 UUIDs in the first place, so any feedback on this would be highly appreciated!

### CODE REVIEW

**Comment by allouis** [comment]
Hey @ctavan thanks for the contribution :dancer: !!

These changes look great to me, and especially for the `X-Request-ID` using a uuid which is based on time and MAC (which could feasibly be the same for requests made at _exact_ same time - is that right?) - a random id seems much better!

However - I'd like to confirm with @ErisDS or @cobbspur before this goes in :relaxed:

**Comment by ErisDS** [comment]
This change seems fine/sensible to me but the change to the request middleware needs to be considered / remembered with regard to the upcoming logging project :)

**Comment by ctavan** [comment]
Thanks for the quick feedback!

> These changes look great to me, and especially for the `X-Request-ID` using a uuid which is based on time and MAC (which could feasibly be the same for requests made at _exact_ same time - is that right?) - a random id seems much better!

@allouis don't worry, also with v1 UUIDs you have pretty strong guarantees that they are unique. At least the [UUID RFC](https://tools.ietf.org/html/rfc4122) contains the necessary safeguards.

In the particular case of the `uuid` npm module we don't even rely on the MAC address because it would not be available in browser environments anyways and the module is supposed to work both, on the server and in the browser. Instead, we generate a random value once per JS runtime process. Please refer to the [README](https://github.com/kelektiv/node-uuid#version-1) for more details.

That said, the semantics for generating v1 UUIDs are still much more complex and bad implementations or wrong usage of correct implementations can lead to various sorts of trouble. So if the specific features of v1 UUIDs are not needed, I think it is always the better choice to just go for v4 UUIDs where all you really rely on is a good random number generator (and with the `uuid` npm module on Node.js that's guaranteed).

So if it's really only about a unique identifier, then v4 is definitely the way to go!

----

> This change seems fine/sensible to me but the change to the request middleware needs to be considered / remembered with regard to the upcoming logging project :)

@ErisDS can you elaborate a bit what the effects of the change in the request middleware will be with respect to the future work you are planning?

----

Also @allouis, @ErisDS, @cobbspur is anyone of you aware of why v1 UUIDs were chosen in the initial implementation in the three cases? I'm really interested in understanding the reasons why developers choose v1 UUIDs over v4 when they use the `uuid` npm module.

**Comment by ErisDS** [comment]
@ErisDS can you elaborate a bit what the effects of the change in the request middleware will be with respect to the future work you are planning?

Nothing serious, we plan to move the middleware to ignition.

RE: remembering why the choice was made, your best bet would be git blame / issue search. It was ~6 years ago.

**Comment by ctavan** [comment]
OK, thanks @ErisDS!

* For the change in log-request I found https://github.com/TryGhost/Ghost/pull/7597 -> @kirrg001  do you have any memories on why `v1` UUIDs were chosen back then?
* For the change in the test utils I found https://github.com/TryGhost/Ghost/pull/9034/files#diff-419650c55e354dc0304b35c40e0285bbR49 -> Again, @kirrg001 any memories on the `v1` UUID choice?

@allouis @ErisDS anything I can improve on this PR to get this merged?

**Comment by allouis** [comment]
@ctavan nope! just slipped - this is great! thank you :dancer:

**Pull request merged**
