### PR TITLE
e2e-test-ghost-webhook-page-published - #15537

### PR DESCRIPTION
**Pull request by ade1705**
e2e-test for page.published webhook - Ref: #15537 

- [x] There's a clear use-case for this code change, explained below
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

Also, if you'd be interested in writing code like this for us more regularly, we're hiring:
https://careers.ghost.org

### CODE REVIEW

**Review by naz — APPROVED** [review]
Nice on @ade1705! Thanks for the contribution 😊

**Review by naz — CHANGES_REQUESTED** [review]
Based on the failing tests there seem to be some fields missing form the body snapshot matcher in the `matchBodySnapshot` method. @ade1705 did buildPageSnapshotWithTiers not work for the `previous` matcher or why was the `buildPreviousPageSnapshotWithTiers` introduced?

**Comment by naz** [comment]
Hey-hey @ade1705 👋  How are the updates going? Anything specific I could help with here?

**Comment by ade1705** [comment]
> Hey-hey @ade1705 👋 How are the updates going? Anything specific I could help with here?

@naz sorry for the delay, working on it. Almost done

**Comment by naz** [comment]
The [other PR](https://github.com/TryGhost/Ghost/pull/15724) for the same event has already been merged. Thank you for the effort @ade1705 🙌

**Pull request closed without merging**
