### PR TITLE
Add #compare Handlebars theme helper

### PR DESCRIPTION
**Pull request by eexit**
Heya!

For advanced theming, I would like to add the ability to evaluate basic conditions. I'm not sure you would enjoy this code to be part of Ghost but it would be nice and would offer even more flexibility for theme developers.

Thanks,

### CODE REVIEW

**Comment by ErisDS** [comment]
Hi again @eexit. 

I appreciate the idea here and the work that has gone into creating this. Ghost's theme API is one of the most important parts of our software, and so we put a great deal of care into any changes that are added.

The best way to get something like this added to the API is to suggest it over on our [wishlist](http://ideas.ghost.org) and get traction for the idea from other theme developers.  It would also be important to get some consensus around the use cases and why this particular syntax works best.

So far, where comparisons have been needed in Ghost, we have made them possible with the `{{#has}}` helper. 

For now, I don't think this addition makes sense, but I'm more than happy to revisit it if there is traction for the idea in future.

**Comment by eexit** [comment]
Hi @ErisDS,

Thanks for the review, I kinda hoped this could be merged but I knew it would be that easy :)
I added this operator because in my theme development, I need to test when I am on a certain page and I'm not sure your theme API allows to target a specific post/page.

For example, if would be really nice to have such `{{#is}}` extension:

    {{#is page_url "/foo/"}}{{/is}}

**Comment by ErisDS** [comment]
@eexit that's an interesting idea. The current setup assumes you'd create a unique template for a specific post or page.

**Comment by eexit** [comment]
@ErisDS Absolutely!

**Pull request closed without merging**
