### PR TITLE
pt-BR translation suggestions

### PR DESCRIPTION
**Pull request by fthiesen**
Suggestions for updating the confirmation email pt-BR translation with more everyday terms and addressing gender-specific issues by using 'no site' instead of 'em'.

### CODE REVIEW

**Review by sergiospagnuolo — COMMENTED** [review]
All changes are ok with me, I would just refrain from changing the line below, since it seems a bit off for me. All the others are ok to go.

_Would not use this_
`"You will not be signed up, and no account will be created for you.": "Você não será cadastrado e sua conta não será criada."`

**Review by Lekler — COMMENTED** [review]
I think replacing “em” with “no site” in the translations might break the logic of some people who use Ghost as a personal blog and the like, since {{siteTitle}} already pulls in the name the person has put in. 

I agree with @sergiospagnuolo comment about not using that particular snippet.

And it would be good to hear your opinion on this issue of changing "em" to "no site" as well @sergiospagnuolo

**Comment by fthiesen** [comment]
Hi @Lekler and @sergiospagnuolo thanks for reviewing the proposed translations and sending your inputs. 

Please consider the following about changing "em" for "no site":

- for the ones using ghost for a personal blog, a blog is still a website. So it would sound something like "you have signed up for the website Mary's Daily Thoughts".
- the use of "em" doesn't sound like Portuguese from Brazil. We wouldn't say "você se cadastrou em Globo.com".

That's why I'm proposing this change. Even thought it's not perfect, it sounds a lot better than using "em", which is not really used in these scenarios. 

Thank you

**Comment by fthiesen** [comment]
@Lekler , @sergiospagnuolo how would you prefer to go about that snippet? I'm suggesting we keep this consistent: signed up = cadastrado; subscribed = inscrito.

"You will not be signed up, and no account will be created for you."

1 — Você não será cadastrado e sua conta não será criada. (current suggestion) 
2 — Você não será cadastrado e uma conta não será criada para você. (alternative suggestion)
3 — Você não será cadastrado e nenhuma conta será criada para você. (current translation with a small change)
4 — Você não será inscrito e nenhuma conta será criada para você. (current translation - no changes)

**Comment by Lekler** [comment]
@fthiesen I like suggestion 2. 
As for the “em/no site” thing, we'll change it, and if there's a problem, just revert it.

**Comment by fthiesen** [comment]
Sounds good! I updated the file to include suggestion 2. Thanks!

**Comment by sergiospagnuolo** [comment]
great, guys! jumping in late: I think the changes are A-OK, and we can always revert back if needed, as mentioned.

**Review by Lekler — APPROVED** [review]

**Pull request merged**
