### PR TITLE
cleanup Gruntfile.js to be more maintainable

### PR DESCRIPTION
**Pull request by underbyte**
Broke the large grunt file into separate files in the grunt folder. This should be more maintainable going forward. I was able to run most of the tasks; except `grunt docs`.

### CODE REVIEW

**Comment by sp90** [comment]
Gulp is much faster, and the benefits of gulp are not just speed, its also much more tightly integrated with nodejs, which means you can use the same modules as for nodeJS. So this custom functionality your talking about might already have been solved. And if not the tight integration with nodejs should make the issues quite easy to solve.

(but maybe we could make a list of functionality that the grunt handels right now. Then people might have the interest in changing it for their own purpose.

It does give a much better and more seamless workflow to swap.

**Comment by javorszky** [comment]
@sp90, if you're up for it, convert all grunt tasks to gulp tasks, open a PR, and we can then test-drive that. Reason Ghost stayed with grunt is because the tasks are already done, and the bulk of the time that grunt tasks take aren't even grunt related, but rather the individual tests.

**Comment by sp90** [comment]
I would be glad to do it, i already have some draw ups of some great gulp setups, 

If you can provide me with a list of functionality i will with out a doubt start working on it :)

**Comment by javorszky** [comment]
@sp90 it's all in the gruntfile ;)

**Comment by sp90** [comment]
@javorszky Okay will look into it :+1:

**Comment by ErisDS** [comment]
Ghost already has a large user base who would be affected by this change. For that reason, there needs to be demonstrable, clear & significant benefits to gulp over grunt for us to make the switch. So far all of the benefits mentioned have been intangible, other than speed, which as @javorszky has already said, won't really affect us as the speed of our tasks is affected by things other than grunt.

**Comment by sp90** [comment]
@ErisDS so even if i convert it all into gulp, it wont be used because you dont wanna trouble the userbase to swap from grunt init & grunt prod with gulp init and gulp prod, the speed is significantly faster, and the modules that you have to write for gulp is probably already in there if not very easy to create

**Comment by sp90** [comment]
Btw stuff like this would be more appropriate to run in npm postinstall so when you run npm install it would run it afterwards.

```javascript
 // #### Run bower install
                // Used as part of `grunt init`. See the section on [Building Assets](#building%20assets) for more
                // information.
                bower: {
                    command: path.resolve(cwd + '/node_modules/.bin/bower --allow-root install'),
                    options: {
                        stdout: true,
                        stdin: false
                    }
                },
```

**Comment by ErisDS** [comment]
> @ErisDS so even if i convert it all into gulp, it wont be used because you dont wanna trouble the userbase 

Not unless there are "demonstrable, clear & significant benefits". 

> the speed is significantly faster

Which tasks will run faster? How much faster? Who will it benefit?

> The modules that you have to write for gulp is probably already in there if not very easy to create

We already have all of the functionality we need written and working! I would so much rather you spent your time helping us fix a bug or add a new feature than rewriting stuff that already works without a clear reason for doing so. Unless you can demonstrate a measurable advantage, this really is little more than a religious debate.

**Comment by josephdburdick** [comment]
@ErisDS Everyone will benefit because:

1. According to Six Revisions, (Gulp processes tasks ~4x faster than Grunt)[http://sixrevisions.com/web-development/grunt-vs-gulp/] (Do a Find in Page for "Measuring Task-Execution Speed" and see tests they've done)
2. Configuration is *much* easier to read for maintainers, contributors, and newbies

I am very interested in using Ghost as a platform to develop sites with my company and for my own clients but I find Grunt configs very difficult to look at. Any thoughts on the link above?

**Pull request closed without merging**
