### PR TITLE
🐛 🎨  old accesstokens are not cleaned up

### LINKED ISSUE #8035: Old accesstokens are not cleaned up
### Issue Summary

Each time a `refreshtoken` is used to get a new `accesstoken` we create a new record in the DB but the old accesstoken record is still kept. Now that we have longer expiry times on the tokens it means that we can't rely on the old tokens being unusable after an hour so we should either delete the old records or update the current record when a new token is generated.

### Steps to Reproduce

1. Log in to the admin
2. Refresh the page (requests a new access token from the stored refresh token)
3. Examine the database, in the `accesstokens` table you will now have at least 2 valid tokens for the same user

### Technical details:

* Ghost Version: master && LTS
* Node Version: 4.7.0
* Database: sqlite

### PR DESCRIPTION
**Pull request by kirrg001**
closes #8035

- we have previously added a logic to ember to refresh tokens on each ember bootstrap
- this has caused 100s of tokens in the database, because when requesting a new pair, Ghost doesn't tidy up the old tokens
- create auth/utils to simplify the logic and re-use everywhere
- decrease old token expiry before creating new ones
- everything runs in a transaction

### CODE REVIEW

**Comment by kevinansfield** [comment]
> LTS is not really affected, because on LTS the mechanism for refreshing tokens is different. On LTS we only refresh the tokens before they expire.

That's not true, we refresh the tokens on app boot on LTS too.

**Comment by kirrg001** [comment]
Thanks - i have updated the PR description and added a TODO instead 👍

**Comment by kirrg001** [comment]
Ready for review 👍 

I have tested with two tabs open. And waited that the old access token expired.
Restarted Ghost a couple of times.

Travis build doesn't start right now 👻 (same for master)

**Comment by kirrg001** [comment]
Travis is green now 🙊

**Review by kevinansfield — APPROVED** [review]

**Pull request merged**
