### PR TITLE
🎨  Move `scheduling` and `storage` in `adapters/`

### PR DESCRIPTION
**Pull request by aileen**
no issue

Move `core/server/scheduling` to `core/server/adapters/scheduling` and
`core/server/storage` to `core/server/adapters/storage`

### CODE REVIEW

**Comment by AileenCGN** [comment]
@kirrg001: review pretty please?

**Review by kirrg001 — CHANGES_REQUESTED** [review]
This all looks good and works 👍 
Could you please move the test files as well?
Thanks!

**Comment by AileenCGN** [comment]
Done, @kirrg001 !

**Review by kirrg001 — APPROVED** [review]
🌮

**Pull request merged**
