### PR TITLE
WIP: added debugging for determining CI speed

### PR DESCRIPTION
**Pull request by daniellockyer**

### CODE REVIEW

**Comment by ErisDS** [comment]
I would merge this 😬

**Comment by ErisDS** [comment]
The timers, I mean. Not debug :D

**Comment by daniellockyer** [comment]
💯%

**Comment by daniellockyer** [comment]
Pushed in https://github.com/TryGhost/Ghost/commit/4639396c3aa9325ab74ca733d037d299b0244271 so I'll just rebase this PR to keep it tracking the values

**Comment by daniellockyer** [comment]
Closing for now until needed

**Pull request closed without merging**
