### PR TITLE
Update html-to-text package

### LINKED ISSUE #5264: Installing 0.6.2 on Node v0.12 causes warning about html-to-text
```
$ npm install --production
npm WARN engine html-to-text@1.2.0: wanted: {"node":">= 0.8.0 <0.12"} (current: {"node":"0.12.2","npm":"2.7.4"})
```
This is using CentOS release 6.6.

### PR DESCRIPTION
**Pull request by jaswilli**
Closes #5264
- html-to-text@1.3.0

### CODE REVIEW

**Comment by JohnONolan** [comment]
OMG WOW :+1:

**Comment by JohnONolan** [comment]
SUCH PR

**Comment by JohnONolan** [comment]
:trollface:

**Comment by jaswilli** [comment]
I'm planning on retiring on this piece of work.

**Comment by JohnONolan** [comment]
:joy:

**Pull request merged**
