### PR TITLE
Routable tags

### PR DESCRIPTION
**Pull request by kevinansfield**
refs #5845
- updates tag settings screen to match content screen behaviour
- updates a number of places where jQuery event handler code was not wrapped in Ember's run loop causing tests to fail

**Notes:**

The tag creation process did appear a little strange when converting the existing functionality. A new tag is created/saved as soon as a field loses focus and the overall tag is in a valid state - this initially caused problems as the tag now has it's own route and appears in the list but you were left on the /new route and the newly added tag was not selected meaning to create another new tag you had to select a different tag first. To work around this I automatically perform a "replace" transition as soon as a tag is saved - it fixes the UI inconsistencies but I wonder if there is a better way to handle saving/creation in general, especially if you want to abort creating a new tag?

TODO:
- [x] Fix meta data navigation
- [x] Fix pagination (currently loads all tags on first load)
- [x] Fix delete tag modal
- [x] Fix styling of invalid fields
- [x] Match selected tag styling with content list's styling
- [x] Add keyboard navigation to match content list's
- [x] Sort tags by ID (fixes issue with selected tag being first in list if loaded directly, once available via API sorting will be by number of posts)
- [x] Unit test tag form component
- [x] Acceptance tests for main tags screen workflows
- [x] Rebase and update tests for changes in #5952
- [x] Fix `Ember.run.bind` where values are dynamic

### CODE REVIEW

**Comment by kevinansfield** [comment]
:disappointed: Realised this needs some more work for mobile. Opening a separate PR for that as this is already huge.

**Comment by ErisDS** [comment]
Playing around with this I've spotted a couple of things:

- the image doesn't seem to get correctly reset between tags. I uploaded an image and it appeared on all tags, and then when I refreshed there was no image on any tag again.
- when typing in the name field, using the arrows on the keyboards moves me around the ui instead of moving be left and right inside the field

**Comment by kevinansfield** [comment]
> the image doesn't seem to get correctly reset between tags. I uploaded an image and it appeared on all tags, and then when I refreshed there was no image on any tag again.

D'oh that's come back? I was sure that had been nailed in https://github.com/TryGhost/Ghost/commit/d49991f8fc12dcb4f94052252060c6a4ddfe0eea :disappointed: 

> when typing in the name field, using the arrows on the keyboards moves me around the ui instead of moving be left and right inside the field

Good catch! I need to toggle the keymaster scope somewhere to prevent that...

**Comment by kevinansfield** [comment]
@ErisDS both issues should be fixed now.

**Pull request merged**
