### PR TITLE
[HOLD] Mediate this jQuery debacle once and for all

### PR DESCRIPTION
**Pull request by acburdine**
refs #5298 

_At last, the treaty had been signed. Peace among the nations seemed at last to be possible. The debate over this treaty had been a long-lasting one. All sides had good arguments, but at last one opinion prevailed out among the others. Everyone throughout the land celebrated as a new era of peace was ushered in._

TODO List:
- [x] Remove old jquery code :tada: 
- [x] Add migration commands to utils
- [x] Fix notifications
- [x] Fix tests
- [x] Code cleanup
- [x] Squash

### CODE REVIEW

**Comment by acburdine** [comment]
@ErisDS This works for the most part; however, showing a notification/alert is rather tricky due to where the migrations fall in the server load stack. I tried sending an internal request to the notifications api add endpoint once the migration occurred, but it didn't work because permissions had not yet been initialized.

Any suggestions as to what I should do?

**Comment by acburdine** [comment]
@ErisDS I just realized something that might make this whole process easier. As I was looking through the notifications api code, I noticed it has not been pipeline-ified yet. Switching it over to the the pipeline way would make this notifications permission thing much easier to fix.

I can pipeline-ify the notifications API, but should I do that in this PR or in a separate one?

**Comment by ErisDS** [comment]
> I can pipeline-ify the notifications API, but should I do that in this PR or in a separate one?

That can be done in a separate PR if you prefer - I mentioned this in slack btw :wink:  it defo makes it easier!

**Comment by acburdine** [comment]
@ErisDS for some reason, the tags api tests fail on this because they call the database migration function. I think this might be a bug with the test utils?

I found it really strange because it only happens with the tag api and none of the others.

**Comment by ErisDS** [comment]
The integration tests in Ghost make calls to the model or API layer and have no stubbing for any of the database - they're full stack tests effectively. Before every test is run, the database is [cleared](https://github.com/TryGhost/Ghost/blob/master/core/test/utils/index.js#L560) and [reinitialised](https://github.com/TryGhost/Ghost/blob/master/core/test/utils/index.js#L436) - meaning the migration is effectively run before every test.

Originally, we used to also use the default fixtures, and every test started from the default that Ghost would start from - with all the default settings, the 'welcome-to-ghost' post and half-created owner user. This posed a few problems, particularly it made it very hard to test specific scenarios like having no posts, and it also made the tests a lot slower.

A little while back I changed the integration tests to start with a blank DB and pass in the data it wanted initialised, so you'll see things like at the top of the Tag API tests:

`beforeEach(testUtils.setup('users:roles', 'perms:tag', 'perms:init', 'posts'));`

`setup` creates a blank DB using `migrations.init(tablesOnly=true)`, and then inserts data according to the arguments passed in. The mapping from strings like `users:roles` to the test fixture creation function is here: https://github.com/TryGhost/Ghost/blob/master/core/test/utils/index.js#L378

I'm not 100% on all the whys and whats here, but in the case of the tag tests, `setup` gets called twice and neither time with `settings`, so there are no default settings in the database. This is partly a bug and partly kind of cool. I totally forgot that you're not really supposed to call `setup` twice - really I should be calling `testUtils.fixtures.insertMoreTags()` directly [here](https://github.com/TryGhost/Ghost/blob/master/core/test/integration/api/api_tags_spec.js#L105) rather than calling setup again.

The affect of calling it twice seems to be that an upgrade style migration gets called, and this is where it's tripping up. The code here assumes that the `ghost_foot` setting is present, when it isn't. 

So there are a couple of takeaways:

- this code shouldn't assume the setting is present
- the tag api code should be updated to call `testUtils.fixtures.insertMoreTags()` directly rather than using setup (althoooooouuuugggh.... it'd be nice to have a helper method instead so we could do something like `testUtils.fixture('tags')`
- this has provided quite a nice way to test the migration code?

**Comment by ErisDS** [comment]
Going to close this, as the commit has been pulled into #5706 - a full set of migrations for 004. It will be merged shortly.

**Pull request closed without merging**
