### PR TITLE
Refactored column migrations to use helpers

### PR DESCRIPTION
**Pull request by daniellockyer**
need to:
* ~verify I didn't fatfinger any changes~ DONE
* ~remove `validation` from `columnDefinitions`~ DONE

### CODE REVIEW

**Review by allouis — APPROVED** [review]
This looks great, I need to give it another check on Monday and compare all the column types, but so far I can't see any issues.

There's one v. minor thing, which is that DDL statements can't/don't use transactions, so everywhere we use `combineTransactionalMigrations` or `createTransactionalMigration` it doesn't really make sense.

Having said that, the duplication would be fairly strong, and this doesn't actually cause any errors, as soon as MySQL receive a DDL statement, it'll close the current (unused in this case) transaction.

It's up to you what you do, I think it might be nice to either create non-transactional methods, OR possible rename the methods to ignore the concept of transactions :shrug:

**Comment by daniellockyer** [comment]
@allouis Thanks for the point! I've switched to not using transactions here: [`ddd859e` (#12360)](https://github.com/TryGhost/Ghost/pull/12360/commits/ddd859ee7fffe708ed208e087c717dd201083f24). We already had a `createNonTransactionalMigration` so I just added a `combineNonTransactionalMigrations` method too. Does this solve your comments? 🙂

**Comment by allouis** [comment]
Yes 100%%!!!

**Comment by daniellockyer** [comment]
Perfect! Will merge once we've fixed CI on master 🎉

**Pull request merged**
