### PR TITLE
Translation from English to Spanish. Proof reading, and checking against official Spanish dictionary called Real Academia Española.

### PR DESCRIPTION
**Pull request by fochoa8**
Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ ] There's a clear use-case for this code change, explained below
- [x] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

### CODE REVIEW

**Comment by fochoa8** [comment]
Check the translation, did it already on all files.

**Comment by sagzy** [comment]
@fochoa8 👋 

Thanks for the additional PR! We've just reviewed and merged your first PR (https://github.com/TryGhost/Ghost/pull/21232), and there are now two variants of some of the suggested translations in `ghost/i18n/locales/es/comments.json`.

Could you:
- merge the latest changes from main into your current branch
- review what the final translations should be, and then ping us again for a review?

Thank you

**Comment by sagzy** [comment]
Related: https://github.com/TryGhost/Ghost/pull/21167

**Review by fochoa8 — COMMENTED** [review]
Reviewed all comments for changes as suggested. Thank You for Your time

**Comment by sagzy** [comment]
LGTM, merging 🙌

**Pull request merged**
