### PR TITLE
[WIP] Harvesting server-side strings

### PR DESCRIPTION
**Pull request by rfpe**
See  #5617

TODO list:
- [x]   /core/server/api
- [x]   /core/server/data
- [x]   /core/server/models
- [x]   /core/server/helpers
- [x]   /core/server/middleware
- [x]   /core/server/apps
- [x]  /core/server/controllers
- [x]  /core/server/config
- [x]  /core/server/permissions
- [x]  /core/server/utils
- [x]  /core/server/ghost-server.js
- [x]  /core/server/index.js
- [x]  /core/server/mail.js
- [x]  /core/server/require-tree.js
- [x]  /core/server/update-check.js

### CODE REVIEW

**Comment by rfpe** [comment]
I could use some help with i18n.js ... I believe that there is a bug on how it loads the translation/en.js file.

    C:\temp\Ghost\core\server\i18n.js:68
               matchingString = matchingString[key] || null;
                                              ^
    TypeError: Cannot read property 'errors' of undefined
       at C:\temp\Ghost\core\server\i18n.js:68:44
       at Array.forEach (native)

**Comment by halfdan** [comment]
I think you may have to call `i18n.init()` for those tests to run - https://github.com/TryGhost/Ghost/blob/14c35ea56c73169e93678f88727e0d2963d72c04/core/server/index.js#L190-L191

**Comment by rfpe** [comment]
@halfdan you are right. However, I am not sure where is the best place to do so. Suggestions?
Calling it here resolves the problem with starting Ghost, but no luck with the tests.
https://github.com/TryGhost/Ghost/blob/1e4c7c4b0c217d6fc22e464c4898c3a2f0d81d89/core/server/utils/startup-check.js#L24

Bear with me, I'm new to js and Ghost's lifecycle :)

**Comment by morficus** [comment]
hey @rfpe - are you still chugging along with these?
If you're not sure if you'll have time for the remaining 2 directories (`/core/server/api` and `/core/server/data`), could you just clean up the history (in accordance to the [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#submitting-pull-requests)) so we can get this long-running PR merged in?

Then somebody else (or you self) can pick up the remaining items and open new PRs as needed.

**Comment by rfpe** [comment]
Hi @morficus - yes, I am working on it. I think I will complete it by today.

**Comment by rfpe** [comment]
@morficus I completed harvesting the strings, but still need to figure out why the tests are failing in my machine. Thoughts?

    Update Check
    3) should report the correct data
    27 passing (33s)
    3 failing
    1) Import DataImporter doesn't import invalid post data from 001:
    TypeError: Cannot read property 'message' of undefined
    at C:\Users\rfpe\Documents\GitHub\Ghost\core\test\integration\import_spec.js:251:25
    2) Import 002 doesn't import invalid post data from 002:
    TypeError: Cannot read property 'message' of undefined
    at C:\Users\rfpe\Documents\GitHub\Ghost\core\test\integration\import_spec.js:415:25

**Comment by morficus** [comment]
@rfpe did you run `npm test` before doing a git-push?
Running that command before pushing is always a good idea, since it will run through all the same tests as Travis-CI and allow you to debug any failed tests locally (which is much easier :-) ).

**Comment by rfpe** [comment]
@morficus I did, I just couldn't find my mistake and wanted another pair of eyes on it. 
Is there a better way to do so? Thanks, btw :+1:

**Comment by morficus** [comment]
Hm... Now it seems like i18n.init() was not called somewhere? I can take a closer look once I'm home this evening.

**Comment by morficus** [comment]
@rfpe 
**Here is what I discovered**:

The test is failing because data migrations are tested outside the regular app flow, which means no i18n strings get loaded... which result in i18n.t() failing and ultimately the test failing.

**Here is what I suggest**:
So to get around this. `i18n.init()` needs to be called [here](https://github.com/TryGhost/Ghost/blob/master/core/test/utils/index.js#L378) during the unit test.

Along those same lines, the initialization of the i18n module during the apps startup process needs to be moved [from here](https://github.com/TryGhost/Ghost/blob/master/core/server/index.js#L191) to line 151 of that same file (that way the strings needed for translations are literally the first thing loaded during the startup process) <-- that is not causing a problem yet, but it could/will in the future.

**Comment by JohnONolan** [comment]
@morficus @rfpe This has gone stale - and it would be a real shame to lose all of this work and have to start over. Could one of you pick this up, refresh, and fix tests per the instructions above? **All** other i18n is essentially blocked on this PR now, so it would be really :+1: to get it moving again!

**Comment by ErisDS** [comment]
It seems we need to resolve the testing issues before we can move forward with this. It would be great to get a separate PR to fix that part and then we can unblock this?

**Comment by kevinkucharczyk** [comment]
I've had a quick look at the failing tests in this PR and the tests are failing during the `cleanDatabase` grunt task, as it's trying to run methods on `models` and `migration` without i18n being initialized.

I believe this could be fixed by either running `i18n.init()` in the `cleanDatabase` task directly, or by adding a check inside the `findString` method of `core/server/i18n.js`:

```
findString: function findString(msgPath) {
        // ...
        if (blos === undefined) {
            I18n.init();
        }

        matchingString = blos;
        // ...
    }
```

This would add a failsafe for whenever i18n is used without initializing it first.

**Comment by ErisDS** [comment]
Going to close this now as #6070 was merged.

**Pull request closed without merging**
