### PR TITLE
Move the "update available" notification to the about page

### LINKED ISSUE #5071: Update Notifications 2.0
A little while back, we added a system to Ghost which regularly asks Ghost.org if there's a new version of Ghost available.

Ghost.org replies with a little bit of JSON like this:

```
{
  "version": "0.5.0",
  "next_check": 1427366737
}
```

This tells Ghost what the current version is, and when it is allowed to ask again. 

Inside of Ghost, this is wired up to our notification system, and if the version number goes above the current version of Ghost, a special notification is shown at the top of Ghost, on all pages, which doesn't go away until the blog is upgraded.

The major problem with this, is that it's incredibly invasive and annoying, so we're currently only using it for major version updates, rather than minors, so as not to infuriate our users when we do fast releases. Clearly, that makes the system significantly less useful.

The second problem is that the message in the notifcation is hardcoded inside of Ghost, and that makes it not particularly useful. There's no way to say 'hey, this interesting thing happened and that's why you should update'. There's also no way to send a notification outside of a version change, which is quite limiting.

To make this whole system SIGNIFICANTLY more useful both to us and to our users, I want to make the following changes:
### Move the "update available" notification to the about page.

As this is where the version information is currently shown, lets show the update information here. It means that users have to check the page to find out, but it does at least mean the information is always to hand in an easy to find place.
### Add support for custom messages

The updates endpoint on Ghost.org is going to be updated to send back a little bit more JSON, that will look like this by default:

```
{
  "version": "0.5.0",
  "next_check": 1427366737,
  "messages": []
}
```

When we want to display a message to our users, it will look like this

```
{
  "version": "0.5.0",
  "next_check": 1427366737,
  "messages": [{
    "id": ed9dc38c-73e5-4d72-a741-22b11f6e151a,
    "version": "0.5.x",
    "content": "<p>Hey there! 0.6 is available, visit <a href=\"https://ghost.org/download\">Ghost.org</a> to grab your copy now<!/p>" 
  ]}
}
```

The intention is that Ghost will read these, and display these custom notifications in the top notification spot where update notifications used to go, allowing us to push a particular release or feature, without interfering with the general concept of 'is there an update available'. The 'top' notifications will need to be changed to be dismissible, unlike the existing version.

**Note:** At some point since 0.5.0, there has been a regression in the notification system, such that top notifications are no longer shown in the correct spot at the top of the screen, but appear in the normal bottom left 'toaster' location. This will need fixing.

Each custom message from Ghost.org will have 3 properties, firstly a GUID which should be stored in an array of `seenNotifications` in the settings table once a message is dismissed, so that the message is not shown again. Secondly, a version string which adheres to semver - this is to indicate which versions of Ghost the notification should be shown to. Finally the HTML content for the notification is provided in full, but should be sanitized via the caja tools already in the Ghost admin client, to ensure this cannot be abused. 

Once we have this in place, we then have 2 different notification concepts driven on versioning - whether or not there is an update available, which is simple factual information and custom messages, which provide an opportunity to communicate important details to our users. 

- [x] update LTS code base
- [ ] port changes to 1.0, https://github.com/TryGhost/Ghost/pull/9123
- [x] add UI @kevinansfield, https://github.com/TryGhost/Ghost-Admin/pull/894

### PR DESCRIPTION
**Pull request by naz**
closes #5071
- adds update notification message to about page
- creates a separate service/component for update notification message

### CODE REVIEW

**Comment by Gargol** [comment]
The simplest way to test the notification is working:
- add `display.value = '0.5.4;` to /ghost/core/server/update-check:210
- change version in package.json:3 to `  "version": "0.5.0",`

**Comment by Gargol** [comment]
At the moment only first part of the task is working `Move the "update available" notification to the about page.`, working on the second part.

**Comment by Gargol** [comment]
Added support for dismissible remote update notifications. At the moment cleaning up the code and adding some tests.

**Comment by Gargol** [comment]
Was working on getting some additional integration tests for this functionality but it looks like that is way to hard in existing test environment. Would love to improve this code and maybe work with someone in a pair to get more test coverage on it.

**Comment by ErisDS** [comment]
Sorry for leaving this without a response for such a long time - the release of Zelda was crazy busy & I just haven't gotten around to testing this out just yet. 

The refactoring work in this PR looks like it's a massive step in the right direction, although there are a few bits left to cleanup & add, like sanitisation of the custom messages & formatting of the default one. I'm happy to work through this if you're still interested in wrapping this up?

**Comment by Gargol** [comment]
Hey Hannah. Would love to finish this one up. No worries about the delay, ghost team did a great job delivering Zelda! What are your thoughts on formatting and sanitisation?

**Comment by ErisDS** [comment]
Hey @Gargol - I was referring to differences between the PR and what was in the original issue. The issue asked that HTML content from the messages be sanitised using google caja, which I didn't see in the PR, and the version message on the about page doesn't include the version.

I need to review the code more closely to understand why - but when I tried testing it out I got a notification with the word `test`, which I should only get if there is a message sent from the update server. That hasn't been updated yet so there shouldn't be any - but I guess you wired it up to make it easier to test.

I can update that endpoint to return a message to anyone on < `0.7` at some point this week, if that would be helpful.

**Comment by Gargol** [comment]
I need to refresh myself on this codebase/issue as well, it has been a while since I wrote it. From what I recall I didn't use `caja` because there was some code for doint that in ember (`gh-format-html`). As for the rest, I'll try to find some time this week to polish this code :smile:

**Comment by ErisDS** [comment]
:+1:

**Comment by Gargol** [comment]
Hi @ErisDS , had a look into the code base and updated the default notification to have something meaningful. 

In terms of sanitation first question is: do we do it on the server side in addition to the client? If yes, which library should be used. I did some initial research and caja doesn't seem to have any good ports to node. On the other hand this project seems to be well mainained - https://github.com/punkave/sanitize-html

**Comment by ErisDS** [comment]
> In terms of sanitisation first question is: do we do it on the server side in addition to the client? If yes, which library should be used. I did some initial research and caja doesn't seem to have any good ports to node. On the other hand this project seems to be well mainained - https://github.com/punkave/sanitize-html

No, I missed that `gh-format-html` was doing the sanitisation. 

Rather than a default notification, I'd test this out by adding the logic to detect if there is a message to show, and then have a snippet of code that you put in the PR/test notes which will overwrite the response from the updates server.

**Comment by acburdine** [comment]
Closing as this was merged in as a part of TryGhost/Ghost-Admin#102

**Pull request closed without merging**
