### PR TITLE
Improved code of date helper

### LINKED ISSUE #7182: Date helper is returning current dates with wrong timezone
Date helper is returning current dates with wrong timezone, due to options.data.blog.timezone returning default timezone ('Etc/UTC'), even if it is changed in settings panel.

### Issue Summary

Inside the date helper, using console.log on options.data.blog.timezone, it is possible to see that 'Etc/UTC' is being returned as the blog timezone, even if another timezone is set.

### Technical details:

* Ghost Version: 0.9.0
* Node Version: 4.4.7
* Browser/OS: Chrome/OSX
* Database: SQLite

### PR DESCRIPTION
**Pull request by stldo**
Trying to fix https://github.com/TryGhost/Ghost/issues/7182, I have made some changes in the date helper. If it was calling this._published, two instances of Moment.js were being created to generate a result.

### CODE REVIEW

**Comment by ErisDS** [comment]
Hey @sbtoledo!

Thanks for taking the time to provide a fix 😀 This refactor looks great 👍 

Could you please add tests which show the behaviour that was broken before is now fixed? This ensures that details like this don't regress in future.

Also, if you could please update your commit message to match [this format](https://github.com/TryGhost/Ghost/wiki/Git-workflow#commit-messages) that would be very much appreciated.

All of this info is compiled in our [pull request guide](https://github.com/TryGhost/Ghost/blob/master/.github/CONTRIBUTING.md#pull-requests) in the contributing guidelines if you're looking for details.

**Comment by sbtoledo** [comment]
Hi @ErisDS, sorry, the bug wasn't fixed, the problem is in another part of the code, outside the helper. I made a custom helper that fetches the value from db and store it in a variable, as a temporary fix, and just wanted to contribute with the resulting code. I'm with a lot of work and didn't have the time to examine the problem more deeply.

**Comment by kirrg001** [comment]
Hey @sbtoledo Thanks for your effort so far. We would like to see this fix in our new release `0.9.1`, which is scheduled for 23rd of August. Could you please inform us if you can or cannot finish your PR until then?Thank you so much!

**Comment by kirrg001** [comment]
@sbtoledo Hey Hey, could you please tell me if i should take over the issue or if you would like to finish it until the 22rd of August?Thank you so much!

**Comment by kirrg001** [comment]
closing in favour of #7232

**Pull request closed without merging**
