### PR TITLE
Modify regex to allow subdir/ghost urls.

### PR DESCRIPTION
**Pull request by patrickskim**
Fixes a bug where reset password and invite links do not route to the right destination.

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!
- [x] Commit message has a short title & issue references
- [x] Commits are squashed 
- [x] The build will pass (run `npm test`).

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by kirrg001** [comment]
Hey @patrickkim 👋

Thanks for your PR and good catch. I can confirm this bug.
The tests are failing, because there is test asserting that this behaviour is not allowed.
See `test:core/test/unit/admin_spec.js`.

An alternative solution to this would be to make the regex very specific to the subdir configuration.
You can fetch the subdir via `utils.url.getSubdir`.

**Comment by patrickkim** [comment]
Will do.

**Comment by patrickkim** [comment]
Suggested changes have been applied. The tests are green.

**Review by kirrg001 — APPROVED** [review]
Thank you 👍

**Pull request merged**
