### PR TITLE
Improve test coverage for mailer

### LINKED ISSUE #5489: Group mail-related functionality together
Ghost only sends 4 types of emails at present:

- welcome
- forgotten password
- user invite
- test email

The code used for sending these emails + the templates is currently quite spread out in the codebase.

I recommend doing something like the following:

- [x] moving mail.js to mail/index.js
- [x] moving  the `email-templates` directory into the new `mail` directory
- [ ] reviewing the test coverage and seeing if it can be improved easily.

It would also be nice to (maybe?) move the logic around sending each individual email into the Mail API, e.g. moving the `sendInviteEmail` function from `api/users.js` into `api/mail.js` and doing similar for the welcome and forgotten password emails. Note that this requires changing API calls inside those functions to use the dataProvider directly, otherwise there would be circular dependencies api/mail.js -> api/user.js -> api/mail.js. 

There might be another way to do this, the goal being to reduce complexity in the user and authentication api files, and keep all mail related stuff together.

See also #5350

### PR DESCRIPTION
**Pull request by damsonn**
closes #5489

### CODE REVIEW

**Comment by damsonn** [comment]
Coverage is up, but it is spread between `mail_spec` and `api_mail_spec` (so in coverage report of *unit* and *integration*). 

I would argue that most of the tests should be in `mail_spec`, as they cover the mailer logic and not the api. But I left it as it is for now.

screen shot 2016-01-13 at 9 26 12 pm

**Comment by ErisDS** [comment]
I agree that as a further improvement it would be better to move the tests to all be in mail_spec and get better coverage in the unit tests. V. happy to merge this as a first step, but it would be better I think to mark it as 'refs' rather than 'closes' so that the issue stays open. 

When it comes to unit testing, not all files need to be tested but I think those that do need it should be as near to 100% as possible.

**Comment by damsonn** [comment]
:+1: 
I'll do that tomorrow so we can keep it as one PR

**Comment by damsonn** [comment]
@ErisDS that's as far as I can go with nodemailer stub...

screen shot 2016-01-23 at 11 29 28 am

**Comment by ErisDS** [comment]
:+1: thanks

**Pull request merged**
