### PR TITLE
[WIP] Update dependencies

### LINKED ISSUE #10755: Update knex.js
Currently Ghost is two major versions (soon to be three) behind the current latest and greatest of knex. Are there any particular reasons, e. g. known backwards incompatibilities or regressions that resulted in locking knex to an old version?
If anything needs to be done to make update feasible, I would like to volunteer for that effort :)

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #10755

### CODE REVIEW

**Comment by kibertoad** [comment]
I suspect that tests are failing due to knex version mismatch with brute, so it might be helpful to merge https://github.com/llambda/brute-knex/pull/8 first :)

**Comment by allouis** [comment]
@kibertoad Thanks for the PR :fist_oncoming: ! 

Would you mind pinging us when the brute-knex PR is merged and we can try run the tests again :relaxed:

**Comment by gargol** [comment]
Hey @kibertoad :wave: We have turned on Renovate this week, so handling dependency bumps now and this PR came back on the radar :smiley: 

Have pinged the maintainer on brute-knex PR to get the :soccer: rolling. Also, have closed Renovates attempt to bump `knex` all the way to `0.18.1` in favor of this PR (so we should bump to that version instead of `0.17.x`). 

Would be good to rebase the changes to get up to speed with master and only keep it to updating knex/bookshelf deps (csv-parser bump was handled separately). Please let us know if could be helpful with anything?

**Comment by gargol** [comment]
Hey @kibertoad! brute-knex has released a new version with a [bump](https://github.com/llambda/brute-knex/pull/8) to knex. Think we can move this PR forward this week?

**Comment by kibertoad** [comment]
OK, so there seems to be a deeper issue underneath, that would require manual debugging to figure out what's going on, as CI logs are pretty uninformative. It'll take some time to setup locally, though.

**Comment by gargol** [comment]
@kibertoad 	the last commit didn't seem to have caused a rebuild on the CI :thinking: 	 Maybe worth rebasing current changes ver master and force-pushing to this branch?

**Comment by gargol** [comment]
hi @kibertoad! just a heads up: we have merged brute-knex v4 bump due to security reasons :wink:

**Comment by gargol** [comment]
It's been a while since this PR started, and there hasn't been much activity. Closing it in favor of handling the version bumps by Renovate.

**Comment by kibertoad** [comment]
@gargol My apologies, still couldn't make it work locally. If renovate upgrade works, then by all means it's a better approach.

**Comment by gargol** [comment]
No worries @kibertoad, the effort is also appreciated! :wink:

**Comment by kibertoad** [comment]
Thank you!

**Pull request closed without merging**
