### PR TITLE
Fix navigation item validation behaviour

### PR DESCRIPTION
**Pull request by kevinansfield**
refs #6433 
- validate last nav item when clicking the `+` button
- validate all nav items when saving
- ignore the last nav item when saving if it's completely blank

### CODE REVIEW

**Comment by ErisDS** [comment]
It's possible I'm misunderstanding this, but it seems to do the opposite of what it says on the tin?



It seems to validate the last item, and not the others, whereas the commit message suggests the behaviour is that the last item should be ignored?

**Comment by kevinansfield** [comment]
That's strange, will check again, it's possible I got some code mixed up between the two nav branches I had on the go.

**Comment by kevinansfield** [comment]
What steps were you taking to show the validation errors? If you click the `+` icon it will always validate as it gives immediate feedback to the button press. Saving when the last item is completely blank should reset the errors and save OK.

**Comment by kevinansfield** [comment]
I've updated the PR text, it wasn't particularly clear.

**Comment by ErisDS** [comment]
:+1:

**Pull request merged**
