### PR TITLE
Pull requests_config.yml 

### PR DESCRIPTION
**Pull request by Somnamboo**
Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test` and `yarn lint`)

More info can be found by clicking the "guidelines for contributing" link above.

_config.yml

#I am surprised myself. I'm just getting to know this apps.
Security vulnerabilities in the environment of another application.
Jekyll vs Cayenne for Ghost.
The scanner suggests: Possible to merge.
Fixes #

### CODE REVIEW

**Comment by Somnamboo** [comment]
#11982

**Comment by Somnamboo** [comment]
Test Suite

**Comment by Somnamboo** [comment]
[Test [https://github.com/Somnamboo/Ghost-reflex/actions/runs/314142244](url))

**Review by Somnamboo — COMMENTED** [review]
unable to render the document prior to diffing

**Comment by naz** [comment]
@Somnamboo please read Ghost's [contributor's guide](https://github.com/TryGhost/Ghost/blob/master/.github/CONTRIBUTING.md). Any changes/features should have prior discussion on forum or GH issues before PR submission.

**Pull request closed without merging**
