### PR TITLE
🐛Fix access to the common article for multiple editors

### LINKED ISSUE #10212: Multiple editors with access can't edit the common article
### To Reproduce

1. Create new article
2. Add 2+ people
3. Try edit:
obraz

Only the first person on the list can edit the content (any time).
**Editing by single person, never more in one moment.**

### Technical details:

* Ghost Version: latest (2.6.1)
* Node Version: 10.13.0 LTS
* Browser/OS: Firefox, latest stable/W10
* Database: MySQL

### PR DESCRIPTION
**Pull request by kacperduras**
Fixes #10212
/cc @gargol

### CODE REVIEW

**Comment by gargol** [comment]
That was quick @kacperduras, thanks! I'll try to look into this next week :smiley: Couple thing that would suggest changing/adding right away:
- following our [commit message](https://github.com/TryGhost/Ghost/blob/master/.github/CONTRIBUTING.md#commit-messages) naming convention 
- and adding few unit tests for the bug this change is fixing (you'd need to create a new suite as there have been no unit tests for this module)

Feel free to reach out if you have any questions.

**Comment by kacperduras** [comment]
Ok, thanks a lot. I haven't got a time in this moment, but tomorrow - no problem :D

**Comment by kacperduras** [comment]
@gargol 

```
[...] following our commit message naming convention
```

Fixed.

```
and adding few unit tests for the bug this change is fixing (you'd need to create a new suite as there have been no unit tests for this module)
```

Any suggestion for the location of the file?

**Comment by rishabhgrg** [comment]
Hey @kacperduras 👋 

Small fix needed for the commit messages, they  need to be in past tense as per the [convention](https://github.com/TryGhost/Ghost/blob/master/.github/CONTRIBUTING.md#commit-messages), so `Fixed` in this case. You can also combine these 2 commits into a single commit.

For the location of test file, that needs go into `core/test/unit/models/relations/authors_spec.js` as the test folder structure here mimics the structure of main file. 😄

**Comment by gargol** [comment]
@kacperduras any progress on the unit tests? :smiley:

**Comment by kirrg001** [comment]
@gargol Hey 👋How about

- you double check the requested code changes again
- merge if it looks good to you
- and if a unit test is 100% required and helps avoiding critical bugs, push one test straight to master afterwards (or to this branch) :)

Would love to see this commit in master and in the release tomorrow 👍 🤩👻

**Comment by kacperduras** [comment]
@gargol Sorry, but I was very busy and I forgot :\ I promise that it will not happen again :)

**Pull request merged**
