### PR TITLE
Point to Forum Instead of Slack in Default Themes Post

### PR DESCRIPTION
**Pull request by dbalders**
No Issue

 - Changes the default themes post to direct users to the Ghost forum
rather than slack
- Updates the tests to reflect this change

### CODE REVIEW

**Review by kirrg001 — APPROVED** [review]
Thanks 😇

**Comment by dbalders** [comment]
Didn't think about this requiring a DB version bump. If this is something you want to proceed with, let me know. I will prob need help updating the hash or whatever is needed.

**Comment by kirrg001** [comment]
Only `/test/unit/data/schema/integrity_spec.js` needs a manual fix.

**Comment by vikaspotluri123** [comment]
>  I will prob need help updating the hash or whatever is needed

I think you can just use the hash that was in the failed test (`0ebf7476d2aec55014643fb577002cc8`)

**Comment by dbalders** [comment]
@vikaspotluri123 thanks, looks to be working.

**Pull request merged**
