### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pensierinmusica**
Added link to changelog

### CODE REVIEW

**Comment by jaswilli** [comment]
Hi @pensierinmusica,

I don't think there needs to be a link to "releases" in the README.  It's a standard part of every GitHub repository and the link is already featured at the top of the page.

**Comment by pensierinmusica** [comment]
Hi @jaswilli, the PR follows this thread: https://github.com/TryGhost/Ghost/issues/4929

(sorry for not mentioning it earlier in the original commit message)

I thought it was sort of more convenient for users to have a direct reference to it at the end of the docs, as not all projects implement the "releases" feature.

**Comment by ErisDS** [comment]
We've just completely rewritten the README, hopefully everything is much clearer now :)

**Comment by pensierinmusica** [comment]
Thanks!

**Pull request closed without merging**
