### PR TITLE
Added Nepali locale for Ghost

### PR DESCRIPTION
**Pull request by sparshrestha**
- [x] Created a new folder `ne` based on locale code for Nepali locale inside `ghost/i18n/locales/`
- [x] Cloned 6 new JSON files pertaining to `en` folder from English locale.
- [x] Added all field translations from English to Nepali for `ghost.json` file.
- [x] Added all field translations from English to Nepali for `search.json` file.
- [x] Added all field translations from English to Nepali for `signup-form.json` file.
- [ ] TODO: Remaining 3 other files viz. `comments`, `newsletter`, and `portal`.

"Thank you for creating Ghost and making it open source.": "Ghost सिर्जना गरेर यसलाई ओपन सोर्स बनाउनु भएकोमा धन्यवाद।"

### CODE REVIEW

**Comment by cathysarisky** [comment]
You will also need to update the SUPPORTED_LOCALES in i18n.js to include this one.

**Comment by sparshrestha** [comment]
[Updated i18n.js to support Nepali locale](https://github.com/TryGhost/Ghost/pull/21552/commits/59b668282752ef9c9bdb7ab5471093fa378081ed)

**Review by cathysarisky — APPROVED** [review]
An AI review of ghost.json looks good.  If you plan to add the other translation files, we can wait a bit before merging?

**Comment by sparshrestha** [comment]
@cathysarisky Sure. I'll add more in the days to come

**Review by cathysarisky — APPROVED** [review]
These pass an AI check.

**Comment by sparshrestha** [comment]
#21635 - Added Nepali locale for newsletter.json

**Pull request merged**
