### PR TITLE
Bumped ghost-ignition version to 3.1.0

### PR DESCRIPTION
**Pull request by rshbhgrg**
no issue

- Bumped ghost ignition to 3.1.0 for unified logging across all Ghost Pro blogs
- Added new logger options
- Includes stringification update for Ignition based on https://github.com/TryGhost/Ghost/commit/9810834f7b4b5728590839254d6e365d291e8265

### CODE REVIEW

**Comment by rishabhgrg** [comment]
@gargol Can you please give this a quick 👀?  Just want to make sure haven't missed anything obvious with ignition update 😄

**Review by naz — APPROVED** [review]
These are good to go :+1:  The only other difference logging wise with the upstream that there were some additional improvements to 'double stringification' issue when logging - https://github.com/TryGhost/Ghost/commit/9810834f7b4b5728590839254d6e365d291e8265, but I don't think that's super important to keep up in both versions :thinking:

**Comment by rishabhgrg** [comment]
@gargol Thanks! 😄Hmm I agree its not super important improve 'double stringification, but could lead to weird double stringified values in logs compared to latest, which won't be nice. Seems like a quick change to files as https://github.com/TryGhost/Ghost/commit/9810834f7b4b5728590839254d6e365d291e8265 here already, I'll do a quick update before releasing. :)

**Comment by rishabhgrg** [comment]
@gargol Updated to include stringification changes as well now ⏲

**Comment by gargol** [comment]
Think it's good to :rocket:

**Pull request merged**
