### PR TITLE
pt-br new i18n strings

### PR DESCRIPTION
**Pull request by sergiospagnuolo**
Add pt-br (Brazilian Portuguese) translations for Portal and native search strings.

### CODE REVIEW

**Review by cathysarisky — APPROVED** [review]
Thanks for these!

**Comment by ronaldlangeveld** [comment]
Thank you for your ongoing translation efforts! 🙏🏻 We’ve made updates with search i18n and some new Portal strings 🔍. You may find a few more strings to translate—if you come across any that need work in PT-BR, don’t hesitate to reach out! 🎉

**Comment by sergiospagnuolo** [comment]
Where we supposed to see the changes right now? I am running the latest version but it does no seem to reflect the current translations. Or am I missing something? 

Captura de Tela 2024-10-01 às 08 35 48

**Comment by cathysarisky** [comment]
I think the last release didn't actually include a fresh release of search.   I think we're waiting on the next release, because there were a bunch of new strings merged yesterday and a bunch more in the works this week -- so one version bump & release at the end of the week right before release?

**Pull request merged**
