### PR TITLE
Speed up routing tests

### PR DESCRIPTION
**Pull request by kirrg001**
refs #9178

- the first test will start the ghost server
- all following test will reuse the server and only truncate the database tables
- you can always force to restart the server
- truncate instead of reset db
- we have to ensure that reusing the server requires us to
  - e.g. reload the settings
  - e.g. reload active theme
- remove fork functionality (you can use `forceStart: true`) - it was super annoying to support the normal way to start Ghost and the fork 🙌🏻
- no test has changed, just the way to start the server

**The next step is: reduce routing tests to a minimum and move as much as possible edge cases to unit tests (if possible).**

### CODE REVIEW

**Comment by kirrg001** [comment]
~ 2-3 minutes faster. It reflects what i saw locally. Routing tests on sqlite need 1m with this PR and 3m on master.

If we reduce and tidy up our tests in general, we can expect another bump.

**Comment by kirrg001** [comment]
I think the chance getting random test failures should decrease, because we have removed the fork functionality. Will see.

**Comment by kirrg001** [comment]
@ErisDS Assigning you to share the knowledge.

Example: https://github.com/kirrg001/Ghost/blob/2582c11c13bdc8d328a881304fdc6dbac0ec9d8b/core/test/functional/routes/api/configuration_spec.js#L12

- no need to start the server
- no need to stop the server
- no need to clean the data afterwards (truncation happens automatically)
- re-use the running server by default
- you can force the server to restart (`{forceStart:true}`)
- there also some more options if needed (https://github.com/kirrg001/Ghost/blob/2582c11c13bdc8d328a881304fdc6dbac0ec9d8b/core/test/utils/index.js#L836)
- the fork helper is dead, you can simply force to restart
- the os tmp folder is not cleaned up, but not really really important

Next step is to reduce the routing tests in general 😀

**Review by ErisDS — APPROVED** [review]
Really Nice 👍

**Pull request merged**
