### PR TITLE
Bump markdown-it to 8.4.1, so uc.micro bumps to 1.0.5 and it is now MIT licensed

### PR DESCRIPTION
**Pull request by silviofdez**
Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

uc.micro npm package had a WTFL prior to 1.0.5 version, this package is a dependency for markdown-it, which is a dependency of Ghost itself.

If we bump markdown-it from 8.4.0 to 8.4.1, then uc.micro bump from 1.0.3 to 1.0.5 and all the components/packages included installing Ghost have a License OSI approved.

This is important because there are certain cloud providers that do not allow to publish software with WTFL license

- [ X ] There's a clear use-case for this code change
- [ X ] Commit message has a short title & references relevant issues
- [ X ] The build will pass (run `npm test`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Review by kevinansfield — APPROVED** [review]

**Comment by kirrg001** [comment]
I'll look into failing tests soon. Looks like their is a bug in our tests.

**Comment by silviofdez** [comment]
Thanks @kirrg001 , please let me know if there is something I can help on my side.

**Comment by kirrg001** [comment]
@silviofdez Could you pls rebase against master? The tests should then pass 👍

**Comment by silviofdez** [comment]
@kirrg001 rebased (using this guide: https://help.github.com/articles/syncing-a-fork/), but still some tests failing

**Comment by kirrg001** [comment]
@silviofdez I've restarted the build. Travis is sometimes super slow in the evening and the chance that builds fail randomly is higher than normal. Let see if it passes now.

**Comment by silviofdez** [comment]
Thanks @kirrg001 , all green now!!! 😄

**Comment by kirrg001** [comment]
@silviofdez 😀That really took long. Travis is out of control. Thanks again for your PR!

**Pull request merged**
