### PR TITLE
Add translation es for server:

### PR DESCRIPTION
**Pull request by roramirez**
Is added translations for spanish language of server strings.

### CODE REVIEW

**Comment by ErisDS** [comment]
Hi @roramirez I appreciate you taking the time to do this. Unfortunately the implementation of translations is completely unfinished.

It is also not the intention that translation files would be included direct into the codebase, but via a kind of plugin that we've loosely referred to as "language packs". Still all of this is no more than an idea at present.

To get a better idea of the state of i18n features in Ghost you can read the issues with the [i18n](https://github.com/TryGhost/Ghost/issues?q=is%3Aopen+is%3Aissue+label%3Ai18n) tag and join the #i18n channel in our [slack community](https://slack.ghost.org).

**Comment by roramirez** [comment]
Hi @ErisDS 

So, when the translations implementation ise finished will can use this strings for Spanish language.

I'll check the issues with i18n tag.

Thanks.

**Comment by cristiandley** [comment]
How i can use this ? @roramirez

**Comment by roramirez** [comment]
Well ... As @ErisDS said, the feature for i18n is unfinished. I think can you only replace the core/server/translations/es.json  file by this one should work.

**Pull request closed without merging**
