### PR TITLE
Display error message on setup if origin doesn't match config.js url

### PR DESCRIPTION
**Pull request by kevinansfield**
refs #6106
- add error handler for authentication step of blog setup
- move setup acceptance test out of 'settings' folder

### CODE REVIEW

**Comment by ErisDS** [comment]
I have triple-checked this as I'm a bit jet-lagged, but it seems to me the setup screen is still spinning  endlessly when starting in production mode with the default my-ghost-blog.com.

**Comment by ErisDS** [comment]
FYI - all I'm doing is `npm install --production` with the default/example production config

**Comment by kevinansfield** [comment]
Stange, I'm doing the same thing here but I'm seeing the error message on this branch...

screen shot 2015-11-26 at 16 13 31
screen shot 2015-11-26 at 16 15 02

```
config = {
    // ### Production
    // When running Ghost in the wild, use the production environment.
    // Configure your URL and mail settings here
    production: {
        url: 'http://my-ghost-blog.com',
        mail: {},
        database: {
            client: 'sqlite3',
            connection: {
                filename: path.join(__dirname, '/content/data/ghost.db')
            },
            debug: false
        },

        server: {
            host: '127.0.0.1',
            port: '2368'
        }
    },

    ...
```

**Comment by ErisDS** [comment]
I had caching turned on. Sorry.

**Pull request merged**
