### PR TITLE
ES6 /helpers/author.js update #9589

### PR DESCRIPTION
**Pull request by hkd987**
Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ true ] There's a clear use-case for this code change
- [ true ] Commit message has a short title & references relevant issues
- [ true ] The build will pass (run `npm test`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by hkd987** [comment]
https://github.com/TryGhost/Ghost/issues/9589

REF

**Comment by kevinansfield** [comment]
@hkd987 you need to re-push without the `core/client` submodule being committed

**Comment by kirrg001** [comment]
The PR also needs a rebase. Thanks!

**Comment by kirrg001** [comment]
@hkd987 ping

**Comment by kirrg001** [comment]
@hkd987

**Comment by kirrg001** [comment]
Closing, because there is no activity. @hkd987 Feel free to re-open this PR when you are back :)

**Pull request closed without merging**
