### PR TITLE
Remove hbs comments from code injection

### LINKED ISSUE #6308: Get ghost_head and ghost_foot to ignore / remove handlebars comments
I've noticed a bunch of times that people copy snippets which include handlebars comments into the `ghost_foot` and `ghost_head` blocks in code injection.

The code injection blocks are currently treated as HTML, and simply included inline.

We could add some magic to strip out / ignore handlebars comments quite easily

Alternatively we could treat ghost_head and ghost_foot as templates and attempt to compile them as handlebars. Not sure what the pros/cons could be here (what do we do with errors?) but it may be worth exploring.

### PR DESCRIPTION
**Pull request by halfdan**
closes #6308

### CODE REVIEW

**Comment by ErisDS** [comment]
How well does this fix cope with markdown block comments, e.g.

```
{{!-- This is me commenting out a markdown block which doesn't work here
{{#if post}}... do something{{/if}}
--}}
<script><!-- ga snippet or somat --></script>
```

**Comment by halfdan** [comment]
@ErisDS Not so well. Good call! Will take a look tomorrow.

**Comment by halfdan** [comment]
@ErisDS This was updated FYI

**Comment by ErisDS** [comment]
Sorry for the slow response, I looked at it and something didn't quite sit quite right. 

Regexp have no idea about context, and it seems to me that even though at first I thought this would be straightforward & useful, now I see it I'm concerned about the interaction of various contexts. Seems somewhat unlikely for the sort of snippets that should go in code injection, but I'm worried we'll accidentally parse out something that should be there.

E.g. 
`var myVarName = "{{! who knows why my string looks like a markdown comment? }}"`

This makes me think we should handle it by using handlebars compile, instead of a regex, but that may lead to other problems, and I'm genuinely not sure what the correct course of action should be.

If we used compile to parse out comments, my expectation would be that there'd be no data or helpers etc made available to the template - so you couldn't use an `{{#if}}` because there'd be no data and it'd always be false. We'd just be using compile to remove the comments.

Perhaps that is introducing a huge overhead for not much reason - i.e. preoptimising based on my bad experiences with markdown regex parsers :joy:

**Pull request closed without merging**
