### PR TITLE
Updating Arabic Translation (installation, usage and config)

### PR DESCRIPTION
**Pull request by myhusam**
Hello, 

First, I am so sorry for being late but believe me typing Arabic in text editor is painful. 

Anyway, I almost did a half decent job and I promise the rest will follow soon. If you could please check if everything alright so I can move to the rest.

Thanks,
Husam

### CODE REVIEW

**Comment by ErisDS** [comment]
Any update on getting someone to sign this off?

**Comment by myhusam** [comment]
I aleady asked more than one but still got no respond. Anyway I am going to finish the reset soon hopfully someone will check after me :(

**Comment by mabouchalkha** [comment]
I can verify that if you want

**Comment by ErisDS** [comment]
@mabouchalkha Yes please - we just need someone to look through it and verify that the translations are basically correct. Not worried about the odd typo or grammar error - just that the instructions are generally right :)

**Comment by gtari** [comment]
https://github.com/myhusam
Hi Husam sorry i was liitle busy how is progress in arabic translate i can verify or finsh the rest if you want?

**Comment by myhusam** [comment]
Hi, no problem. If you could please verify what I've done it'll be great. 

Thanks

**Comment by ErisDS** [comment]
I'm going to close this now as we are going to remove this version of the documentation. The translated versions are out of date with the main documentation. Long term we're looking into solutions where we can use a service like transifex to properly track translations across the Ghost UI, documentation and website.

**Pull request closed without merging**
