### PR TITLE
🐛  be able to serve locked users

### LINKED ISSUE #8645: User profile pages return 404
### Issue Summary

When viewing a blog post, clicking the author name/link should take you to the profile page with their blog posts.

This works for the administrator but not other users; these users get a 404.

### Steps to Reproduce

Create a ghost blog instance using Ghost-CLI.

Import data from previous blog with multiple users.

Users are imported and can be viewed in admin; clicking their links in the blog returns 404 page.

### Technical details:

* Ghost Version: 1.0.0 Beta 2
* Node Version: 6.11.0
* Browser/OS: N/A
* Database: sqlite3

### LINKED ISSUE #8710: Author 404
Not sure what's happening here:

https://lionsroar.ghst.pro/the-buddha-taught-one-thing-only/

Author is listed as Sharon Salzberg, but when you click on her profile URL at the bottom of the post: https://lionsroar.ghst.pro/author/sharon-salzberg/ you get a 404

Within Ghost admin, the post shows as being authored by another user entirely:

image

Editing the content and saving/updating the post does not change anything.

This post was imported, so I'm not sure if it might be an import error. I have the import file if anyone wants it - not going to post it here because it has private user email addresses in it.

Wouldn't normally say this was a blocker, but given how much the importer is going to be used it seems like it might be one?

Ghost 1.0-rc1

### PR DESCRIPTION
**Pull request by kirrg001**
closes #8645, closes #8710

- locked users were once part of the category "active users", but were moved to the inactive category, locked users are right now imported users only
  -> we have added a protection of not being able to edit yourself when you are either suspended or locked
- but they are not really active users, they are restricted, because they have no access to the admin panel
- support three categories: active, inactive, restricted

### CODE REVIEW

**Comment by kevinansfield** [comment]
This works but it seems like suspended users are still not available? My understanding was that "suspended" is essentially the same as "locked" as far as the front-end is concerned - the users posts are kept and their profile is visible they just have no ability to access the admin area or reset their password.

**Comment by kirrg001** [comment]
I've interpreted this differently yesterday, but now that i think about it again, it makes sense to serve 200 for suspended users as well. I will add a another commit and then we can confirm with @JohnONolan before merging.

**Comment by JohnONolan** [comment]
> the users posts are kept and their profile is visible they just have no ability to access the admin area or reset their password.

This sounds right to me. The use-case behind this feature request is always that people have an author with some posts who is no longer a contributor to the site, so they want to suspend that author to prevent them from logging in, but not delete any of their content

**Comment by kirrg001** [comment]
👍  updated

**Pull request merged**
