### PR TITLE
Add the 'compress' and 'preloadHeaders' options to defaults.…

### LINKED ISSUE #9863: Add 'compress' and 'preloadHeaders' options to default.json config
It would make sense to add any configuration values that have some default behavior into [default.json](https://github.com/TryGhost/Ghost/blob/master/core/server/config/defaults.json#L57) file for easier lookup of available options in the app. First two candidates:

```
  "compress": true,
  "preloadHeaders": 0,
```

Compress behaves as being set to `true` by [default](https://github.com/TryGhost/Ghost/blob/cd690efad15dc51546d9099c59a59af88b641f42/core/server/web/parent-app.js#L28). As for [preloadHeaders](https://github.com/TryGhost/Ghost/blob/cd690efad15dc51546d9099c59a59af88b641f42/core/server/web/parent-app.js#L33) we need to add it's default value and investigate if anybody is using this feature (does it work properly? :thinking: ) and maybe think of further action after investigation.

### PR DESCRIPTION
**Pull request by lunaticmonk**
…json config (#9863)

Fixes #9863

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `npm test`)

### CODE REVIEW

**Comment by lunaticmonk** [comment]
@gargol seems to work fine.

**Comment by gargol** [comment]
Reviewed initial [conversation](https://github.com/TryGhost/Ghost/pull/6461) around netjet integration. @lunaticmonk the only change that would make is setting `preloadHeaders` to `false` instead of `0` as that's how it was [initially implemented](https://github.com/TryGhost/Ghost/pull/6461/commits/7bbfc37df6217233725b024473e05a794f555a77#diff-198522c016d444fe14bb9882f7614d2dR216). Will merge it in as soon as that value is updated :wink:  Thanks!

**Comment by lunaticmonk** [comment]
@gargol Done :thumbsup:

**Comment by lunaticmonk** [comment]
@gargol Done :thumbsup:

**Pull request merged**
