### PR TITLE
Stop gap measure to issue #9418

### PR DESCRIPTION
**Pull request by bartt**
Only accepts subscriptions that:

1. Have a referrer.
1. Originate from a valid blog post or static page on the Ghost site.

This prevents fake subscribers as reported in issue #9418.

A better long term solution would be to include a nonce and adding email verification to complete subscription.

### CODE REVIEW

**Comment by bartt** [comment]
I've dropped the requirement of the referrer field in the form data. But do require a referrer header in POST request to /subscribe. See https://github.com/TryGhost/Ghost/commit/f249382b87965aaa3be445921d84b24a2675e6a6. These changes will be part of the pull request if you're willing to reopen.

**Comment by kirrg001** [comment]
> But do require a referrer header in POST request to /subscribe

See [RFC](https://tools.ietf.org/html/rfc7231#section-5.5.2).

> A user agent MUST NOT send a Referer header field in an
   unsecured HTTP request if the referring page was received with a
   secure protocol

**Comment by bartt** [comment]
@kirrg001 there is no mixing of HTTP and HTTPS protocols here. Unless you want to allow 3rd party sites to POST to /subscribe to subscribe new email addresses on a Ghost site that is only accessible over HTTPS.

**Comment by kevinansfield** [comment]
I would prefer a solution that doesn't require a Referrer header. There's no guarantee that the header will be sent by a web browser.

By default we have the `'no-referrer-when-downgrade'` [referrer policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) set (no referer header is sent for requests to HTTP from HTTPS so same as most browser defaults) but this is configurable on a per-site basis so it's quite possible that certain blogs will not send any referer header with their requests. It's also possible for users to disable referer headers via their browser settings/extensions.

**Comment by ErisDS** [comment]
Wouldn't this: https://github.com/expressjs/csurf be a better option?

**Comment by bartt** [comment]
@ErisDS While use of nonce is a good thing to add, it wouldn't prevent these drive-by signups.

From my logs I can tell that it is always a request for the home page followed by a submission of the subscribe form:

```
[27/Feb/2018:18:04:55 +0000] "GET / HTTP/1.1" 200 8092 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KH
TML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
[27/Feb/2018:18:04:55 +0000] "POST /subscribe/ HTTP/1.1" 200 1367 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" confirm=&location=&referrer=&email=owlumuc%40hotmail.com
```

It appears that Javascript has been disabled or that the POST request follows so fast that Javascript hasn't populated the hidden location and referrer inputs. (I can't which as Cloudfare caches my Javascript assets so I don't see the Javascript requests.)

A nonce wouldn't prevent this kind of spam as the form is loaded from my site and then submitted. I'll rework my pull request to only inspect the location field and require it either maps to a valid post ID or (in case of the home page or /subscribe) at the very least matches the scheme and host of the site (i.e `scheme:://hostname:port`) of the site.

**Pull request closed without merging**
