### PR TITLE
New mobilemenu prototype

### PR DESCRIPTION
**Pull request by JohnONolan**
This is a prototype for how the new mobile menu should work - it needs picking up and emberifying by someone who knows what they're doing - ideally by PRing to this branch so we can keep all the work in one place (like Zelda).

So the main things are, when the viewport is below 800px:
- The following snippet is injected into `.view-title` on every page. 
  `<button class="gh-mobilemenu-button" role="presentation"><i class="icon-gh"><span class="sr-only">Menu</span></i></button>`
- The main navmenu is hidden (done with CSS)
- When the button is clicked, `.gh-main` gets a class of `.open` (the navmenu is revealed with CSS)
- When anywhere outside `.gh-nav` is clicked, `.open` is removed from `.gh-main` (the navmenu closes with CSS)

When the viewport resizes it should move gracefully between desktop menu and mobilemenu.

(Sorry about the framerate when the window is resizing - pull down this PR to test for yourself)

mobilemenu

### CODE REVIEW

**Comment by JohnONolan** [comment]
@novaugust Possibly one for you? I think you did all the stuff with old mobile-menu, which was similar

**Comment by ErisDS** [comment]
@novaugust this PR and master have deviated in extremely conflicting ways. I have attempted to rebase and was able to resolve the introduction of `{{gh-main}}` but am unable to resolve what to do with the removal of content-cover here vs the refactor in master.

Please can you have a go?

**Comment by novaugust** [comment]
@ErisDS Sure =)

**Comment by novaugust** [comment]
I've rebased this, it's living over at https://github.com/novaugust/ghost/tree/zelda-mobile-nav

**Comment by ErisDS** [comment]
Best approach to this is if @JohnONolan gives you collab on his repo then you can push over this branch. Second best is open your own PR from that branch and close this :wink:

**Comment by JohnONolan** [comment]
do the 2nd one - imo

**Pull request closed without merging**
