### PR TITLE
Removed duplicate stripe customers&subscriptions

### PR DESCRIPTION
**Pull request by allouis**
refs #12100

We want to add unique constraints to the subscription_id and customer_id
fields in the members_stripe_customers_subscriptions and
members_stripe_customers tables respectively. In order to do this safely
we must first ensure that no duplicate entries exist.

### CODE REVIEW

**Comment by allouis** [comment]
This needs to be updated to use the 3.29 directory

**Review by naz — CHANGES_REQUESTED** [review]
@allouis I think there might be something tricky going on with date comparisons determining "newest" record. Have run these migration on MySQL and SQLite and received different results for which record was considered "newest". Below are `members_stripe_customers_subscriptions` before and after migration. Notice that for SQLite the "oldest" record was left and for MySQL the "newest" one.

#### SQLite
pre migration
```
sqlite> select id, subscription_id, updated_at from members_stripe_customers_subscriptions;
5f2a228f233f8da9435a8394|sub_HmBMqvT838z8LZ|2020-08-05 03:07:59
5f2a22a5233f8da9435a8398|sub_HmBMqvT838z8LZ|2020-08-05 03:08:21
5f2a22ad233f8da9435a839a|sub_HmBMqvT838z8LZ|2020-08-05 03:08:29
```
post migration
```
sqlite> select id, subscription_id, updated_at from members_stripe_customers_subscriptions;
5f2a228f233f8da9435a8394|sub_HmBMqvT838z8LZ|2020-08-05 03:07:59
```

#### MySQL
pre migration
```
mysql> select id, subscription_id, updated_at from members_stripe_customers_subscriptions;                                                 
+--------------------------+------------------------------+---------------------+                                                          
| id                       | subscription_id              | updated_at          |                                                          
+--------------------------+------------------------------+---------------------+                                                          
| 5f294f40fba003f04f9bac27 | sub_5f295168251d48f42cbd2cf1 | 2020-08-05 00:06:24 |                                                          
| 5f29516a251d48f42cbd2cf3 | sub_5f295168251d48f42cbd2cf1 | 2020-08-05 00:15:38 |                                                          
| 5f29518abb1900f4966fa992 | sub_5f295168251d48f42cbd2cf1 | 2020-08-05 00:16:10 |                                                          
+--------------------------+------------------------------+---------------------+  
```
post migration
```
mysql> select id, subscription_id, updated_at from members_stripe_customers_subscriptions;
+--------------------------+------------------------------+---------------------+
| id                       | subscription_id              | updated_at          |
+--------------------------+------------------------------+---------------------+
| 5f29518abb1900f4966fa992 | sub_5f295168251d48f42cbd2cf1 | 2020-08-05 00:16:10 |
+--------------------------+------------------------------+---------------------+

**Review by kevinansfield — APPROVED** [review]

**Comment by allouis** [comment]
@naz The migration has been updated to only run for MySQL :relaxed:

**Review by naz — APPROVED** [review]
Tested scripts all over again on the set of 10K members (all with semi-real stripe_customers/subscriptions). The subscription orphan-detection script nicely picks up any "new orphans" that customer orphan detector might create :chains: Scripts ran very quickly as well :heavy_check_mark:

**Review by daniellockyer — APPROVED** [review]

**Pull request merged**
