### PR TITLE
[HOLD] Remove old body classes

### LINKED ISSUE #2597: Remove the old body classes
**Note:** This must only happen once we have shipped 2 releases in which the new, replacement `paged` and `page-{{slug}}` classes are available.

The new classes should become available with the closure of issue #1967, which should happen in the release after 0.5.0.

Once we are ready we need to remove the `archive-template` body class and also the `page-template-{{slug}}` classes. This is done in the `body_class` core helper.

### PR DESCRIPTION
**Pull request by alecho**
- closes #2597 

Please check the diff on the tests. I'm not 100% sure they have the expected behavior.

### CODE REVIEW

**Comment by alecho** [comment]
I'm not sure why this failed on io.js 1.2 in the testing environment: https://travis-ci.org/TryGhost/Ghost/jobs/59001415

Anyone know whats going on?

**Comment by novaugust** [comment]
If just one env is failing, it's more than likely just a problem with the tests. I've restarted the failing test, should go now

**Comment by ErisDS** [comment]
All of those deprecation issues are hanging around waiting for us to have better tools for informing users that their themes or blogs are about to break. I need to write up an issue documenting the plan for this & what's necessary. Although these are just some classes and the breakage would be minimal, I'd prefer to do all the deprecations we have so far in theme & config land at the same time.

**Comment by alecho** [comment]
Glad to see the build is passing and that it was just an issues with Travis running the tests. @ErisDS, can you confirm that the assertions are correct? I'm happy to target another branch or keep rebasing this one until `master` is ready.

**Comment by ErisDS** [comment]
The code is correct :+1:

**Comment by acburdine** [comment]
@ErisDS do we want to get this in for 0.9 since there's a lot of breaking changes there?

**Comment by ErisDS** [comment]
No, I don't know if we will ever do this now. I looked at doing it for 0.8 and found that Casper still uses the old classes, which means every theme that used Casper as an example also uses the classes.

I'm a bit stumped to be honest and it isn't really important.

**Comment by ErisDS** [comment]
Closing in favour of #7510 due to the divergence being too large to reconcile.

**Pull request closed without merging**
