### PR TITLE
🐛 Fix sidebar members number not updated after member create & delete

### PR DESCRIPTION
**Pull request by h2akim**
no issue

- Fix sidebar members count after creating and deleting members

### CODE REVIEW

**Comment by ErisDS** [comment]
I'm not clear on how this change relates to the fixes made in https://github.com/TryGhost/Ghost/commit/dac3fff90f7142a6c05f1d389de5d65afe58fc84 - are they additional fixes?

**Comment by ErisDS** [comment]
I'm not clear on how this changeset relates to the fixes made in https://github.com/TryGhost/Ghost/commit/dac3fff90f7142a6c05f1d389de5d65afe58fc84 - are they additional fixes?

@h2akim really appreciate the PR, can you possibly update and clarify the description? Thanks!

**Comment by h2akim** [comment]
@ErisDS the sidebar member count is not updated after add/delete a member - need page reload to get actual member count.

This PR is an attempt to fix this small issue - when user add / delete a member, the member count on the sidebar instantly tally with the number of members from the member list.

Screenshot 2022-09-08 at 11 41 33 PM

**Comment by ErisDS** [comment]
Hey @h2akim thanks for coming back to me so fast :) That makes sense, they're additional fixes for a slightly different bug - I was a bit confused for a second sorry. Thanks so much for taking the time to raise this. I've asked @kevinansfield and @ronaldlangeveld to review the changes. We should be able to get it merged tomorrow :)

**Review by ronaldlangeveld — APPROVED** [review]

**Comment by ronaldlangeveld** [comment]
This is great thanks @h2akim! 💯

**Pull request merged**
