### PR TITLE
Altered migration utility to always use `algorithm=copy` for MySQL

### PR DESCRIPTION
**Pull request by daniellockyer**
refs https://github.com/TryGhost/Toolbox/issues/309
refs https://github.com/TryGhost/Ghost/commit/2bfd8f8b7ec1f487c92b8497955f573bbd14f422

- we've previously had issues when dropping a column on `posts`
  because it's a large table and it can take a veeeeeeery long time with
  the default SQL produced by Knex
- we found a magic incantation that makes it super speedy (context in
  commit above) => `, algorithm=copy`
- for that migration, we did it all manually but we can now change the
  utility to always append this to the generated SQL so we don't have to
  think about the specific table size when adding or dropping columns
- this changes the `addColumn` and `dropColumn` utilities to append the
  string to SQL in MySQL, or just executes the SQL for SQLite

### CODE REVIEW

**Comment by naz** [comment]
@matthanley a note on testing this change - a [perfect real world candidate](https://github.com/TryGhost/Ghost/pull/14586) is the `author_id` removal. I'll rebase that PR over this one to have a nice testing ground :ok_hand:

**Review by naz — CHANGES_REQUESTED** [review]
There's something funky going on with SQLite - when I used these changes to run dropping of `author_id` column from `posts` table, the column did not get dropped. It does get dropped when run with the previous version of `addColumn` method.

**Comment by naz** [comment]
The MySQL version did work just fine :ok_hand:

**Comment by daniellockyer** [comment]
@naz Nice catch! It turns out `.toSQL()` with SQLite is funky because it does the whole table dance. I've pushed a fix, so it should be good now

**Review by naz — APPROVED** [review]
SQLite does work now :1st_place_medal:

**Pull request merged**
