### PR TITLE
🐛 Fixed embedded cards for non-utf8 content

### LINKED ISSUE #14973: Error when parsing bookmark cards
### Issue Summary

When I copy a URL to my post and it turns to Bookmark card automatically.
But for some site(e.g. some Chinese site), it fails to parse correct content with error encoding. Some fails to fetch icon and thumbnail preview. It’s not site problem, I am sure there is something wrong with Ghost cause I can get these correctly in other CMS system.

### Steps to Reproduce

Please try to paste these in post:

http://slide.news.sina.com.cn/slide_1_86058_547338.html#p=1

https://new.qq.com/omn/20220613/20220613A0A3G200.html

### Ghost Version

5.2.2

### Node.js Version

16.15.1

### How did you install Ghost?

Follow official tutorial.

### Database type

MySQL 8

### Browser & OS version

Ubuntu 20.04LTS

### Relevant log / error output

_No response_

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

### PR DESCRIPTION
**Pull request by jbenezech**
Closes #14973

When fetching content using a non-standard charset, characters were not properly decoded to utf-8 resulting in mangled text in the editor.
      &rarr;Detect charset and use iconv to decode the page text

When requesting a non bookmark card, if no oembed data could be found and we fallback to bookmark, a second network request to fetch the content was issued. This seemed unnecessary.
     &rarr;refactored to avoid that

### CODE REVIEW

**Comment by ErisDS** [comment]
Hey again @jbenezech! Thanks again, again for this PR 😬 Really love how you've tackled this and it looks good to me from a code perspective. Asking @daniellockyer for a second pair of eyes on this one to check out the new dependencies before merging.

If you happen to have a minute, can you share if you've used these dependencies before or had any particular reason for choosing them?

Also the yarn.lock changes are conflicting already - again if you have a second to pull main, rebase and run `yarn` to fix those and push again that would be super helpful but we can do it if not, so no worries there.

**Comment by jbenezech** [comment]
@ErisDS
- iconv-lite : pretty popular, already used in Ghost (not sure how you manage versions)
- charset: tiny, could do ourselves, but maintains some edge cases. Mature, 500k/week downloads

Will rebase and push in the morning

**Review by daniellockyer — APPROVED** [review]
The new dependencies LGTM except they should be pinned in this repo. Renovate will come along and open a PR to do it so it's not a big deal either way

**Comment by ErisDS** [comment]
Thanks for providing that info and updating the PR @jbenezech 🙌  - the PR is now merged and labelled - you're on 🔥 🔥 🔥 

Ghost isn't very good at special character support rn and there was a [recent discussion](https://github.com/TryGhost/Ghost/issues/14662) about adding support in more key places that I can reopen if it's interesting to you? 

Also similar lines is the [i18n project](https://github.com/TryGhost/Ghost/issues/15502).

We're specifically looking for experts to take on this work and help us make sure it gets implemented well and doesn't break anything 🙂

**Pull request merged**
