### PR TITLE
[WIP] Fix naming convention for unoptimized versions of images

### PR DESCRIPTION
**Pull request by 1DxSU1t6**
refs #10912 

This is a draft proposal for fixing the references issue – please provide feedback.

### CODE REVIEW

**Comment by allouis** [comment]
@1DxSU1t6 Hey! Super appreciate this work :relaxed: I will be taking some time on Monday to look at this :dancer:

**Comment by 1DxSU1t6** [comment]
Hi @allouis , have you had a chance to take a look at this yet?

**Comment by allouis** [comment]
Hey @1DxSU1t6!

So far this looks good, I'll be interested to see what the migrations look like.

One thing I would mention is that this seems to add a feature of retreiving the original image, which we don't currently have. I think it adds noise to this PR (it's quite a complex system atm and the less we have to think about, the easier IMO) and should be included in a separate PR after this work has been done - what do you think?

**Comment by 1DxSU1t6** [comment]
@allouis thanks for taking a look! I will work on the migration in the coming days.

I agree re. moving the added feature in a separate PR, however that's actually one of my main motivations of working on this ;) I would like to use imgix for my images for a blog hosted on Ghost Pro, and the only way to accomplish that is to provide a way to access original images at a stable URL. So I'll split it, but I'd greatly appreciate if you'd review and consider merging the other PR too.

**Comment by gargol** [comment]
Hey, @1DxSU1t6 any updates? :wink:

**Comment by gargol** [comment]
Doing a little start of the year cleanup here. @1DxSU1t6 or anybody who comes around the issue feel free to pick up where it was left off:wink:

**Pull request closed without merging**
