### PR TITLE
Fix server errors for signin

### PR DESCRIPTION
**Pull request by cobbspur**
refs #5635
- fixes format for server errors
- changes signin-api validation errors to be text rather than alerts
- adds some errors messages

### CODE REVIEW

**Comment by ErisDS** [comment]
All of the translation of server side errors from `new Error` into proper Ghost errors here is really nice :+1:, I think all the codes are good - but will let @sebgie decide for certain.

The possibility to randomise the error messages was IMO intended to be a frontend / UI / ember app thing rather than a change to the API. Worth checking with @JohnONolan but from my perspective the API should probably be consistent, and the conversion from 'boring' message to one of a few 'fun' messages would be something done in the client application. It can work either way, if we want that fun aspect built in at the API level then we can leave it as-is.

**Comment by ErisDS** [comment]
P.S. I meant to mention that the sign in screen jumps around with this change. I'm not sure if there is something that should be done in this PR or if that's a CSS thing for @JohnONolan

**Comment by sebgie** [comment]
>  I think all the codes are good

I think so too, :+1:

> It can work either way, if we want that fun aspect built in at the API level then we can leave it as-is.

Both options are okay for me. If someone uses the API and relies on the error message s/he is doing something wrong anyway :-P.

**Comment by cobbspur** [comment]
I have taken out the randomised errors for now - probably turn them into a component instead in the future when it is confirmed b @JohnONolan  that they are wanted

**Pull request merged**
