### PR TITLE
Added import theme function as an experimental feature under labs

### PR DESCRIPTION
**Pull request by oocoder**
First time adding to an OSS project, let me know if I missed something or anything I can improve upon. Thanks.

### CODE REVIEW

**Comment by dbalders** [comment]
hey @oocoder! do you mind squashing all of these into one commit?

**Comment by oocoder** [comment]
I tried to follow the rebasing instructions but I'm not sure if did it right. I started again with a new branch, trying to see if I can get it to only one commit.

**Comment by dbalders** [comment]
@oocoder to squash use:

    git rebase -i HEAD~2 

where `2` is the number of commits you want to squash. Then, change `pick` to `p` for the one commit you want, and then change to `f` for all the commits you want to squash into that one.

**Comment by oocoder** [comment]
Hhmm, not sure why the ci failed for node 0.10.x (DB=sqlite3, NODE_ENV=testing) but not for (TEST_SUITE=client).  Can anybody shine some light into this? Thanks.

**Comment by ErisDS** [comment]
Hey @oocoder I know you messaged in slack a few times - I was on holiday at the time & did reply when I got back but haven't seen you there since.

Aaanyhoo, this is a PR that proposes a new feature, which is usually done through ideas.ghost.org or discussion in slack (which unfortunately didn't happen properly cos I wasn't around). The point of that process is to identify properly what the problem is before designing a solution.

As you've said, its your first time proposing something to an OSS project. Not every project is the same, but in this one at least we care deeply about ensuring the features that get added are done for the right reasons and in the right way. That is, that the problem is identified in full and the solution proposed covers the most important aspects and is well designed.

Therefore, my expectation would be that the PR message here would contain all the background - what problem are you solving? Why is the proposed solution the right way to solve it? What research did you do if any? What challenges did you face whilst implementing it that made you make the code decisions you made? And so on and so forth.

Essentially, you're trying to sell this to the people with the power to hit merge. 

In this case, whilst I can guess at the problem, I don't really follow the solution being part of the importer. Hence why explanation is important :smile:

**Comment by oocoder** [comment]
Hi Hannah, Thanks for reaching out and I hope you had a great vaca.  

I definitely agree with you, having a review process and architecture code affinity not only ensure quality of the product but also creates a path for software engineers to improve their skills. 

Following process, I posted the feature under ideas.ghost.org http://bit.ly/1RsD9ZE.

What problem are you solving?
Quick background, Sandstorm.io is a platform to run/host open source web projects with todays apps model.  It allows for any user (non-devs) to quickly and seamless install within his/her private space any of the configured open source projects. 

The problem I'm trying to solve, is that within Sandstorm.io world there is no shell access.  Therefore changing the default theme to a custom one, becomes something more than a non-dev user would like to deal with.

Why is the proposed solution the right way to solve it? What research did you do if any? What challenges did you face whilst implementing it that made you make the code decisions you made? 

I don't know if its the right implementation, I need team's/community input on this.  I was looking for a sample and I ran into the importer feature from the labs page.  It seems logical at the time to mimic that. 

I hope this helps and I'll try to login more often to slack dev channel.  My hope was to do a small contribution and learned from the experts in the process.  I learned a lot by just looking at the Ghost code and from Git's Rebase'ing dance.

**Comment by ErisDS** [comment]
Going to close this now in favour of #7209. Really appreciate the work you put into try to get this feature added. We felt strongly that this did not belong as part of the importer and needed to be added as part of a bigger feature addition. I hope you'll enjoy what we've done as I believe it solves your use case 😄

**Comment by oocoder** [comment]
Oh thats fine, it was more of a personal challenge to learn more about
NodeJS and open source projects.

I'm just glad to see that the feature was finally implemented the right
way.  The Sandstorms.IO peepz will be happy. :)


Thanks,


*Alex R Maldonado*
@OOCoder
646-807-8693

**Pull request closed without merging**
