### PR TITLE
Refactor SSO Adapter to allow third party SSO with OAuth2

### PR DESCRIPTION
**Pull request by delfimrego**
The use case of this refactor is to allow Third party Single Sign On (SSO)

https://forum.ghost.org/t/third-party-single-sign-on-sso/3321/28

To allow OAuth2 SSO, the server needs to provide a callback and some other endpoints. The existing SSO base adapter was not able to to do that. Thus this refactor, to allow my brand new [brand new ghost-passport-sso](https://github.com/delfimrego/ghost-passport-sso) adapter :)

The changes includes new endpoints under '/ghost/sso':

- '/ghost/sso/providers': returns a list of available providers, so that the admin client can list them in the Sign-on page (https://github.com/TryGhost/Ghost-Admin/pull/1803 submitted)

Then it's the responsibility of the sso adapters to add the additional endpoint. For OAuth2 that would be:
- '/ghost/sso/providers/<provider>': to provide a redirect to the OAuth2 provider (google, facebook, ...)
- '/ghost/sso/providers/<provider>/callback': to receive the credentials and create the session

The SSOBase adapter also has some additional methods for creating endpoints, find users and create sessions. This avoids adding too much dependencies inside external implementations.

I'm looking forward to your review and comments. Hope this gets approved.

Please include a description of your change & check your PR against this list, thanks!

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test` and `yarn lint`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by matthanley** [comment]
Hey @delfimrego  👋 

Thanks for submitting the PR. I've skimmed the changes and it looks like it's not backwards-compatible with existing SSO adapters, which means it won't be merged. We're tracking SSO support as an internal project, so I'd recommend waiting for the official implementation to be released.

**Comment by delfimrego** [comment]
@matthanley fair enough. Looking forward for the release then.
Meanwhile I have a solution that works for me. Thanks.

**Comment by putt1ck** [comment]
@delfimrego is your solution the code in your repo? We need SSO (CAS/OAuth2) for a setup and would be very happy to collaborate on making it happen

**Comment by delfimrego** [comment]
Hi,

Yes, it's on my repo. Would be glad to Collab to improve the integration.

A quinta, 5/08/2021, 09:27, Chris Puttick ***@***.***>
escreveu:

**Comment by malwarepad** [comment]
> Hey @delfimrego 👋
> 
> Thanks for submitting the PR. I've skimmed the changes and it looks like it's not backwards-compatible with existing SSO adapters, which means it won't be merged. We're tracking SSO support as an internal project, so I'd recommend waiting for the official implementation to be released.

It's been 3 years man... The current login system is frustrating and the community would really appreciate basic oauth 2.0 support. It's been requested for years but no efforts have been made to integrate it. 

https://forum.ghost.org/t/documentation-on-getting-oauth2-working-with-external-provider/18685
https://forum.ghost.org/t/third-party-single-sign-on-sso/3321

**Pull request closed without merging**
