### PR TITLE
Updated Spanish translations

### PR DESCRIPTION
**Pull request by itmarck**
This pull request fixes the following items in `es/portal.json` file:

- Missing translation for Spanish
- Syntax error in a button element which causes wrong render
- No needed English phrases inside translation

Second commit was for shorting the length of a modal title that overlaps the icons.

Third commit was for updating the full file to informal Spanish grammar.

---

### <samp>🤖 Generated by Copilot at e1e8b2f</samp>

This pull request improves the localization of the Ghost portal feature for Spanish-speaking users. It adds or updates translations for various portal-related messages and labels in the file `ghost/i18n/locales/es/portal.json`.

### CODE REVIEW

**Comment by markstos** [comment]
Thanks for this. I noticed the contribution includes a mix of informal and formal grammar. For example: "te pueden" vs. "su dirección". Was switching between formal and informal intentional?

When I review the Spanish translations already there, I see there was already a mix of informal and formal language as well. For example: "tu comentario" and " usted no reciba".

When I search for other translation pull requests for the question for formal vs informal, both the Ukrainian and German translations choose to use informal language:

https://github.com/TryGhost/Ghost/pull/1289#issuecomment-28228982

https://github.com/TryGhost/Ghost/pull/16637

If you agree that using informal grammar consistently makes sense, would you mind updating the remaining cases of formal grammar throughout the file as well?

Thanks!

**Comment by itmarck** [comment]
Sure, thanks for your review. I choose the form based of the previous translations for the similar message. It's nice that you already have the informal grammar as preferred. I'd like to switch the full file to informal grammar in this pull request then. Let me know if you think it could be done in two separates PRs.

**Comment by itmarck** [comment]
Sure, thanks for your review. I choose the form based of the previous translations for the similar message. It's nice that you already have the informal grammar as preferred. I'd like to switch the full file to informal grammar in this pull request then. Let me know if you think it should be done in two separates PRs.

**Comment by markstos** [comment]
I'm not  a core Ghost dev, but since scope of work is still to improve the Spanish translation, continuing to use the same PR seems appropriate.

**Comment by markstos** [comment]
I'm learning Spanish by chatting with a friend in Peru, and the more I learn about the country, the more it seems interesting to visit!

**Comment by itmarck** [comment]
Sounds cool, I'll be updating the PR this week. I'm from Peru too btw, nice you like it!

**Comment by itmarck** [comment]
Updated and rebased, the pull request is ready for review.

**Comment by markstos** [comment]
Looks good to me. Gracias!

**Pull request merged**
