### PR TITLE
[WIP] Clients API

### PR DESCRIPTION
**Pull request by acburdine**
Fixup for #6195, refs #4175 

TODO:
- [x] Rebase initial code, ensure it works
- [x] Fix up any unwanted behavior
- [ ] Add tests
- [x] Update once client permissions are a thing (blocked on #6301, #6628)

### CODE REVIEW

**Comment by zinyando** [comment]
@acburdine I am testing your branch against the client branch. I am getting an error on Client model not being an allowed type in `api.slugs.generate`. I am still testing will let you know of other problems I encounter.

**Comment by ErisDS** [comment]
@acburdine I just remembered! This should be unblocked now 😁  all the permissions are in master already

**Comment by acburdine** [comment]
@zinyando I'm fairly certain this should work with all of the network requests. I'm just writing tests now 😄

**Comment by zinyando** [comment]
@acburdine Ok I will take a look at it and make sure everything works on the ember app

**Comment by ErisDS** [comment]
Closing this - we're having a bit of a rethink around how we do API authentication, and will raise new issues when we've got a clear idea how to move forward.

**Pull request closed without merging**
