### PR TITLE
😱 🎨 Refactor storage adapter

### PR DESCRIPTION
**Pull request by kirrg001**
refs #7687 

There are four main changes in this PR:
1. we have outsourced the base storage adapter to npm, because for storage developers it's annoying to inherit from a script within Ghost
2. we hacked theme storage handling into the default local storage adapter - this was reverted, instead we have added a static theme storage here
3. use classes instead of prototyping
4. optimise the storage adapter in general - everything is explained in each commit

The base storage adapter is not yet released. 
You can find the implementation here https://github.com/kirrg001/Ghost-Storage-Base/tree/storage-base.

#### TODO
- [x] release ghost-storage-base and change package.json
- [x] double check target dir - used by the importer?
- [x] test in browser
- [x] ensure installing a custom storage adapter still works 😎

#### Next steps
We would like to change the location of adapters. Right now custom storage adapter live in `content/storages`. We would like to change this to `content/adapters/storages` and `content/adapters/scheduling`.

### CODE REVIEW

**Comment by kirrg001** [comment]
This is ready for review. After review, i will publish the base storage adapter.

**Comment by ErisDS** [comment]
The targetDir option for save is used by the importer, which will need resolving. Other than that this PR looks 👍  - just needs a rebase I think?

**Comment by kirrg001** [comment]
> The targetDir option for save is used by the importer, which will need resolving

👍 Thanks!

**Comment by kirrg001** [comment]
I have updated the PR, ready for final review 👍

**Pull request merged**
