### PR TITLE
This commit allows the excerpt helper to fully utilize all downsize options

### PR DESCRIPTION
**Pull request by dangerdespain**
I rearranged the pick/map functions so that other options like "append" and "round" aren't filtered out of the truncateOptions object (the append option seems to be super useful!)

### CODE REVIEW

**Comment by dangerdespain** [comment]
Tests pass locally - please let me know if there's anything I get to modify on my end!

**Comment by novaugust** [comment]
Hey @dangerdespain, everyone's tests were failing due to a dependency issue. The fix for that has now been merged into master - if you could just rebase off of that and push again, we should get green

**Comment by ErisDS** [comment]
Hi @dangerdespain, I appreciate you taking the time to do this.

This PR is making changes to Ghost's theme API, which is the most publicly visible part of the platform. Changes to the theme API need to be very carefully considered, and in this case, the lack of support for the `round` and `append` options in Ghost is deliberate. 

With regards to `round`, you can read about why we didn't add support for it in [this PR](https://github.com/TryGhost/Ghost/pull/4421) and the related issue - in short the way it works isn't as intuitive as we would want for the theme API - and so we decided to pursue a different angle as explained in #5060. 

With regards to append, this feature doesn't make a great deal of sense for the `excerpt` helper in its present form, because all formatting is stripped and therefore there it is quite possible to put any text you want after your excerpt next to the `{{excerpt}}` helper. It's quite a different case for the content helper, where the append attribute isn't supported yet due to the limitations explained in #2163.

With all this in mind, I'm going to close this PR. If there is something you're trying to do with the theme API and can't, let us know about it so we can be certain that the plans in #5060 aren't missing something big and if you're interested, the spec outlined in #5060 needs someone familiar with downsize to look into how to achieve it :)

**Comment by dangerdespain** [comment]
The impetus behind this PR was that my OCD alarm bells were ringing when I realized that truncated and non-truncated excerpts both had the append text hardcoded into the hbs template. I'm building a photoblog (as I travel Thailand!) and don't use much text. More often than not, the post text fits entirely in the excerpt and it was driving me nuts to see "..." or "cont'd" after the content. I agree that making this work for both the content and excerpt helpers is going to be a helluva challenge.

I read up on #5060 (thanks for the link!) and agree that the round option doesn't seem to work as hoped.. Perhaps I'll take a stab at it when I have the bandwidth to take a deeper dive. Otherwise, I'll chug along with a personal branch I can move my odd personal touches into apps instead [=

Thanks!

**Comment by ErisDS** [comment]
> The impetus behind this PR was that my OCD alarm bells were ringing when I realized that truncated and non-truncated excerpts both had the append text hardcoded into the hbs template. I'm building a photoblog (as I travel Thailand!) and don't use much text. More often than not, the post text fits entirely in the excerpt and it was driving me nuts to see "..." or "cont'd" after the content. 

That's an interesting problem - I can see how that would be irritating. My initial recommendation would be to use a tag to indicate your photoblog posts, and display a different excerpt for those. We plan to make this more intuitive by making private tags a possibility soon - so you could use a tag that wouldn't be visible to readers.

**Comment by shyswork** [comment]
@ErisDS 
Could you please share how one can do this (use tag to indicate special kind of posts and display different excerpt for those)?
I have exactly the same problem, I have multiple posts with just a few words and image and I struggle to conditionally show "read more" button depending on how large is text in a post.
I have made a simple inline js script to check excerpt length in characters and add/remove "read more" button. I check for pure text in excerpt returned by {{excerpt character="100"}} and if it is less than 100 I remove "read more" button but it doesn't work if the text contains UTF symbols. Then the text length I get is not calculated correctly (or rather calculated differently by 'downsize') so I may end up with 99 characters in excerpt and fail in my condition. 

I would really appreciate if there would be an easy way to check if excerpt is the whole text content or not.

**Comment by ErisDS** [comment]
@shyswork I recommend swinging by our [slack](https://ghost.org/slack) community and asking for some help with your use-case there.

**Pull request closed without merging**
