### PR TITLE
Adds pt-BR translations to newsletter.json and fixes other strings

### PR DESCRIPTION
**Pull request by Lekler**
Following pull requests #21251 and #21497, this commit adds pt-BR translations to newsletter.json and fixes other strings in pt-BR locale files.

### CODE REVIEW

**Comment by cathysarisky** [comment]
Suggestion:  Could you please put your newsletter translating efforts into #21497, which was submitted first?  If I flag both of these for merge, they don't agree on some of the newsletter.json wording, and that's going to be a mess.  So I suggest that you remove newsletter.json from this submission, and instead discuss any changes you think are appropriate on the other PR there.  (The suggestion feature is great for making line-by-line suggestions.)  Then we can merge that one for the newsletter strings, and this one for the portal strings, without merge conflicts. :)  Does that sound reasonable?

@sergiospagnuolo , if you have time to look at these portal translations, I'd appreciate your review!

**Comment by sergiospagnuolo** [comment]
I think @Lekler is better collaborator than I am, I would stick with his reviews, they seem fine to me. I will close my PR

**Comment by cathysarisky** [comment]
Works for me, @sergiospagnuolo . Once you've looked over his copy, please leave a review here! :)

**Comment by Lekler** [comment]
@sergiospagnuolo perdão por ter feito esse pull por cima do teu. 
Estava testando umas coisas aqui no VS Code e na minha cabeça (de autista) pensei que estava editando o teu merge, por isso mencionei ele até.
Vou me policiar para não acontecer de novo e obrigado por deixar esse ser o Pull Request, nas próximas alterações que fizer te menciono pedindo para revisar (caso tenha tempo).

**Pull request merged**
