### PR TITLE
Updated members signup flow to handle invalid payments

### PR DESCRIPTION
**Pull request by rshbhgrg**
no issue

- Adds new payment page for post signup in case of stripe payment failure
- Works similar to upgrade flow, needs better design
- Fixes hung state in case of payment failure on signup but user is created

### CODE REVIEW

**Review by allouis — COMMENTED** [review]
Looks good to me! One thing though, should we be passing the coupon through in the case that there is one?

**Comment by allouis** [comment]
Tested this locally and all seems good - I noticed the loading spinner didn't seem to work on the second page though, might have been a local issue.

**Comment by rishabhgrg** [comment]
@allouis Yeah coupon and loading spinner were not added to it in the current state, I'll update to pass through both :)

**Comment by rishabhgrg** [comment]
@allouis Updated! Coupons are carried over now and spinner is added

**Pull request merged**
