### PR TITLE
🐛  download theme: target folder is a symlink

### PR DESCRIPTION
**Pull request by kirrg001**
no issue

- always transform requested folder path into real path
- `realpath` always returns the correct path, doesn't matter if the folder is a symlink or not

Problem: It was not possible to download a theme if the theme was a symlink.

### CODE REVIEW

**Comment by kirrg001** [comment]
If we approve this, i will create another PR to master 👍

**Comment by kevinansfield** [comment]
LGTM but wondering if there are any security issues here, should we ensure that the symlink is pointing to something within the configured content dir?

Eg. if I somehow uploaded a theme that was actually a symlink to `../../` would the download then contain whole ghost directory including the config files?

**Comment by kirrg001** [comment]
If you upload a zip, which was originally a symlink to `../../` - you need to pass the gscan validation. gscan will complain if a specific structure isn't present.

What we could do is making the gscan validation more powerful. We already validate against symlinks in the asset folder, we could validate if the root folder is a symlink.

**Comment by kevinansfield** [comment]
Ok, I think this should be fine, I can't think of any other situations a symlink could end up in the themes directory without direct access to the server 👍

**Pull request merged**
