### PR TITLE
🎨  gulp: use yarn

### PR DESCRIPTION
**Pull request by kirrg001**
refs #7427

### CODE REVIEW

**Comment by ErisDS** [comment]
What is the reasoning behind this change? This PR links to #7427 but I see no discussion there either. Does it really make sense to enforce yarn for all contributors?

**Comment by kirrg001** [comment]
It was mentioned in slack that we want to replace the gulpfile usages - but don't remember where.

I agree with your argument that we force using yarn. How about making it optional?
Since i am using yarn, my installation is so fast. That's why it's nice having it in the gulp tasks as well.

**Comment by acburdine** [comment]
Maybe use yarn, and fallback to npm if yarn is not available?

**Comment by kirrg001** [comment]
closing, because of https://github.com/TryGhost/Ghost/issues/7427#issuecomment-286077031

**Pull request closed without merging**
