### PR TITLE
Update some client dependencies

### PR DESCRIPTION
**Pull request by acburdine**
no issue
- move password-generator off of specific git commit hash
- lock jquery deparam version

### CODE REVIEW

**Comment by acburdine** [comment]
Wasn't sure if I should squash these into one commit, and can do that if wanted.

**Comment by kevinansfield** [comment]
Did you see any reason for `password-generator` to be tied to that specific commit?

**Comment by acburdine** [comment]
It was because at the time there was no bower file present.

**Comment by acburdine** [comment]
Or rather, the project itself had not been published to bower

**Pull request merged**
