### PR TITLE
post-scheduling: 503 retry logic for default adapter

### PR DESCRIPTION
**Pull request by kirrg001**
is related to #6861 and #6413

In case the blog returns HTTP code `503` (for example in case of maintenance), the default scheduler will retry to ping the URL after x seconds. 

**I've decided against to stop after x tries.**

### CODE REVIEW

**Comment by kirrg001** [comment]
@ErisDS ready for review.
i decided against a max retry in case of HTTP `503`. Do you agree?

**Comment by ErisDS** [comment]
Difficult to agree or disagree when I don't know why you decided against it ;)

**Comment by kirrg001** [comment]
sorry for no instant reasoning. `503` is a temporary state and when we add a max try, we risk loosing a job which does not get published.

**Comment by ErisDS** [comment]
Yep, I'm with you. I think a maximum, even if it's really quite big (30, 50?!), is still a safe thing to add so that we don't end up retrying something forever.

**Comment by kirrg001** [comment]
added a very high max tries, ready to review/merge 👍

**Comment by kevinansfield** [comment]
👍 LGTM. Two questions:

1. Are we happy that blogs won't be in maintenance mode for more than 2.5 minutes? (30 x 5sec retries)
2. Are jobs deleted if they fail or are they left in a "failed" state for later review?

**Comment by kirrg001** [comment]
1. That's a good question, thats why i didn't add the max tries at all, because we don't know. Maybe 10minutes is a better timeout.

2. For `Ghost(Pro)` yes (i also added the reason why they failed), but for default scheduling we don't store any information - everything lives in the process.

**Comment by kirrg001** [comment]
additional information to (1): this logic is not used for `Ghost(Pro)`. Maybe that's why 2.5 minutes are OK, because we can't control what people do with their blog.

**Comment by kevinansfield** [comment]
Thanks, I think we're probably good with 2.5 minutes for now as we haven't yet fully determined when maintenance mode will be used. Anyone upgrading to this version won't have any jobs scheduled and so won't run into problems but it's definitely something to consider in the future wrt to maintenance mode.

👍 for the failed jobs, as long as it's documented that jobs are ephemeral unless a persistent scheduler is swapped in then I think we're fine.

**Pull request merged**
