### PR TITLE
Fix redirect loop when path is same as subdir.

### LINKED ISSUE #5914: redirect loop when password protecting blog at example.com/private/
I've set up an instance of Ghost behind nginx as a reverse proxy. Ghost can be reached under `example.com/private/` (so the admin interface is at `example.com/private/ghost/`). The nginx config looks like this:

        location ~ ^/private(/.*)?$ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $http_host;
                proxy_pass http://127.0.0.1:2368;
        }

The correct URL (`http://example.com/private/`) is set in `config.js`.

When enabling password protection for the blog a user that is not logged in gets a redirect loop (Ghost sends a redirect to `/private/` which is what the user requested. When following the redirect Ghost sends the same redirect.). When already logged in the blog works as intended. Using a different folder such as `foo` instead of `private` does not trigger this behavior.

* Ghost Version: tested 0.7.0, 0.7.1 and master (f7015600b8bbd61d76fa324fff69fac2dd8c2452)
* Client OS: Gentoo Linux (amd64)
* Server OS: Gentoo Linux (amd64)
* Node Version: 0.12.6
* Browser: Chrome 45.0.2454.85 and wget-1.16.3-r1
* Database: SQLite

### PR DESCRIPTION
**Pull request by delgermurun**
closes #5914
- Test whether or not path is same as subdir
- Added unit tests

### CODE REVIEW

**Comment by ErisDS** [comment]
I think the assertion in this PR is incorrrect:

> Should not replace if asked path is same as subdir.
> For example: If we ask path for '/private', when subdir is '/private/',

This is just one single case where what looks like a duplicated subdirectory is in fact desired. There are no other cases that I can think of. Can you find other cases where this is also true?

**Comment by delgermurun** [comment]
Yeah, this is tricky solution even problem is also tricky edge case. I am not sure there is any other cases.

**Comment by delgermurun** [comment]
@ErisDS Actually I remembered one use case. Let's say `subdir` is `/blog` and I've written article with `/blog` slug. So `urlJoin` returns `/blog` instead of `/blog/blog` (I've tested it via `console.log` inside urlJoin function). Fortunately `localhost:2368/blog/blog` doesn't redirect to `localhost:2368/blog`.

**Comment by delgermurun** [comment]
@ErisDS Noticed one issue with above circumstance (`subdir` is `/blog/` and post with `/blog` slug). On home page (ie: on channels page) this post's url points to `/blog/` not `/blog/blog`.

**Pull request closed without merging**
