### PR TITLE
Added /tiers endpoint to Content API

### PR DESCRIPTION
**Pull request by allouis**
refs https://github.com/TryGhost/Team/issues/1313

When adding the tiers endpoint the Content API was missed, this is
needed so that themes can access Tiers via the `{{#get}}` helper.

### CODE REVIEW

**Comment by allouis** [comment]
@matthanley This still needs a test - but should I update the `{{#get}}` helper as part of this so that it works with themes?

**Review by matthanley — APPROVED** [review]
Not tested locally, but lgtm

**Comment by matthanley** [comment]
@allouis could you also make sure to track related changes to the docs and GScan for switching from `@products` to `#get tiers` before this is merged

**Comment by allouis** [comment]
Added an issue here: https://github.com/TryGhost/Team/issues/1405

**Pull request merged**
