### PR TITLE
Add helper for JavaScript-escaping strings

### PR DESCRIPTION
**Pull request by obskyr**
Added a new helper, `js_escape`, which lets themes escape strings so they work in JavaScript strings. This allows for themes to use things like `post.title` within `<script>` tags, which I've seen themes do before and subsequently fail and mess up the layout whenever the title includes an apostrophe (which plain ol' `encode` doesn't escape).

Also sneakily moved a require, since all requires but that one was in alphabetical order.

Tested and works as it should.

### CODE REVIEW

**Comment by ErisDS** [comment]
Hi @obskyr thanks for taking the time to do this. 

Adding new helpers to the Ghost theme API is never done without significant discussion around what problem we're solving, why we need to solve it, why a helper is the right solution and what the helper should look like. Helpers also need significant test coverage.

In this case, I understand the idea, but I think it would be helpful to start at the beginning. What are you trying to do and why? What are the differences between escaping for js and encoding for a URL? Is it just the apostrophe or are their other characters etc?

Once we've got a clear picture of the what, then we can look again at the best way to solve it. Perhaps there's no need for a new helper but we should instead either provide options for `encode`, or change what encode does. Also worth a read: https://github.com/TryGhost/Ghost/issues/4362

**Comment by obskyr** [comment]
Ah, of course! Adding a feature for the sake of adding a feature is, naturally, not a very good approach.

The `js_escape` helper is meaningfully different from `encode` in three separate ways:

* `js_escape` escapes apostrophes, `encode` does not.
* `js_escape` escapes using backslashes, `encode` escapes using `%` codes.
* `js_escape` does not escape all special characters; only characters that need to be escaped in JavaScript strings.

Beyond the first point, the second and third are very important, as they mean the string being used isn't actually altered. Using `encode` in JavaScript, a string like `Welcome to my "blog", whatever that means!` turns into `Welcome%20to%20my%20%22blog%22%2C%20whatever%20that%20means!`. As this isn't the same string, it won't work with some things: `replace`s, for example, or display / use in contexts where text isn't URL-unescaped.

The case I added the helper for was one where the theme author was adding a share button to the page using `document.write`. The HTML used there looks like this:

```html
<script>
    document.write('<a href="http://www.tumblr.com/share?v=3&amp;u=' + encodeURIComponent('{{url absolute="true"}}') + '&amp;t={{encode title}}" class="popup">');
</script>
```

Whenever the title of the post includes an apostrophe in this case, the JavaScript string gets spliced and is rendered invalid, thus messing up the layout. To achieve a string that is both `js_escape`d and `encode`d, either `encodeURIComponent({{js_escape string}})` or `{{js_escape (encode string)}}` can be used, which will fix cases like this one.

Using post titles, among many other things, unencoded in JavaScript may be useful in other cases, too. Building XHRs with headers and content, adding text or attributes to JavaScript-created elements, etc.

Hope I've managed to clear things up as to why I feel this is a necessary helper. If you've got other questions, I'd be happy to answer them.

**Comment by obskyr** [comment]
Made sure iteration through replacements will always work - it's order-dependent, and while JS object keys are almost always iterated through in order of addition, the JS specification does not make sure this is the case. Switched over to arrays.

**Comment by obskyr** [comment]
Were you thinking the encode helper would have an optional "format" argument or something along those lines instead?

**Pull request closed without merging**
