### PR TITLE
Fix pagination for tags with post_count

### LINKED ISSUE #5551: Pagination not working on tags endpoint.
The new `fetchPage` method does not construct a working `count()` query for tags.  Probably because the tags query it starts with already contains a group-by and an aggregate function (for the posts count field).

### PR DESCRIPTION
**Pull request by ErisDS**
closes #5551
- adds new test fixture generator and tests for tag pagination
- changes how post_count is added to use a select subquery rather than a join

### CODE REVIEW

**Comment by ErisDS** [comment]
Amazing, this is actually failing just on postgres - whoohoo for tests :tada:. Will fix tomorrow.

**Comment by ErisDS** [comment]
Ok, I'm totally baffled by this. Can someone shed some light on the correct way to fix this?

**Comment by jaswilli** [comment]
The tl;dr is that there are rules about columns appearing in the select list when an aggregate function is involved.  Apparently sqlite3 and mysql are just fixing it up for you?  I'm not sure.  I believe that if you tell bookshelf to add a `group by` clause with `tags.id` that postgresql should stop complaining.  I think you can get away with leaving the other tags columns out since they're not part of the join result set and aren't causing confusion.

**Comment by ErisDS** [comment]
I've tried adding a `groupby` but it seems to change the behaviour of the query. I'm not sure if it's complaining about the main query or subquery - I assume subquery because it only errors on those tests, but either way I haven't found a fix that doesn't just cause a different error yet.

**Comment by jaswilli** [comment]
Sorry, I misjudged what SQL was going to be generated by those bookshelf statements.  When I actually ran it through bookshelf the output seems fine to me. Maybe something further down the line from bookshelf (like the pg library or the postgresql optimizer) is making a change? I'm not sure what to do about it--maybe try and rework the query using a different form of the same request.

**Comment by jaswilli** [comment]
I did a little digging and figured out what's going on.  Adding the post count subquery makes the SQL generated in the pagination fetchPage method invalid: https://github.com/TryGhost/Ghost/blob/master/core/server/models/base/pagination.js#L147

**Comment by ErisDS** [comment]
Can you explain what about it is invalid? Do you have a link to some docs or something? I'm keen to understand what I did wrong! It seems to work fine even from the pg CLI. I'm very confused!

I figure that the solution is that the post count subquery should be added after the aggregate count, which should be an easy enough change, I'd still like to get a better understanding of what was wrong.

**Comment by ErisDS** [comment]
I have moved the extra count so that it is only added to the collection query, and not the count/aggregate query. This allows all the tests to pass. 

This now resolves #5551. There are other issues to do with counts including adding them for other models, and ensuring that they only count public data, but these are tasks listed out in #5615. This at least removes a UI blocker.

**Pull request merged**
