### PR TITLE
Admin host redirect bug

### PR DESCRIPTION
**Pull request by ErisDS**
This PR adds a test to match the behaviour I'm seeing fail locally, but to start with it passes.

In the second PR, I changed the behaviour of the fake req.hostname to match the real behaviour in express, which makes the new test fail in the same way I'm seeing IRL, but also makes 3 other tests fail 🤔 

refs #11766

### CODE REVIEW

**Comment by ErisDS** [comment]
The underlying bug here is that if the adminURL contains a port there will be an infinite "host does not match" redirect. Full reproduction in the issue: https://github.com/TryGhost/Ghost/issues/11766

This happens because req.hostname does not include the port. [This change](https://github.com/TryGhost/Ghost/commit/7284227f1ebb8835f2f9a91dea988332383fc219#diff-95ca75e05f86961a3f30db14087f0a7bR99) from `req.get('host')` to `req.hostname` therefore broke this, as ports are included in host, but not hostname ([see the code in express that removes ports](https://github.com/expressjs/express/blob/b93ffd4bdc09c3af925eed80c28bd37f63bb3cfc/lib/request.js#L445-L449)). 

When the change to req.hostname was made, the equivalent test code [was left still returning host inc port](https://github.com/TryGhost/Ghost/commit/7284227f1ebb8835f2f9a91dea988332383fc219#diff-440175ca485d10a10315a23e52197153R17), meaning the tests were no longer correct.

Because of this, when I added a test case to match the real-world behaviour I'm seeing, and it [did not fail](https://github.com/TryGhost/Ghost/pull/11767/commits/92aebaa480276e097ec2e6fed282b2e19d70fe2f).

Originally, I changed the tests [in this commit](https://github.com/TryGhost/Ghost/pull/11767/commits/a21bbf2f1749ffac32fb5d629349f7b215810b17) and thought that the fix would be to make everything be compared by hostname.

But that has other problems:

1) the comparison won't take ports into account. Real use cases for this are probably near zero but it seems janky.
2) For the frontend ssl redirect, we redirect to the requestedHost, so there was another bug here, where frontend ssl redirects cannot have worked for urls with ports?!

Thinking about it, we _have_ the correct, trusted, requested host with port available to us in the form of `req.vhost.host`.  Therefore changing from `req.get('host')` to `req.vhost.host` would give us the same value (host inc port) but the correct, trusted one. This should fix the original issue correctly and indeed all the tests now pass again.

@kevinansfield please can you have a read of this explanation and see if you agree that this change is the most correct?

**Review by kevinansfield — APPROVED** [review]
@ErisDS 👍  explanation and change makes sense 🙂

**Comment by thosmos** [comment]
I'm having trouble getting access to the admin panel.  I've tried a few different things.  
given:
```
  "server": {
    "port": 9580,
    "host": "127.0.0.1"
  },
```
This redirects endlessly
```
  "admin": {
    "url": "http://localhost:9850"
  },
```
As does this:
```
  "admin": {
    "url": "https://ghost.mydoman.org"
  },
```
with an nginx of:
```
upstream ghost {
  server 127.0.0.1:9580;
  keepalive 128;
}
server {
    server_name ghost.mydomain.org;
    client_max_body_size 128m;
    proxy_read_timeout 60;
    access_log "/var/log/ghost_access_log";
    error_log "/var/log/ghost_error_log";
    root /home/myuser/web;
location / {
        proxy_pass http://ghost;
        proxy_set_header Connection "";
        proxy_set_header Host             $http_host;
        proxy_set_header X-Real-IP        $remote_addr;
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
}
    listen 443 ssl; 
}

```

**Comment by ErisDS** [comment]
Is that with this fix, or without it? :|

**Pull request merged**
