### PR TITLE
Local French improvements

### PR DESCRIPTION
**Pull request by bst1n**
I've changed "email" to "e-mail", which is more correct in French. The official term is "courriel" but it sounds a bit old-fashioned.
Apart from that, I've made a few harmonisations and small corrections to ensure consistency between the files.

### CODE REVIEW

**Comment by sagzy** [comment]
Thanks @bst1n! There are some conflicts on the translations files, would you be able to merge the changes from main on your branch, resolve the conflicts, and then ping us again?

**Comment by bst1n** [comment]
Hi @sagzy, I'm sorry but I'm a beginner on Github and I didn't understand what I should do.

1. Should I close this pull request, restart from the Ghost repository and submit my changes? If so, I need to download the files I've modified to keep a record of my work and inject it into a new branch. That sounds tedious to me, so I guess it's not good practice.
2. But on the other hand, in order to synchronise my fork, I have to discard my commits and I'm worried that this will delete my work on the files. So I feel lost, I don't know what action to take.
3. When I click on resolve conflicts, what I'm offered seems to be to go back over my last changes, which doesn't make sense either.

I'm sorry! I need some help.

**Comment by bst1n** [comment]
I've tried something, I think it's good.

**Comment by sagzy** [comment]
Hey @bst1n, glad you were able to sort it out! Git conflicts occur when the same line of code has been modified by two separate branches (in this case, your PR + `main` branch) and git doesn't "know" which version to choose automatically.

You can read more about resolving merge conflicts [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts).

**Review by sagzy — APPROVED** [review]
The changes looks good! Thanks @bst1n

**Pull request merged**
