### PR TITLE
Optimize uploaded images

### PR DESCRIPTION
**Pull request by PaulBGD**
Previously images were not optimized. This PR allows images to be optimized, without forcing the user to lose quality.

### CODE REVIEW

**Comment by PaulBGD** [comment]
Seems I forgot to check the test, just a moment.

**Comment by jaswilli** [comment]
Hi @PaulBGD,

There's an issue that contains the discussion on image processing (#4453), you should stop by and add this proposal to the mix.

**Comment by PaulBGD** [comment]
@jaswilli Seems it's already on there, I didn't see any implementations however.

**Comment by jaswilli** [comment]
Right, so if you're interested in solving one of the image processing issues you should mention it in the issue and ask for feedback on your proposed solution :smile:

**Comment by ErisDS** [comment]
Hey there @PaulBGD - I'm excited to see someone has a suggestion for how to handle optimisation :) 

It would be great if you could take a looking at the existing discussion that @jaswilli pointed you to #4453 and then frame your proposal in terms of the issues outlined there - how does your PR solve the problem? Why is the dependency added here the right thing to do? How does it fare in terms of speed? 

It seems like you have some knowledge on the subject, so I'm really keen to have you share what you know so that we can understand your proposal fully.

**Comment by PaulBGD** [comment]
@ErisDS This PR isn't really related to that issue. This PR only performs basic optimizations to the uploaded image. It doesn't resize them, crop them, remove weird iPhone data, etc.

**Comment by ErisDS** [comment]
@PaulBGD it is 100% related - that issue talks about all of the various problems and solutions for any kind of image manipulation, of which image optimisation is just one. All I'm really asking is for you to provide some details about the dependency you've included and why it's worth including a dependency that only solves one of the problems.

**Comment by PaulBGD** [comment]
@ErisDS this is a different type of optimization however, this doesn't do anything on that issue.

**Comment by jaswilli** [comment]
@PaulBGD A random PR that overlaps an existing issue, adds new binary dependencies, and has had no discussion is not going to get merged. Single sentence responses dismissing what we're asking is not going to get it done.

If you'd like to work through this PR on the linked issue to see if it's something we can use that would be great.  Until then I'm closing this.

**Pull request closed without merging**
