### PR TITLE
Eslint refactor - max-top-level-suites

### PR DESCRIPTION
**Pull request by dhuang612**
was experiencing errors with other branch, recreated and resolves errors showing up from travis

### CODE REVIEW

**Comment by dhuang612** [comment]
now that this has conflicts, can I get the code reviewed to make sure I completed this correctly. 
I can then update my copy with your upstream version and resubmit?

**Comment by dhuang612** [comment]
closing this one due to incorrect commit messages.

**Comment by gargol** [comment]
@dhuang612 not sure about the status of this PR. It seems to have been rebased incorrectly over master or something. Could you please update it? Thaaanks!

**Comment by dhuang612** [comment]
@gargol 
hey, I think i'll close this and re-create this pr.

I was trying to figure out where this one was at previously.

**Pull request closed without merging**
