### PR TITLE
Team Acceptance Test

### PR DESCRIPTION
**Pull request by acburdine**
Given that I've finished up most of the things I'm working on, and have a decent amount of time, I thought I'd jump in and just write tests for a while. This may not be a PR for all of the needed acceptance tests, but hopefully I can get most of them done (except for the ones that are already taken/in progress)

refs #6039

### CODE REVIEW

**Comment by ErisDS** [comment]
> Given that I've finished up most of the things I'm working on, and have a decent amount of time, I thought I'd jump in and just write tests for a while.
:heart_eyes:

**Comment by zinyando** [comment]
@acburdine I was thinking of doing some of these tests too. I can take on some if you want or we can work together on this :)

**Comment by acburdine** [comment]
@zinyando sounds good :smile: My plan at the moment is to do the team tests and finish up the setup tests. Let me know which ones you take on, or you could submit commits to this PR. Whatever works best.

**Comment by acburdine** [comment]
@kevinansfield do you want me to put all the acceptance tests into one commit, or can I split them out into multiple commits? :wink:

**Comment by kevinansfield** [comment]
@acburdine as discussed on the sprint call, splitting each test into a separate PR would be good as we can merge them in as they are ready.

:+1: on the team test, my only concern is the testing of all the validation text. Acceptance tests should only be a high-level overview, making sure the various areas are rendered and testing any core interaction with the API. We really want to push the testing of any detail down into integration and unit tests - there's a lot that needs to be filled out in that respect but they should eventually be what we rely on most, hopefully as our use of components increases it becomes easier to test at that instead of attempting to force everything into acceptance tests like we did in casper.

**Comment by acburdine** [comment]
@kevinansfield fixed and rebased :smile: If the 404 PR gets merged before this I can add the 404 tests to /team/ as well.

**Comment by acburdine** [comment]
@kevinansfield Added the 404 testing to teams and it seems to work :+1:

**Comment by kevinansfield** [comment]
:+1: LGTM :smile:

**Pull request merged**
