### PR TITLE
Add bower and ember-cli install as global:

### PR DESCRIPTION
**Pull request by roramirez**
Update README instructions for section Developer Install
Added bower to install as global because after is used  like that in
instructions.

### CODE REVIEW

**Comment by ErisDS** [comment]
@kevinansfield & @kirrg001 the README has changed since, however is bower needed adding as a global to the new npm init command... orrr should the Ghost-Admin Grunt file use a path like `./npm_modules/bower/bin`?

**Comment by kevinansfield** [comment]
> orrr should the Ghost-Admin Grunt file use a path like `./npm_modules/bower/bin`

The `useLocal: true` option should mean that grunt picks up the locally installed bin rather than a global. I'll delete my global bower and test.

**Comment by kirrg001** [comment]
>  I'll delete my global bower and test.

I did that already when we have added `npm run init`. But it's good to double check 👍

**Comment by kevinansfield** [comment]
```
~/code/ghost/ghost/core/client master* ⇡
❯ which bower
bower not found

~/code/ghost/ghost/core/client master* ⇡
❯ grunt init
Running "shell:npm-install" (shell) task
yarn install v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning ember-truth-helpers@1.2.0: The engine "ember-cli-app-version" appears to be invalid.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 16.61s.

Running "shell:bower-install" (shell) task

Done.

~/code/ghost/ghost/core/client master* ⇡ 19s
```

I think we're good? Global bower is only needed if you want to manually run `bower install`

**Comment by ErisDS** [comment]
Ok then this is safe to close 😊

@roramirez - the tools & documentation have been updated in the last 2 weeks, with more to come. Hopefully it's a little clearer but let us know if you find any holes!

**Pull request closed without merging**
