### PR TITLE
feat: configurable mailgun bulk email batch size #15725

### PR DESCRIPTION
**Pull request by jakub-k-slys**
Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ ] There's a clear use-case for this code change, explained below
- [ ] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

---

### <samp>🤖 Generated by Copilot at 3a2f539</samp>

This pull request adds a new setting `mailgunBatchSize` to the Ghost application, which allows the user to configure the batch size for sending emails via the mailgun integration. It also updates the email service, the mailgun client, and the email analytics provider to use the new setting value. Additionally, it adds tests, migrations, and fixtures to support the new setting.

### CODE REVIEW

**Comment by jakub-k-slys** [comment]
Hi @SimonBackx, will you be able to review the PR and provide feedback?
CC @ltoinel @alias-rahil @KarimJedda

**Comment by SimonBackx** [comment]
Hey @jakub-k-slys, thank you for your contribution! 😊 Is there any reason why you would like to change the batch size? AFAIK, Mailgun only supports up to 1.000 recipients at the same time, and I don't see a reason to reduce this number, or do you have any?

**Comment by jakub-k-slys** [comment]
Hi @SimonBackx. Many thanks for getting back! When it comes to Mailgun, it offers plenty of subscription plans that current ghost codebase works well with. However, there is also Flex plan that allows to send up to 1000 emails per month without being charged and you pay for everything above 1000. The major issue with this plan is Mailgun limits the number of recipients in batches. It is limited to 9 :( and that's something I was hit by (and other fellows). I am hoping that reducing the number of recipients in batches would allow me to send newsletters again... Therefore I'd like to introduce an ability to adjust how big the batch can be. Does it make sense to you? Looking forward to hear you!

**Comment by SimonBackx** [comment]
Hey @jakub-k-slys! I definitely think you should check with Mailgun support to get your limit increased. This has been raised a couple of times on the forum, and it is a limit Mailgun sometimes enforces on new accounts to prevent spam: https://forum.ghost.org/t/too-many-recipients-error-while-sending-email-newsletter-using-mailgun/10716/12

Apart from that, given the amount of users with these issues, and to make it easier to build a sending history, we could allow a similar change in Ghost, but the solution you've implemented is a little bit too complex, given the very limited use case. So if you want to make the following changes, we can get this merged:

- Switch from using a setting to [a configuration value](https://ghost.org/docs/config/). A configuration value is defined in a config file, and doesn't change after booting. I don't think we need complicated UI to change this value, since this is already a very technical thing to setup, so it shouldn't be visible for normal users (that will only complicate things during setup).
- Remove all UI changes

You can add the config under `ghost/core/core/shared/config/defaults.json`, under a new `bulkEmail` key and `batchSize` value.

You can alter `ghost/mailgun-client/lib/MailgunClient.js` to read the new config value, and replace the static variable with a getter method. You can then use the same getter in `ghost/email-service/lib/MailgunEmailProvider.js` `getMaximumRecipients`

**Comment by jakub-k-slys** [comment]
@SimonBackx what you proposing sounds really great. I will try to rework the PR in my spare time according to your suggestions and will back to you. Many thanks for help! 😃

**Pull request closed without merging**
