### PR TITLE
Allow use of round and append downsize options for excerpt helper

### PR DESCRIPTION
**Pull request by zeropaper**
I thought it would be nicer to be able to cut the excerpt text at the end of a paragraph and the downsize module allows that rather easily.

### CODE REVIEW

**Comment by zeropaper** [comment]
No idea what cause the test to fail. Would be glad to fix.
Can somebody point me to some documentation / hints?

**Comment by halfdan** [comment]
@zeropaper That's a random test failure - not connected to your PR.

**Comment by zeropaper** [comment]
I thought so, glad it's the case.

**Comment by ErisDS** [comment]
Hi @zeropaper, those options are deliberately not supported in Ghost - the theme helpers are the most public facing part of the Ghost codebase, so changing them has to be done with great care. There has been extensive discussions and PRs around excerpts, the most up-to-date info being here: #5060.

Adding `append` is something that would need to be done for both `{{excerpt}}` and `{{content}}`. Until #5060 is done, `append` only really makes sense for `{{content}}` as there are no HTML tags output by `{{excerpt}}` and therefore adding HTML after the excerpt is straightforward. Adding `append` to `{{content}}` (or any helper which does output HTML) is non-trivial, as discussed in issue #2163.

I'd love to see the discussion on #2163 reach a resolution and I'd also love to see PRs for #5060, but adding these two options in their current form is not something that would be merged.

**Pull request closed without merging**
