### PR TITLE
Add Node 4.3 LTS to testing and engines

### LINKED ISSUE #6473: nodejs LTS update to 4.3
Now the latest nodejs LTS version is 4.3, but ghost only recognize 4.2 and will show ERROR: Unsupported version of Node when starting, though there is a way to omit the version check, but I think it's better to add support for 4.3 to prevent confusing users.

### PR DESCRIPTION
**Pull request by naoyak**
Closes #6473
- Add 4.3 to Travis
- Add 4.3 to engines for version check

### CODE REVIEW

**Comment by ErisDS** [comment]
This should categorically NOT be removing 4.2.

**Comment by naoyak** [comment]
Is Ghost keeping 4.2 support? The [security release announcement](https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/) seems to say that 4.3 LTS supersedes 4.2.

**Comment by ErisDS** [comment]
This version number change is confusing, and I believe, completely wrong for LTS. I'm pretty peeved that Node have done this.

Dropping support for one version in favour of another in the engines would prevent anyone on 4.2 from upgrading to the next version of Ghost - but they wouldn't get a notice about that until halfway through the upgrade. This means they'd be stuck HAVING to upgrade to 4.3 at an inopportune moment. 

We shouldn't be forcing people's hand like that, and neither should Node. Especially when 4.2 was declared LTS. If it is LTS then it should still be supported, that's what LTS means.

**Comment by naoyak** [comment]
I guess it was their (odd) way of forcing as many users as possible to upgrade. Thanks for the explanation.

**Comment by halfdan** [comment]
@ErisDS I agree that this is very unconventional and annoying. To be fair though, they declared 4.x LTS - not 4.2. I suppose we need to allow for 4.x in Ghost.

**Comment by naoyak** [comment]
@halfdan :+1: That sounds reasonable. If you want to be anal I guess you would say `>=4.2.0 <5.0` since 4.2.0 was the first LTS release, but based on the discussions over at Node it seems that they are allowing semver-minor changes into LTS on a case-by-case basis.

Would you only want Travis to run on the latest LTS (i.e. `4.3` currently)?

**Comment by ErisDS** [comment]
I believe the best solution here is to make sure that both the engines and travis are not tied to a minor version, so we don't end up in this situation again.

travis - `4`
engines - `>=4.2.0 <5.0

**Pull request closed without merging**
