### PR TITLE
Fix urlFor to handle secure correctly as well as canonical urls.

### PR DESCRIPTION
**Pull request by jtwebman**
Fix urlFor to handle secure correctly and forcing default

issue #6270
- Exposed getBaseUrl on the config class.
- Fix formatting config index as array was more then 140 characters long.
- Updated getBaseUrl to handle secure by replacing http with https if true.
- Fixed ghost_head helper to output canonical base url no https.
- Fixed ghost_head helper to set secure correctly for the rss link.
- Fixed navigation helper to pass secure in each nav item, so that urlFor can u$
- Fixed {{url}} to pass secure correctly to config.urlFor.
- Fixed test to use urlSSL over https besides for canonical.
- Add tests for {{url}} and to make sure they output https for absolute and secure.
- Update twitter and og url to use the canonical url

### CODE REVIEW

**Comment by ErisDS** [comment]
I believe the fix here is correct, although I've not yet finished testing it properly. However, I'm not convinced that passing the `forceDefault` attribute down to the url helper level is the right thing to do.

For one, `forceDefault` isn't the clearest attribute name, and this would become part of the theme API. It needs a little more consideration as to whether this option is needed at the theme level (surely themes would just use relative urls if they didn't want the default absolute url).

I believe the reason for adding this is that the url helper is being called in `ghost_head`, and I think a more sensible course of action for the time being is to change `ghost_head` to call `config.urlFor` instead?

**Comment by jtwebman** [comment]
I agree @ErisDS. I'll make the change to go ahead and remove that flag from the helper and the `config.urlFor` and just fix the `ghost_head` to use the `blog.url` for the canonical link.

**Comment by jtwebman** [comment]
@ErisDS ok `forceDefult` removed. Do you want me to go ahead and swash the commits again?

**Comment by ErisDS** [comment]
Just taken this for a proper spin, the underlying issues are all solved :+1: 

One detail - I *think* that the og url and twitter url should use the default / canonical url because if they don't users sharing via http and https would end up sharing different urls and I'm not sure how twitter and facebook cope with that with regards to share counts.

I think, if we use the default/canonical for the meta data here, it will mean even if users use 2 different protocols and share the links, twitter & facebook will be told what the canonical url is and get the same url  either way.

**Comment by jtwebman** [comment]
Ok, I'll make the change tonight so that they use the canonical url. Also I'll rename the props variable to canonicalUrl vs defaultUrl to make it less confusing.

**Comment by jtwebman** [comment]
@ErisDS All done.  :+1:

**Pull request merged**
