### PR TITLE
[WIP] Refactored api middleware stack directly to routes

### PR DESCRIPTION
**Pull request by rshbhgrg**
refs #9866 

- move middleware stack from v2/admin/middleware.js directly to routes.js
- move middleware stack from v2/content/middleware.js directly to routes.js
- do not refactor web/api/v0.1

### CODE REVIEW

**Comment by rishabhgrg** [comment]
I am actually not 100% after moving if it looks better with middleware stack inside `route.js` or if it was cleaner when it was in a separate file. The stack itself is not too many lines, main concern is its not looking clumsy and also it stays obvious where to make changes in mw stack after this. Wdyt? 🤔

**Comment by gargol** [comment]
The only thing that worries me in this refactor that we end up having 2 different conventions in `/api/v2` folder and the rest of the codebase :) @kirrg001 do you remember what were the reasons for this move other than readability?

**Comment by kirrg001** [comment]
> reconsinder e.g. web/v2/admin/middleware - put the middleware stack helper to routes.js?

The task was to reconsider :) I just thought that this middleware.js is weird with this single stack. Maybe it should belong to `api/v2/middlewares/auth` and then you can do `local.middlewares` or so.

**Comment by kirrg001** [comment]
@rishabhgrg Can we close this? :)

**Pull request closed without merging**
