### PR TITLE
Harvest server side strings

### LINKED ISSUE #5617: i18n: harvesting server-side strings
## The Problem
Ghost is currently pretty much UK-based English-language only, and has barely any features to account for timezones, locales, languages, alphabets, keyboard layouts or anything else that isn't UTC/English in either the admin or in themes. Even the USA folks luck out, sorry! All this is set to change with full support for multiple locales and languages across the admin and your blog posts. [[src](#3801)]

## The Solution
(see #5345 for full details)

The first phase of the multi-part rollout is to remove all strings that are hard-coded in the app and put them in a centralized location (referred to as "harvesting"). At the end of phase 1 English would still be the only language supported in Ghost and there would be no noticeable change to the end-user, but it will put things in a place where translations can start taking place.

But this is a big job and no one person can do it all alone (unless you're brave and have lots of free time)!  
Each piece of the string harvesting can be done separately and referencing this issue, which make a few good small issues for either beginners or folks that want to contribute but may not have a lot of time free time.

This commit is to help demonstrate how to go about harvesting strings and replacing it with the proper i18n function: https://github.com/morficus/Ghost/commit/a1559cde068f1861bf672e66ef2354c4d1fb6288

(PS: This particular issue is focused only on harvesting string that are server-side. There will be another issue for client-side strings.)

## Tasks
To grab a task, just leave a comment below indicating which you will be working on.

Places that have lots of strings across many files:

* [ ] /core/server/api
* [ ] /core/server/data

Places with a healthy amount, but not too many files:

* [ ] /core/server/models
* [ ] /core/server/helpers
* [ ] /core/server/middleware
* [ ] /core/server/apps

Places that have a small amount of strings that need harvesting:

* [ ] /core/server/controllers
* [ ] /core/server/config
* [ ] /core/server/permissions
* [ ] /core/server/utils
* [ ] /core/server/ghost-server.js
* [ ] /core/server/index.js
* [ ] /core/server/mail.js
* [ ] /core/server/require-tree.js
* [ ] /core/server/update-check.js

### PR DESCRIPTION
**Pull request by kevinkucharczyk**
This closes #5617 and is an updated version of #5627.

I have rebased @rfpe's changes onto the current master, added new strings and fixed some typos.

Of course, all thanks go to @rfpe, as he made the vast majority of changes here.

### CODE REVIEW

**Comment by ErisDS** [comment]
Hey @kevinkucharczyk, thanks for making such quick progress on this. Just a headsup, we're working on wrapping up the very last few changes before doing a release, and so wide-spread changes like this are all being held back until just after the release so they don't cause regressions and have plenty of time in master being tested.

Unfortunately, this does mean it'll need a rebase, but I'll give you a headsup as soon as we're ready, if that's ok?

**Comment by kevinkucharczyk** [comment]
Of course, I'll gladly do another rebase later on - just let me know when you're ready! :smile:

**Comment by ErisDS** [comment]
Now / this weekend would probably be a good time to rebase this and get it merged. There's nothing else pressing to be merged :+1:

**Comment by kevinkucharczyk** [comment]
Alright, I've performed a rebase and updated what needed updating. Let me know if there's more stuff to be done :smiley:

**Comment by ErisDS** [comment]
I'm getting an error after checking this PR and starting Ghost:

```
Unhandled rejection TypeError: Object #<Object> has no method 't'
    at Object.errors.logWarn (/Users/hannah/Ghost/Ghost/core/server/errors/index.js:76:43)
    at /Users/hannah/Ghost/Ghost/core/server/index.js:211:28
    at Array.forEach (native)
    at /Users/hannah/Ghost/Ghost/core/server/index.js:210:33
    at tryCatcher (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/Users/hannah/Ghost/Ghost/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:492:13)
```

I

**Comment by kevinkucharczyk** [comment]
Which version of node are you on and how are you starting Ghost? I can't seem to reproduce your error on my machine :confused:

**Comment by ErisDS** [comment]
From the stacktrace I see the error is coming from /Users/hannah/Ghost/Ghost/core/server/index.js:210, which is code handling invalid themes on startup. I have invalid themes in my theme dir, I'm guessing you probably do not?

**Comment by kevinkucharczyk** [comment]
Looks like I had some circular references between i18n.js and errors/index.js. Should be good now.

**Comment by ErisDS** [comment]
Apologies for letting this sit for a while, we've done a couple of bugfix-only releases, and I'm now looking at merging this in. We've definitely not made any changes which conflict, but I'm not sure if there's anything that has changed which may mean messages are missing.

I have spotted one issue with this PR, and that is the change to the preinstall scripts:

`"preinstall": "npm install semver lodash chalk intl-messageformat intl && node -e \"require('./core/server/utils/startup-check.js').nodeVersion()\"",`

Having this many libraries installed at the preinstall hook is bound to make getting Ghost installed even harder than it already is. I'd get it if there was one extra library for translating, but with this many needed I'm tempted to say that these particular strings (the startup check error messages) can do without being translated.

They all point to documentation anyway, and if anything, it's the docs that would need to be translated, I think?

We definitely shouldn't be depending on chalk and lodash at this point IMO. I could see a case being made for one extra dependency, but not 4 extra ones here.

Still, I also don't really want to hold this PR back any longer, so I'm tempted to merge and start a new issue to fix this up / discuss what it should look like. Any thoughts?

**Comment by kevinkucharczyk** [comment]
@ErisDS First of all, thank you for reviewing this PR :smiley:

I've added the dependencies to the preinstall script because they were required by `i18n.js`, which in turn is used in the `startup-check.js` script. I've decided to go this way in order to have translations exist consistently in all files, instead of ignoring this one check.

However, I'm not sure whether translations are really required in all backend places, since some errors/logs are only ever shown in the command line. Perhaps those messages should always be kept in english, so that it's easier to debug any issues.

I'm fine with merging this for now (if the core team is okay with that, it is a big change after all) and starting a new discussion. We should also make sure that all contributors are aware of the introduced i18n format - all new backend strings should be introduced with `i18n.t`.

**Pull request merged**
