### PR TITLE
Es6 migration 9589

### PR DESCRIPTION
**Pull request by iancottam91**
ES6 migration - Update the folder `/lib/common`

refs #9589

- use const and let
- removed lodash
- use template literals
- user arrow function to preserve `this`

### CODE REVIEW

**Comment by vikaspotluri123** [comment]
Hey @iancottam91 👋 do you plan on migrating the rest of the lib folder? If so, I can add you as working on it in the [checklist](https://github.com/TryGhost/Ghost/issues/9589#issuecomment-383177370) so people don't step on eachother's toes 😄

**Comment by iancottam91** [comment]
Hey @vikaspotluri123  Yep I'll migrate some more of the lib folder. Feel free to add me to the checklist.

Is it ok for me to do small PRs like this for a few files, rather than one big PR for the entire folder?

**Comment by vikaspotluri123** [comment]
Yep, PRing small quantities of files would be perfect 👌

I've marked you as working on it!

**Review by kirrg001 — APPROVED** [review]
Thanks :)

**Pull request merged**
