### PR TITLE
fix(twitter-card): use proper image tag

### PR DESCRIPTION
**Pull request by gergelyke**
The reason:

https://dev.twitter.com/cards/types/summary
- [x] Commit message has a short title & issue references
- [x] Commits are squashed 
- [x] The build will pass (run `npm test`).

### CODE REVIEW

**Comment by acburdine** [comment]
Hey @gergelyke!

I can't say whether or not this can be merged, but you also need to re-write some of the tests. If you look at the travis failures it should show you which ones you need to edit.

Thanks! 😄

**Comment by gergelyke** [comment]
Hello @acburdine ,

got it, fixing it now!

G

**Comment by gergelyke** [comment]
It is fixed - how can we make sure it is merged? Currently, the Twitter share card is not working with Ghost.

**Comment by acburdine** [comment]
Thanks! I'll take a look in a bit and verify it.

What I meant by that earlier is that I wasn't sure if I myself should merge it. If it's not working with twitter currently though, I'll definitely check it.

**Comment by gergelyke** [comment]
It works with facebook properly, but not with twitter. It should be merged asap.

**Comment by gergelyke** [comment]
any chance we can merge it today?

**Comment by acburdine** [comment]
@gergelyke Even if we did, you'd still have to wait until the next release of ghost to use it in production 😄 

/cc @ErisDS

**Comment by gergelyke** [comment]
When would that happen?

**Comment by acburdine** [comment]
Hopefully soon, although the next release is a pretty big one so it might be another week or so.

**Comment by gergelyke** [comment]
Got it ,thanks!

**Comment by acburdine** [comment]
@gergelyke Sorry for taking so long (had to figure out how to test it correctly).

This looks good 👍

**Pull request merged**
