### PR TITLE
[WIP] Refactor core/server/require-tree.js

### PR DESCRIPTION
**Pull request by halfdan**
This is a start at refactoring require-tree and moving it into seperate testable utils modules.

ToDo:
- [ ] Split up loading of package.json and validating it
- [ ] De-duplicate code in load-themes and load-apps
- [ ] Improve message handling
- [x] Squash commits

### CODE REVIEW

**Comment by ErisDS** [comment]
This looking pretty smart so far :smile:

**Comment by jaswilli** [comment]
Does this preserve the existing symlink functionality?

**Comment by halfdan** [comment]
@jaswilli Yes

**Comment by ErisDS** [comment]
Closing in favour of #5923

**Pull request closed without merging**
