### PR TITLE
🐛  fix brute

### PR DESCRIPTION
**Pull request by kirrg001**
no issue

- brute-knex uses timestamp type, see https://github.com/llambda/brute-knex/blob/master/index.js
- so we also defined timestamp type
- but see http://stackoverflow.com/questions/9192027/invalid-default-value-for-create-date-timestamp-field
- and see http://stackoverflow.com/questions/35237278/mysql-invalid-default-value-for-timestamp-when-no-default-value-is-given
- **mysql does not allow a second timestamp without default value, that's why initialising mysql does not work right now - it crashed because it complains that it needs a default value for the timestamp field**
- we have two options: define a default value or allow null or use dateTime
- let's use dateTime, as 1. we are using it for all our dates in Ghost and 2. it's recommended
- read here http://www.sqlteam.com/article/timestamps-vs-datetime-data-types
- there are some difference between these two types, i think the most important difference is that timestamp type changes the date if the tz changes in your database
- another fix: lifetime is timestamp not a bigInteger, this was a mistake i think (see https://github.com/llambda/brute-knex/blob/master/index.js#L115)

### CODE REVIEW

**Comment by kirrg001** [comment]
ready for review

**Comment by cobbspur** [comment]
LGTM 👍

**Comment by kirrg001** [comment]
Do not merge yet, i am testing something. Will come back soon.

**Comment by kirrg001** [comment]
I have added two more fixes.

And i think i found another issue, which shows me:

```
Uncaught delete from `brute` where `lifetime` < '2016-11-09T20:01:57.210Z' - ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2016-11-09T20:01:57.210Z' for column 'lifetime' at row 1
  Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2016-11-09T20:01:57.210Z' for column 'lifetime' at row 1
      at Query.Sequence._packetToError (node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14)
      at Query.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:536:20)
```

I am getting the error when running:
`LEVEL=error TRAVIS=true NODE_ENV=testing-mysql grunt test:core/test/functional/routes/api/authentication_spec.js`

This error appears also with other data types.
But this could be a local mysql issue. I have to investigate. PR stays WIP.

**Comment by kirrg001** [comment]
Seeing now in Travis. Reminder for me tomorrow.

`Uncaught Error: delete from "brute" where "key" = 'jZAy0XL4YHB+gE2DzISaqkexo69UeaM9w9IsEq3FgDM=' - SQLITE_ERROR: no such table: brute`

**Comment by ErisDS** [comment]
One way to fix ERR_TRUNCATED_WRONG value errors:

- Find your my.conf file (usually in /usr/local/mysql-version-number)
- Inside that file, remove STRICT_TRANS_TABLES from the sql-mode line. You'll then need to restart MySQL.

I don't think we want to make this required for Ghost though, so figuring out why the datatype is wrong is probably a good idea.

**Comment by kirrg001** [comment]
Ok i have pushed more fixes to Ghost and our brute-knex fork:
https://github.com/cobbspur/brute-knex/commit/0cb28fa8e3230dcbf6bca8b991dbb340b9fff6cc

1. err.next is not always available, see https://github.com/AdamPflug/express-brute/issues/45
2. brute-knex has used a wrong date handling (they tried to insert JS iso format into mysql, which does not work, only when configuring mysql to ignore this) - @cobbspur we should update this as well in Ghost Auth
3. brute-knex now uses bigInteger (we should probably deny using other types) - bigInteger can store UTC timestamps including the accuracy of milliseconds
4. brute-knex tests are green now - we should think about releasing a version of the fork

We could reconsider defining a custom schema in Ghost, because it's not needed?

**Comment by kirrg001** [comment]
Travis is green, Ready for review 👍

**Comment by ErisDS** [comment]
> We could reconsider defining a custom schema in Ghost, because it's not needed?

IMO the schema should be managed by Ghost, not by brute-knex. Brute-knex should be configured to not every do any schema handling.

**Comment by kirrg001** [comment]
> IMO the schema should be managed by Ghost, not by brute-knex. Brute-knex should be configured to not every do any schema handling.

We are passing an option to ignore schema handling in brute-knex. See https://github.com/cobbspur/brute-knex/blob/override/index.js#L24
Schema creation is controlled by Ghost.

**Comment by ErisDS** [comment]
👍 IMO this is correct.

**Comment by cobbspur** [comment]
@kirrg001 Tested and this is working fine.

Only real question is if you really want to display the error when provided.

E.g 
https://puu.sh/shTEX/7069046718.png

**Comment by kirrg001** [comment]
> Only real question is if you really want to display the error when provided.

Ha no! How is it possible to have no brute table?Can you show me how to reproduce?

**Comment by cobbspur** [comment]
It may be an unlikely scenario but I simply drop the table after creation to see what error I would get (this is in sqlite3)

**Comment by kirrg001** [comment]
> It may be an unlikely scenario but I simply drop the table after creation to see what error I would get (this is in sqlite3)

I think we can ignore this scenario.

**Comment by kirrg001** [comment]
Ready to merge 👍

**Pull request merged**
