### PR TITLE
Database version 004 - Good to merge

### PR DESCRIPTION
**Pull request by ErisDS**
This is done on top of / should be picked into #5688. I've made a few fixes, as well as adding an extra op to change the type of the private blog settings. This needed some updates to the settings model, otherwise the changes weren't made.

The fixes should possibly be merged back into other commits in #5688 and I can rebase this on top / PR the main change direct to @sebgie's branch for #5688. I just wanted to push so I had it all to hand.

Whilst I was looking at this, I came across two other things:
1. fixture modifications possibly ought to be wrapped in a transaction in an ideal world?
2. the `to003` code in permissions/index.js is horribly broken and I have no idea how it ever worked!

---

refs #5614 and #5503
- update private blog type
- add logInfo where missing
- switch order of populate settings & update fixtures

Private blog settings should not be returned by public endpoints
therefore they need a type which is not `blog` or `theme`.
`core` doesn't suit either, as those settings don't usually have UI
To resolve this, I created a new type `private` which can be used
for any setting which has a UI but should not be public data

### CODE REVIEW

**Comment by halfdan** [comment]
Any reason this couldn't be resolved with a private boolean field on the
settings model?

**Comment by ErisDS** [comment]
@halfdan Settings come in various types already, these two should not be set to `blog` - this was an oversight. `blog` settings are intended to be those which are publicly available/useful - e.g. can be included in `<meta>` tags in the frontend or requested from the API without auth. `core` settings are ones which are internal only, and have no UI, this is a new class or type of setting - one which has a UI in the admin interface, but which should not be public.

**Comment by ErisDS** [comment]
This has been updated with:
- new jQuery notification message & comment
- https link for jQuery
- updated `client_trusteddomain` table to be called `client_trusted_domains`
- fixed an issue with the use of `_.extend` 
- new log messages (to be squashed)
- updated my fix for settings edit to not ignore empty values (I couldn't empty out `ghost_foot`, whoops!)

Still @TODO:

- Add migration for tags (see #5709)
- Test jQuery migration now works from 0.5.5 -> this PR
- Test all of these migrations work with sqlite, mysql & postgres
- Fix the bug with upgrades from db version 002

**Comment by ErisDS** [comment]
I've now completed the following 3 tasks and added them to this PR:
- Add migration for tags (see #5709)
- Test jQuery migration now works from 0.5.5 -> this PR
- Fix the bug with upgrades from db version 002

The tests for the jQuery migration flagged up that we were only populating the databaseVersion setting as part of migrations, rather than adding all missing settings, so I changed the code [here](https://github.com/ErisDS/Ghost/commit/886ec10e7bd40f7113d2ccba37806ddd28c85c6b#diff-6de8093fcafa73ed84f9cb2c3a4b80dcL36)

There turned out to be 2 bug fixes for migrating from older pre-multiuser blogs. The first was to fix the horribly broken promise code [here](https://github.com/TryGhost/Ghost/commit/7a55bb6d13ecfd3d435ec30b615662fb42e1e47b#diff-c6627a612dec0f7aa5425f34ce277eedL92). The second was to resolve an issue with the creation of passwords [here](https://github.com/TryGhost/Ghost/commit/7a55bb6d13ecfd3d435ec30b615662fb42e1e47b#diff-7a2fe80302d7d6bf67f97cdccef1f71fL391) when there is no owner user present in the DB - this helps with old migrations plus any failed fixture initialisations. More info on that issue can be found [here](https://github.com/felixrieseberg/Ghost-Azure/issues/1#issuecomment-135556311).

I have now tested upgrading from Ghost 0.4.2 and Ghost 0.5.5 with sqlite. What remains is to also test these upgrades on mysql & postgres, as well as testing upgrading from 0.6.0: 

| Version | DB | Tested By |
|------------|-----|----------------|
| 0.4.2 | sqlite | Hannah |
| 0.4.2 | mysql |  |
| 0.4.2 | pg | |
| 0.5.5 | sqlite | Hannah |
| 0.5.5 | mysql | |
| 0.5.5 | pg | |
| 0.6.0 | sqlite | |
| 0.6.0 | mysql | |
| 0.6.0 | pg | |

Databases for testing upgrading can be found here: https://github.com/TryGhost/Ghost-Config/tree/master/ghost-versions

**Comment by ErisDS** [comment]
Updated:
- Rebased against current master, inc the tag UI fix
- Added both of #5771 & #5773 to this PR
- Updated the name of `results` to `hash` in `Fix upgrade path from really old versions`
- Updated the jQuery migration to not insert the code if it has already been inserted (meaning running `FORCE MIGRATION=true` is safe)

TODO:

- New post fixture.

**Comment by ErisDS** [comment]
Added the new fixture - the content is still WIP, but the general premise of how the fixture is added won't change, so this can be tested.

**Pull request merged**
