### PR TITLE
Notifications refactor

### PR DESCRIPTION
**Pull request by kevinansfield**
issue #5409 
- [x] remove old 'notification.location' concept
- [x] fix display of persistent (alert) notifications
- [x] change persistent/passive status types to alert/notification to keep naming consistent
- [x] re-enable timed auto-close of notifications
- [x] move filtering of alerts/notifications from components into notifications service
- [x] reduce public notifications interface to showAlert/showNotification
- [x] review all notifications and update/remove as per new requirements
- [x] update notification/alert colours as per new requirements
- [x] tests
- [x] rebase and resolve merge conflicts from inline-errors
- [x] update general settings to use inline errors (+ kill generic error notification)
- [x] update signin to use inline errors
- [x] update reset to use inline errors
- [x] update signup to use inline errors
- [x] update user form to use inline errors
- [x] update setup/three to use inline errors
- [x] review error handling in code-injection
- [x] review error handling in upload modal
- [ ] `notifications.showErrors` is used in a number of places to display validation errors. Review and remove/update
- [ ] add method for alerts/notifications to have a click action specified
- [ ] remove `notification.location` concept in the API

Known issues:
- [ ] Notifications are still shown after server-side "user not found" error during sign-in as the server does not respond with a DS.Errors compatible format

### CODE REVIEW

**Comment by ErisDS** [comment]
Whoop it's green :tada:

**Comment by kevinansfield** [comment]
Yep, nearing the end now! Hoping to have some time tomorrow evening after the dev meeting to get the last inline-validation bits done.

Regarding the clickable notifications, do they need to open in the same tab or a new tab?

**Comment by JohnONolan** [comment]
> Regarding the clickable notifications, do they need to open in the same tab or a new tab?

Will be a mix, mostly same tab - but "view post" links in new tab

**Comment by ErisDS** [comment]
@kevinansfield correct on all counts :+1:

**Comment by ErisDS** [comment]
Seeing as this is passing, would it be worth getting it rebased and squashed up a bit and merging in it's current form, and then sharing out the remaining work?

**Comment by kevinansfield** [comment]
Yeah, that will probably be best. I'll find some time today to cleanup/rebase/squash and raise some issues for the final todos.

**Comment by ErisDS** [comment]
Perfect thanks :+1:

**Comment by kevinansfield** [comment]
Rebased and squashed into 3 main areas of work so it's easier to track review.

Main issues remaining:

- A method to handle clickable notifications
- I believe there are still edge cases where the editor displays notifications that don't comply with the rules set out in #5409
- Final run-through to check situations where notifications are displayed in place of inline-validations or alerts due to `notifications.showErrors` being used
- I've noticed that at least in one place (signin/signup) the API's error response for validation related concerns is not compatible with DS.Errors meaning that it can't picked up by the inline-errors implementation.

**Pull request merged**
