### PR TITLE
Provide Developer access to Content output

### PR DESCRIPTION
**Pull request by jdcauley**
This PR is an example of exposing a hookable point in the content lifecycle for developers to filter content without directly impacting core.

It adds a function call to an array of functions that can be provided at a stage outside of core.

If the theoretical implementation is considered acceptable, it could be implemented similarly to adapters for use.

If this is already possible please advise as it isn't apparent in the docs.

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test` and `yarn lint`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by jdcauley** [comment]
would replace ref #12021

**Comment by jdcauley** [comment]
Would resolve https://github.com/TryGhost/Ghost/issues/9448

**Comment by jdcauley** [comment]
@ErisDS could you advise if there is any version of a system like this that could be acceptable?

Happy to refactor into anything that might be more acceptable for the project?

**Comment by ErisDS** [comment]
The way we work on Ghost is extremely problem-focused. That means, we spend a lot of time trying to understand problems before we attempt to solve them. What is the problem? What are the use cases that make this problem apparent? How often does that use case occur and who does it affect? And so on...

As far as I can tell based on this and #12021 the problem you actually want to solve - the underlying use case - is adding `loading="lazy"` to images in content (and maybe to add WebP support).

The reason neither of these things are supported right now is due to issues with those features. Lazy loading is so new, there are (or at least were last time we checked) browser inconsistencies and bugs that meant it was broken - iirc one major browser (chrome?) wouldn't load an image that's marked lazy if it appears above the fold. WebP isn't yet supported in Safari.

As _soon_ as these things stabilise, we'll be adding them as native features.

Circling back to the solution you're trying to implement - you're looking at creating ways to extend content rendering. The _only_ acceptable version of this IMO would be the ability to register custom mobiledoc renderers because without that you just run into issues with content being rendered in different ways for different contexts (email, rss etc) and the solution not being flexible enough. Not to mention trying to do this stuff with regex is never a happy path.

Any sort of ability to do custom server-side code comes with security considerations. That alongside the addition of new extension points generates additional long-term maintenance commitment for the team. 

So to go back to where I started - there are multiple concerns. There is no clear use case that wouldn't be better solved by a direct feature implementation, and given that these features will be added directly, there's then no value to counterbalance the maintenance overhead.

I hope all this makes sense. If you wanted to do a review of lazy loading support and build the real feature, we'd be super interested!

**Comment by jdcauley** [comment]
@ErisDS do you have a planned spec for your lazy load implementation?

For my personal use case solving Lazy Load would get what I want done.

There are other cases where I would like to be able to extend content or add other schema types to output

**Comment by ErisDS** [comment]
No there's no spec because adding the attribute is fairly straightforward.

The only reason for not having added support when it was launched, is that on the [feature page](https://web.dev/native-lazy-loading/) last time I read it, it clearly said that in one major browser (Chrome I think) if `loading="lazy"` was applied to an image above the fold, then there was a bug where the lazy loading events were not being fired and so the images wouldn't load.

Browsers not supporting `loading="lazy"` isn't a problem, but browsers having a buggy implementation meaning some images won't load at all is obviously not a feature ready for mainstream!

This bug is no longer mentioned, so it basically needs testing across all major browsers to double check it works properly, and then it will be a case of adding the attribute to the mobiledoc rendererer.

**Comment by jdcauley** [comment]
I can attest to this not being a standing issue, as we've been using it across a non-trivial number of sifted for 6 months without notable issues.

**Comment by ltoinel** [comment]
@ErisDS  : My contribution to support Lazy loading 

https://github.com/TryGhost/Koenig/pull/156

**Pull request closed without merging**
