### PR TITLE
🎨  protect invalid dates

### PR DESCRIPTION
**Pull request by kirrg001**
refs #8703

e.g. if you somehow are able to send and store `00:00:0000 00:00:00` for a date, Ghost would fetch the date and transforms it into an invalid JS date. This can cause trouble on usage.

### CODE REVIEW

**Comment by kevinansfield** [comment]
👍 verified the timeout bug on current LTS, switching to this PR fixed the timeout issue for the existing post and an import didn't put the invalid times into the database.

Is #8703 staying open until the underlying stalled connection bug is fixed?

**Comment by ErisDS** [comment]
IMO #8703 only needs to stay open whilst we resolve the issue in Ghost itself

**Comment by kevinansfield** [comment]
> IMO #8703 only needs to stay open whilst we resolve the issue in Ghost itself

The stalled connection bug seemed deeper? When there was an invalid time I got the following error in Ghost's logs but it never returned a response to the browser:

```
ERROR: [default.hbs] Invalid time value 
 Rendering Error Page 
 Ghost caught a processing error in the middleware layer. 
 RangeError: [default.hbs] Invalid time value
    at getPublishedDate (/Users/kevinansfield/code/ghost/Ghost-LTS/core/server/data/meta/published_date.js:7:53)
    at getMetaData (/Users/kevinansfield/code/ghost/Ghost-LTS/core/server/data/meta/index.js:45:24)
    at Object.ghost_head (/Users/kevinansfield/code/ghost/Ghost-LTS/core/server/helpers/ghost_head.js:87:23)
    at Object.<anonymous> (/Users/kevinansfield/code/ghost/Ghost-LTS/core/server/helpers/index.js:64:28)
    at Function.Waiter.resolve (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/express-hbs/lib/async.js:83:3)
    at Object.<anonymous> (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/express-hbs/lib/hbs.js:396:18)
    at Object.eval (eval at createFunctionContext (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:14:166)
    at main (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at renderTemplate (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/express-hbs/lib/hbs.js:483:13)
    at _stackRenderer (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/express-hbs/lib/hbs.js:524:9)
    at Waiter.callback (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/express-hbs/lib/hbs.js:503:7)
    at Waiter.resolve (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/express-hbs/lib/async.js:43:12)
    at /Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/express-hbs/lib/async.js:84:15
    at /Users/kevinansfield/code/ghost/Ghost-LTS/core/server/helpers/index.js:65:13
    at tryCatcher (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/kevinansfield/code/ghost/Ghost-LTS/node_modules/bluebird/js/release/async.js:17:14) 
```

To me that suggests there's still a bug in the error handling? This PR silently fixes the invalid time error but it seems like if a different error was raised in the same place then there's still the potential for a Ghost to fail without sending a response and so creating a stalled connection?

**Comment by kirrg001** [comment]
@kevinansfield So the reason why the connection hangs is that Ghost throws an un-catched Date Range Error. So the affected meta helper does not protect the condition with try/catch. We could add a try/catch there, but invalid dates **cannot** appear anymore with this PR, because as soon as we load a date from a database, it get's validated and sanitised - so a try/catch should have to affect. 

In general you are absolutely right. We should actually do a review of all fragile conditions in our helpers area to prevent Ghost from not responding 👍

**Comment by kevinansfield** [comment]
When I had a look it was [this line](https://github.com/TryGhost/Ghost/blob/lts/core/server/errors/index.js#L343) that was hanging - if a template error for the error page is forced or this is swapped for `res.send('500')` a response was sent. So is it hanging because it's a handlebars helper that crashes meaning no more handlebars templates can be processed for the request?

Reason I wanted to pursue it a little deeper was because as a user having an error output because I have invalid data would be more useful than Ghost silently auto-fixing my bad data with magic values.

If we're happy with the auto-fix behaviour I'll merge 😄

**Comment by kevinansfield** [comment]
I'll merge as-is, it fixes the reported problem and we can always re-visit if we get reports that the sanitised dates in place of an invalid date error causes confusion (my main thought here was wrt pagination, if an import is made and the published_at values are set to `now()` it'll appear to have worked but the pagination will be broken as we saw with the fixtures in 1.0).

**Comment by ErisDS** [comment]
> The stalled connection bug seemed deeper? When there was an invalid time I got the following error in Ghost's logs but it never returned a response to the browser:

Sorry, I totally misunderstood what you meant by the "stalled connection bug" thinking you meant the behaviour we're seeing on infra, rather than something in Ghost.

**Pull request merged**
