### PR TITLE
Increase the user bio field length to 800 characters.

### PR DESCRIPTION
**Pull request by johnbellone**
There have been a [few posts about this in the forum][1]. The primary
use case here is to have a longer bio for an author. This is an
arbitrary number that I chose - if it should be longer am absolutely
open to suggests!

[1]: https://forum.ghost.org/t/bio-length-for-users/1084

### CODE REVIEW

**Comment by johnbellone** [comment]
The corresponding change for the administrative application is https://github.com/TryGhost/Ghost-Admin/pull/1684.

**Comment by ErisDS** [comment]
Hey @johnbellone - the forum post you linked to is one where I asked for a use case and never got a reply. We don't tend to make changes like this without clear use cases and you've said yourself you picked a random number.

IMO this should stay as-is until there's a clear case for changing it.

**Comment by johnbellone** [comment]
@ErisDS I do have a use case - 200 characters is quite small for a "bio" for an author - and I picked 800 characters because the bio I was trying to use was 754 characters. I don't know what other use case I could supply but I definitely will if you give me an idea!

**Comment by johnbellone** [comment]
I am currently linking to https://jbellone.blog/author/jbellone for my author page on my blog. A single paragraph will quickly hit the 200 character limit. For example, this comment alone is 206 characters.

**Comment by johnbellone** [comment]
@ErisDS I updated the **[bio](https://jbellone.blog/author/jbellone)** in the database to give you an example.

**Comment by johnbellone** [comment]
@ErisDS Any thoughts?

**Comment by naz** [comment]
Hey @johnbellone . I've reopened the "idea" on [Ghost forum](https://forum.ghost.org/t/bio-length-for-users/1084/5) to see if it picks up any traction. Lets come back to this PR when we validate a need for this change. For now, closing this PR along with one in [Ghost Admin](https://github.com/TryGhost/Ghost-Admin/pull/1684).

**Pull request closed without merging**
