### PR TITLE
Upgrade ember-simple-auth to 1.1-beta

### PR DESCRIPTION
**Pull request by acburdine**
cleans up a lot of the deprecation notices :smile:

### CODE REVIEW

**Comment by ErisDS** [comment]
I think there was a plan to update this to beta.3 and then maybe ship the beta? I've added a WIP tag for now to show that this is intentionally not merged :wink:

**Comment by acburdine** [comment]
Yeah that was the plan, I'll get that finished today :smile:

**Comment by acburdine** [comment]
Was running into an odd bug where reset tokens weren't being cleared but that was happening on master as well as with these changes and I couldn't reproduce the issue on a live blog so I _think_ it's just something local to me that's messed up. Would appreciate if someone could verify though that it doesn't cause the issue.

Issue I'm talking about: second request to authentication/revoke (to revoke the refresh_token) fails with a 401 error. This happened consistently on my local setup (multiple browsers w/incognito test, even re-cloned the repo and tried it fresh). Was testing it back as far as 0.7.6 and had the same issue, so not sure if it's just my local setup or something more going on.

**Comment by kevinansfield** [comment]
@acburdine would you mind updating to the latest beta? We can get this some time on master then to make sure there are no regressions

**Comment by acburdine** [comment]
Yep I'll do that when I'm back at my computer

**Comment by kevinansfield** [comment]
Strange, we're getting a whole lot of deprecations for `Ember.merge` but that should be worked around according to the ESA code 🤔 I can't find anything in our own code that would be causing it either - perhaps a different addon?

In any case, we'll need to hide the deprecation before we can merge as it outputs so much additional text for every test that Travis gives up 😞

**Comment by acburdine** [comment]
@kevinansfield rebased and that should fix the tests 👍

**Pull request merged**
