### PR TITLE
🐛 Fixed async helpers nested in template helpers

### LINKED ISSUE #10643: express-hbs 2.0.2 causes infinite loops and crashes Ghost
https://github.com/TryGhost/Ghost/pull/10642 reverts the update to express 2.0.2 to avoid this bug.

### Issue summary

When using the `{{#get}}` helper inside of a helper's template file, Ghost seems to end up in an infinite loop and crashes.

### Technical details

In an effort to narrow the cause of the problem the following scenarios have been tested (✅=working, ❌=infinite loop):

- ✅ `{{#get}}` inside a regular partial
- ❌ `{{#get}}` inside the original [`navigation.hbs`](https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/tpl/navigation.hbs) used by [`{{navigation}}`](https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/navigation.js)
- ❌ `{{#get}}` inside of a theme's `partials/navigation.hbs` override
- ❌ `{{#get}}` inside the [`pagination.hbs`](https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/tpl/pagination.hbs) file or a theme override

Our template-driven helpers all use [`templates.execute()`](https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/template.js#L8-L25) which compiles a hbs template string if necessary then calls the resulting function. These are non-async helpers, whereas [`{{get}}`](https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/get.js) is an async helper (returns promise).

I've generated a [flamegraph](https://vigilant-swartz-96c9bf.netlify.com/flamegraph.html) which highlights the calls within `express-hbs` [here](https://github.com/barc/express-hbs/blob/master/lib/resolver.js#L27-L31) and [here](https://github.com/barc/express-hbs/blob/master/lib/hbs.js#L602-L630) that appear to be looping.

### PR DESCRIPTION
**Pull request by allouis**
closes #10643

The async resolver in express-hbs relies on storing the state of the
promises on the `this` value inside of a helper, which is always set to
the `context`. This patch updates our helpers which render templates, to
use `this` as the context when rendering their templates.

### CODE REVIEW

**Comment by allouis** [comment]
This PR updates the `navigation` and `pagination` helpers to forward the context from the _helper_ to the underlying _template_. So it does technically change the functionality, both by providing more context to the sub template, and modifying the context at the level of the helper.

I'm wondering if the current way was intentional, and this change would be a regression @ErisDS ?

1. The reason we make the change is because `express-hbs` stores a "resolverCache" to look up async values from.

2. The cache is created at the top level and stored on [`this` or `context`](https://github.com/barc/express-hbs/blob/master/lib/hbs.js#L364) to be passed down to nested templates.

    2.a. It will never be stored on `data` AFAICT because always one of `context` or `this` will exist_

3. When we render the templates, we don't forward the `context` _or_ the `this` value. 

4. The sub template appends promises to be resolves to a resolverCache that the top level has no idea about.

If this is a regression, we _can_ fix it in `express-hbs`, but either way, the implementation for async helpers in `express-hbs` is pretty brittle, and I think needs a refresh to stop something like this cropping up again.

**Comment by ErisDS** [comment]
Nothing intentional, but IMO using _.merge/_.extends to override the first variable AND assigning is an antipattern due as it looks like the first variable has been unexpectedly overridden. IMO should be one or the other.

**Comment by allouis** [comment]
@ErisDS I've updated to simply assign to `this` rather than `_.merge` and assign to new identifier.

I've also remove the assigning `options.hash` because both helpers are just used without arguments or hash e.g. `{{navigation}}` `{{pagination}}`

**Comment by ErisDS** [comment]
> I've also remove the assigning options.hash because both helpers are just
used without arguments or hash e.g. {{navigation}} {{pagination}}

This is incorrect. We want to be able to pass variables to these templates,
if you look up my previous commit on these helpers you’ll find history of
this change with the relevant issue.

**Comment by allouis** [comment]
@ErisDS Rebased to reinstate this functionality

**Pull request merged**
