### PR TITLE
Added e2e tests for `page.unpublished` webhook

### PR DESCRIPTION
**Pull request by iamhalldor**
Adding test coverage for webhook events as per #15537

### CODE REVIEW

**Comment by halldorbjarni** [comment]
The test fails when run via `yarn run test:all` but `yarn test:single test/e2e-webhooks/pages.test.js` succeeds (at least locally). There seems to be some state pollution in the test harness that produces different urls for the `author url` AFAICT. 

I haven't been able to figure out where it's coming from yet but I'd much prefer fixing the interdependency between tests than allowing for both urls in the snapshot matching.

**Comment by halldorbjarni** [comment]
Any idea why the urls are different @naz? The fixtures are initialized for each test class so not sure why there's a difference between running the test class vs a whole suite.

**Comment by naz** [comment]
Hey @halldorbjarni 👋  The issue with a '404' URL has been haunting Ghost for a while now. For more context you can have a read through this issue - https://github.com/TryGhost/Ghost/issues/10360 (pt. 3 mentions this exact 404 issue). There's a whole family of bugs that are related to how Ghost calculates public resource URLs and this is one of it's variations. We are planning a bigger rewrite of the routing system, until then having a "centralized and documented hack" is our best solution.

There's a documented [local URL matcher](https://github.com/TryGhost/Ghost/commit/320c6e0dd3f9338081f7284d7a800c3c39d412f4) used in [post webhook tests](https://github.com/TryGhost/Ghost/blob/6b7088ba20415719e4e18df79464829125b68ee0/ghost/core/test/e2e-webhooks/posts.test.js#L18) and other places with similar behavior to the on in this PR.  My suggestion would be using the `anyLocalURL` matcher for the author's url attribute matching here. I is a hacky solution, but should unblock progress. All uses of `anyLocalURL` will be substituted with a concrete snapshot url match once we fix the root of all 404 bugs - routing 🙃 

Hope this answer helps and massive thanks for putting your time into this contribution!

**Comment by halldorbjarni** [comment]
Updated! Thanks for the clarification @naz, I definitely spent some time going down the debug rabbithole thinking this was due to a dirty test database... 😅

**Review by naz — APPROVED** [review]
🚀 exactly what we discussed! Good job @halldorbjarni 👍

**Comment by ErisDS** [comment]
Hey @halldorbjarni thanks for this PR, it's merged and should be included in today's release.

I'm looking at your bluebird PRs now :)

**Pull request merged**
