### PR TITLE
[Spike] Internal/Hidden Tag admin support

### PR DESCRIPTION
**Pull request by kevinansfield**
refs #6165
- use `#` to denote hidden tags in editor tags input
- display hidden/internal tags in content list (see screenshot)

WIP spike of client functionality outlined in #6165.

screen shot 2015-12-08 at 14 56 47

### CODE REVIEW

**Comment by kevinansfield** [comment]
@ErisDS The filtering is going to be a bigger job, does it make sense to clean the above commits up a bit and add tests so that we can release something then improve on it with additional functionality later?

**Comment by ErisDS** [comment]
The new functionality needs to be walled off behind the labs flag :wink:

**Comment by acburdine** [comment]
Just gave this a spin and can't get the tag hidden state to persist :disappointed: 

Not sure whether that's intended or not.

**Comment by kevinansfield** [comment]
This is currently in an unfinished/broken state, both the specs and database field name have changed since so it definitely needs revisiting!

**Comment by acburdine** [comment]
Cool -> I figured out why the state wasn't persisting which led me to assume that it was broken.

**Comment by acburdine** [comment]
Closing in favor of #6771

**Pull request closed without merging**
