### PR TITLE
Moved api controllers into api/v0.1

### PR DESCRIPTION
**Pull request by kirrg001**
refs #9866

- preparation for v2
- moved api/ to api/v0.1
- do export v0.1 straight from the api folder
- require('../api') still works fine
- that means currently if you require the api folder, we return v0.1 by default
- there were some direct requires of api files in the test env
  - some of them use rewire
  - for now, we just correct the require path to require api/v0.1/
  - we touch the test env next week

### CODE REVIEW

**Comment by kirrg001** [comment]
@rishabhgrg Can you pls give me an instant review? Thanks :) I just moved the files to /v0.1.

**Comment by kirrg001** [comment]
The idea is to start with smaller PR's for `api/v2` and `api/shared`.
I'll share more in the next PR's.

e.g. big overview
e.g structure

**Comment by rishabhgrg** [comment]
Yeah sounds good, this LGTM! :)

**Comment by kirrg001** [comment]
@rishabhgrg Thanks 👍

**Pull request merged**
