### PR TITLE
url helper breaks subdomains

### PR DESCRIPTION
**Pull request by ianlopshire**
Fixes bug where the url helper breaks subdomains of blog url in navigation

Closes #5303

### CODE REVIEW

**Comment by ianlopshire** [comment]
I miss-type the issue number. It should be #5033.

**Comment by ErisDS** [comment]
Hi @ianlopshire, welcome and congrats on your first PR to Ghost :+1: 

Could you please take a few minutes to have a read of our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md) and review your code style and commit message? This PR is currently not passing out build.

In addition, a bug fix like this needs to include tests to show that the issue has been resolved and prevent regressions in the future. The existing tests for `urlFor` can be found here: https://github.com/ianlopshire/Ghost/blob/master/core/test/unit/config_spec.js#L150

Thanks :+1:

**Comment by ianlopshire** [comment]
I've added unit tests for the `nav` context of `urlFor` and it passed build locally.

**Comment by ianlopshire** [comment]
@ErisDS  is there anything else I need to do for this PR?

**Comment by ErisDS** [comment]
No nothing really - the second code block doesn't make instant sense as to what it's doing, but otherwise I've just not found a moment to take it for a spin yet, will get to it.

**Pull request merged**
