### PR TITLE
RSS Fix: Do not convert protocol relative URLs

### LINKED ISSUE #5567: RSS feed incorrectly converts protocol relative URLs
Using Ghost 0.6.4.

The RSS feed of the blog converts all relative URLs from posts into absolute URLs. In this process, It fails to take into account those "protocol relative URLs" and incorrectly appends the blog's base URL as a prefix.

For example, this URL: "//imgur.com/gallery/9hOdzsx" will be converted to "http://my-ghost-blog.com//imgur.com/gallery/9hOdzsx", which is wrong. The expected behavior is that the "protocol relative URLs" should not change.

### PR DESCRIPTION
**Pull request by hwdsl2**
closes #5567
- Fixed an issue with protocol relative URLs in the RSS feed
- Such URLs should be kept as-is and not prefixed with baseUrl
- Added corresponding test to cover this case

### CODE REVIEW

**Comment by ErisDS** [comment]
Not sure why #5576 was closed? If you're having trouble, ask and we'll help!

**Comment by hwdsl2** [comment]
Hi @ErisDS, I tried to use the _.startsWith(attributeValue, '//') as suggested by @halfdan, however it throws an error:

Error: Cannot find module 'lodash.startswith'

Therefore I switched to an alternative method as described in:
http://stackoverflow.com/a/4579228

Please check the new pull request and see if it's OK. Thank you.

**Comment by hwdsl2** [comment]
Travis build URL: https://travis-ci.org/TryGhost/Ghost/builds/71443115

**Comment by halfdan** [comment]
Tests are failing because we aren't using the latest version of lodash - which I'm updating in #5580.

**Comment by ErisDS** [comment]
Our version of lodash is now updated in master. If you rebase this branch against master, the `startsWith` function should work for you.

**Comment by hwdsl2** [comment]
Thanks @ErisDS. Actually in my commit I used an alternative method to achieve it. Is that OK? Or do you still want me to change it to use the startsWith function?

**Comment by ErisDS** [comment]
Sorry, I missed that and had thought the other PR was needed. This looks good :+1:

**Pull request merged**
