### PR TITLE
Added Sinhalese locale for Portal

### PR DESCRIPTION
**Pull request by kasuncfdo**
Added translations for Sinhalese (si) locale for portal. which is making it possible for the Sri Lankan community to engage with ghost sites in a more reliable.

in order to improve the translation experience will update once I see it in action!

image
image
Excample Ghost site: [Technews.lk](https://technews.lk) Technews in Sinhala

looking forward contributors to improve the translation.
Any feedback, improvements are welcome!

### CODE REVIEW

**Comment by kasuncfdo** [comment]
@daniellockyer

**Comment by kasuncfdo** [comment]
Sure @daniellockyer would love to test it locally before committing

**Comment by daniellockyer** [comment]
Ok great! If you've got the Ghost repo cloned locally, you can:

1. add `si` to the list of [supported locales](https://github.com/TryGhost/Ghost/blob/b9014a47f83806179f28d4316ed2af59109b4d21/ghost/i18n/lib/i18n.js#L3-L23)
2. run `yarn dev --portal`
3. Load `http://localhost:2368/ghost/#/settings/general` to change your locale to `si` + save
5. Go to http://localhost:2368/, click the Portal button and it should show Sinhalese 🙂 

Note: it seems Vite doesn't auto-rebuild Portal when you change a locale JSON file, so for now you'll need to save any file in `ghost/portal/src` in order to trigger that until I find a workaround

**Comment by kasuncfdo** [comment]
yeah as I expected I've encountered some issues when trying to run it on vs code unfortunately, @daniellockyer as for now, the contributed sinhala words are okay for the site because on sites traditionally we uses Sinhala with English words together for contents because of the accessibility. in addition, I will improve the si translation in another pr once this merged and tested

**Comment by kasuncfdo** [comment]
@daniellockyer I faced issues running it on VS Code, but as for now the Sinhala words are fine for the site since we typically use Sinhala mixed with English for accessibility. I'll improve the translation in future PRs once I see it in action and test. in addition, I also improved the current translation state for the portal completely.

**Comment by daniellockyer** [comment]
Thanks @kasuncfdo! Looking forward to seeing further PRs in the future 😀

**Pull request merged**
