### PR TITLE
🎨  Use svg icons in default templates

### PR DESCRIPTION
**Pull request by aileen**
refs #8107

Replace icon fonts in server side rendered default templates with svgs.

### CODE REVIEW

**Comment by kirrg001** [comment]
In Ghost-Admin we use `ember-inline-svg`, can't we use something similar here?
e.g. https://www.npmjs.com/package/handlebars-helper-svg

**Comment by AileenCGN** [comment]
Yes, we could. But is it worth it to add an additional dependency for two svgs?

**Comment by kirrg001** [comment]
Hmm depends a little how big the dependency is. But in general, your question is correct.
Is the svg code for both the same here? This has definitely no priority.

**Comment by AileenCGN** [comment]
Two different svgs only (yet the same as in Ghost Admin) and I would also need to add them to the `server/public` folder and serve them like we do with the other images here: https://github.com/TryGhost/Ghost/blob/master/core/server/blog/app.js#L58-L60

**Comment by kirrg001** [comment]
Are the svg's here the same as in Ghost-Admin?
If yes, i would definitely re-use them via a shared access?

**Comment by kevinansfield** [comment]
> If yes, i would definitely re-use them via a shared access?

Bear in mind there's no longer any "shared access" between Ghost and Ghost-Admin, the files would need to be duplicated to exist in each project.

In my mind the current implementation seems best at this time. The inlined SVGs are not used anywhere else in Ghost and anyone copying the default templates will immediately have access to the images without needing to use another helper to pull in files dynamically.

**Comment by kirrg001** [comment]
>  anyone copying the default templates will immediately have access to the images without needing to use another helper to pull in files dynamically.

Good argument!

> Bear in mind there's no longer any "shared access" between Ghost and Ghost-Admin, the files would need to be duplicated and exist in each project.

Why is that again? Sorry, I have forgotten the reason why we have to duplicate the asset files.

**Comment by kevinansfield** [comment]
> Why is that again? Sorry, I have forgotten the reason why we have to duplicate the asset files.

Asset files that live in Ghost-Admin will have their file names changed during building as part of the cache-busting, the SVGs may also end up not being part of the build as they are not referenced anywhere but only in-lined.

If files live in Ghost, Ghost-Admin doesn't have access to them for use in the build process so it can't inline them and it would need to fetch files dynamically across the network at runtime.

**Review by kirrg001 — APPROVED** [review]
👍

**Pull request merged**
