### PR TITLE
feat: configurable mailgun bulk email batch size #15725

### LINKED ISSUE #15725: Mailgun BATCH_SIZE with a fix value of 1000 is incompatible with new users
### Issue Summary

Hi,

When you want to use Mailgun with the flex offer, they block your account to a maximum BATCH_SIZE to 10.
This value is currently to defined to 1000 and cannot be overide with settings by the end user.

in bulk-email-processor.js : 
`
module.exports = {
    BATCH_SIZE: MailgunClient.BATCH_SIZE,
`

Could be  : 
`
module.exports = {
    BATCH_SIZE: bulkEmailConfig?.mailgun?.batch_size,
`

A new setting to allow the users to set a BATCH_SIZE to 10 could be great to allow Mailgun to evaluate the mail quality before to increase to 1000 the batch size.

Thank-you ! 

### Steps to Reproduce

1. Create a ghost instance.
2. Create a Mailgun account.
3. Add 11 members to the newsletter
4. Send a newsletter
5. Mailgun will not accept more that 10 members in the recipient.

### Ghost Version

v5.19.0

### Node.js Version

v16.17.0

### How did you install Ghost?

Ghost CLI + Ghost Update

### Database type

MySQL 8

### Browser & OS version

_No response_

### Relevant log / error output

_No response_

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

### PR DESCRIPTION
**Pull request by alias-rahil**
Makes the `BATCH_SIZE` parameter configurable. Closes #15725.

- [x] There's a clear use-case for this code change, explained above
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test:all` and `yarn lint`)

### CODE REVIEW

**Comment by alias-rahil** [comment]
@daniellockyer I am not sure if I have added the migration steps properly. Could you please review?

**Comment by jakub-k-slys** [comment]
How will configurable batch size help send emails to for instance 100 members?

**Comment by alias-rahil** [comment]
> @alias-rahil How will configurable batch size help send emails to for instance 100 members?

Ghost sends newsletters in batches by making multiple requests to mailgun. Therefore, if your mailgun account has a maximum batch size limit of 10, you can configure the batch size to make Ghost send the newsletter in batches of 10 instead of the default 1000. However, for a member list of 100, Ghost would need to make 10 requests, which might result in a rate limit error (429). Therefore, there is a need to implement a back-off delay. If I find the time, I may create another PR for that. This PR would solve the issue for people who have approximately 50 members.

**Comment by jakub-k-slys** [comment]
@alias-rahil batching mechanism is already there?

**Comment by alias-rahil** [comment]
> @alias-rahil batching mechanism is already there?

@jakub-k-slys I believe it is [here](https://github.com/TryGhost/Ghost/blob/main/ghost/email-service/lib/batch-sending-service.js).

**Comment by wvengen** [comment]
Any chance of getting this merged? I have been unable to send emails because of this, with a lot of back and forth with Mailgun support but no solution yet.

**Comment by jakub-k-slys** [comment]
Greetings All. This bug also prevents me from sending emails. Any news on this matter? @alias-rahil @wvengen @daniellockyer @ErisDS

**Comment by KarimJedda** [comment]
This also fixes https://github.com/TryGhost/Ghost/pull/14947 

Can it please be reviewed/merged?

**Comment by alias-rahil** [comment]
closing in favour of #16993

**Pull request closed without merging**
