### PR TITLE
improvement: contentPath for production

### PR DESCRIPTION
**Pull request by kennethlimcp**
Needed for dockerized ghost with external volume specified.

eg: `docker run -d -v $(pwd):/var/lib/ghost ghost:latest`

The `docker-entrypoint.sh` syncs to the `/var/lib/ghost` folder so it helps with the path pointed there by default.

Signed-off-by: Kenneth Lim kennethlimcp@gmail.com

### CODE REVIEW

**Comment by acburdine** [comment]
@kennethlimcp I'm not sure how this helps?

You can put the same code in your local `config.js` and it should give you the same result.
The issue with adding it to `config.example.js` is that it would then appear on any new installations of ghost, and would need to have some sort of documentation be present

Also, this is essentially duplicating the default value for this config parameter.

**Comment by kennethlimcp** [comment]
Opps, sorry. :)

Is this the default behavior? I see images ending up in `/usr/src/ghost/data/images` in a new docker installation.

**Comment by acburdine** [comment]
It should be considering the Ghost repo has all of the default folders in the `content` directory.....The docker image isn't maintained by the Ghost core team so it's possible that it's doing some overrides of the default behavior on its own.

**Comment by ErisDS** [comment]
Have a read of https://github.com/TryGhost/Ghost/issues/6995, there are ways to do this without changing code. I'm not going to merge this PR at this time, however we do have a plan to change how Ghost's configuration works, which you can read about here: https://github.com/TryGhost/Ghost/issues/6982

**Pull request closed without merging**
