### PR TITLE
 🐛Fix for image not being deleted from cache

### LINKED ISSUE #10174: Images, themes and other files not being deleted from cache after upload
When uploading an image to your profile pic with wrong dimensions (rectangular), it stays in the cache.
It isn't a big issue, but it shouldn't have that behaviour. If using a container based setup (like docker) and you restart the container, the cache gets cleared. But in a regular setting it would stay until reboot.
I tested it on my localhost setup, macOS Mojave, with and without docker.

### To Reproduce

1. Upload a rectangular picture
2. Check cache path, image is still stored there

I expect it to be deleted, specially because it stays unoptimized. So theoretically it could eat up to 50mb of space per failed profile picture (if using default upload size limit) and basically most setups aren't doing reboots regularly.

### Technical details:

* Ghost Version: 2.6.0
* Node Version: 10.13
* Browser/OS: Any
* Database: SQLite3

### PR DESCRIPTION
**Pull request by notanengineercom**
Fixes #10174
It deletes the image from cache if it's not square.

- [x] The build will pass (run `yarn test`)

### CODE REVIEW

**Review by naz — CHANGES_REQUESTED** [review]
Left a comment in the issue this PR is fixing. There's nothing wrong with the code itself but would lean towards a more global solution for the problem. @notanengineercom let me know if you'd like to discuss further or collaborate on the fix :)

**Comment by notanengineercom** [comment]
Hey @gargol! At the end I figured out that the unzipped path of the theme in the cache was handled by gscan in the theme validate.js at /services. I added to the return value that path so it can be deleted in the promise.finally() of the themes.upload (before it never deleted the unzipped theme).

**Comment by notanengineercom** [comment]
No I haven't, I could try it later. Seeing the autoreap code I it looks good for files handled by multer/express, no need to delete files in other functions (like images upload save function). But it wouldn't handle the unzipped theme, as it's created outside the express/multer scope, and it would have no access. The unzipped folder is generated by gscan, and the namin is a random uuid.

**Comment by notanengineercom** [comment]
I just tried autoreap. It works as expected. It deletes everything on success upload. So that's great. But on failure, it doesn't delete the folder for the unzipped fake theme. [Link to image](https://d.pr/free/i/s5ooTE).

**Comment by kirrg001** [comment]
@gargol FYI we [manually remove the tmp images](https://github.com/TryGhost/Ghost/blob/2.6.2/core/server/api/v2/upload.js#L27) in the upload controller (success case). 

---

In general: i am not sure about adding https://github.com/joelabair/multer-autoreap 🤔 Two reasons i can think of:

- this library adds [console logs](https://github.com/joelabair/multer-autoreap/blob/master/index.js#L26) if unlinking does not work. IMO it's a no go that third party dependencies add console.logs. Also there is no way for Ghost to interfer with this library properly on error case
- we already manually unlink the images (as mentioned above). the library basically just calls `fs.unlink`. what was the reason for not calling `unlink` in the validation catch function manually?

I definitely see the point that unlinking could happen in a centralised place (for error and success cases).

**Comment by notanengineercom** [comment]
@kirrg001 That was my initial thought and that's why I added the unlink on the error handler file [3d317523b8315b1a1ef1c48a044b993f172b7268](https://github.com/TryGhost/Ghost/pull/10175/commits/3d317523b8315b1a1ef1c48a044b993f172b7268),  and one extra for the unzipped themes files, created by gscan (you can only access the file inside the gscan scope). If you see this three commits ([1](https://github.com/TryGhost/Ghost/pull/10175/commits/3d317523b8315b1a1ef1c48a044b993f172b7268), [2](https://github.com/TryGhost/Ghost/pull/10175/commits/4c404b85f14061b73ed3dedb3cb14c36e0cc3aed), [3](https://github.com/TryGhost/Ghost/pull/10175/commits/738caf09ede18a49999661ad07330a11f14c6796)), they should fix the issue with no other dependencies, and it's quite an simple fix. I added reverted the code back and added multer as @gargol suggestion.

**Comment by kirrg001** [comment]
> The reason behind looking into centralized file cleanup solution was that we'd need to always remember to do cleanup when we use multer.

Agree to that. It's annoying. If there is a proper lib which is better, i am fine with using it. 

But IMO it's easier to write & maintain our own mini request listener for this case. 

- register res.on event (we already have 2 examples e.g. [see](https://github.com/TryGhost/Ghost/blob/master/core/server/web/shared/middlewares/log-request.js#L27))
- fs.unlink if not disabled
- proper Ghost error handling

Not saying we have to do that now 🤣

**Comment by gargol** [comment]
Hey :wave: @notanengineercom did you have a chance to further look into this PR? Would suggest we go with manual cleanup using `require('fs-extra').unlink(req.file.path);` in places where it's appropriate and do another PR with more centralized handling like `mutler` or something custom as a follow up to this? What are your thoughts?

**Comment by notanengineercom** [comment]
Hey @gargol & @kirrg001! I could for now revert the PR to an [older commit](https://github.com/TryGhost/Ghost/pull/10175#commits-pushed-3d31752), where I did the quick and dirty fix of `require('fs-extra').unlink(req.file.path);` at the error-handler. But I do like the idea of a centralized cleanup solution. It'll make the code cleaner (error-handler.js should just do error-handling, not some file manipulation) and it'll prevent future files not being deleted if new functionality added (no need to always manually add the unlink, some new files maybe saved in the cache not via the upload form...). For example the images created with the new crop and dimensioning libs the team is building, will have new endpoints and probably multiple files on the same response, so it'll need a way to delete the cache of the resized images. 
I was actually thinking of using a res.on event, as a solution before considering multer-autoreap, so if it's fine with you for now I can revert this pull request to the previous commits I mentioned, and open a new PR with the centralized and Ghost-ish lib for this fix with the Ghost error-handler and a scalable middleware.

**Comment by notanengineercom** [comment]
@gargol @kirrg001 you can close this PR as I deleted the repo and _think_ that I have proposed a [better solution](https://github.com/TryGhost/Ghost/pull/10274) 😃

**Pull request closed without merging**
