### PR TITLE
Client dependency updates

### PR DESCRIPTION
**Pull request by kevinansfield**
no issue
- minor version bumps for the majority of out-of-date client dependencies

### CODE REVIEW

**Comment by jaswilli** [comment]
Are we really doing a separate commit for each dependency now? That seems aggressive, especially for dev dependencies.

**Comment by kevinansfield** [comment]
@jaswilli we've been doing that for quite a while, e.g. #6463

**Comment by jaswilli** [comment]
I saw that. Standardizing the format is great, but there's no need to arbitrarily separate each dependency into its own commit. 

What if two dependencies depend on each other? Are we going to break the build to adhere to this rule?

IMO, they should be grouped together in small batches and only completely isolated if common sense dictates.

**Comment by kevinansfield** [comment]
> What if two dependencies depend on each other? Are we going to break the build to adhere to this rule?

When that's happened the dependencies have been updated together in a single commit, usually named with the primary dependency.

What exactly is the argument against a separate commit for each dependency other than "it seems aggressive"? The only argument I can see is that the commit history is a bit more verbose but is that really an issue?

**Comment by jaswilli** [comment]
It definitely adds noise to the commit history--and what's the justification for adding that noise? What benefit is there to isolating every single dependency update to its own commit? Wouldn't simply settling on standard phrasing for dependency update commits suffice?

For a project that's always preached squashing commits unless there's a clear reason not to, this is a really strange shift in behavior.

> What exactly is the argument against a separate commit for each dependency

I just made it above. It's completely arbitrary and doesn't work in cases where changes depend on each other.

**Comment by ErisDS** [comment]
Here's the background convo: https://ghost.slack.com/archives/dev/p1444213666000208

I don't think it makes any sense to do a big bundle of unrelated version bumps in one commit. Chances are changes in difference dependencies all have different impacts. The main point is for clarity of what got updated when, and ability to revert. It does make sense to group related version bumps - that was also discussed.

**Comment by kevinansfield** [comment]
> What benefit is there to isolating every single dependency update to its own commit? Wouldn't simply settling on standard phrasing for dependency update commits suffice?

IMO:
- easy dependency rollback (ok, marginally easier but it's happened already)
- ability to provide a more detailed commit comment with each upgrade, highlighting what's changed and why any application-level changes were necessary
- consistency - updates are usually made independently one at a time, multiple updates in a single PR such as this are the exception rather than the rule
- at-a-glance view of what dependencies have changed directly from the commit history, there's no need to dig into the full commit comments to view which dependencies have changed that may be affecting your current work

**Comment by jaswilli** [comment]
> I don't think it makes any sense to do a big bundle of unrelated version bumps in one commit.

No, it almost never makes sense to update 15 dependency in one commit. Just like it doesn't make sense to update 15 dev dependencies in isolated commits. It's pretty straightforward to come up with a small batch of updates in a single commit. Then you don't have to deal with some random "rule" and what to do when it clearly makes no sense to follow it.

> at-a-glance view of what dependencies have changed

`git log --grep='deps:' --no-merges`

Anyway, this is not the hill I'm going to die on. Carry on.

**Comment by ErisDS** [comment]
> Anyway, this is not the hill I'm going to die on. Carry on.

:joy: 

The long term plan is that [greenkeeper will fix their thing](https://github.com/TryGhost/Ghost/issues/6452) and then we'll use that and all of this PITA will go away. For now, I personally feel more comfortable with this style over the previous one. It's just seems vaguely a lesser evil IMO.

**Pull request merged**
