### PR TITLE
update: developer installation README instructions

### PR DESCRIPTION
**Pull request by FarhadG**
With node `v0.10.35` and following the instructions for the `developer` local copy, installing via `npm i` wasn't enough to bring in `bower` correctly. I updated the `README` with having `bower` installed globally (similar to `grunt`) for easy installation.

---

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!
- [x] Commit message has a short title & issue references
- [x] Commits are squashed 
- [x] The build will pass (run `npm test`).

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by kevinansfield** [comment]
`grunt init` should be installing bower along with the other client dependencies, if it's not then that's a bug in the grunt scripts and not a docs issue. Can you confirm that `grunt init` is failing for you when you don't have bower installed globally?

There was a similar issue raised recently #7005 with fixes already applied.

**Comment by FarhadG** [comment]
Yes, that is the issue. I can check later as to why this is not installing correctly.

**Comment by vickychijwani** [comment]
I can confirm this as well, `grunt init` fails even after pulling in the latest changes in Ghost core + admin, if Bower is not installed globally.

**Comment by acburdine** [comment]
@kevinansfield I fixed it as part of TryGhost/Ghost-Admin#90 (which isn't merged yet)

**Comment by kevinansfield** [comment]
@acburdine would you mind splitting that small bit out into a separate PR so that we can resolve this issue? Thanks!

Closing in favour of fixing the underlying issue rather than updating the docs.

**Comment by acburdine** [comment]
@kevinansfield done 😄

**Pull request closed without merging**
