### PR TITLE
Use request lib in xmlrpc

### PR DESCRIPTION
**Pull request by kirrg001**
refs #9178, refs https://github.com/TryGhost/Ghost/pull/8980

I am not really sure how to test that. @AileenCGN Any idea?

### CODE REVIEW

**Comment by AileenCGN** [comment]
I don't know how to test this manually either, @kirrg001...

**Comment by kirrg001** [comment]
@ErisDS Any idea how to test the change?

**Comment by AileenCGN** [comment]
@kirrg001 Can you rebase this pretty please? I will check it again tomorrow and would like to merge it then, once I figured a good way to test it.

**Comment by kirrg001** [comment]
did 👍

**Comment by AileenCGN** [comment]
@kirrg001 I tested this whilst logging the response body and the refactoring to use `got` seems to work fine. Nevertheless, I received this message: `server error. requested method weblogUpdate.ping does not exist.` from trying to ping the Ping-O-Matic service. Unfortunately, I couldn't find any official docs/announcements, but seeing [this](https://stackoverflow.com/questions/9347164/what-does-rpc-pingomatic-com-respond-with-to-valid-pings) seems to say, that this service doesn't exist anymore.

Maybe someone else knows about it? If not, I'd suggest that we remove the service?

**Comment by AileenCGN** [comment]
Catching up on my last statement, we found the original issue with this comment:

> https://github.com/TryGhost/Ghost/issues/2148#issuecomment-37603415

> Ping-O-Matic doesn't bother returning a confirmation - so I have no idea if that service still works (or if my request is broken)

So maybe it's always been like this. Do you have any information regarding this, @halfdan?

If not, I suggest we keep it in there for now. We can always open a new PR to delete it, if it turns out that it definitely doesn't work anymore.

**Comment by kirrg001** [comment]
@AileenCGN agree

**Pull request merged**
