### PR TITLE
Add attributes for `{{tags}}` and `{{#foreach}}` helpers

### PR DESCRIPTION
**Pull request by johnny94**
issue #6205
- added `from` and `to` attribute for `{{tags}}` and `{{#foreach}}` helpers.
- added tests for these new atttributes

### CODE REVIEW

**Comment by ErisDS** [comment]
Hey @johnny94, thanks for the PR! I've just taken this for a spin. Much like my original PR that added limit, this is [missing a bit of code](https://github.com/TryGhost/Ghost/pull/6242/files) and some tests to ensure that `@last` and `@first` still work when adding these attributes. E.g. if I do:

```
{{#foreach posts from="2" to="3"}}
{{#if @first}}FIRST{{/if}}
{{#if @last}}LAST{{/if}}
{{/foreach}}
```

I would expect FIRST to be output, and then LAST, but actually neither are output. I hope this makes sense, could you possibly update your PR to add handling for these? Thanks :+1:

**Comment by johnny94** [comment]
@ErisDS Sure! I will fix it

**Comment by johnny94** [comment]
Hey @ErisDS, I have fixed it. Please check it, thanks!

**Comment by ErisDS** [comment]
Excellent thanks, this is working great now :+1: 

Could you clean up the commit history, so it's ready to merge ([explanation here](https://github.com/TryGhost/Ghost/wiki/Git-workflow#clean-up-history))? Thanks.

**Comment by johnny94** [comment]
I have cleaned up the commit history, thanks!

**Pull request merged**
