### PR TITLE
Update slovak translation for search

### PR DESCRIPTION
**Pull request by pipozzz**
This PR udpates slovak translation of search section.

### CODE REVIEW

**Review by cathysarisky — APPROVED** [review]
A quick AI check detects no problems.  Thanks for your work on these!

**Comment by pipozzz** [comment]
I have one question , even if I chagne publicaion language to `sk` I still see english words in search 
Can you take a look please ?
image
image

Thanks in advance !

**Comment by cathysarisky** [comment]
Hey, could you please check in settings > labs that you have the “portal translations” toggle turned on? It controls search, too.

**Comment by pipozzz** [comment]
image

yes I have

**Comment by cathysarisky** [comment]
You need to be on Ghost 5.99 (or higher, once there is a higher.  I started up my development site, which is running 5.99, put the language to sk and turned the slider on, and here's what I see:

image

If you're on Ghost Pro or other managed hosting, you're probably on 5.98 still.  Ghost Pro usually rolls out the newest version on Monday and Tuesday.  If you're self hosting, you'll need to update, and that update is available (through ghost-cli) currently.

**Comment by pipozzz** [comment]
oh , I just used latest docker image, I thought it is on latest released versiob, I'll check that too, thanks for direction.

**Comment by cathysarisky** [comment]
5.99 released on Friday.  I think the docker images lag at least a couple days. :)

**Pull request merged**
