### PR TITLE
Ember & Ember-Data 2.2 update

### PR DESCRIPTION
**Pull request by acburdine**
no issue

updates Ember and Ember-Data to 2.1, and updates a number of other smaller dependencies to their latest versions.

Also removes a couple of unused dependencies that are included by default with ember-cli

cc @kevinansfield

### CODE REVIEW

**Comment by acburdine** [comment]
@kevinansfield travis is failing on a dependency conflict with ember-cli-shims, except with the ember-cli-shims version I upgraded to it should work, soo..... Can you try this on your local? I tried cleaning my cache and re-installing everything and wasn't able to reproduce the travis errors.

**Comment by kevinansfield** [comment]
I've tried clearing travis' cache for that PR and re-started it. If it's still failing I'll be able to take a look locally in the morning.

**Comment by kevinansfield** [comment]
Looks like `store.push` has changed and broken some of the tests 🙁, should be quite a simple fix I think - https://github.com/emberjs/data/issues/3402

**Comment by kevinansfield** [comment]
One thing that's breaking the acceptance tests is that `store:main` in the container has now changed to `service:store`... that doesn't help with the `store.push` issues however.

It's taking a bit too long to dive into this right now and I need to get back to the current sprint work but what I would suggest is comparing our serialiser functions against the corresponding RESTSerializer functions. The adapters and serialisers are two areas where we really need to get unit tests in place - they've been the biggest pain points with ember data upgrades so far.

**Comment by acburdine** [comment]
@kevinansfield the serializers looked good to me, turns out the unit tests were a simple matter of actually depending upon the serializers.

As for the acceptance tests, I believe looking up service:store was the issue, however I think I found a better way to do it, at least for now. I removed the store.push stuff from the acceptance tests and instead had the `users/me` endpoint return the user with the role. That I think is more similar to how the actual behavior should work.

Looking into one of the last failures, which I think has something to do with the DS.Errors stuff.

**Comment by acburdine** [comment]
I got the tests to pass, tried running it locally with casper tests and ran into a huge bug with saving. Upon fixing that, I ran into another casper test failure that is due to John's PR fixing email validation.

I'll try and fix it and pr the changes tomorrow.

**Comment by kevinansfield** [comment]
> turns out the unit tests were a simple matter of actually depending upon the serialisers.

Ah, of course! Unit tests don't load the world and so wouldn't be picking up any of our customisations.

> I removed the store.push stuff from the acceptance tests and instead had the users/me endpoint return the user with the role. That I think is more similar to how the actual behavior should work.

Good shout, definitely a better way of handling it.

**Comment by kevinansfield** [comment]
I rebased this on top of https://github.com/TryGhost/Ghost/pull/6052 in order to test an ember.js bugfix PR and the rebase seems to have fixed the errors that we're currently seeing on this PR.

It would be good to get this properly rebased and merged soon after we cut the next release.

**Pull request merged**
