### PR TITLE
Use ember-invoke-action for closure action handling

### PR DESCRIPTION
**Pull request by acburdine**
no issue
- replace instances of `this.get('action')()` with more a more readable syntax

### CODE REVIEW

**Comment by jaswilli** [comment]
👍 on this. You could also consider doing something a little more concise such as:

```
let onTeardown = this.get('onTeardown') || Ember.K;

onTeardown();
```

**Comment by kevinansfield** [comment]
I experimented with [ember-invoke-action](https://github.com/martndemus/ember-invoke-action) after seeing it used in the `one-way-controls` addon - https://github.com/TryGhost/Ghost/commit/40b3834ba169790420e6295fe2905564e210a823#diff-2fbf91fd97ceb22df74969cb922a19beR101. I quite liked it as it resolves the syntax issue and takes both old-style and closure actions into account. Perhaps another option to consider?

**Comment by jaswilli** [comment]
The invoke syntax is definitely the best of the three. I guess the question is, is it nice enough to add another dependency?

**Comment by acburdine** [comment]
Since the `one-way-controls` addon uses it, and we use `one-way-controls`, then by extension it's included anyways. I'll refactor this to use that addon.

**Pull request merged**
