### PR TITLE
Add translate Vietnamese for Search

### PR DESCRIPTION
**Pull request by cuongthachHQ**
I translated search strings to Vietnamese.

### CODE REVIEW

**Review by cathysarisky — APPROVED** [review]
As far as my AI translator helper can tell, looks good! :)

**Comment by cathysarisky** [comment]
@cuongtqtran , I'm not sure if you saw them, but there are a couple strings missing from the vi translation for portal also.

**Comment by cuongtqtran** [comment]
> @cuongtqtran , I'm not sure if you saw them, but there are a couple strings missing from the vi translation for portal also.

Thank you, Cathy, for the reminder. You are the best. I have just added the missing translation strings for the portal as well.

**Review by cathysarisky — APPROVED** [review]
Thank you! :)  Looking forward to seeing all these non-English portals fully translated! :)  

And you're far too kind. It's the translators who make all of this possible. :)

**Pull request merged**
