### PR TITLE
✨add yarn.lock file and cleanup .travis.yml

### PR DESCRIPTION
**Pull request by acburdine**
no issue
- add yarn.lock with latest dependencies
- remove unused travis cache lines and install deps via yarn

### CODE REVIEW

**Comment by acburdine** [comment]
@AileenCGN once this gets merged it might be a good idea to update the gulp tooling to use yarn instead?

**Comment by AileenCGN** [comment]
Yeah maybe! Afaik @kirrg001 and @kevinansfield are taking over the gulp issue.

**Comment by acburdine** [comment]
@kirrg001 I'll update this for the latest dependency updates - but can we merge this at some point soon? (I'd rather not have to keep updating this PR every time a dependency is changed 😛)

**Comment by kirrg001** [comment]
> I'll update this for the latest dependency updates - but can we merge this at some point soon? (I'd rather not have to keep updating this PR every time a dependency is changed

sorry, will look at it tomorrow 👍

**Comment by kirrg001** [comment]
I can see two failing jobs on travis. I restarted one job to see if it was coincidence. 
Here is the other job: https://travis-ci.org/TryGhost/Ghost/jobs/194309397
Is that related to yarn install?

**Pull request merged**
