### PR TITLE
🐛  subscribers: fix delete post and delete all content

### PR DESCRIPTION
**Pull request by kirrg001**
refs #7875

- do not delete subscribers if deleting all the content
- ensure dropping all the content and deleteting a single post will delete the reference in the subscriber if exist

- [x] raise GQL issue regarding filtering, see https://github.com/TryGhost/GQL/issues/22
- [x] manual browser test
- [x] pull change into master

### CODE REVIEW

**Comment by kirrg001** [comment]
Will finish this PR Monday morning.

**Comment by kirrg001** [comment]
Ready for review!

**Comment by ErisDS** [comment]
I don't think this change will be needed in master, because there is no FK constraint on master?

**Comment by kirrg001** [comment]
I wanted to remove the deletion of the subscriber in case the user deletes all the blog content.

**Comment by ErisDS** [comment]
Ahhh 👍

**Pull request merged**
