### PR TITLE
:art: add unit tests for HB translate helper

### PR DESCRIPTION
**Pull request by cweave**
Added unit tests to extend on my MR #15529 / issue #15500. Added a regex in `t()` to explicitly check for smart apostrophes in the event that they are not stripped out/come through as undefined.

Participating inHacktoberfest :)

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks! 

- [x] There's a clear use-case for this code change, explained below
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

Also, if you'd be interested in writing code like this for us more regularly, we're hiring:
https://careers.ghost.org

### CODE REVIEW

**Review by ErisDS — CHANGES_REQUESTED** [review]
Hey @cweave, so sorry for taking an age to get back to you on this. I looked at it when you did it and wanted to sort out an issue with our existing tests to try to help with this PR and it's taken me an age as we've been shipping some pretty big features 😬 

Finally I got it done today. You can see my changes [which add a test utility]( https://github.com/TryGhost/Ghost/commit/a8b16767340e19a56a229b9a91b298b468a1dbd3) and then extend it for [testing errors](https://github.com/TryGhost/Ghost/commit/25d5839e964cfd76f9636a4447a52b5e6b2e52f5).

I think in the case of this PR, using the function call method isn't accurately testing how this works with smart quotes, because the quotes are inside the string, rather than wrapping it. 

However, I think if you use the new `shouldCompileToError` util, it _may_ be possible to write a test that more closely matches how this works in reality.

So hopefully it'll be able to change do something like `shouldCompileToErrr('{{t “This causes an error”}}', {}, {name: 'IncorrectUsageError'})`.

I hope this makes some sense?

**Comment by ErisDS** [comment]
I know it's been a long time since you opened this and you might not have time to come back to it now (although I hope you will). I've added `hacktoberfest-accepted` anyway as I was the one who blocked this and I know you worked hard on it ❤️

**Comment by cweave** [comment]
@ErisDS I appreciate tagging it! I will come back and do the updates! I haven't had a chance to compare your comments with the code yet, but I think it make sense. When I was writing the tests, I think I was experiencing a little bit of bugginess and felt that the test was a little flakey, but it was consistently producing the same results by time I put the PR in. So, I'll take a look at all that and get an update in ☺️

**Comment by ErisDS** [comment]
Hey @cweave this PR is now pretty ancient. I'm gonna close it, but if you're still interested in working on this, please re-raise the PR fresh and we'll figure out how to work through it.

(Please don't comment to request re-open, comments get lost, new PRs trigger new automations and will get our attention)

**Pull request closed without merging**
