### PR TITLE
🐛  force 008 sqlite user to re-run 008

### PR DESCRIPTION
**Pull request by kirrg001**
refs #7351 (closes)

See detailed description here: https://github.com/TryGhost/Ghost/issues/7351#issuecomment-250414759

We will force sqlite 008 database version users to re-run 008, because of a new fix.
Tested with #7459

### CODE REVIEW

**Comment by ErisDS** [comment]
The logic for how to force-rerunning here looks sound. 

However, the test failures might be hinting at a race-condition or timing error, which would also be the cause of #7345. I didn't have time to properly look  at that issue, and I know re-running usually fixes it.

**Comment by kirrg001** [comment]
This PR was failing randomly, because the migration re-run was triggered in in `NODE_ENV` testing, which is not needed. 

https://github.com/TryGhost/Ghost/pull/7461/files#diff-79a58308a1a36ab1b54544a17f88997aR95

This is not a pretty check, but the whole thing is not pretty!

**Comment by ErisDS** [comment]
I think actually, the test error is indicative of a bigger problem:

If I checkout this PR, delete my database & start ghost, then I get version 008 without the migration 006 setting being set. The second time I start my blog, the migration reruns.

**Comment by kirrg001** [comment]
yeah i know hehe. do you have an idea how to avoid?

**Comment by ErisDS** [comment]
> do you have an idea how to avoid? 
add the 006 setting as a fixture?

**Comment by kirrg001** [comment]
Hm thought about that, hmm i thought it might be weird. but can't think of something else.

**Comment by ErisDS** [comment]
Or make a different migration setting for 006/01 and check for 006/01 or 006/01?

**Comment by kirrg001** [comment]
will add `006/01` to the default fixture settings.

**Comment by ErisDS** [comment]
I just updated my last comment to make more sense, sorry.

**Comment by ErisDS** [comment]
Setting the default value to 006 fixes the case of a fresh install, but stops the script from being run in any upgrade scenario because populateDefaults is run before any upgrade 😫

There are the following cases:

1. Fresh install / populate
2. Upgrade from < 006
3. Upgrade 006/007 where dates are still in the wrong format
4. Upgrade from 006/007 where dates are in the right format
5. Upgrade from 008 where dates have already been fixed
6. Upgrade from 008 where dates are still wrong
7. Normal boot after all migrations have happened

This is in a sense related to https://github.com/TryGhost/Ghost/issues/7345 as well. The requirements for populating defaults are:

- Fresh install requires the defaults to be set first. 
- Upgrades expect the defaults to be populated in advance.
- A normal boot always requires the defaults to be populated before Ghost starts.

However, at the moment due to the maintenance mode refactor there is no guarantee of the timing of populating defaults when it comes to upgrades, and, I think, populations. 

I have a PR incoming which I think resolves all the remaining problems.



At the

**Pull request merged**
