### PR TITLE
🎨  escape sameAs for structured data

### LINKED ISSUE #7832: Escape sameAs for structured data
https://search.google.com/structured-data/testing-tool can show a syntax error if the sameAs field for example the website of an author contains a non escaped string.

See https://github.com/TryGhost/Ghost/blob/lts/core/server/data/meta/schema.js#L39

We already escape some of the fields like description. 
https://github.com/TryGhost/Ghost/blob/lts/core/server/data/meta/schema.js#L123

### PR DESCRIPTION
**Pull request by kirrg001**
closes #7832

- escape output for json-ld

### CODE REVIEW

**Comment by kevinansfield** [comment]
One problem I can see is that this will generate invalid URLs - `escapeExpression` will generate HTML-escaped content rather than URI-encoded content.

I think it would be better to do something like `encodeURI(decodeURI(data.author.website))` - that should ensure that we don't have invalid chars in the URL and the `decodeURI` call ensures that we don't end up with double-encoding if the user-supplied URL already contains encoded characters

**Comment by kirrg001** [comment]
> One problem I can see is that this will generate invalid URLs - escapeExpression will generate HTML-escaped content rather than URI-encoded content.
I think it would be better to do something like encodeURI(decodeURI(data.author.website)) - that should ensure that we don't have invalid chars in the URL and the decodeURI call ensures that we don't end up with double-encoding if the user-supplied URL already contains encoded characters

I've used `encodeURI` with Google Test-Tool, but it was not accepting this variant :(
That's why i decided to go with this solution.

**Comment by kevinansfield** [comment]
That's strange, perhaps I'm not understanding where this is being used. Would you mind linking me to the Google Test-Tool?

**Comment by kirrg001** [comment]
@kevinansfield https://search.google.com/structured-data/testing-tool/u/0/

**Comment by kevinansfield** [comment]
So it does appear that Google expects the json+ld content to be HTML-escaped, surprising but it works 😄 PR LGTM and fixes the broken html/xss for my test values 👍

**Pull request merged**
