### PR TITLE
Themes service API cleanup

### PR DESCRIPTION
**Pull request by naz**
This is a follow-up PR to https://github.com/TryGhost/Ghost/pull/10818

There was a long waiting TODO item in themes service to make the API exposed to other modules cleaner, which this PR does. Next up on the list to cleanup in this service is probably the `init` method as it does too much and accesses SettingsCache directly, but that's a topic for another PR :smiley: 

@allouis in the previous PR you had a proposal to rename `settings` into `storage`. Did a summary about why I think `settings` should stay as a name in [this comment](https://github.com/TryGhost/Ghost/pull/10818#issuecomment-507226803) happy to continue the discussion here :wink:

### CODE REVIEW

**Review by allouis — APPROVED** [review]
Changes look good!

**Comment by allouis** [comment]
Yo @gargol thanks for the ping and ref to last comment :) 

Continuing that discussion about `settings` vs. `storage`

> 1. ...[Using storage] gives the impression that the service might be implementing StorageAdapter

I get this concern and I thought about it too - personally I think it's fine, but it could deffo get confusing - thought this is a reason _not to use_ `storage`, rather than a reason _to use_ `settings`

> 2. The settings naming tries to follow the naming of the redirect's settings and the one in routing

As for this, both of the redirects and routing "settings" - though they are files, are in fact settings - both of them use YAML syntax which is specifically for configuration/settings.

The theme service on the other hand is primarily focused on the storing/extraction of zip files. IMO we should make that clear in the code - maybe `storage` is the wrong word, and given that we interface with the filesystem directly - maybe we could use something to reflect that, e.g. `themeService.fs`? 

I don't think this is blocking - but whilst we're refactoring this stuff we may as well take a bit of time to nail down some of the superficial things like naming.

**Comment by gargol** [comment]
Having a step back and looking at what's exposed from `/themes/index.js`:
- `init`
- `getActive`
- `getApiVersion`
- `activate`
- `settings`
  - `get` - gets JSON representation of the theme for API response
  - `getZip` - gets zip file from **storage**
  - `setFromZip` - saves zip to **starage**/loads it from **storage**/activates 
  - `destroy` - removes theme files from **storate**, removes from theme list cache
- `middleware`

After having this list in front of my eyes the `storage` naming starts to make more sense, but under the condition the `settings.get` is moved out to the `/themes/index.js` (renamed to getJSON?). 

Think a sensible move would be having following `/themes/index.js` signature:
- `init`
- `getActive`
- `getApiVersion`
- `activate`
- `getJSON` - moved from `settings.get`
- `storage` - renamed from `settings` it's methods stay as is
- `middleware`

Wdyt @allouis?

**Comment by allouis** [comment]
That list makes it much nicer to see :relaxed: 

You're deffo right about moving the `get` method out - `getJSON` makes sense to me :+1: 

The rest of what you've written all looks good to me :dancer: 

The only other thing I would say, is that `setFromZip` probably _shouldn't_ activate the theme, and that should happen in the upload controller (or wherever calls it) - just to keep each method doing one thing. Another option would be adding a top level method like `setFromZipAndActivate` - what do you think about that @gargol ?

**Comment by gargol** [comment]
@allouis agree that `setFromZip` does a bit too much, but would keep the changeset here to a minimum as there are [loads](https://github.com/TryGhost/Ghost/blob/4529ab5/core/frontend/services/themes/index.js#L14) of other [comments](https://github.com/TryGhost/Ghost/blob/4529ab514c9d299d4cdb86bc4abb0bc3c948cbd5/core/frontend/services/themes/Storage.js#L11) around the themes module to reorganize responsibilities, so would rather do these changes when that comes on a table.
 
For now, the main goal - calling fewer things from "server" and making the API minimal is achieved :tada: 

FYI, also had to rename `Storage` to `ThemeStorage` to avoid conflict in naming.

Think it's good to go, will merge after the release is done :rocket:

**Comment by allouis** [comment]
>  so would rather do these changes when that comes on a table.

Reasonable to me :dancer: 

Woop woop :tada:

**Pull request merged**
