### PR TITLE
Speed up Ghost boot time

### PR DESCRIPTION
**Pull request by daniellockyer**
Speed up Ghost boot time by replacing the JS-only RSA key generator library with a native alternative.

---

After profiling the initial boot, I saw the key generation library took around 25% of the boot time. (Flat section in the middle with red at the top.) JS-only libraries tend to be pretty slow for crypto.

image

I benchmarked some alternatives and [`rsa-keypair`](https://github.com/sunjith/node-rsa-keypair) (a native lib) is much faster.

```
keypair x 3.99 ops/sec ±34.45% (15 runs sampled)
rsa-keypair x 48.53 ops/sec ±8.31% (23 runs sampled)
Fastest is rsa-keypair
```

Server (in development mode) boot time on my laptop:
* Before: ~2.1s
* After: ~1.7s

So it looks like it's about 20% faster for me.

Just required a quick switch-out but should work the same. :+1:

### CODE REVIEW

**Comment by kevinansfield** [comment]
Hey @neosilky 👋 Thanks for this, looks really interesting! In general we've tried to keep away from native/binary dependencies because they've historically caused a lot of install problems for users across the myriad of environments in which Ghost is used. That said, startup performance is important to us so I've raised this internally to review in more detail 🙂

**Comment by kevinansfield** [comment]
Looking at where `keypair` is used it looks like there may be a potential refactoring to skip it altogether on boot.

The `dynamicDefault` object is used to populate default settings values for when they don't already exist, however it's still generated on every boot. Normally this isn't much of an issue because it's really quick but the usage of `keypair` has changed that. It may be that we can refactor the members keypair generation so that it only happens once on first boot, or we can move the generation to where it's used and only run it if the keypair is not already stored in settings. /cc @allouis, @rishabhgrg

**Comment by neosilky** [comment]
@kevinansfield Sure thing! The library only relies on OpenSSL but maybe there are situations where this could cause a problem.

I do have some other changes that would help performance. They're just JavaScript changes but mostly requires switching pretty lodash code for uglier vanilla code. Probably not something you want to do but it's an option.

**Comment by neosilky** [comment]
@kevinansfield Even better! :smile:

**Comment by kevinansfield** [comment]
> I do have some other changes that would help performance. They're just JavaScript changes but mostly requires switching pretty lodash code for uglier vanilla code. Probably not something you want to do but it's an option.

If they have a measurable impact (especially on boot time) and the code isn't obscured too much then we're definitely open to those sorts of contributions 🙂

**Comment by neosilky** [comment]
> If they have a measurable impact (especially on boot time) and the code isn't obscured too much then we're definitely open to those sorts of contributions slightly_smiling_face

Ok cool, will see what I have :+1:

**Comment by rishabhgrg** [comment]
@kevinansfield Raised an issue [here](https://github.com/TryGhost/Members/issues/27) to track update for members keypair generation, overall agree its a good idea to move keypair away from boot if possible at best, or only on first boot at worst. :)

**Comment by allouis** [comment]
Hey @neosilky Only just got round to catching up with this.

@kevinansfield @rishabhgrg This looks like a sane and solid change for this - I think we should merge it regardless of updates to keypair generation being skipped.

@rishabhgrg Are you able to move that issue to this repo as the changes concern files in here :+1:

**Comment by neosilky** [comment]
@allouis There have been a couple of updates to the new library since I pushed. Would you like me to update my PR and re-push?

**Comment by allouis** [comment]
@neosilky That would be great, afterwards I can test and get this in :relaxed:

**Comment by neosilky** [comment]
> @neosilky That would be great, afterwards I can test and get this in relaxed

Should be good to go!

**Comment by allouis** [comment]
Awesome! Thanks :dancer:

**Comment by allouis** [comment]
Yo @neosilky thanks again for this PR (and the research/stats behind it!)

My laptop must be a bit slower than yours, because my boot time went from ~4.5 seconds to ~2.2 seconds! This has made my life so much better :sweat_smile: :ghost:

**Comment by neosilky** [comment]
> Yo @neosilky thanks again for this PR (and the research/stats behind it!)
> 
> My laptop must be a bit slower than yours, because my boot time went from ~4.5 seconds to ~2.2 seconds! This has made my life so much better sweat_smile ghost

Haha - excellent! Would love to hear if it made much of a difference for your Pro platform.

Need to get around to sending in my other changes... It's a fairly minimal speedup for me, but now I know it's even more beneficial on other machines, they should still be useful.

**Pull request merged**
