### PR TITLE
Replace busboy upload middleware with multer

### PR DESCRIPTION
**Pull request by jaswilli**
Refs #6362 
- deps: multer@1.1.0

This shows that `multer` is pretty much a drop in replacement for the existing custom file upload middleware built with `busboy`.

The only adjustments that needed to be made were due to `multer` using `originalname` and `mimetype` instead of `name` and `type`.  The storage module's `save` method has a public interace which specifies that `name` is required, so we have to fix that up on the file payload.

### CODE REVIEW

**Comment by ErisDS** [comment]
This is more how I imagined that making this replacement would look - it removes a significant piece of code and therefore reduces complexity?

However, the property name changes are quite annoying. This was a missed consideration when creating the storage API - that the image object was busboy specific and not something standardised.

Unfortunately, I think that we need to also alias/fix the `type` vs `mimetype` change? I checked out a couple of the storage modules listed on the wiki and they depend on that property. `mimetype` is probably a better name for the property than `type` though - so perhaps we should do a deprecation dance??

**Comment by jaswilli** [comment]
> Unfortunately, I think that we need to also alias/fix the type vs mimetype change?

It's not explicitly called out as part of the spec, but yeah, it's probably the polite thing to do.

> do a deprecation dance

What did you have in mind here? Obviously we can update the wiki doc and add a blurb to the release notes. I don't think we have any reasonable way of detecting what a `StorageBase` implementor is doing and trigger a run-time warning?

We could also just hit the road and start submitting PRs against the handful of custom storage modules that exist...

**Comment by ErisDS** [comment]
>> do a deprecation dance
> What did you have in mind here?

:grin: I didn't really know.

How about, advance warning on the wiki page and in a "coming changes" blog post (which we can link to in the 0.7.9 release post) and then merging the change for [0.8.0](https://github.com/TryGhost/Ghost/milestones/0.8.0)?

Could also shove a deprecation warning into 0.7.9 for anyone with a custom storage engine (you're right there's no way to know what code they use). For once we can do this stating exactly which version the deprecation is going away in, instead of then being stuck with indefinite deprecation warnings!

**Comment by jaswilli** [comment]
Updated to copy both `originalname` and `mimetype` to `name` and `type`.

**Pull request merged**
