### PR TITLE
removed bluebird import, refactored Promise.props to Promise.all

### PR DESCRIPTION
**Pull request by krischanthas**
File /ghost/core/core/server/models/base/plugins/raw-knex.js

removed require bluebird, refactored Promise.props(props) to Promise.all([props])
---

### <samp>🤖 Generated by Copilot at 3591d63</samp>

Improved model relations plugin by removing unnecessary dependency and using native promises in `raw-knex.js`.

### CODE REVIEW

**Comment by daniellockyer** [comment]
Hey @krischanthas! Thanks for the PR 🙂 

A lot of this PR seems to be changing single quotes to double quotes, and formatting changes. Can you revert those changes so we just have the change to remove `Promise.props` from the file?

**Comment by krischanthas** [comment]
@daniellockyer sorry about that - I've reverted the changes to double quotes and formatting. Please review again, thanks!

**Comment by krischanthas** [comment]
@daniellockyer any idea why the regression tests are failing?

**Comment by daniellockyer** [comment]
Promise.props does not translate as easily to Promise.all as the PR suggests. Here is an example of how it could be achieved - https://github.com/serverless/serverless/pull/8414/files

Also, please remove package-lock.json as we ship the yarn lockfile in this repo

**Comment by daniellockyer** [comment]
Hi @krischanthas - a separate PR to resolve this has been merged, so we've removed all uses of Bluebird in this repo! 🙂

**Pull request closed without merging**
