### PR TITLE
Removes "email" from settings

### LINKED ISSUE #5299: Remove settings/general email address
On the general settings screen we have a field for admin email address, which is apparently used for important notifications (it's not). Everything to do with this (UI / back end / DB defaults) can be removed, and anything using this email address can be converted to using the blog owner's email address instead.

### PR DESCRIPTION
**Pull request by acburdine**
closes #5299

Removes the settings email which is no longer used. Also fixes a couple of tests regarding this email in the importer, and a bug in the authentication spec test.

### CODE REVIEW

**Comment by acburdine** [comment]
@JohnONolan I wasn't sure if I should change the label on the setup form. Currently the input for the email reads "Used for important notifications." I didn't know what to change it to, and since most of the UI is going to be changing soon anyway, is it worth going back in and changing?

Also, I'm pretty sure I got all of the instances in which the email was being used (aka pretty much none), but it would be helpful if someone could make sure I got everything. From what I tested however, it appears that everything works.

**Comment by JohnONolan** [comment]
Yep don't worry about setup form :)

**Comment by acburdine** [comment]
@ErisDS Anything else I need to do with this?

**Comment by ErisDS** [comment]
I've read it through and all seems sane - held it back as I wanted to give it a thorough testing on both old and new blogs etc to see if I can find any edge cases :palm_tree: 

I'm sure it's fine, will get to testing it soon :grin:

**Pull request merged**
