### PR TITLE
🐛  Fixed error for password authentication with Bearer Token

### PR DESCRIPTION
**Pull request by kirrg001**
refs #8613

### Background
- if you send a request to /authentication/token with `grant_type:password` and a Bearer token, Ghost was not able to handle this combination
- because it skipped the client authentication, see https://github.com/TryGhost/Ghost/blob/1.17.0/core/server/auth/authenticate.js#L13
- and OAuth detects the `grant_type: password` and jumps in the target implementation
- the target implementation for password authentication **again** tried to fetch the client and failed, because it relied on the previous client authentication
- see https://github.com/TryGhost/Ghost/blob/1.17.0/core/server/auth/oauth.js#L40 (client.slug is undefined if client authentication is skipped)
- ^ so this is the bug

### so when is a client authentication required?
- RFC (https://tools.ietf.org/html/rfc6749#page-38) differentiates between confidential and public clients, Ghost has no implementation for this at the moment
  - so in theory, public clients don't have to be authenticated, only if the credentials are included
- so with the current implemention
  - it is possible to skip client authentication for `grant_type: refresh_token`, because the implementation does not use the client, see https://github.com/TryGhost/Ghost/blob/1.17.0/core/server/auth/oauth.js#L11 - the refresh token generation uses the connected client it from the old refresh token
  - but the password authentication requires the client, see https://github.com/TryGhost/Ghost/blob/1.17.0/core/server/auth/oauth.js#L52, because it connects the client id with the generated token

### decision
- to not invent a breaking change here, i'll think we should just fix what we have here in Ghost at the moment - require client authentication for password authentication and all other cases can be skipped
- that means if you send a Bearer token and `grant_type: password`, client authentication is required and you will receive a new access token if user/pass is valid
- **we can change this behaviour in the next major**

## Notes
I have removed the extra client request to the database for the password authentication, this is not needed. We already do client password authentication [here](https://github.com/TryGhost/Ghost/blob/1.17.0/core/server/auth/auth-strategies.js#L19);
If a Bearer token is present and you have not send a `grant_type` (which signalises OAuth to do authentication), you can skip the client authentication.

@kevinansfield Any concerns?
@sebgie I'm pulling you in here, because you initially implemented OAuth in Ghost.

### Alternative?
Alternatively, we could require client authentication for **any**  grant type. But i don't know if this could break a client. 

Let me know if something is not clear enough.

### CODE REVIEW

**Comment by sebgie** [comment]
The bug is that it is possible to get into the password grant flow without a valid client :+1:.

To clarify when client auth is required as it sounds it is done randomly above:
If the user doesn't have a token that is already tied to a client, client authentication is required. This means that using the access/refresh tokens doesn't require client authentication.

Retrieving a new access token and accessing the public API requires a valid client_id/client_secret. The naming in this case is not great since the secret is not really secret and both are used to simply identify a client. Identification of a client can help to log client activity and to block clients that do something unwanted which obviously was never implemented.

**Comment by kevinansfield** [comment]
I have confirmed this fixes the error I was seeing earlier. @kirrg001, @sebgie is this good to go or does it need further tweaks/different approach?

**Comment by kirrg001** [comment]
> The bug is that it is possible to get into the password grant flow without a valid client

Correct. Thanks for confirming.

> If the user doesn't have a token that is already tied to a client, client authentication is required. This means that using the access/refresh tokens doesn't require client authentication.

Okay i'll update the comment.

> is this good to go or does it need further tweaks/different approach?

I have to check one more thing.

**Comment by kirrg001** [comment]
@kevinansfield pushed an update for the comment. Good to go now 👍

**Comment by kirrg001** [comment]
Report came in, see #9228. Please update the commit message 👍

**Pull request merged**
