### PR TITLE
Allow to migrate initial database without active theme

### PR DESCRIPTION
**Pull request by ertrzyiks**
It is possible to use Ghost without an active theme. The front page
renders an error and we can set a new active theme with the admin panel.
However, it was impossible to migrate a fresh database without active theme folder
in place.

In this commit we introduce `showWarning` option for validation function.
When it is set to true, then validation displays warning instead of
rejecting active theme in case it is missing. Validation works as before
when that option is set to false or omitted.

It's somehow related to #4866

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!
- [x] Commit message has a short title & issue references
- [x] Commits are squashed 
- [x] The build will pass (run `npm test`).

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by kirrg001** [comment]
Hey @ertrzyiks! Thanks so much for your pull request.

On database population all default settings keys are inserted to the database e.g. `activeTheme`. So these database operations **must** work for sure, because Ghost relies on them. If the default casper theme folder is not present, Ghost complains and does not insert the `activeTheme` setting key, which causes the error message on server start. 

`ERROR: Unable to populate database: The theme "casper" cannot be activated because it is not currently installed.`

Your fix here is not wrong, but it feels a bit hacky ? because you are using the `importing` flag to tell the settings model to ignore theme validation on database population. The `importing` flag should be only used for the importer logic. 

The `validateActiveTheme` function is used when the value of the `activeTheme` settings key changes. In my opinion we have to differ between: changing the active theme from the admin panel and activating the default casper theme on database population. So here is my suggestion:

```
return validation.validateActiveTheme(themeName, {showWarning: model.isNew()});
```

We could pass an options object into the `validateActiveTheme` to signalise to show a warning or reject the whole function call. If the settings model is new (this only happens on database population), then we only show a warning, otherwise if you try to activate a theme via the admin ui and the theme is not present, we return an error as before.

**Comment by ertrzyiks** [comment]
Hey @kirrg001 , I used that flag just because it's already there and I didn't link `importing` flag with that specific feature of Ghost. I was thinking that initial database population is also kind of importing so it seemed to be ok. 

I guess you are right and we need to a dedicated solution for this specific case and I will update my PR, hopefully this week. 

Thanks a lot for the review 👍

**Comment by kirrg001** [comment]
@ertrzyiks Thanks! There are for sure multiple ways to tackle this 👍

**Comment by ertrzyiks** [comment]
Hey @kirrg001 , I update the PR according to your suggestion, but I'm not happy about it yet. I reused original error message and the warning says 
> Warning: The theme "casper" cannot be activated because it is not currently installed. 

which is false. In fact, "casper" theme has been activated (= became an active theme).

Do you think we need a dedicated message for this case?

**Comment by ertrzyiks** [comment]
Also, I would like to add specs for this option, I guess [this](https://github.com/TryGhost/Ghost/blob/lts/core/test/unit/validation_spec.js) will be a good place, isn't it?

**Comment by kirrg001** [comment]
> Also, I would like to add specs for this option, I guess this will be a good place, isn't it?

Yes! 🙂

**Comment by kirrg001** [comment]
> Do you think we need a dedicated message for this case?

Yeah i would add a specific message or use an existing one.'

Thanks again for your fast updates 😎

**Comment by ertrzyiks** [comment]
@kirrg001 It's kinda done. Please let me know if the copy I reused for the warning makes sense to you. Also, I need to spend more time on manual testing during the weekend.

I had problem with stubbing `errors.logWarn` which turned out to be leak from another spec - that's why I put `is_spec` to a sandbox.

**Review by kirrg001 — CHANGES_REQUESTED** [review]
I found a problem:

If you reset your database. And delete the default casper theme folder (+ all custom themes). Setup your blog via the admin panel, i am no longer able to show the settings panel to choose a theme, because `settings.availableThemes` is undefined and the admin code crashes, because it expects an array.

Furthermore i wondered how to receive the error via the admin panel for: `theme can't be activated`, see https://github.com/TryGhost/Ghost/blob/lts/core/server/data/validation/index.js#L149. Because e.g. i upload a custom theme, i navigate to the admin panel, then i remove the custom theme folder and try to activate it, it should activate successfully, because it is using the config cache, see https://github.com/TryGhost/Ghost/blob/lts/core/server/data/validation/index.js#L136. And if i restart Ghost, the custom theme won't be available anymore in the admin UI theme list. This doesn't have to be part of your PR, just leaving this here. Maybe i will raise a different issue.

**Comment by ertrzyiks** [comment]
Hey @kirrg001, I was able to get that validation error by not refreshing admin panel in the browser after I restarted ghost without any theme. The `availableThemes` option was preloaded in the javascript and submitting the form sent theme name to the backend which reported this exact validation message.

About `availableThemes` itself, I think it is a separate issue. Even without my changes you can reset database having the casper theme installed and then remove it leaving admin panel in a broken state.

**Comment by kirrg001** [comment]
> About availableThemes itself, I think it is a separate issue. Even without my changes you can reset database having the casper theme installed and then remove it leaving admin panel in a broken state.

I will check that again. Thanks!

**Comment by kirrg001** [comment]
@ertrzyiks I will review this PR next month again (~15th of June). We have monthly LTS releases. Thanks for your work and your patience 👋

**Comment by kirrg001** [comment]
> About availableThemes itself, I think it is a separate issue. Even without my changes you can reset database having the casper theme installed and then remove it leaving admin panel in a broken state.

yeah 👍 see https://github.com/TryGhost/Ghost/pull/8587

**Review by kirrg001 — APPROVED** [review]

**Pull request merged**
