### PR TITLE
📌 Pinned Node v10 to ^10.13.0

### PR DESCRIPTION
**Pull request by kirrg001**
no issue

- see https://nodejs.org/en/blog/release/v10.13.0/

**requires CLI release**

### CODE REVIEW

**Comment by kirrg001** [comment]
https://github.com/TryGhost/Ghost-CLI/pull/854

**Comment by kirrg001** [comment]
CLI was released.
https://github.com/TryGhost/Ghost-CLI/releases/tag/1.9.8

**Comment by kirrg001** [comment]
@gargol We can release this today.

**Comment by gargol** [comment]
lgtm

**Pull request merged**
