### PR TITLE
✨  [FEATURE] AMP⚡

### PR DESCRIPTION
**Pull request by aileen**
Support _AMP (Accelerated Mobile Pages)_ for Ghost. For every blog post there will be an equivalent AMP post. The AMP version of the post can be reached by adding `/amp/` to the end of the URL (e. g. `https://myghostblog.com/welcome-to-ghost/amp/`). The default template for AMP is in the Ghost core (`/core/server/apps/amp/lib/views/amp.hbs`) and can be overwritten by adding a custom `amp.hbs` in your theme folder in `content/themes`.

This PR includes also changes for structured data and JSON+LD, as we will now output the `height` and `width` of images. See PRs #7152, #7151 and #7153.

Overview of included AMP PRs:
- #7157: HTML version of the AMP template
- #7171: AMP routing and controller implements AMP in `/apps/` and handles the `/amp/` route.  
- #7205: Change the use of context to handle as array, as a preparation for the upcoming `['amp', 'post']` context.
- #7174: Update `{{ghost_head}}` to deal with the `amp` context and adds _new_ helpers for the AMP template:
  - `{{amp_components}}`: adds AMP script tags to `<head>` depending on HTML content
  - `{{amp_content}}`: transforms the regular HTML into AMP HTML and strips out prohibited HTML tags.
- #7126: Bugfix: code injection can't be used in `{{ghost_head}}`, when in `amp` context.
- #7215: `<audio>` tags get transformed now into AMP HTML
- #7223: _New_ helper `{{amp_ghost_head}}` to use instead of `{{ghost_head}}`

### CODE REVIEW

**Comment by amilajack** [comment]
Will existing custom themes have to adapt to the new changes or will they work out of the box?

**Comment by AileenCGN** [comment]
Hey @amilajack,

they will work out of the box with our default AMP template:

image

**Comment by kirrg001** [comment]
good work @AileenCGN 
👍 👍

**Comment by alexbagirov** [comment]
Yay!

**Comment by amilajack** [comment]
@AileenCGN What release is this going to be in?

**Comment by AileenCGN** [comment]
The next one, Ghost 0.10.0! 🎉

**Comment by PunKeel** [comment]
First feedback :(

- Logo needs to be raster (no svg), and be the full logo [AMP Logo Guidelines](https://developers.google.com/search/docs/data-types/articles#amp-logo-guidelines). That's not the case in my setup :(
- Every article needs a _post image_, else the _Article_ validation will fail and render the AMP markup useless. (<- This makes me really really sad. None of my articles have a post image :sob:)

Everything else looks fine to me.

**Comment by AileenCGN** [comment]
Hey @PunKeel, sorry to hear, that you're not happy with the AMP result. Here a few thoughts:

> Logo needs to be raster (no svg), and be the full logo AMP Logo Guidelines. That's not the case in my setup :(

We didn't implement a logo as image yet (regardless if svg or jpg or any other format), because of this requirements. The publisher logo has many restrictions, just as you pointed it out, and it would be impossible to implement a satisfying solution for every possible case. Therefore, we decided to render the title of the blog in this *first* version of our default template.

> Every article needs a post image, else the Article validation will fail and render the AMP markup useless.

Yes, it is required, to have an article image in your schema.org data. 

But.... when you have uploaded a post image, it will be included in your schema.org data. It's just not rendered in the template. The same applies to the logo. When you have uploaded a blog logo and it fits the size requirements (< 60px height and < 600px width), then it will be rendered in the structured data. Check it out 😉 !

Of course, we made sure, that the AMP posts will pass the validations. You can try it yourself. Use the debugging route to check for any validation errors like this:

`https://my-ghost-blog.com/my-amp-post/amp/#development=1`

When you open a page like this and then check your console (developer tools), you will see, that it get's validated. You can even check, if the page will be served and validated from the Google AMP Cache servers, when you open this URL (just replace the last part of it with your data):

`https://cdn.ampproject.org/c/s/my-ghost-blog.com/my-amp-post/amp/`

Google will then tell you, that your page passes the validation or not.

I assume, that you already know, how to check your schema.org data? If not, try the [Google structured data testing tool](https://search.google.com/structured-data/testing-tool/u/0/).

I hope, I could make you feel a bit better about our AMP support and that your concerns are a bit less? If you have any further questions, just drop them here, or have a look in our [slack channel](https://ghost.slack.com/).

Cheers, ⚡  Aileen

**Pull request merged**
