### PR TITLE
[WIP/SPIKE] Tour wiring

### LINKED ISSUE #5169: Welcome Tour: Wire up tour system to display
This issue is part of the [welcome tour feature](https://github.com/TryGhost/Ghost/issues/5168) and should be implemented behind a config flag (not labs) to start with. An example of how to do this exists in [this PR](https://github.com/TryGhost/Ghost/pull/5115).

---

Description:

On the client side, we need a way to define tour items including an identifier which matches data on the server side, the position of the throbbing icon and the content to be shown. Once defined that information needs to be wired up such that the throbbing icons are shown in the place, and that they correctly show the tip content.

Spec:

The tour will consist of a number of tour items, the exact details of which have not yet been finalised. Each one will display an icon which when interacted with will display a tip with some content. The idea of this issue is to create a set of components etc that will display tour items in the right place, and ensure the interaction of these items are correct. For now I've kept the details of triggering tour items to display in [another issue](https://github.com/TryGhost/Ghost/issues/5170) so the result of this issue should be at least one tour item which always displays in the correct place.

There needs to be a way to define a set of tour items to display. Each item needs at least the following information (and possibly other details) defined in a sensible place:
- An identifier  
  This will match data on the server side in future and could just be a semantic name like 'content'
- Position for the throbbing icon  
  Because of the flexible nature of the admin UI, this needs to be based on an element on the page. e.g. the content example shown would be something like `top: 105px, right:0x` relative to: `.content-list-content`. There may also need to be other information as to when the throbber _can_ be displayed, i.e. if it's in the navigation bar it can stay all the time, but when located on a screen
- Position of the tip in relation to its icon  
  This would be one of top, right, bottom or left and defines where the content sits and which way the arrow points.
- The content of the tip
  This is made up of 3 parts, a title, body and foot. The foot should probably be the same for all tips. The body needs to be full HTML. Potentially could use the identifier to reference a template, or just define the html inline. 

This information should be used to effectively generate and display the tour icons in the correct location. Navigating around the admin UI should result in tour items which belong to a screen disappearing with that screen. The tour items should not appear at all on mobile. 

The tour icons will need to be a new component, the tips should use the existing popover component. These items already exist in HTML/CSS form in [this PR](https://github.com/TryGhost/Ghost/pull/5084). One addition to the existing popover behaviour that will be necessary as part of this is the addition of a translucent layer behind the tip content to help it stand out (should be `background: rgba(54,83,109,0.08)` [as shown here](https://github.com/TryGhost/Ghost/pull/5084/files#diff-b8a0a97b38057780e937bcd711ad862fR9))

The tips should appear when the icon is clicked on (TBC, may be hover?) and be dismissed when the 'ok thanks' button or 'Opt out of these tips' link is pressed. Clicking outside of the tip or pressing 'esc' should also close the tip (this is built in to the dropdown/popover behaviour in Ghost). 

Closing the tip should hide both the content and icon immediately. For now a refresh will bring them back, but keep in mind persistence will be added later and these items won't always need to be displayed.

The result of this issue should be 2 demo tour items which display correctly and can be interacted with to show the tip content. It would be a good idea to setup one in a global location (on the nav bar) and one in a screen specific location (as per the animation above) to demonstrate that this is all working correctly.

### PR DESCRIPTION
**Pull request by acburdine**
closes #5169, refs #5168

TODO:
- [x] finish converting old Sass code to CSS
- [x] get the demo working correctly (harcoded html/css)
- [x] build out tour component
- [ ] build out wiring system
- [ ] As always, tests
- [ ] :tada:

### CODE REVIEW

**Comment by kevinansfield** [comment]
> likely going to use ember-wormhole for the rendering

Now that the modals refactor PR is merged we already have [liquid-tether](https://github.com/pzuraq/liquid-tether) included which takes the concepts of ember-wormhole and ties them into liquidfire so that we have a central place to manage the animations.

**Comment by acburdine** [comment]
Ah okay. ember-wormhole was the first thing that came to mind, but I'll have a look-see at what liquid-tether can do and use that instead :smile:

**Comment by acburdine** [comment]
So for the moment this is working as a component with hardcoded content. I will work on finishing up the dynamic tour wiring over the next couple of days but would appreciate some input on the CSS side of things just to make sure I copied everything over correctly.

cc @JohnONolan @kevinansfield

**Comment by JohnONolan** [comment]
It looks totally fine as far as I can see :+1:

**Comment by acburdine** [comment]
Closing in favor of TryGhost/Ghost-Admin#20

**Pull request closed without merging**
