### PR TITLE
Update NPM dependencies

### PR DESCRIPTION
**Pull request by kkirsche**
Update NPM dependencies

### CODE REVIEW

**Comment by jaswilli** [comment]
Hi @kkirsche ,

Welcome to the project!  This is a lot of dependencies to be updating all at once.  It makes troubleshooting any issues that come up down the road difficult because so many things changed in one commit.  Also, since you're new to the project I'm not sure what sort of testing has been done to ensure that all of these updates work as expected.

As it stands right now I just don't have the comfort level necessary to merge this PR.

**Comment by kkirsche** [comment]
And what would provide you with that comfort level?

**Comment by kkirsche** [comment]
Sorry that may have come off as rude where I didn't mean it too. Thanks for the welcome and I can understand your concern. What can I do to remedy your concerns and help bring your project's dependencies up to current versions?

Most are under semantic versioning and I have purposely avoided major version updates such as for LoDash to 3.3.1. 

In some cases, such as Moment.js it's nothing more than a version bump from 2.8.9 to 2.9.0 simply because they added a new repository. 

I'd be interested in showing that this has no issues but I don't know what you would require for that.

Thanks for understanding.

**Comment by ErisDS** [comment]
Hi @kkirsche, thanks for taking the time to send this, but I agree with @jaswilli here - submitting a PR that does this many updates without any testing notes doesn't make me feel comfortable about merging it either. Package updates are usually done by either someone from or very familiar with the package, or by someone who has some history contributing to the Ghost project. 

We also usually split up making changes to dev and non-dev dependencies, and separate out again the express-specific stuff. 

I'd be much happier accepting a PR that updated a smaller group of dependencies and which included notes on relevant bits of the code which have been tested. E.g. image uploads for body parser etc.

**Pull request closed without merging**
