### PR TITLE
Optimize PNG images losslessly using Google zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
This is not a code level change, just a lossless re-compression on PNG images which can make the images smaller but loss nothing on the visual quality. There are 8 PNG images optimized in this case, and there sizes reduced as below:

```
 core/server/public/404-ghost.png                           | Bin 3681 -> 3003 bytes
 core/server/public/404-ghost@2x.png                        | Bin 7958 -> 5529 bytes
 core/test/utils/fixtures/images/favicon.png                | Bin 6792 -> 2406 bytes
 core/test/utils/fixtures/images/favicon_not_square.png     | Bin 3386 -> 2661 bytes
 core/test/utils/fixtures/images/favicon_size_too_large.png | Bin 247144 -> 221762 bytes
 core/test/utils/fixtures/images/favicon_too_large.png      | Bin 79774 -> 77905 bytes
 core/test/utils/fixtures/images/favicon_too_small.png      | Bin 1470 -> 985 bytes
 core/test/utils/fixtures/images/ghost-logo.png             | Bin 8638 -> 6516 bytes
```

Let me know if there is anything should be fixed here please, thanks a lot.

### CODE REVIEW

**Comment by kirrg001** [comment]
@kevinansfield https://github.com/TryGhost/Ghost/pull/9226. You've closed a similar PR in the past. Could you please close this as well and add a small explanation? Thanks 👍

**Comment by kevinansfield** [comment]
#9226 was opened by a bot which was why it was closed. Most of the images that are being changed here are test fixtures and so have no effect other than making the repo a few bytes smaller.

The reduction in 404 image size is the only public-facing change but again really minor, can be merged if you want to. If it's merged I wouldn't put it in the changelog however because the commit message makes it sound like a major feature when it's really something no-one will notice unless they are serving a _lot_ of 404 pages to real visitors.

**Comment by AileenCGN** [comment]
The tests are failing because the assertions in `core/test/unit/web/middleware/serve-favicon_spec.js` are checking the file size.

**Comment by kevinansfield** [comment]
OK, I'm in favour of closing this then, there's very minimal benefit gained from the introduced changes. The 404 image size can be looked at separately if/when we revisit it in the future.

**Pull request closed without merging**
