### PR TITLE
Always call `_super` when using Ember hooks

### PR DESCRIPTION
**Pull request by kevinansfield**
no issue
- review use of Ember core hooks and add a call to `this._super` if missing
- use `...arguments` where no or named arguments were passed to `_super` to allow for future extensions to the API parameters
- fix a few occurrences of using the wrong component lifecycle hooks that could result in multiple/duplicate event handlers being attached

`_super` should always be called when overriding Ember's base hooks so that core functionality or app functionality added through extensions, mixins or addons is not lost. This is important as it guards against issues arising from later refactorings or core changes.

As example of lost functionality, there were a number of routes that extended from `AuthenticatedRoute` but then overrode the `beforeModel` hook without calling `_super` which meant that the route was no longer treated as authenticated.

### CODE REVIEW

**Comment by ErisDS** [comment]
Is this something that should go in before the release? Sounds like it fixes bugs?

**Comment by kevinansfield** [comment]
Any incidental bug fixes are not likely to be user-visible. It was more of a code smell that I noticed and thought best to address before it becomes more widespread.

I would be fine leaving it out of this release in order to give it more time on master for testing in case there are any unintentional side-effects.

**Comment by ErisDS** [comment]
:+1:

**Comment by rwjblue** [comment]
Giant :+1:! Not calling `_super` is a massive refactoring hazard (for both application code and Ember internals).

**Pull request merged**
