### PR TITLE
[Fix] images added to posts in markdown are displayed differently than images added using the '+' button #16685 

### PR DESCRIPTION
**Pull request by asenseofpradhyu**
Fix:- #16685 

I've made some CSS changes that address an issue related to image alignment in the markdown editor. Previously, when adding an image directly in the markdown, the image was not center-aligned as it should be when using the image button.

**Changes Made:**

Adjusted the CSS to ensure that images added through markdown are center-aligned, matching the behavior of images added using the image button.

**Before Fix:**
Screenshot 2023-08-12 at 5 50 04 PM

**After Fix:**
Screenshot 2023-08-12 at 5 50 50 PM

**This fix enhances the user experience when working with images in the markdown editor.** 

Please let me know if any further adjustments or clarifications are needed. Thank you!

### CODE REVIEW

**Review by FraneCaleta — APPROVED** [review]

**Comment by asenseofpradhyu** [comment]
Any update on this @FraneCaleta ?

**Comment by FraneCaleta** [comment]
> Any update on this @FraneCaleta ?

Unfortunately, I don't have _merging_ rights on this project, so someone else will have to do it.

**Comment by asenseofpradhyu** [comment]
Hey @minimaluminium 

Any update on this ?

**Comment by daniellockyer** [comment]
This is no longer needed because we've removed this editor 🙂

**Pull request closed without merging**
