### PR TITLE
Added Greek Locale for portal,comments,ghost and signup-form

### PR DESCRIPTION
**Pull request by nikostzoras**
Hey, I just added the Greek locale for Ghost. There is an error, but I can't understand why.
The translations are 99% accurate, and I'm pretty confident that all users will understand every text displayed. Some changes could be made to shorten the sentences, but I think this is a great start.

### CODE REVIEW

**Comment by royalfig** [comment]
Hi @nikostzoras, thanks for the contribution!

Unfortunately, the folder name, `greek`, isn't right. You need to use the [ISO language code](https://www.w3schools.com/tags/ref_language_codes.asp). Please update the folder name and then we can merge the changes.

**Comment by nikostzoras** [comment]
This is my first time using GitHub and I have no idea what I'm doing. I managed to translate Ghost following the instructions from the official Ghost youtube channel. How can I edit the files ? Thanks for your time and patience

**Comment by amirsaam** [comment]
@nikostzoras you need to name your folder `el` and add this code to `ghost/i18n/lib/i18n.js` too.

p.s. to devs, please remember to release a new version for portal and comments-ui after merging.

**Comment by 9larsons** [comment]
Closing this out. We have the strings for the right locale code (`el`).

**Pull request closed without merging**
