### PR TITLE
Removed members internal app

### PR DESCRIPTION
**Pull request by allouis**
Removes the members "app" in favor of directly mounting the staticRouter, this accomplishes two things:

1. Remove unnecessary third place for members to live
2. Makes members a first class citizen in terms of the siteApp

### CODE REVIEW

**Comment by allouis** [comment]
@kirrg001 hopefully this addresses the concerns from here: https://github.com/TryGhost/Ghost/pull/10262#discussion_r240145977

**Comment by kirrg001** [comment]
Does it make sense to outsource members completely out of Ghost as part of this cycle? 🤔 

e.g. (let me know if this split does not make sense at all)
members-api (makes it possible to extend Ghost core if labs setting is true)
members-client (makes it possible to extend Ghost frontend with members bundle if labs setting is true)

We install them as dep and **hardcode somewhere in Ghost** that they are getting activated if the labs setting is true.

Later on if we work on apps or whatever, we can decide how to install the members package. Members can even be a core part of Ghost. There is no limitation.

Could you please share with me why we have to [extend Casper ](https://github.com/TryGhost/Casper/commits/members)for members? Just double checking because i am not sure why :) 

The future separation:
Ghost Core (API/Models/Extendable)
SDK
Frontend/Client

**Comment by allouis** [comment]
@kirrg001 Whilst we're designing members to be separate from ghost - I don't think it makes sense to actually split it in this cycle - it adds maintenance overheard, and I don't see much benefit right now. 

I think the split between `members-api` and `members-client` does make sense, but whether they should be separate packages, or just separate systems within a package, I'm not sure as one does not work at all without the other. The current architecture essentially treats `lib/members` as an external dependency and this PR has hardcoded wire up of the client and api subsystems.

We've extended Casper for integration with members, first to add the "Log in" and "Log out" buttons, and second to add the content-api sdk to fetch members content once the page has loaded - this is on a separate branch because we don't want to put alpha features into Casper.

**Comment by rishabhgrg** [comment]
fwiw I also think it doesn't make immediate sense to move out members in this cycle. There are still parts that need to be wired in to core and there will be new learnings/changes to members dep that come out of it, so guess its better to maintain changes in `lib` for now and then move it out closer to completion.

**Comment by kirrg001** [comment]
As long as it's on your radar, it's perfect 🙂

**Pull request merged**
