### PR TITLE
Fix for Mail ‘from’ option shows no effect

### PR DESCRIPTION
**Pull request by mandarons**
Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [x] There's a clear use-case for this code change, explained below
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test:all` and `yarn lint`)

This PR fixes [Fix for Mail ‘from’ option shows no effect](https://forum.ghost.org/t/mail-from-option-shows-no-effect/31857)

We appreciate your contribution!

Also, if you'd be interested in writing code like this for us more regularly, we're hiring:
https://careers.ghost.org

### CODE REVIEW

**Comment by ldpr** [comment]
Just wanted to drop a quick message to thank @mandarons for this PR and confirm that this has fixed this issue for my setup.

**Comment by lvnilesh** [comment]
related issue https://github.com/TryGhost/Ghost/issues/12802

**Comment by fasaravi** [comment]
+1

**Comment by mhkarimi1383** [comment]
+1

**Comment by samiy803** [comment]
+1

**Review by samiy803 — APPROVED** [review]

**Review by mhkarimi1383 — APPROVED** [review]

**Review by saiunes — APPROVED** [review]

**Comment by QuentinN42** [comment]
@ErisDS can this PR be merged ?
Or can you explain how to setup ghost as the following config :
- A website on `example.com`
- An account on mailgun with only `mail.com`
- Send email from `noreply@mail.com`

**Comment by mhkarimi1383** [comment]
I have just made my instance working by running a simple replace command in Kubernetes Lifecycle hooks

**Comment by mhkarimi1383** [comment]
@ErisDS any updates on this PR??

**Comment by shirish87** [comment]
Please consider this PR for merging. Seems like a straightforward fix.

**Comment by woodfairy** [comment]
Is it possible to merge this PR? Cannot run Ghost at all because of this...

**Comment by mhkarimi1383** [comment]
I moved from this project since they are not merging this issue to fix a simple problem....

**Comment by jenishngl** [comment]
@ErisDS @daniellockyer - Can someone else check and merge this PR please. Its been too long already

**Comment by ldpr** [comment]
9 months for a PR that's one line of code.

That's concerning.

**Comment by woodfairy** [comment]
Are there still no updates on this PR? A small comment from the dev team would be great...

**Comment by thorrak** [comment]
+1

**Comment by woodfairy** [comment]
@ErisDS @JohnONolan any news regarding this PR? simply merging it would solve a lot of issues for a lot of people

**Comment by itsAnuga** [comment]
And message from Lead DevOps: https://github.com/TryGhost/Ghost/issues/18590

**Comment by thorrak** [comment]
> And message from Lead DevOps: [#18590 (comment)](https://github.com/TryGhost/Ghost/issues/18590#event-10639976123)

I interpreted that as them just not being appreciative of having a duplicate discussion opened. It would be nice if there was an official comment, though. I went ahead and manually made the change on a local copy of Ghost, but would love to see this get merged!

**Comment by mandarons** [comment]
Look like they have enabled the CI to run and it is all green! This is a good sign to get this PR merged. :)

**Comment by thorrak** [comment]
Well... CI _used_ to have been run.

**Comment by ErisDS** [comment]
Apologies for the radio silence here. I realise this one line fix looks like a super simple and easy to merge solution to the problem. However, it has some unintended side effects	and there are some underlying architectural concerns that need deeper attention here.

We realise this problem is affecting lots of people so have prioritised getting the core team to look at this ASAP. 

I will follow up here again with more info on what's happening next week.

**Comment by ErisDS** [comment]
Hello everyone - realise I'm a bit late on the promised update. 

We've done a deep dive and are just pulling together all the pieces. We've confirmed this change cannot be merged without causing serious issues. We're now looking to see if there's a different quick fix, or if it needs a bigger piece of work.

My next update will come by the end of the week 🔜 and should either be a fix 🎉 or a plan for how we're going to do the bigger piece of work.

**Comment by ErisDS** [comment]
Bad news: there's no quick fix for right now. The web of different from addresses that we use is not easy to untangle, and linked to a bigger piece of work we need to do. 

Good news: that piece of work is planned to be started on immediately.

I'm sorry there isn't an easy resolution, but this will be resolved as soon as it can be. I'm going to close this PR for now, and also post a summary on the issue.

**Comment by mhkarimi1383** [comment]
> Bad news: there's no quick fix for right now. The web of different from addresses that we use is not easy to untangle, and linked to a bigger piece of work we need to do. 
> 
> Good news: that piece of work is planned to be started on immediately.
> 
> I'm sorry there isn't an easy resolution, but this will be resolved as soon as it can be. I'm going to close this PR for now, and also post a summary on the issue. 

Wow, after 11 months 😲

**Pull request closed without merging**
