### PR TITLE
Add explicit string-width resolution to fix ESM + CJS compat issue

### LINKED ISSUE #20065: Outdated version of string-width is causing the Docker image entrypoint loading to fail.
### Issue Summary

The update to fix arm32 architecture (https://github.com/TryGhost/Ghost/commit/c2485af853f7b3b86f7f141b8496439cdc4881b4) introduce a regression in the way the Ghost package is launched. When running `node index.js` there is a module resolution error similar to this issue https://github.com/nrwl/nx/issues/19249. I managed to solve the issue locally by adding `"string-width": "4.2.3"` to the `resolutions` section.

Here is the Docker test showing the error: https://github.com/docker-library/ghost/actions/runs/8756974313/job/24034646549

I would like to contribute this fix but I am not sure which `package.json` to use because the packaged one seems to be generated from the source ones.

### Steps to Reproduce

There is probably an more streamlined reproducible but building the Docker image here then running it (https://github.com/docker-library/ghost/tree/master/5/debian)

```
docker build -t ghost .
docker run --rm ghost 
```

### Ghost Version

5.82.3

### Node.js Version

18.*, 20.*

### How did you install Ghost?

In Docker using the Ghost CLI

### Database type

MySQL 5.7

### Browser & OS version

_No response_

### Relevant log / error output

_No response_

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Fixes #20065

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [x] There's a clear use-case for this code change, explained below
- [ ] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

### CODE REVIEW

**Review by daniellockyer — CHANGES_REQUESTED** [review]
Won't this set all `string-width` to the same version? We have like 3 or 4 different majors in the codebase atm and I'm concerned there are breaking changes between them (I've not checked yet)

Also, you'll need to re-run `yarn` from the top-level in order to pick this up in `yarn.lock`

**Comment by daniellockyer** [comment]
Hmm, it might also need adding to `ghost/core/package.json`. Perhaps this is why the previous fix didn't work 🤔

**Comment by daniellockyer** [comment]
The commit wasn't shipped in v5.82.10. We'll need to wait until tomorrow's release for that

**Comment by LaurentGoderre** [comment]
@daniellockyer really? Here's what I saw

Screenshot 2024-05-16 at 9 52 23 AM

**Comment by daniellockyer** [comment]
@LaurentGoderre GitHub doesn't show the correct history flow. That release was done from a branch of v5.82.9 with one commit applied on top

**Pull request closed without merging**
