### PR TITLE
Adds structured data to first index/tag/author page

### LINKED ISSUE #4677: Structured Data 2.0
In #3900, we added structured data to posts using the open graph, twitter card, and schema.org formats.

This improves the functionality of Ghost posts within social media and search engines, making them more shareable and searchable. It's all done in Ghost core without impacting on themes, and it's pretty awesome :) Now it's time to roll this out across other parts of a Ghost blog. Rather than just on post pages, we want {{ghost_head}} to output fancy structured meta data on the home page, and the *first* page of the tag and author listings. 

For the homepage, the focus is on this being a representation of the entire blog - if someone is sharing this URL, they're sharing the site itself. For the tag and author listings, what's being shared/discovered is the tag/category or author and the content is all related. All of these pages have the potential to have a cover image so it should be easy to create really nice preview.

**NB** that the data below is only intended to be output on the first page, not /page/2/ etc of any of the listings.

## Open Graph

The below represents proposed output for the homepage in `{{ghost_head}}` based on the [Open Graph protocol](http://ogp.me/) specification.

Should be tested against https://developers.facebook.com/tools/debug and https://developers.pinterest.com/rich_pins/validator/

```HTML
<meta property="og:site_name" content="{{@blog.title}}" />
<meta property="og:type" content="website" />
<meta property="og:title" content="{{@blog.title}}" /> 
<meta property="og:description" content="{{@blog.description}}..." />
<meta property="og:url" content="{{@blog.url}}" />
<meta property="og:image" content="{{@blog.cover}}" />
```

For the tag front pages:

```HTML
<meta property="og:site_name" content="{{@blog.title}}" />
<meta property="og:type" content="website" />
<meta property="og:title" content="{{meta_title}}" /> 
<meta property="og:description" content="{{meta_description}}..." />
<meta property="og:url" content="{{url absolute="true"}}" />
<meta property="og:image" content="{{image absolute="true"}}" />
```

For the author front pages:

```HTML
<meta property="og:site_name" content="{{@blog.title}}" />
<meta property="og:type" content="profile" />
<meta property="og:title" content="{{author.name}}" /> 
<meta property="og:description" content="{{author.bio}}" />
<meta property="og:url" content="{{url absolute='true'}}" />
<meta property="og:image" content="{{cover\*}}" />
```
\* This needs some sort of workaround to get an absolute url for the author cover rather than image

## Twitter Cards

The below represents proposed output for the homepage in `{{ghost_head}}` based on the [Twitter Cards](https://dev.twitter.com/docs/cards) specification.

Should be tested against https://dev.twitter.com/docs/cards/validation/validator

```HTML
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{{title}}" />
<meta name="twitter:description" content="{{meta_description}}" /> 
<meta name="twitter:url" content="{{url absolute='true'}}" />
<meta name="twitter:image:src" content="{{@blog.cover}}" />
```

For the tag front pages:

```HTML
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{{meta_title}}" />
<meta name="twitter:description" content="{{meta_description}}" /> 
<meta name="twitter:url" content="{{url absolute='true'}}" />
<meta name="twitter:image:src" content="{{image absolute="true"}}" />
```

For the author front pages:

```HTML
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{{author.name}}" />
<meta name="twitter:description" content="{{author.bio}}" /> 
<meta name="twitter:url" content="{{url absolute='true'}}" />
<meta name="twitter:image:src" content="{{cover\*}}" />
```

\* This needs some sort of workaround to get an absolute url for the author cover rather than image

**NB: all image meta tags should be conditional on whether the blog/author/tag has a cover image, if there isn't one, the `twitter:card` value becomes just 'summary'**

## Schema.org / JSON-LD

I don't believe any of these pages really fit into any particular schema so best to leave this out for now.

### PR DESCRIPTION
**Pull request by cobbspur**
closes #4677
- Tests if page is first page or paginated
- Adds relevant structured data to index/tag/author page
- Does not add structured data on paginated pages
- For author structured data, cover image overrides image
- blog cover image is made absolute by image helper
- Tests updated and additional tests for tag and author pages

### CODE REVIEW

**Comment by JohnONolan** [comment]
I think this needs to be rebased onto latest master for testing, also there's a typo in the commit message.

**Comment by cobbspur** [comment]
@JohnONolan PR updated if you can take for a test spin :)

**Comment by JohnONolan** [comment]
Notes:

* Should be no ellipses after blog.description (ever) (actually this seems to be a pre-existing bug everywhere in the structured data implementation. We should only use ellipses if the meta description is being populated by `{{excerpt}}` - but not if it's being populated by `{{meta_description}}`
* Seem to be completely missing JSONLD for http://schema.org/WebSite
* Tag archives archives should fall back to `{{description}}` (if populated) if no `{{meta_description}}` exists (just like posts fall back to excerpt - but again - no ellipses for this one)
* Tag archives also need JSONLD, probably http://schema.org/Series

**Comment by cobbspur** [comment]
@john, Thanks for the feedback,  but this issue has no mention of JSONLD. The current implementation for that is as previosuly specced so that really needs to be raised as new specced issue IMO.

I will start on the ellipses etc

**Comment by JohnONolan** [comment]
Then the issue was unfortunately written incompletely, but it is not a separate piece of work.

**Comment by cobbspur** [comment]
Well the point here @john is that there is no spec, the spec I am working on indicates JSONLD for the post page only, if that is to be on other pages now too then there must be a spec to say where it should appear and what content should be included, you clearly have ideas of what information you want to be included but you haven't conveyed those ideas anywhere. Should it be on the first index page now.. the archives, the author pages etc Is is the same subset of information as the post page, there are a gazillion things on schema pages, that's a lot of bloat so there should be a minimum subset of data.

For the ellipses issue, if I am taking it out from metadescription, is there really any need to add it to an excerpt fallback? And for tags if there is no description what are they falling back to or are they then to be left blank?

**Comment by JohnONolan** [comment]
>the spec I am working on indicates JSONLD for the post page only

As I explained, that was a mistake in the issue.

>there must be a spec to say where it should appear and what content should be included

There is a spec for this issue, and there was a spec for the previous issue. There is no such thing as a perfect spec, so if you're waiting for a perfect document that outlines every possible permutation and is completely infallible to later change, you may be waiting a while.

If you find part of a spec to be unclear or incomplete, you can quite simply ask for more information. That's how it works.

>you clearly have ideas of what information you want to be included but you haven't conveyed those ideas anywhere

That is literally exactly what is happening in this Pull Request. A PR is the starting point of an implementation, not the end.

>Should it be on the first index page now.. the archives, the author pages etc

This has not changed since the spec in the linked issue - "data below is only intended to be output on the first page, not /page/2/ etc of any of the listings." - which is why I didn't say anything about it needing to be changed.

>Is it the same subset of information as the post page, there are a gazillion things on schema pages

It is exactly the same as the data already specced in the linked issue for every single other service: site name, type, title, description, url, image. The JSONLD supports all of these, and the only ones which are not clearly identical are the attributes for "type" - which is why I included the information for exactly what those should be in the comment on this PR.

I see that I left out an exact type description for author page, so that should be - incase it's not clear - https://schema.org/Person

If you're unclear on any other attributes: ask.

>For the ellipses issue, if I am taking it out from metadescription, is there really any need to add it to an excerpt fallback?

Yes, there is - that's why I wrote it. A meta_description is 140 predetermined characters. An excerpt is ~140 arbitrarily trimmed characters. An ellipses is relevant to one and not the other.

>for tags if there is no description what are they falling back to or are they then to be left blank?

Yep, blank. Or rather: no description field at all.

**Comment by john** [comment]
Hi folks, would you mind not @john'ing me? That's my github username, I'm getting notifications every time you do :-)

**Comment by cobbspur** [comment]
Sorry John, a habit from other another platform

@JohnONolan Please have a look through this now, I think I understand what is needed now but a couple of things could be wrong, most notably the @context and @type properties.

We have 4 objects effectively for JSONLD,

post -> no changes here other than removal of ellipses for metadescription and addition to excerpt

tag -> '@context': 'http://schema.org',  
           '@type': 'Series',
           publisher: title,                                        Blog title
           url: url,
           image: coverImage                               (tagImage),
           name: self.tag.name,
           description: metaDescription               falling back to tag description

author -> '@context': 'http://schema.org',
                 '@type': 'Person',
                 publisher: title,                                Blog title
                 name: self.author.name,
                 url: authorUrl,
                 image: coverImage,                     Same as author image in post JSONLD
                 description: self.author.bio,
                 sameAs: self.post.author.website || null,

Looking through the docs, we could possibly have The Blog title for Author for tags if it has @type of Organization but that looked a little heavy handed.

One thing that does crop up a lot is sameAs attribute. For an author that is their website if they have one but I have left it blank otherwise, this is where global value for a blog's main website could be useful in the General Settings.

This is a WIP, the tests need updating but i want to know I am on the right track first.

**Comment by JohnONolan** [comment]
@cobbspur Looks perfect :+1: 

>One thing that does crop up a lot is sameAs attribute. For an author that is their website if they have one but I have left it blank otherwise

This sounds like the correct approach, too

**Comment by cobbspur** [comment]
@JohnONolan This should be good to merge now (pending travis)

**Comment by JohnONolan** [comment]
LGTM :+1: pending code review for merge

**Pull request merged**
