### PR TITLE
Update to PR 4852 ({{navigation}} helper)

### PR DESCRIPTION
**Pull request by ErisDS**
This is a small update / cleanup on top of PR #4852, to fix the tests and the [output notes](https://github.com/TryGhost/Ghost/pull/4852#issuecomment-74382386) by @JohnONolan 

Note: I have cleaned up the space around the `nav-current` class, but I wasn't certain if there was some other issue with it not working? I tested it out on various page types, both with and without a subdirectory, and here is the result:

If there's a case I've missed please let me know :)

### CODE REVIEW

**Comment by JohnONolan** [comment]
@ErisDS Does nav-current work on the homepage? That's where it was not working for me

**Comment by JohnONolan** [comment]
*Watches gif properly* - ok I see it works on the homepage there - it didn't on mine previously. :+1: looking good

**Comment by ErisDS** [comment]
Yeah, the thing is it appeared to work for me anyway, so it might be worth you taking this for a spin as I'm concerned I missed something.

**Comment by JohnONolan** [comment]
Tested - works for me now

**Pull request merged**
