### PR TITLE
Replace the current tag input with a selectize based input

### LINKED ISSUE #5648: Tag component behaviour bugs
Typing naturally in the new tag component doesn't always give a nice UX at the moment. Certain actions can result in duplicate tags. It also seems that the tag component loses focus after some actions, which means (for example) if you hit backspace after doing the wrong thing you can end up navigating 'back' away from the editor.

Here are a couple of reproduction cases:

- [ ] Duplicate tag entry

Reproduction steps 1:
- Start typing a tag that exists
- halfway through typing the tag, press the `TAB` key
- the existing tag is entered twice

**Note:** if you press `ENTER` or `,` halfway through instead, the correct thing happens. That is the half-written tag gets added as a tag, and added just the once:

Reproduction steps 2:

- Start typing a tag that exists
- once the tag is written in full, complete the tag by pressing the `TAB`, `ENTER` or `,` key
- the existing tag is entered twice

**Note:** clicking on the tag will result in just one tag being entered

- [ ] Lost focus

Reproduction steps 1:

- fill out the tag component with 2 tags using one of the methods which causes duplication above
- place the cursor at the end
- press backspace twice to delete the tag
- the component loses focus and pressing backspace again to delete the other tag will cause the `back` navigation to fire

Reproduction steps 2:

- start typing an existing tag
- complete the tag 
- the component loses focus

Whenever I'm typing in the component, adding or removing tags, the component should retain focus.

Whilst I'm raising things here, I think the intention is to get the `x` icon back for removing tags?

- [ ] Re-add `x` icon for removing tags

### PR DESCRIPTION
**Pull request by kevinansfield**
issue #3800, closes #5648
- uses ember-cli-selectize addon for the tag editing functionality in the PSM

### CODE REVIEW

**Comment by acburdine** [comment]
Haven't looked at how this works exactly, but at first glance seems great! This only thing I would say is to not rely on `model.tags` explicitly in the removeTag method, mostly because that behavior will be broken once Ghost updates Ember-Data to 2.0, because deleted records are no longer removed from hasMany relationships until a save occurs.

**Comment by kevinansfield** [comment]
> as deleted records are no longer removed from hasMany relationships until a save occurs.

I'm not sure that will be an issue here as we're explicitly removing the tag from the relationship then destroying (delete & save) the tag if it's a new record. In any case, do you have a reference where the ember-data 2.0 change is documented?

You've also made me question whether the relationship is restored to it's previous state if you exit the editor without saving, I'll have to add a test for that! Thanks.

**Comment by acburdine** [comment]
If it's a new record, sure it works fine. However, if it's an existing tag, it won't be removed from the array until the entire list of tags is saved. Here's the release notes for 2.0-beta.1 in which it explains the change: https://github.com/emberjs/data/releases/tag/v2.0.0-beta.1

**Comment by kevinansfield** [comment]
For existing tags we're not deleting anything just removing it from the association so this ember data change doesn't affect anything.

If instead we were actually deleting tags (we don't want to do this as other posts may still be using them) then we would need to put a filter in front of `model.tags` so we only pass non-deleted records to the tags input.

**Comment by acburdine** [comment]
Oh wow oops :confused: I completely missed that fact :smile: Please excuse my stupidity.

**Comment by kevinansfield** [comment]
No worries, it happens to all of us! 😄 Plus, you pushed me to check that we aren't leaving rogue tags all over the place - we're not, they're deftly swept away by `post.updateTags` that's initiated by the leave-editor modal so it's all good :)

**Comment by halfdan** [comment]
Looks and works great. There's a minor UI issue with the icon of the author field:

screen shot 2015-08-19 at 15 28 38

**Comment by kevinansfield** [comment]
Pushed a quick-fix for the author icon z-index issue.

The ember-cli-selectize addon currently pulls in the default selectize stylesheet so there is some slight inconsistency with the rest of the app - will that need addressing now or is it better to have something working that can be touched up later?

**Comment by JohnONolan** [comment]
@kevinansfield should be fine to get it in with defaults and then I'll do a second pass on it for styles

**Comment by JohnONolan** [comment]
Also LICEcaps for this type of PR are always welcome <3

**Pull request merged**
