### PR TITLE
Allow to use both lowercased and uppercased env variables

### PR DESCRIPTION
**Pull request by mahnunchik**
Hi @kirrg001 

It is for #8935

### CODE REVIEW

**Comment by kirrg001** [comment]
@mahnunchik Thanks! Could you please fix the lint error? Thanks :)

**Comment by kirrg001** [comment]
I think the nconf implementation is a little bit confusing and not sure we should merge this.

e.g. you have a config key in Ghost e.g. `useMinFiles`

```
useMinFiles=true node index.js
```

`nconf` adds `useminfiles` and `useMinFiles` to the env object, so this still works, [see]( https://github.com/indexzero/nconf/blob/master/lib/nconf/stores/env.js#L64), which results in Ghost having two keys in the config object (`config.get('useminfiles')` and `config.get('useMinFiles')` works).

**Comment by mahnunchik** [comment]
@kirrg001 it should not break the current code, but it will make it much more convenient to use environment variables.

**Comment by kirrg001** [comment]
> it should not break the current code

Yeah i know, but the concern i've raised is a about messing up our config object.

cc @ErisDS

**Comment by ErisDS** [comment]
I have been thinking about this. Using uppercase for environment variables is fairly standard, and therefore it would be _really_ good if we could support this.

Although this option in nconf is intended to make this supported, it is actually broken in the next version bump 0.8.5, as tracked in https://github.com/indexzero/nconf/issues/271. 

I also agree that this option has an unintended side effect. Almost every config value in Ghost has a snakeCased key, meaning most of them would be stored in memory twice. This is an unnecessary waste.

I've added a comment here: https://github.com/indexzero/nconf/issues/271#issuecomment-337667124 explaining this. 

I believe the way forward here is to come up with a better option/implementation in nconf, that doesn't impact memory usage. Once that is supported I'd be more than happy to accept a PR that upgrades nconf and adds support to Ghost.

I hope that makes sense. Going to close this PR as we aren't going to merge this approach.

**Pull request closed without merging**
