### PR TITLE
Started moving meta data fetching to functions.

### PR DESCRIPTION
**Pull request by jtwebman**
Started moving meta data fetching to functions.

issue #6186
- Moved asset helper logic to a asset url function.
- Created author image function to be used in ghost_head helper.
- Created author url function to be used in the ghost_head helper.
- Created canonical url function to be used in the ghost_head helper.
- Moved meta_description helper logic to a function.
- Moved excerpt helper logic to a function.
- Created an index in data/meta to be used in ghost_head helper to get all data.
- Created keyword function to be used in the ghost_head helper.
- Created modified data function to be used in the ghost_head helper.
- Created next url function to be used in the ghost_head helper.
- Created ogType function to be used in the ghost_head helper.
- Created previous url function to be used in the ghost_head helper.
- Created published data function to be used in the ghost_head helper.
- Created rss url function to be used in the ghost_head helper.
- Created schema function to be used in the ghost_head helper.
- Created structured data function to be used in the ghost_head helper.
- Moved meta_title helper logic to a title function.
- Moved url helper logic to a url function.
- Wrote tests for all the new functions

This is just the first step. I plan on refactoring the ghost head to use these new functions!

### CODE REVIEW

**Comment by novaugust** [comment]
!!!!!!!!!! 
all the tests.

**Comment by jtwebman** [comment]
@novaugust Was there an issue with the tests?

**Comment by kevinansfield** [comment]
@jtwebman No issue with the tests, it's a reference to http://knowyourmeme.com/memes/x-all-the-y, you may notice it popping up a lot around here :wink:

**Comment by novaugust** [comment]
I just noticed the huge line count, and had some mind blowage when I saw that it was pretty much all tests

**Comment by ErisDS** [comment]
> I just noticed the huge line count, and had some mind blowage when I saw that it was pretty much all tests

The best kind of pull request :tada: :cake: :sparkles:

**Pull request merged**
