### PR TITLE
Refactored migrations to use helpers

### PR DESCRIPTION
**Pull request by daniellockyer**
- this removes a lot of code duplication and streamlines how we do
  things across the codebase

### CODE REVIEW

**Comment by daniellockyer** [comment]
@allouis @tpatel This PR should be ready for review now. It's just some more refactoring of 'add column' and 'add table' migrations that I missed last time. I've double-checked the columns myself, but can't hurt for others to look too 😀 

I think it's easier to check [commit](https://github.com/TryGhost/Ghost/pull/12385/commits/286d91e9fc2823af6ffa19c39ba889d265e03418) by [commit](https://github.com/TryGhost/Ghost/pull/12385/commits/f0f65aef4d74883bcfa418bc6089711220973182) and you can keep context on what to check for.

**Review by tpatel — APPROVED** [review]
Looks good to me :clap:

**Comment by allouis** [comment]
Should the `addTable` helper be taking a static definition of the table at the point in which the migration was added, similar to our column migrations?

e.g.

```js
addTable('name', {
  column: {definitions: 'here'}
});
```

**Comment by daniellockyer** [comment]
@allouis Probably. When adding it to old migrations, should it be the column definition at the time the migration was created, or the current definition? 🤔 

For this PR, I'm just bringing the migrations in line with each other - I can look into the column definition thing in a future one. 🙂

**Comment by allouis** [comment]
> For this PR, I'm just bringing the migrations in line with each other - I can look into the column definition thing in a future one.

:ok_hand: Seems reasonable to me!

> When adding it to old migrations, should it be the column definition at the time the migration was created, or the current definition?

Good question: IMO it should be the column definition at the time the migration was created - as that captures what was intended when it was written - BUT if it's a huge pain in the arse, current definitions won't hurt.

**Review by allouis — APPROVED** [review]

**Pull request merged**
