### PR TITLE
i18n: return defaultLocale in config request

### PR DESCRIPTION
**Pull request by ololoken**
refs https://github.com/TryGhost/Ghost-Admin/pull/1017
- expose i18n locale for use in admin i18n support

### CODE REVIEW

**Comment by kirrg001** [comment]
Please respect our [contributor rules](https://github.com/TryGhost/Ghost/blob/master/.github/CONTRIBUTING.md). This PR does not refer to any issue or to any [forum](https://forum.ghost.org) discussion. Furthermore, it does not explain why you need to expose this information.

You can access your blog locale via the private settings endpoint. Closing.

**Comment by kevinansfield** [comment]
@kirrg001 I think the problem is that it was re-recreated after an earlier one was closed https://github.com/TryGhost/Ghost/pull/9634. It's part of the admin i18n PR here https://github.com/TryGhost/Ghost-Admin/pull/1017 which I haven't had a chance to review properly yet.

I'll re-open and update the issue description.

**Comment by kirrg001** [comment]
👍 Thanks for sharing.

**Comment by kirrg001** [comment]
@kevinansfield You are assigned and PR is > 3 months old. Could you pls review, reassign or close? Thanks 🙂

**Comment by kevinansfield** [comment]
Closing as per https://github.com/TryGhost/Ghost-Admin/pull/1017#issuecomment-420310841

**Pull request closed without merging**
