### PR TITLE
[HOLD] 🐛  https image urls if accessed over SSL

### LINKED ISSUE #8372: Unsecure image links when RSS accessed from HTTPS
Probable regression from PR #5189.

> When the RSS is accessed over SSL, the title feed links appropriately to https. However, the links to the posts and images still points to http.

### PR DESCRIPTION
**Pull request by kirrg001**
closes #8372

- https image urls if accessed over SSL (fix secure option for images)

@AileenCGN Could you please double check tomorrow morning?
I am afraid i have overseen a usage or a special hidden behaviour.

Thanks 👋

### CODE REVIEW

**Comment by kirrg001** [comment]
@AileenCGN 

We use `urlFor('image'...)` a couple of times in the code base e.g. for rss. And it looks to me it's working correct for rss. There are two cases: you access your blog via https and you have https configured as Ghost url. Both cases should work. Could you investigate the image url behaviour for HTTPS again?

**Comment by AileenCGN** [comment]
@kirrg001 Through the entire codebase, I couldn't find one example where `urlFor('image', ...)` is used in a way that would make sense to use the removed `data.image.secure` property. [Only in RSS](https://github.com/TryGhost/Ghost/blob/lts/core/server/data/xml/rss/index.js#L124), the data object contains a `secure` property, but not in a way, that it would be checked by `data.image.secure`, as it's provided in RSS as `data.secure`.

I reckon, the whole inconsistent usage of the `urlFor()` helper needs some review regarding the checks for `data.[context].secure`.

**Comment by kevinansfield** [comment]
Is this good to merge or does it need additional work/more testing?

**Comment by kirrg001** [comment]
@kevinansfield Still on hold. I will take over a little investigation tomorrow morning 👍

**Comment by kirrg001** [comment]
I had no time to investigate here. I would like to move this into the next LTS release, because i've double checked rss image urls for HTTPS blogs and they all looked correct. I would count #8372 as none critical right now. The outcome of the investigation here might be bigger, because it looks like the url utility and the secure flag handling is kinda wrong or very very hard to understand.

I will re-open #8372 for now and leave another comment there.

**Comment by ErisDS** [comment]
Closing this as I've also closed #8372.

**Pull request closed without merging**
