### PR TITLE
Update Ember to 1.12.1 and Ember-Data to 1.0.0-beta.18

### PR DESCRIPTION
**Pull request by acburdine**
No issue
- fixed "{{#each}}" helper in templates to use block syntax
- fixed deprecated ember.controller getter/setter function to use new syntax

### CODE REVIEW

**Comment by acburdine** [comment]
Currently this will still throw a deprecation error for some of the initializers. To fix this I need to change some of them to be instance-initializers, but I am going to put that in with the ember-cli update, as there's a resolver module update that needs to happen.

**Comment by jaswilli** [comment]
Can you split out the removal of the prototype extension usage into a separate piece of work? When there are library updates it's much easier to troubleshoot if they've been upgraded in isolation.

**Comment by acburdine** [comment]
@jaswilli Done.

**Comment by jaswilli** [comment]
Looks pretty good.  There are a handful of `typeKey` -> `modelName` conversions that were missed though (`git grep typeKey`).

**Comment by acburdine** [comment]
Those didn't initially throw deprecation errors....probably because they weren't used :smile:

**Pull request merged**
