### PR TITLE
Rewrite default private.hbs for new zelda styles

### LINKED ISSUE #5073: [Zelda] Private blogs login form & settings design
Main issue: https://github.com/TryGhost/Ghost/issues/4993

---

The password protected blogs feature has two pieces of design work needed to complete it: 

1) The design for the login page, which is going to live at `/private/`
2) The spec/design for the location of the password and message inputs somewhere in the settings panel.

### PR DESCRIPTION
**Pull request by acburdine**
closes #5073
- changes format to match new zelda layout

### CODE REVIEW

**Comment by acburdine** [comment]
@ErisDS To comply with the original spec in #5073, I had to abandon the `{{input_password}}` helper and instead hardcode in the class and placeholder that weren't available with the helper.

**Comment by ErisDS** [comment]
@acburdine The solution would be to add the extra `gh-input` class & the placeholder to the helper instead. We need to keep that helper as it's part of the theme API, and it needs to continue to work.

**Comment by acburdine** [comment]
@ErisDS @JohnONolan Anything else necessary for this PR?

**Comment by JohnONolan** [comment]
Should look like this now (below) -- which is just a case of removing a few lines of CSS that were customising the old form inputs.

**Pull request merged**
