### PR TITLE
Updated reading time and slugify helper

### PR DESCRIPTION
**Pull request by rshbhgrg**
refs #10618

- Removed duplicate calculation for reading time by using SDK method
- Removed safe string calculation using slugify in Ghost-SDK string package

### CODE REVIEW

**Comment by gargol** [comment]
@rishabhgrg saw this PR and it rang a bell for another one that the contributor closed right away (and I forgot about it) - https://github.com/TryGhost/Ghost/pull/10710 . It came out of this forum thread -https://forum.ghost.org/t/how-to-increase-reading-time/6958 . Maybe the `wordsPerMinute` parameter could be considered as an improvement (maybe follow up to this PR)? The naming should definitely be checked first though :)

**Comment by rishabhgrg** [comment]
@gargol That's a good suggestion, thanks for the heads-up. I think it makes sense to make wordsPerMinute configurable for calculating reading time, as it already takes an options hash for some other configuration. 

Also, I think the right place to extend it will be the SDK helper, so both Ghost/Ghost-Admin can use the same method. I'll make a not of it in existing issue and try to push a follow-up PR next monday 😄

**Comment by rishabhgrg** [comment]
@gargol Any idea why contributor closed the PR right away? 🤔

**Comment by gargol** [comment]
> @gargol Any idea why contributor closed the PR right away?

@rishabhgrg  No idea. I guess, it was his first ever code contribution on GitHub and didn't know how things work :thinking:

**Comment by rishabhgrg** [comment]
@gargol Cool, fwiw the PR was actually not too far off 😄 I have added a task on the parent issue [here](https://github.com/TryGhost/Ghost/issues/10618) to add the new param for reading time, we can reach out and add on the forum thread once that gets done. 😄 Thanks again for the heads-up

**Pull request merged**
