### PR TITLE
Added image counting to the {{reading_time}} helper

### PR DESCRIPTION
**Pull request by rkalis**
issue #9200
- Added imageCount utility, which counts images using an img-tag regex, amended from the general tag-regex found in wordCount
- Added this imageCount to the {{reading_time}} helper, adding 12 seconds to the reading time for every image
- The feature image is still counted as before

### CODE REVIEW

**Comment by ErisDS** [comment]
Hi @rkalis! Thanks for taking the time to implement this.

I wanted to flag up that the [article](https://blog.medium.com/read-time-and-you-bc2048ab620c) referenced in #9200 recommends an algorithm where it adds 12 seconds for the first image, 11 for the second, 10 for the 3rd and so on.

Would you mind updating your code to follow this pattern?

Thanks again!

**Comment by rkalis** [comment]
I have a different commit ready for adding a reading speed (wpm) option to the helper, would you like it in the same PR, or should I open a new one (is it even still a wanted feature)?

**Comment by rkalis** [comment]
I added the commit for the wpm helper, cleaned up the tests as well. Also made sure it has no conflicts with the changes made with the translatability changes.

**Review by kirrg001 — APPROVED** [review]
This looks good to me from the code perspective. Have not tested it.

**Comment by ErisDS** [comment]
Really sorry for dropping the ball on this. Code looks good 👍 However, I would prefer not to include the wpm option for now.

It was listed on the original issue as a potential future improvement, but it's the kind of thing I would only add if it was often-requested. So if it had been requested a lot, we would definitely add it, but so far I've not heard a single request for it.

Every option adds maintenance & documentation overhead, and therefore it's best not to add anything unless we're certain it will be used.

Other than that this is good to go IMO.

**Comment by rkalis** [comment]
No worries, I understand it's a big project, there's a lot that needs attention :).

Sounds logical to try to keep the amount of features limited to those that are actually being used. It won't be a lot of effort either to add it back in if it would be requested more often in the future 👍 .

I pushed a rollback for the wpm feature, while keeping the changes made to the tests.

**Comment by ErisDS** [comment]
Awesome, thanks for the understanding and for the help getting this implemented. I'll let @kirrg001 do the merge, releases are every Tuesday 😄

**Comment by rkalis** [comment]
## When your pull request to TryGhost/Ghost gets merged
Mr Open Source

On to the next 😉

**Pull request merged**
