### PR TITLE
Updated Traditional Chinese translations

### PR DESCRIPTION
**Pull request by brienjohn**
I think this is far better now that most wordings are natural and consistent except for “Send an email and say hi”, which I can’t find any equivalent in Traditional Chinese.

### CODE REVIEW

**Comment by daniellockyer** [comment]
@brienjohn This now conflicts with the changes in `main` - can you check whether your changes are still needed and rebase/close as appropriate? 🙂

**Comment by brienjohn** [comment]
@daniellockyer sorry I’m not really familiar with github’s interface. Can you tell me how I can check the changes and conflicts that you mentioned?

**Comment by daniellockyer** [comment]
@brienjohn If you look at the bottom, there's a "Resolve conflicts" button

CleanShot 2023-06-20 at 14 38 34@2x

and then there's a change you'll need to fix

CleanShot 2023-06-20 at 14 39 16@2x

**Comment by daniellockyer** [comment]
Thanks @brienjohn! 🙂

**Pull request merged**
