### PR TITLE
🐛 Fixed img-url to output relative url by default

### LINKED ISSUE #10595: img_url helper outputs absolute urls by default
Docs: https://docs.ghost.org/api/handlebars-themes/helpers/img_url/
Refs: https://github.com/TryGhost/Ghost/issues/10578

We've introduced a breaking change by mistake. With Ghost 2.0 the image url helper and the url helper always have output relative urls by default.

## Steps to reproduce:

1. Upload a feature image for a post
2. Use {{img_url feature_image}} in post template
3. See that it outputs absolute url by default

### PR DESCRIPTION
**Pull request by allouis**
closes #10595 

This includes a fair amount of cleanup as it was starting to get messy in there just applying new changes.

Review commit commit will be easier :+1:

### CODE REVIEW

**Comment by allouis** [comment]
(rebased to make sure commit msg was in past tense)

**Comment by kirrg001** [comment]
> Fixed img-url to output relative url by default

Isn't it "Fixed content mixed warnings"? Maybe both? 🤔

**Comment by allouis** [comment]
Hmmm, I guess this is indirectly responsible for mixed-content warning, but that _only_ happens if blog config is incorrect, and if a theme uses `absolute=true` then this doesn't fix any mixed content warnings. Was trying to be specific with the bug that was raised and the bug that was fixed.

If you think we should add it though I will - though I don't think we'll fit both descriptions in a 50 character commit :dancer:

**Review by kirrg001 — APPROVED** [review]
LGTM. Haven't tested it manually, but we can test tomorrow.

**Comment by kirrg001** [comment]
>  and if a theme uses absolute=true then this doesn't fix any mixed content warnings. Was trying t

But there is no bug with "absolute=true" or?

**Comment by allouis** [comment]
> But there is no bug with "absolute=true" or?

The mixed content warnings is not a bug caused by this, it's a bug caused by incorrect config, and it's highlighted when a site uses absolute urls - which this bug has caused for themes using the v2 api.

The mixed content warnings are caused by incorrect config (url set to http, when site is on https) and using absolute urls for content.

This fixes themes using absolute urls without explictly requesting them, but any theme using `absolute=true` would also see mixed content warnings if the config was incorrect.

**Pull request merged**
