### PR TITLE
Make read-directory ignore invalid package.json files

### PR DESCRIPTION
**Pull request by vadimdemedes**
Refs #5940, #5923

This PR makes refactored `read-directory` module backwards-compatible. Before this PR, `read-directory` would throw error, when invalid `package.json` file comes in the way. Now, it is simply swallowed.

**Note**: `parse-package-json` works as expected, throws error when file is invalid.

All warnings and errors regarding contents of themes/apps are handled by `validate-themes` module, so there's no degradation in functionality.

### CODE REVIEW

**Comment by vdemedes** [comment]
@sebgie all these errors are handled and displayed by `validate-themes` middleware, so they are visible to the user anyway :) If `parse-package-json` would log errors:

1. tests would have mixed output
2. users would see double messages (because of `validate-themes`)

    Could you please also remove the example theme ;-)?

Hmm, you mean to not create a fake theme in the test and have only invalid `package.json` in the temporary directory?

**Comment by sebgie** [comment]
Sorry for not being clear:

1. I use the same app as before and I don't see any output in the console. Theme warnings are shown but there is no warning for an invalid package.json in an app. Ghost doesn't error anymore but I would expect a warning for the invalid package.json.
2. Creating an example theme is fine but it should be removed after running the test.

**Comment by vdemedes** [comment]
@sebgie Updated, now removes only files created during tests.

**Comment by vdemedes** [comment]
Closing this PR in favor of #6021.

**Pull request closed without merging**
