### PR TITLE
Dockerfile dev

### PR DESCRIPTION
**Pull request by ashikkalavadiya**
While deploying latest on serve with Docker, it will be usefull if Ghost repository(master) contain Dockerfile and we can deploy latest code to our developing server.

### CODE REVIEW

**Comment by halfdan** [comment]
See #5335

**Comment by ashikkalavadiya** [comment]
@halfdan it will be usefull if we have it in our repo as other repo contains Dockerfile as well as Vagrantfile. i found 3rd party Dockerfile , but it dowlnoads last released version. not latest on master.
Thanks

**Comment by ErisDS** [comment]
As far as I understand, Docker doesn't make much sense for development. Happy to merge these into Ghost-Config but they don't belong in the main repo :)

**Comment by ashikkalavadiya** [comment]
I have referred some repos and found Dockerfile in main repo. such in one of our competitor [Automattic/wp-calyps](https://github.com/Automattic/wp-calypso)

**Comment by faddat** [comment]
Actually, this really does belong in the main repo, right in the root folder.  There are some reasons for this:

1) Ghost is a popular web application.
2) When the Dockerfile is in the root of the repo, hub.docker.com will let you make an Automatic build from that Dockerfile.  Once that is up, your docker image is kept up to date automatically.  
3) This improves the automation status of your project, making it easier to do things with at scale.

**Comment by kevinansfield** [comment]
@faddat I imagine if we were to move forward with Docker then it would be in a separate repository as there are many different ways to set up Ghost, especially in dev vs production. Discourse [has gone in a similar direction](https://github.com/discourse/discourse_docker)

**Comment by faddat** [comment]
That's true.  They have, I've got to admit that I really don't like their
direction, haven't from the time they started moving in that direction.
Long live NodeBB!

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Pull request closed without merging**
