### PR TITLE
✨ Implemented "resizer", a way to configure and work with different image sizes

### PR DESCRIPTION
**Pull request by tonydotgit**
Hi guys,

This is my latest improvement to my previous PR (#9789) which I decided to close in order to improve commits, the way how the solution was implemented, fixing tests issues and a couple more things.

I hope this improvement can be adopted by the community and improved as needed. I'e to say I'm not a NodeJS developer neither had worked with Ghost before nor contributing in "an important way" to the open source community, so this is a huge step for me and I'm open to your feedback. I like to help and would like to get my solution merged so if there's something wrong or have a better idea about the implementation let me know.

Before moving on, here's my checklist:

- - -
- [x] There's a clear use-case for this code change
   -  Issue #4453, I'm going to tag @ErisDS and @JohnONolan as based on the tagged issue I think both of you guys are interested in this.
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `npm test`)
- - -

Now, more about this proposed solution...

### CONFIGURATION:
There's a new property in the default configuration file, `resizer`, and it does have all the settings required to make this image resizing functionality works.

| Property    | Type    | Default Value   | Description                                                                                                                                                                    |
|-------------|---------|-----------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| defaultSize | string  | medium          | Defines the default size to be used while writing a post, the default value is "medium". If it has a null value or an empty string then the original size is going to be used. |
| enabled     | boolean | true            | If "false" given, then it wont attempt to create different image sizes.                                                                                                        |
| glue        | string  | -               | Is used to "join" filename + image size name.                                                                                                                                  |
| sizes       | object  | {*} (see image) | The collection of supported sizes, each size has 2 properties: height and width. You can define as many sizes as you want.                                                     |

Configuration

### WRITING A POST:
The process is the same, you click on upload image, select the image from your computer and that's it!
Writting a post

### THE IMAGES FOLDER:
Now you have a beautiful gallery to play with across your theme. You can pick any of the image sizes that fit better with index, loops, sidebars or any other section of your theme:
Images folder

## That's it. What do you think?
Please share your feedback so I can improve the "tool" and grow myself as developer.

### CODE REVIEW

**Comment by ErisDS** [comment]
Hi @TonnyORG, I really appreciate your interest in this and that you chose us for your first (and second) PR. 

As you've seen from the extensive discussion on the issue - image processing features are something we're very particular about in terms of how it should be designed and implemented. 

Right now our team is fully focused on details around Ghost 2.0 and not able to work with you on this (sorry, we are such a small team right now!), but we do have a sneaky plan to look at this subject very soon.

Watch this space 👀 🎉 

If you want to come talk to us about contributing & ways to get involved, you can always find us on forum.ghost.org.

**Comment by TonnyORG** [comment]
@ErisDS sounds good, I started there, and looked around the issues and forum and per John quote I felt like this was a good feature to work at:

> Omg I can't believe it has been 5 years and nobody has fixed this, what a joke
The way open source works is that people who care about an issue write code to solve it. If you care about this issue, please write some code to solve it.

However, I was wrong. Now I'm kinda lost again, but I like how Ghost is moving so can you point me to the place where I can actually find issues where my code is more guaranteed to be used?


Thank you!

**Comment by ErisDS** [comment]
Hey @TonnyORG, you're not wrong - and for clarity there's also nothing wrong with the code you've got so far. It's just unfortunate timing. With big features like this we go through a design process & right at this moment we both already have started a plan internally and don't have the time to translate that to a community project.

We have 2 labels on GitHub that are easy wins: "Good first issue" indicates something that anyone should be able to tackle, and "Help wanted" indicates the core team are unlikely to work on it.

When it comes to tackling something bigger - I'd highly recommend talking to us on the forum to see if we have capacity for a community project, get consensus on a spec & figure out what pieces need design input before jumping in.

**Comment by TonnyORG** [comment]
@ErisDS gotcha, it does make sense. Sorry for the misunderstanding. Hopefully, I can contribute in the next features, I'm more than happy to help grow up Ghost 😄

**Comment by TonnyORG** [comment]
Np at all @Camusensei and ty for your words, I also hope I can help to integrate this soon as this is a need for me as well.

**Pull request closed without merging**
