### PR TITLE
Enable Node 4.2 testing

### PR DESCRIPTION
**Pull request by jgillich**
- Do not error when node unsupported if engine-strict=false is set
- Default engine-strict=true via .npmrc
- Run engine check in preinstall script

issue #5821

### CODE REVIEW

**Comment by ErisDS** [comment]
Now we're on the right track :smile: 

The great thing about this, is its totally future proof - we can add allowed failures for node 5.x and start keeping track of changes in advance. 

I also really like the idea of using an env variable here, however I have a few concerns about using the npm engine strict config var:

1. the meaning/behaviour of engine-strict seems to keep changing, although if I'm understanding https://docs.npmjs.com/files/package.json#enginestrict correctly, then it was only the `engineStrict` option in `package.json` that was deprecated, the config flag/env var version is still active. Still, I'm not 100% how this will impact running `npm install ghost` and whether the behaviour in that case will be correct?

2. Do you know what versions of npm the config flag/env var version works for? The documentation is not versioned - I believe it is pretty much every version but it's a question worth considering.

3. I have a very strong aversion to adding dotfiles ... this is getting ridiculous (and code climate wants one too if we want to configure it properly): 

If it is the case that using the `engine-strict` npm setting is the only way to ensure correct behaviour for running both `npm install` inside the ghost project and running `npm install ghost`, then I agree it makes sense to use it.

If however, the `engine-strict` npm setting does not result in additional 'good behaviour' for the `npm install ghost` case (or worse causes problems), then I'd propose having a ghost-specific config flag something like `GHOST_NODE_VERSION_CHECK=false` instead as that eradicates complications from npm and the `.npmrc` file.

As an additional note, I'm working on writing up some docs on Ghost & node version support which can be output in the error message here to give people loads of useful info including what versions have what level of support, why, and how to override it.

**Comment by jgillich** [comment]
1. Ok, so setting `engine-strict` makes npm fail if it it can't satisfy `engines`. It does however only work for dependencies, not for the project that you're installing. What we're doing here is just checking it manually, there shouldn't be any side effects.
2. I found a mention of both the flag and environment variables in the 1.4 docs, I don't think we have to worry about that. :smile: But even if npm doesn't support it, the check will evaluate to false and it keeps installing. (This might actually be a bad thing, any errors in versionCheck are currently ignored).
3. npm doesn't really say if a value has been set manually. But if we really don't want another dotfile, we could just check the environment variable manually (but then we would miss other ways to set it, like ~/.npmrc and cli options).

**Comment by ErisDS** [comment]
> there shouldn't be any side effects

Can you verify this please?

> we could just check the environment variable manually 

Surely this would require it to be set manually?

I guess my underlying question is "What is the tangible benefit of using npm's engine-strict over using a Ghost-specific env variable?"

**Comment by jgillich** [comment]
> I guess my underlying question is "What is the tangible benefit of using npm's engine-strict over using a Ghost-specific env variable?"

Let me be a bit more clear, we **want** [engine-strict=true](https://docs.npmjs.com/misc/config#engine-strict). It makes npm verify that all dependencies support the engine the user is running. The reason to also use it for our startup check is that you would only have to set a single env variable to override it. This is all covered in npm's documentation, there's nothing obscure about this.

**Comment by ErisDS** [comment]
I understand what the setting does. We had `engine-strict=true` - and we were told by staff @ npm it was deprecated and to remove it: https://github.com/TryGhost/Ghost/pull/5114.We were also told it was causing problems when installing ghost from npm.

That's why I'm asking you to verify that this mechanism (using the same setting in a different way) isn't going to cause the same issues.

**Comment by jgillich** [comment]
Oh, `engineStrict` was actually removed because it was confusing and they felt package authors shouldn't have control over that setting: https://github.com/npm/npm/issues/7171#issuecomment-70608972

But that was never about `engine-strict` as in the npm config.

I really can't think of any issues this could cause. For apps that require ghost as a package, the .npmrc doesn't apply, so it's up to them to make sure the node version is supported.

**Comment by jgillich** [comment]
@ErisDS Here is the test output, checking all versions supported by us against all dependencies:
```
hawk 3.1.0 does not satisfy engine 0.10.0 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.1 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.2 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.3 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.4 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.5 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.6 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.7 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.8 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.9 (>=0.10.32)
boom 2.9.0 does not satisfy engine 0.10.0 (>=0.10.40)
boom 2.9.0 does not satisfy engine 0.10.1 (>=0.10.40)
boom 2.9.0 does not satisfy engine 0.10.2 (>=0.10.40)
boom 2.9.0 does not satisfy engine 0.10.3 (>=0.10.40)
boom 2.9.0 does not satisfy engine 0.10.4 (>=0.10.40)
boom 2.9.0 does not satisfy engine 0.10.5 (>=0.10.40)
boom 2.9.0 does not satisfy engine 0.10.6 (>=0.10.40)
boom 2.9.0 does not satisfy engine 0.10.7 (>=0.10.40)
boom 2.9.0 does not satisfy engine 0.10.8 (>=0.10.40)
boom 2.9.0 does not satisfy engine 0.10.9 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.0 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.1 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.2 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.3 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.4 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.5 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.6 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.7 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.8 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.9 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.0 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.1 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.2 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.3 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.4 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.5 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.6 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.7 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.8 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.9 (>=0.10.40)
hawk 3.1.1 does not satisfy engine 0.10.0 (>=0.10.32)
hawk 3.1.1 does not satisfy engine 0.10.1 (>=0.10.32)
hawk 3.1.1 does not satisfy engine 0.10.2 (>=0.10.32)
hawk 3.1.1 does not satisfy engine 0.10.3 (>=0.10.32)
hawk 3.1.1 does not satisfy engine 0.10.4 (>=0.10.32)
hawk 3.1.1 does not satisfy engine 0.10.5 (>=0.10.32)
hawk 3.1.1 does not satisfy engine 0.10.6 (>=0.10.32)
hawk 3.1.1 does not satisfy engine 0.10.7 (>=0.10.32)
hawk 3.1.1 does not satisfy engine 0.10.8 (>=0.10.32)
hawk 3.1.1 does not satisfy engine 0.10.9 (>=0.10.32)
boom 2.10.1 does not satisfy engine 0.10.0 (>=0.10.40)
boom 2.10.1 does not satisfy engine 0.10.1 (>=0.10.40)
boom 2.10.1 does not satisfy engine 0.10.2 (>=0.10.40)
boom 2.10.1 does not satisfy engine 0.10.3 (>=0.10.40)
boom 2.10.1 does not satisfy engine 0.10.4 (>=0.10.40)
boom 2.10.1 does not satisfy engine 0.10.5 (>=0.10.40)
boom 2.10.1 does not satisfy engine 0.10.6 (>=0.10.40)
boom 2.10.1 does not satisfy engine 0.10.7 (>=0.10.40)
boom 2.10.1 does not satisfy engine 0.10.8 (>=0.10.40)
boom 2.10.1 does not satisfy engine 0.10.9 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.0 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.1 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.2 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.3 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.4 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.5 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.6 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.7 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.8 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.9 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.0 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.1 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.2 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.3 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.4 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.5 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.6 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.7 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.8 (>=0.10.40)
hoek 2.16.3 does not satisfy engine 0.10.9 (>=0.10.40)
hawk 3.1.0 does not satisfy engine 0.10.0 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.1 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.2 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.3 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.4 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.5 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.6 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.7 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.8 (>=0.10.32)
hawk 3.1.0 does not satisfy engine 0.10.9 (>=0.10.32)
cryptiles 2.0.5 does not satisfy engine 0.10.0 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.1 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.2 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.3 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.4 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.5 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.6 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.7 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.8 (>=0.10.40)
cryptiles 2.0.5 does not satisfy engine 0.10.9 (>=0.10.40)
```

**Comment by jgillich** [comment]
Network requests in unit tests are ok? Sorry, there was no other way to get the node versions. And it's not what makes the test slow, 90% of the time is spend at `npm.ls`.  :unamused:

**Comment by ErisDS** [comment]
@jgillich Sorry if I gave you the wrong impression, I don't think this test is something that we should run all the time - I was thinking more along the lines of having a tool for checking this easily. It's not really a test because surely if it was, it would be failing right now?

As for going back to the discussion here about the engine-strict flag, I wanted to write up what was discussed in Slack...

Essentially, the engine-strict parameter is fine, unless you try to install ghost using `npm install ghost` on a version of Node <0.10.40, in which case you'll get a very unhelpful error message something like:

```
npm ERR! Error: No compatible version found: hawk@'>=3.1.0-0 <3.2.0-0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.1.0","0.2.0","0.3.0","0.4.0","0.5.0","0.5.1","0.5.2","0.5.3","0.6.0","0.6.1","0.7.0","0.12.0","0.12.1","0.12.2","0.13.0","0.13.1","0.14.0","0.15.0","1.0.0","1.1.0-pre","1.1.1","1.1.2","2.0.0","2.1.0","2.1.1","2.1.2","2.1.3","2.2.0","2.2.1","2.2.2","2.2.3","2.3.0","2.3.1"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at next (/usr/share/npm/lib/cache.js:698:17)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

The problem is that within our dependency tree, there are dependencies which have set their engines to things like `>=0.10.40` as seen in the test output above. It isn't actually causing us a problem, but in terms of complete version correctness, if we add engines-strict back as the default config, then we should also be either getting rid of those dependences or not supporting anything less than 0.10.40.

This gives us 3 options from here:

1. set our node version to > 0.10.40
2. leave it as is and add documentation for the issue as it only occurs for people npm installing
3. do something else

The problem with 1 is that we lose support for versions of node which people are currently running on with no warning, particularly a problem for people who use ubuntu LTS and are on node 0.10.25. The upgrade path would be:

- grab the latest ghost
- delete your old core folder and replace with the new one
- run `npm install --production`
- get an error and have to upgrade node or undo your Ghost upgrade.

This is just horrible, and we really need to provide a smooth mechanism for telling people it's time to upgrade node that's not halfway through an install. This needs to be done within the next few months but isn't realistic for right now.

The problem with 2 is that the error message that gets output from npm is confusing and says to report the error to npm. We had this situation [before](https://github.com/TryGhost/Ghost/pull/5114) and it resulted in folks from npm complaining to us because they were getting lots of complaints. I don't really want to end up there again.

So we're back to 3. 

As much as I think engine-strict is a nice solution, it really isn't viable right now.

**Comment by ErisDS** [comment]
Update: I spoke to the folks at npm. They advised that `.npmrc` has a security issue which means it is no longer included in packages as of [npm 2.14.1](https://github.com/npm/npm/releases/tag/v2.14.1) adding further complications, and also suggested that this is not the intended use case for engine-strict.

It seems to me that we need to define a custom env var that will allow users to disable the version check feature if we want to offer that.

**Comment by jgillich** [comment]
The test isn't failing because I commented that part out. But it might as well be a Grunt task?

So, custom env var it is. Hopefully I can get that done tomorrow.

**Comment by ErisDS** [comment]
> But it might as well be a Grunt task? (Edit: Just came to my mind that this could as well be a simple cli tool, nothing Ghost specific in there)

I was thinking it would make for a neat tool like npm-check :) https://www.npmjs.com/package/npm-check

Could also be wired up as a grunt task :)

> So, custom env var it is. Hopefully I can get that done tomorrow.

That would be awesome - 0.7.2 is almost ready now and it would be ideal to get this in as part of it.

**Comment by ErisDS** [comment]
Everything else for 0.7.2 is pretty much done now. @jgillich are you working on this? At the bare minimum I want to get the preinstall hook into the next version to reduce confusion :wink:

**Comment by jgillich** [comment]
@ErisDS All done now, sorry for the delay. My crappy Acer notebook died last Friday so I had to move everything to another computer.

**Pull request merged**
