### PR TITLE
[Hold] Hashtags 

### PR DESCRIPTION
**Pull request by ErisDS**
WIP PR to start adding hidden tag features. 

refs #6165 
- setup a config/labs flag ready for the hidden tags feature

### CODE REVIEW

**Comment by ErisDS** [comment]
@kevinansfield I set this up yesterday based on how the public API flag is done and noticed that setting `hiddenTags:true` or `publicAPI:true` in config.js doesn't auto-set it to true like it used to. It used to be that this was the quick more-devvy way to set the flag whilst working on a feature. It's not super important because the UI flag works just fine, but if it's a quick fix (something to do with injecting the config service?) it would be a nice to have.

**Comment by kevinansfield** [comment]
Updated with the checkbox behind the labs flag. It was a little trickier than it should have been as we're using a `feature` controller rather than a service which means that components can't use it directly - I'll create a new issue for that.

**Comment by ErisDS** [comment]
I'm having similar problems on the server side, we're using a labs flag to dynamically change things which are usually only ever changed on application load.

**Comment by ErisDS** [comment]
This PR now checks off the following items from #6165:

- Add labs flag for internal tags
- Add new checkbox to tag management screen to mark/unmark a tag as internal
- Filter the result from {{tags}} to not include internal tags
- Return a 404 from /tags/:slug/ for internal tags

The basic functionality for these tags is now complete, and this PR should be good to merge.

**Comment by kevinansfield** [comment]
I think there may be an issue with creating new hidden tags alongside a post...

PUT to `http://localhost:2368/ghost/api/v0.1/posts/13/?include=tags`:

```
{
    "posts": [
        {
            ...
            "tags": [
                {
                    "id": "1",
                    ...
                },
                {
                    "uuid": "ember2011",
                    "name": "new-hidden",
                    "slug": null,
                    "description": null,
                    "meta_title": null,
                    "meta_description": null,
                    "image": null,
                    "hidden": true
                }
            ]
        }
    ]
}
```

Response (note that the new tag's `hidden` attr has been ignored):
```
{
    "posts": [
        {
            ...
            "tags": [
                {
                    "id": 1,
                    ...
                },
                {
                    "id": 32,
                    "uuid": "b58110d1-cc74-41c1-97f0-3bc911fa53d2",
                    "name": "new-hidden",
                    "slug": "new-hidden",
                    "description": null,
                    "image": null,
                    "hidden": false,
                    "meta_title": null,
                    "meta_description": null,
                    "created_at": "2015-12-08T14:16:55.499Z",
                    "created_by": 1,
                    "updated_at": "2015-12-08T14:16:55.499Z",
                    "updated_by": 1,
                    "parent": null
                }
            ],
            "author": 1,
            "url": "/twelve/"
        }
    ]
}
```

**Comment by ErisDS** [comment]
@kevinansfield just to check - you're talking about new functionality you're adding and not a bug with this PR?

**Comment by kevinansfield** [comment]
Yeah, it's only affecting creation of hidden tags through the editor tags input. I had assumed the `hidden` field would be respected however a tag was created (direct/embedded) which was why I raised it here.

**Comment by ErisDS** [comment]
Ok, I know what's causing this, will look to get a fix sorted.

**Comment by ErisDS** [comment]
@kevinansfield got a fix added to this PR :)

**Comment by ErisDS** [comment]
Holding this til after the 0.7.3 release

**Comment by ErisDS** [comment]
Closing in favour of #6771

**Pull request closed without merging**
