### PR TITLE
Enter key submits form in setup step 2

### PR DESCRIPTION
**Pull request by cobbspur**
Issue #5315
- adds keyPress action to gh-input to activate parent controller action
- links action to gh-input for setup template
- removes html for unused password strength hint

### CODE REVIEW

**Comment by halfdan** [comment]
Looks good! :+1:

**Comment by jaswilli** [comment]
"enter" is a bound event, so instead of adding specialized logic into `gh-input` you could do:
``{{gh-input enter=(action "setup")}}` with no changes to needed to the `gh-input` component itself.

**Comment by cobbspur** [comment]
That would be nicer but I haven't been able to implement that. I am not quite sure what I am missing. There is a focusOut action so possibly it is clashing with that but the setup method does not called using if i use:
 `{{gh-input type="text" name="blog-title" enter=(action "setup") placeholder="Eg. The Daily Awesome" class="gh-input" autofocus="autofocus" autocorrect="off" value=blogTitle focusOut=(action "validate" "blogTitle")}}`

**Comment by cobbspur** [comment]
Okay so I think I have this working now. The problem I believe is that the `{{gh-input}}` components are already nested inside a `{{#gh-form-group}}...{{/gh-form-group}}` component.

If I add the setup action to the gh-form action controller such as `{{#gh-form-group action="setup"}}` then the gh-input helper does indeed call the controller action. 

PR updated.

**Comment by jaswilli** [comment]
I wouldn't expect that to be necessary.  I just tried adding `enter=(action "setup")` to the email address `{{gh-input}}` component and pressing enter inside the input runs the setup action as expected.

Maybe your browser was holding onto cached assets?  Can you try it again just to make sure?

**Comment by cobbspur** [comment]
ah okay quite possibly, i will take another look at it in incognito mode

**Comment by cobbspur** [comment]
updated PR. note to self: always test in incognito mode

**Pull request merged**
