### PR TITLE
Add trailing slashes on relative URL unless [.?#]

### LINKED ISSUE #6428: Navigation UI: Revisit auto-adding trailing slashes
The original implementation of the navigation UI automatically added trailing slashes to urls. However, this resulted in issues with knowing when to add them or not add them, and the behaviour got reverted amongst the many small issues we had with our automatic URL updating.

I think we now have it working much better, not changing URLs to be absolute Ghost urls when they're not meant to be. 

In a few, very strict cases, it would be good if we could auto-add the slashes again, to prevent 301 redirects from happening as much as possible.

If the URL entered:
- is relative to the Ghost blog (including any subdirectory)
- the URL entered doesn't include a `.`, `#` or `?`

Ideally, we'd have a way to verify that the URL entered is a valid URL for the blog, and long term, we'll likely add a way to do that, as well as autocomplete etc.

Short term, I think these 2 rules are enough to make it safe to add a slash, but it warrants a fair bit of testing.

### PR DESCRIPTION
**Pull request by halfdan**
closes #6428

### CODE REVIEW

**Comment by halfdan** [comment]
trailing-slash

**Comment by ErisDS** [comment]
Love the screencast - only example I don't see covered is what happens with absolute URLs to external sites?

**Comment by kevinansfield** [comment]
:+1: LGTM, would you mind adding a test for trailing slashes being added to non-trailing-slash input? Right now we're only testing against input that already has a trailing slash.

**Comment by halfdan** [comment]
@ErisDS Fair point :)

trailing-slash

**Comment by halfdan** [comment]
@kevinansfield Done

**Pull request merged**
