### PR TITLE
Translated remaining parts to German

### PR DESCRIPTION
**Pull request by ashikinoko**
Hello

I have translated the remaining parts into German.

Also, I have replaced the word "email" with "e-mail". In the previous translated version both "email" and "e-mail" were used. 

I am very much looking forward to be able to use Ghost in a full German version. Thank you for your valuable work. Let me know if I can be of further assistance with the German version. 

### <samp>🤖 Generated by Copilot at c7df06c</samp>

This pull request updates the German localization files for Ghost. It fixes some errors in `ghost.json`, adds a new file `portal.json` for the portal feature, and removes an unnecessary file `signup-form.json`. These changes aim to improve the user experience and maintainability of the German version of Ghost.

### CODE REVIEW

**Comment by daniellockyer** [comment]
@ashikinoko Would you be able to rebase this PR and fix the conflicts? 🙂

**Comment by ashikinoko** [comment]
Sorry, I am not a programmer. Could you tell me what exactly I have to do? I did the translations according to your youtube manual "How to help translate Ghost".

**Comment by ashikinoko** [comment]
Ok, I resolved the remaining conflicts. Hope it worked. Let me know if not.

**Comment by daniellockyer** [comment]
We've since merged a PR containing more German translations, so I'm going to close this PR as stale 🙂

**Pull request closed without merging**
