### PR TITLE
deps: jscs@2.6.0 & ember-suave@1.2.3

### PR DESCRIPTION
**Pull request by kevinansfield**
no issue
- fixes an error that popped up after ember-suave's `brocolli-jscs` dependency moved to `2.6.0` which duplicated some of the rules that `ember-suave` used to implement (https://github.com/dockyard/ember-suave/issues/84)

### CODE REVIEW

**Comment by ErisDS** [comment]
@kevinansfield not sure if you've seen this is failing on the lint task. Does Travis maybe need a cache clear?

**Comment by kevinansfield** [comment]
Nope, i'd missed that :smile: Caches cleared and job restarted

**Comment by ErisDS** [comment]
:disappointed: it's still not happy

**Comment by kevinansfield** [comment]
I think I need to revisit the grunt tasks, the one for linting isn't pulling in all the deps and so fails because `ember-suave` adds a jscs preset.

It only showed up in this instance because I re-ran the `lint` task by itself after clearing the caches, normally the previous jobs will have pulled in the deps and so it runs ok.

**Comment by kevinansfield** [comment]
Hmm, I'm stumped now, or we're still hitting cache issues. On that last run it complained about unsupported rules but the rules it's complaining about are included in jscs 2.6.0 which is included in the root package.json's `devDependencies`.

Unless... does travis use a global version of `jscs`? I had assumed it used whatever was installed locally but that might explain the confusion.

**Comment by kevinansfield** [comment]
Fixed! Noticed `grunt-jscs` was finally updated with the latest `jscs` version as a dependency. Whether it was due to that or travis' cache fairies aligning I'm not sure but it should be good to go now :smile:

**Pull request merged**
