### PR TITLE
Resize unsplash image width query to reduce download for smaller devices

### PR DESCRIPTION
**Pull request by isonaj**
Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [X] There's a clear use-case for this code change
- [ ] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test` and `yarn lint`)

More info can be found by clicking the "guidelines for contributing" link above.

I've seen this issue come up in a few places:
https://github.com/TryGhost/Casper/issues/644
https://forum.ghost.org/t/unsplash-support-for-img-url-size/7081

Apparently, it's been done, but I haven't seen it. This change is to apply the standard local size to external URLs that include a width parameter (such as Unsplash and Cloudinary).

### CODE REVIEW

**Comment by atakane** [comment]
Hi @isonaj, thank you for the code. It was a missing feature for years. 

This update somehow brakes /amp pages on 3.35.2. The server sends 404 for "amp" pages. I'm not familiar with how the pages rendered in Ghost, however, it might be related to "&amp;" replace code.

**Review by hc0503 — APPROVED** [review]

**Comment by deanp70** [comment]
Any update on this, this would be really awesome to incorporate into the project?

**Comment by rickynguyen4590** [comment]
I am so happy if we could merge this PR...I am newbie in Ghost, note sure I could help.

**Comment by ErisDS** [comment]
@isonaj Thank you for this PR! I apologise for the delay but this is on my list to review ASAP.

**Comment by ichitaka** [comment]
Hi, this issue has been closed, even though this feature is necessary to have a proper search engine ranking when using the Unsplash featured image.

**Comment by tobiaseichert** [comment]
I second that. Right now, the workaround is to download the image from Unsplash und upload it so image sizes will be applied properly.

**Pull request closed without merging**
