### PR TITLE
Replace unneeded lodash methods with native JS

### PR DESCRIPTION
**Pull request by halfdan**
There are a couple of lodash functions in use that are covered by native JavaScript. This PR replaces those uses.

Note: I left _.each untouched since we often use _.each on objects. Since this is some more work I'd like to hear feedback on this first. `.forEach` is only defined on arrays and our objects would have to be passed through `Object.keys` to be iterable.

### CODE REVIEW

**Comment by acburdine** [comment]
So in theory if enough of these are replaced, would it be possible to switch to modularized lodash builds?

**Comment by halfdan** [comment]
@acburdine Pretty sure that'd be possible.

**Comment by halfdan** [comment]
And once we drop v0.10 we may be able to drop lodash completely.

**Comment by ErisDS** [comment]
Is there a quantifiable or tangible benefit to our users here? 

Type specific changes like `Object.keys()` instead of `_.keys()` and `_.isArray` -> `Array.isArray` I get, to a point, as there's no need for the abstraction. 

With things like map/reduce, I think the power of lodash is the type agnostic concept of a collection.  It makes maintaining and refactoring code much simpler. There's a reduction in cognitive load that lodash provides as well, which I believe will disappear over time, but the fact that the functions all share a recognisable signature makes functional code easier to write IMO.

However, I'm fully on board that "great for users" > "great for developers" so if there are tangible benefits for users (speed, memory usage, etc) then I'm all for it.

In a similar vein, I don't _think_ (at the moment) modularised lodash builds are all that useful, given that lodash is a dependency of most of our major dependencies, we have to load it anyway.

I'm fully willing to be educated that I'm completely wrong on this, but I think taking the time to provide reasons for syntactic changes is necessary, otherwise they're just changes for changes sake.

**Comment by ErisDS** [comment]
Closing this as it's gone stale - might be worth opening an issue to discuss the changes?

**Pull request closed without merging**
