### PR TITLE
Improvement Czech translations

### PR DESCRIPTION
**Pull request by nesty156**
I updated the Czech translations for the new beta features. Czech colleagues, feel free to correct me grammatically, I will be happy.

### <samp>🤖 Generated by Copilot at 909b9fe</samp>

This pull request adds or updates the Czech translation for several files in the `ghost/i18n/locales/cs` directory. These files contain the strings used for various features in Ghost, such as comments, email, membership, and signup form. The purpose of this pull request is to provide localization support for Czech users and readers who want to use or interact with Ghost publications in their native language.

### CODE REVIEW

**Comment by daniellockyer** [comment]
Hi @nesty156 - please rebase and resolve conflicts 🙂

**Comment by nesty156** [comment]
Hi @daniellockyer I did merge it and resolve conflicts, but branch is out-of-date.

**Comment by lbednarik** [comment]
I just almost started the translation by myself from scratch :-D

Well, I really need this to be merged. The current Czech locale is insufficient.

**Comment by lukasbednarik** [comment]
@nesty156 I'm afraid you need to merge the `TryGhost:main` into your branch again. There's one change in `comments.json` file (new line `"{{amount}} more": "{{amount}} dalších",`).

Please make sure all tests pass after the merge.

We need to hope this will be merged before the Ghost team make another change.

**Comment by nesty156** [comment]
@royalfig , @daniellockyer rebased.

**Comment by sagzy** [comment]
Closing, as newer translations for Czech have been merged in by now

**Pull request closed without merging**
