### PR TITLE
fix: memory leak

### LINKED ISSUE #7189: Lot more requests since 0.9 - potential memory leak
### Issue Summary

Since updating to 0.9, our ghost instances are serving a lot more traffic:

screen shot 2016-08-09 at 09 03 45

Is this the expected behavior?

### Technical details:

* Ghost Version: 0.9
* Node Version: 4.x
* Database: PG

### PR DESCRIPTION
**Pull request by kirrg001**
closes #7189 

The version bump to bookshelf `0.10.0` and knex `0.11.10` in Ghost `0.9.0` has caused a memory leak. This PR fixes the memory leak. We also need to downgrade lodash, because of this issue #7158.

We will investigate further what is causing the problem, but with this PR everything should be back to normal memory usage.

### CODE REVIEW

**Comment by gergelyke** [comment]
thanks a lot! can we merge this and fix asap?

**Comment by kirrg001** [comment]
@gergelyke sure 👍

**Comment by ErisDS** [comment]
@gergelyke would it be possible for you to deploy this fix and confirm it resolves the issue for you?

**Comment by codybonney** [comment]
Thanks so much for digging into the memory leak issue!

**Comment by gergelyke** [comment]
@ErisDS sure thing! going to do it right now

**Pull request merged**
