### PR TITLE
Bookshelf Lodash Fix

### PR DESCRIPTION
**Pull request by acburdine**
Pushing this to ensure bookshelf doesn't break on upgrade. (I was having migration/timezone-related issues locally). SHOULD NOT BE MERGED 😉 

**EDIT: this is good to be merged because we're temporarily upgrading to lodash master before the release.**

### CODE REVIEW

**Comment by acburdine** [comment]
@ErisDS I think I know why the tests are failing. I made some breaking changes to the extends method in bookshelf, and it broke certain migration unit tests because the right methods weren't stubbed out, causing the sqlite database to actually try and handle the query, and because they are unit tests, it breaks.

**Comment by ErisDS** [comment]
Whoop all passing. I think it might be worth updating this to point to current bookshelf master? The release is coming in the next few days, but I think it would be good to get this merged in to a) help with testing and b) catch any runtime bugs. 

We can do a quick update to the release once it's done, but it's going to be the same commit + more changelog docs I think.

**Comment by acburdine** [comment]
Will do. I'll lock it to the specific master commit though just to avoid any issues with further commits should they arise before the release.

**Comment by acburdine** [comment]
@ErisDS done :)

**Pull request merged**
