### PR TITLE
Various post-repo-split cleanup

### PR DESCRIPTION
**Pull request by ErisDS**
no issue
- remove bower from dependencies, greenkeeper ignores & .editorconfig
- remove old custom jscs rule for ember

### CODE REVIEW

**Comment by ErisDS** [comment]
This is failing because the `bower install` command in `shell:ember:init` no longer has access to a bower.

@kevinansfield Should I add bower to the package.json in Ghost-Admin, or is there some other way to do this with a task inside of Ghost-Admin/Gruntfile.js & subgrunt that you're aiming for?

**Comment by kevinansfield** [comment]
My plan was to add `bower` as a dependency in Ghost-Admin and have a grunt task that does the dep installs + about page generation that can be called via `subgrunt`

**Comment by acburdine** [comment]
@ErisDS If the client ref is updated this should be good to go 👍

**Comment by acburdine** [comment]
just needs a rebase now :)

**Comment by ErisDS** [comment]
rebased & pushed

**Pull request merged**
