### PR TITLE
Disable pool by default for production server

### PR DESCRIPTION
**Pull request by bgervan**
Without this config, we get ECONNRESET after 10 minutes of inactivity on docker based setup.

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [x ] There's a clear use-case for this code change
- [x ] Commit message has a short title & references relevant issues
- [x ] The build will pass (run `yarn test` and `yarn lint`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by gargol** [comment]
Hi @bgervan. I'm not sure this is the best place to fix the issue you are having with your docker setup. It has never come up before and think it's best if you start with a discussion of this and possibly other alternative approaches on our community forum - https://forum.ghost.org/

**Comment by bgervan** [comment]
It has come up some thread, but no one sent a PR.
Why do you think it is not the best place?
I found this solution on the forum and I have burnt a few hours to figure out this solution. What is the default value for this config then? 
I am not sure, it won't come up for other architect too. For docker, it is come up because the wait limit for maria db is 10 minutes. I don't think that should cause a problem.

**Comment by gargol** [comment]
>It has come up some thread, but no one sent a PR.

@bgervan do you have a link to a thread where this issue was discussed?

**Comment by bgervan** [comment]
https://github.com/TryGhost/Ghost/issues/9739
This forum maybe connected to this issue as well:
https://forum.ghost.org/t/econnreset-with-pool-setting/7269/5

**Pull request closed without merging**
