### PR TITLE
Reload user after import

### LINKED ISSUE #5436: Bug: Cannot access user role after import
This is a bug that has been around for a while.

When you import a file in labs then navigate to any user (newly imported or existing) the role select box is missing: 

If you refresh the page it returns:

Notes: 
Roles used to be included by default when fetching users but now have to be specified with an include parameter - in which case it is worth bearing in mind for the intermittent loss of tags issue #4999 which also used to be included by default when  fetching posts. 

The labs controller action 'onUpload' uses self.store.unloadAll('post') and does the same for tags, role, users and settings which should clear the cache. Taking this out removes this bug but this is possibly just hiding a big somewhere else

Steps to reproduce:
1) Log into ghost as Owner or Administrator and navigate to /ghost/settings/labs 
2) Import a file (there are import fixtures in ghost you can use in /core/test/utils/fixtures/export/)
3) Once uploaded navigate to /ghost/settings/users and pick any non-Owner user
4) After confirming that role select box is missing, reload page

### PR DESCRIPTION
**Pull request by halfdan**
fixes #5436

### CODE REVIEW

**Comment by halfdan** [comment]
Random unrelated test failing.

**Comment by cobbspur** [comment]
Taken this PR for a test run, it certainly solves the bug of not being able to select the role. The only question is whether this is the best course to take following discussions here https://github.com/TryGhost/Ghost/pull/5424 @novaugust  and @jaswilli were taking about using window.location to reload the page entirely which also solves this issue

**Comment by halfdan** [comment]
@cobbspur That would make the page flicker (during reload) and not provide a good user experience. There's also Ember.Application.reset (http://emberjs.com/api/classes/Ember.Application.html#method_reset), but that would result in the same.

**Comment by cobbspur** [comment]
I completely agree but others do not and I don't have the greatest knowledge when it comes to the database etc to argue, if it is the best practice then this is what we will need to do. The option was to perhaps have a modal that displays information (as in that PR  above) with a confirm button that reloads the page which is not quite so jarring a user experience :)

**Comment by halfdan** [comment]
IMHO that's all we need after the `unloadAll`. Don't see any other reason to completely reload the app.

**Comment by ErisDS** [comment]
Seeing as this fixes the issue, let's merge it and if we run into more issues we can revisit.

**Pull request merged**
