### PR TITLE
Issue #5371 added support for GET endpoint `/tags/slug/:slug`

### PR DESCRIPTION
**Pull request by augbog**
I added supported for the new endpoint mentioned in issue #5371. I also added unit tests. I am not sure if I did the unit tests correctly and simply went off of the ones mentioned in the issue for the PostModel and PostAPI.

Let me know if I did it correctly please! From my understanding, the functionality already exists but the endpoint was simply missing.

### CODE REVIEW

**Comment by ErisDS** [comment]
Hi there @augbog, thanks for taking the time to work on this! You're correct that the functionality was already there and this just needed a route & some tests :+1: 

I'm not sure how, but your branch has picked up some other commits and there is also a lint error causing the build to fail. There are a couple of ways to fix up the extra commits - doing a straight `git rebase master` against the latest master *should* remove them in theory. Alternatively, the branch-dance should work - that is, create a new branch from master, cherry pick your commit, delete your `augbog-feature` branch, and then finally rename your new branch to `augbog-feature`. 

Either way, force pushing your branch will update this PR and if you need a hand just ask in the #ghost channel on slack. 

For fixing up lint errors, I recommend making your change & using `git add` and `git commit --amend` to add them to your existing commit. 

Hopefully this helps get the PR ready to merge!

**Comment by augbog** [comment]
Awesome thanks for the detailed advice! I believe I was able to make those changes and I ran `grunt jshint` to make sure there were no other lint errors. Let me know if there are other issues!

**Comment by novaugust** [comment]
@augbog When it passes on most boxes and just fails on a few, it's something transient with our tests - I restated them, and am sure they'll go this time

**Comment by ErisDS** [comment]
Hi @augbog really sorry, I just spotted that the commit message needs an update as well (this is otherwise good to go). Can you please update the message to fit [this format](https://github.com/TryGhost/Ghost/wiki/Git-workflow#commit-messages) - it's important for our changelogs & leveraging GitHub features. Thanks :+1:

**Comment by augbog** [comment]
Done! Hope that works! Sorry I should have read that documentation. I'll be sure to go through it.

**Comment by ErisDS** [comment]
Thanks for the quick update :+1:

**Comment by augbog** [comment]
No thank you! Hope to contribute a lot more :)

**Pull request merged**
