### PR TITLE
Create mikotea9

### PR DESCRIPTION
**Pull request by MikoTurkNode**
9tea

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ ] There's a clear use-case for this code change, explained below
- [ ] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

### CODE REVIEW

**Comment by markstos** [comment]
Please check existing PRs before creating new ones. This appears appear be a duplicate of #19742 and #19738 

So  far none of the authors of these three PRs have explained the value the change adds to Ghost.

**Comment by markstos** [comment]
Here's what I believe is happening:

The TEA project claims it wants to support open source developers using some kind of blockchain technology. Somehow, more popular projects will be rewarded more.

I believe people are rushing to add this file without explaining what it does because in each case it establishes their blockchain wallet as the "code owner" of the popular Ghost project, even though they aren't regular contributors. 

So in practice  the TEA project is not helping to support the Ghost project, but is instead causing a rush of self-serving PRs to be submitted to cash-in on other people's work.

Have I missed something? Because so far no alternate explanation for these tea.xyz submissions has been put forth. 

And this is fun: I tried searching for the meaning of the "codeOwners" field for TEA, but for a project that claims to support open source, they don't make the documentation of this file format easy to find. Yes, they include a "what is  this file" link in the file, but it doesn't take to you page that explains what the YAML means, it's just a page that  describes in hand-waving terms how their crypto project is awesome.

This why people hate on crypto.

**Comment by dtolnay** [comment]
@markstos it's worse than that: they specifically used your project as an example in an official _"How to register a project with tea"_ YouTube video. https://www.youtube.com/watch?v=no9t3rNGI_w

<br>

I also have a project named ghost, which is also getting spammed as a result (https://github.com/dtolnay/ghost).

<br>

In another place, they use Node.js as an example (https://tea.xyz/rewards-for-oss-contributions), so Node is also getting spammed.

@mxcl @michaelessiet

**Comment by mxcl** [comment]
Hey everyone. We’re really sorry about this.

Firstly, we are taking down the videos. Using real projects in the example videos was a huge mistake and we own it.

Secondly we are going to add verification steps to ensure we do not generate YAML for projects without proof that the user is a legitimate contributor.

For now we will remove ghost from the listing.

Our project genuinely wants to help open source and not hinder it and our efforts are entirely focused on that which ofc includes ensuring that this kind of malicious and despicable behavior ends as soon as possible.

Thank you for your understand and sincerely: I'm very angry about this, if it was happening to my projects I would also be incredibly unhappy about it.

**Comment by freundTech** [comment]
> Thank you for your understanding and sincerely: I'm very angry about this, if it was happening to my projects I would also be incredibly unhappy about it.

This did happen to your own project. You closed more than 50 pull requests adding `tea.yaml` files to https://github.com/teaxyz/white-paper on February 21st and 22nd (https://github.com/teaxyz/white-paper/pull/151, https://github.com/teaxyz/white-paper/pull/153, https://github.com/teaxyz/white-paper/pull/156, ...). Interestingly those PRs stopped appearing around the same time PRs against Ghost and other projects started appearing.

While I don't have any definitive proof, this **really** makes it seem, as if you used to use https://github.com/teaxyz/white-paper as the example project, then changed it to Ghost to not have to deal with those PRs any more.
You obviously knew about those problems and still went ahead with the project, which is at least grossly negligent, if not malicious!

**Comment by michaelessiet** [comment]
We didn't change the project in the examples to Ghost because it had always been Ghost which was a huge mistake on our part. We're getting spam PRs to our white paper repo(we had one opened 2 days ago) because these spammers assume that anything that is on GitHub is can somehow be registered. In our community we encouraged people to help translate the white paper for wider accessibility, that is why the spam started earlier than the rest.

We own this mistake and it's something we're actively working to stop from happening again. We'll be having a town hall on X next week in case any of you would like to join and voice your opinions on how we can do better. After all, the tea protocol wouldn't work without the open-source community.

**Comment by mxcl** [comment]
> Interestingly those PRs stopped appearing around the same time PRs against Ghost and other projects started appearing.

I applied moderation options to prevent non collaborators from submitting PRs.

> While I don't have any definitive proof, this really makes it seem, as if you used to use https://github.com/teaxyz/white-paper as the example project, then changed it to Ghost to not have to deal with those PRs any more.

We would never do such a thing, but even if we did, what incentive could we possibly have to upset the ghost project to this extent? I think Ghost is an awesome project and would love it if tea protocol could help its maintenance in the future.

> You obviously knew about those problems and still went ahead with the project, which is at least grossly negligent, if not malicious!

I really wish we *had* known this was going to happen so we could have avoided it.

An additional hurdle to creating `tea.yaml` is going live this morning. This sort of thing should stop, if not we will take further action. Again, we're very sorry about this: it's very far from our mission and goals that we created this problem.

**Comment by freundTech** [comment]
>  In our community we encouraged people to help translate the white paper for wider accessibility, that is why the spam started earlier than the rest.

> I applied moderation options to prevent non collaborators from submitting PRs.

> I really wish we *had* known this was going to happen so we could have avoided it.

That seems like a good explanation and definitely makes me think that it was non-malicious, however, I'll stand by my assessment that it was grossly negligent to continue with the public launch *after* you had to close ~50 spam PRs against your own repo (and changed repo settings to prevent further spam PRs).

**Comment by mxcl** [comment]
The launch had already happened. Our negligence was certainly in not anticipating that this would happen. I feel quite stupid  with hindsight and will regret it for a long time. Thanks for your understanding.

**Comment by markstos** [comment]
@mxcl A concrete thing that can be done is to make https://tea.xyz/what-is-this-file Actually go to someplace useful. 

The page it goes now does not mention YAML or show YAML. The page literally says nothing about the tea.yml file format. Put an honest statement that would help open source projects. Something like:

> If a pull request has been submitted to your project to add tea.yml by a contributor you don't recognize, it is likely an attempted scam. Whoever owns the `codeOwners` account may receive some reward from this project the future. That list of addresses should correspond to main contributors of this project. If they do not, scammers may attempting fraudulently  enrich themselves at your expense and those PR should be reported to Github as abuse. There's a "crypto scam" option in their abuse system.

If my description isn't perfect it could be because I've never seen the actual documentation for the `tea.yml` file format because the "What is This File" link has never gone some place useful!

**Comment by michaelessiet** [comment]
@markstos thank you for pointing that out. We just changed the page this link redirects to a few minutes ago. The new page, specifically header it redirects to now is https://docs.tea.xyz/tea/i-want-to.../begin-earning-tea-and-interact-with-the-protocol/registering-an-oss-project#what-is-the-tea.yaml-file-and-why-does-my-project-need-it

**Comment by markstos** [comment]
@mxcl @michaelessiet Whatever you are doing, the malicious PRs keep coming. Here's another: https://github.com/TryGhost/Ghost/pull/19788

**Comment by markstos** [comment]
@mxcl @michaelessiet To help manage the tea.xyz crypto abuse PR, could you create a Github Action for this project to use that checks to see if a PR touches a `tea.yml` file, and any supported variations, and then automatically rejects it with a customizable auto-reply that could be sent to users?

I think a number of open source projects currently burdened with tea.xyz crypto abuse PRs would find that useful.

**Comment by michaelessiet** [comment]
@markstos  I hope this helps

```yaml
name: Close PRs with tea.yaml changes or additions

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  close-pr:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get list of changed files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Check for tea.yaml
        id: check_for_tea
        run: |
          echo "Changed files: ${{ steps.files.outputs.all }}"
          if echo "${{ steps.files.outputs.all }}" | grep -q "tea.yaml"; then
            echo "::set-output name=detected::true"
          else
            echo "::set-output name=detected::false"
          fi

      - name: Close PR if tea.yaml is changed
        if: steps.check_for_tea.outputs.detected == 'true'
        uses: peter-evans/close-pull@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          comment: This pull request has been automatically closed because it contains changes to tea.yaml, which is not allowed. Please contact the repository administrator for more information.

```

**Comment by michaelessiet** [comment]
Hey everyone, here's the [link](https://x.com/teaprotocol/status/1765121621814059192?s=20) to the office hours I mentioned [earlier](https://github.com/TryGhost/Ghost/pull/19743#issuecomment-1969173995)

**Comment by markstos** [comment]
@michaelessiet Services like Github Sponsors, Open Collective and Patreon are already working for users who wish to reward to open source developers with donations. What value TEA might add beyond what they do has to be measured against the additional burden it generates with crypto abuse PRs.

**Pull request closed without merging**
