### PR TITLE
Decorate tag and author links with a class

### PR DESCRIPTION
**Pull request by ChuckM**
I needed to call out a different treatment for Author and
Tag links in my post-excerpt divs, this seemed to be the
most straight forward way to achieve that.

### CODE REVIEW

**Comment by ChuckM** [comment]
Sorry about missing the unit tests, I've added them in and squashed it back into a single commit to make it easier to review.

**Comment by JohnONolan** [comment]
@ChuckM is there a reason you aren't able to target these elements via their parent selectors?

**Comment by ChuckM** [comment]
@JohnONolan not independently. They are commonly bunched together, for example in the loop.hbs that is part of casper the footer has class post-meta which is on both of the <a> tags. I could have fixed this by trying to figure out how to have both the author link and the tags links in separate parent selectors (I style the tags to be links but not "styled" which is to say they don't pop out as links but if you mouse over them you can click them) while the author continues to be a more visible link with an unvisited/visited value. Giving them their own class gave them a selectability that worked for my theming efforts that I was not able to produce otherwise.

**Comment by JohnONolan** [comment]
What about wrapping the author link in a span? Or modifying the output of the {{tags}} helper?

**Comment by ChuckM** [comment]
Sure you could put it in a span, or if you were feeling like it you could write more complicated handlebars code to extract out the individual tags or the individual author. There are lots of ways to address it. That said, if you have the ghost code automatically class them, then it makes tweaking a theme a lot simpler for a lot of users, it is a few lines of CSS rather than trying to recreate that part of the theme that gives them the styling on tags or authors that they want.

**Comment by JohnONolan** [comment]
All very true - but what you're (maybe?) overlooking is that a PR to master doesn't just affect your blog, it affects everyone. So what you're suggesting would quite literally output hundreds of thousands of extra classes on tens of thousands of blogs - all to enable one use-case which is already solvable at a theme-level.

For that reason I don't think this is something that's going to be right for core at present. Typically we try to keep what Ghost outputs as light as possible. We certainly don't always do a good job of it; but that's the goal.

**Comment by ChuckM** [comment]
@JohnONolan  I appreciate the feedback. I did actually evaluate it with respect to its compatibility with other ghost blogs[1] and, caveat they didn't already come up with a class named 'author-link' or 'tag-link' they would be unaffected except for the small number of additional characters in the generated output. And this change allows for greater flexibility in theme customization by non-expert users, and opportunities for theme designers to differentiate their themes in a consistent and maintainable way. 

If one analyzes your argument John it comes down to, "we won't make our software easier to use [2] for theme designers and bloggers because we don't understand how changes in our system propagate to users of our system."  and by implication you indict me with not understanding how changes to your system propagate to your end users as well. I do not agree with that assertion. I would encourage you to use  your work arounds for styling these elements in the theme of your choice and to render them with both a default build and a build with this change. You can then verify for yourself that the output is pixel for pixel identiical with or without the presence of class identities on these anchors.  If you've have time left, then make the styling changes to achieve the same look using the anchor identities. Then evaluate which choice makes the most sense for your users.

Either way, I appreciate the work the Ghost team has done in providing this software and it is a credit to everyone involved that it is so easy to understand and customize. I wish for you nothing but success.

[1] my methodology was to use some of the free themes and try them on altered and unaltered versions of Ghost.

[2] Granted I made the claim that it is easier to use of the anchors for authors and tags have classes but this philosophy seems to be at the root of classes on all of the elements in Ghost so I felt it reasonable to stipulate this as an agreement in our points of view. I admit that it is entirely possible that it is your position that it is not easier to style an element that does not have an identity.

**Comment by JohnONolan** [comment]
Chuck, I think you misunderstood. I really wasn't talking about compatibility of adding more classes, I was talking about LoC. Thousands of extra classes on tens of thousands of blogs quite quickly adds up to millions of additional LoC in everyone's source for a use-case which is very vague (nobody has ever requested it before) and already solvable in multiple ways without this change.

We care a great deal about the ease of use and convenience of Ghost for theme developers - but ease of use and convenience (including speed) for end-users will always come first.

Your analysis of "my argument" is disappointingly flawed and flippant. We've been at this for 2+ years now. I think we have some idea how the decisions we make propagate to end users. In fact it is that very knowledge which is the predominant factor in not making this change.

It's very easy to wander into someone else's codebase and start pointing at all the things you think are wrong based on 5 minutes of looking at the code. It's a lot harder to actually try to maintain a codebase for the largest majority of use-cases with full historical context, rather than just the most vocal few.

**Comment by ChuckM** [comment]
@JohnONolan , if you have time I would find it helpful to understand this statement:

> I was talking about LoC. Thousands of extra classes on tens of thousands of blogs 
> quite quickly adds up to millions of additional LoC in everyone's source for a use-case 
> which is very vague (nobody has ever requested it before) and already solvable in 
> multiple ways without this change.

These are the places where I'm confused, and really I'm trying to learn here, there is no criticism implied here at all. You mention, "Thousands of extra classes", and I can't see the 'thousands'. The change adds only two classes `author-link` and `tag-link`.  So I don't understand how you got to 'thousands' here.  Later we talk about installs and thousands makes sense to me, but here I see just the two classes, which allow you to select out just the anchor's for either the author or tags in a given section. 

I do understand "tens of thousands of blogs", which is basically every where Ghost installs, Each install would get two additional classes they could potentially (but not  be required to) style. After all if you have a class and no related CSS it doesn't change in the document.  But you used this "tens of thousands of blogs" with the clause "adds up to millions of additional LoC in everyone's source" and that I am not understanding at all. When I was testing this change it was adding about 28 characters for each author and tag anchor, that was the sum total of the difference in the output. Which leaves me scratching me head where the millions of lines of additional "LoC", which I interpreted as "Lines of Code",  comes from.  Can you clarify where all the lines of code are coming from? This change, for  99.99% of the people using it initially, doesn't add any lines of code to their blog, at worst it adds another 20 - 30 characters for each time they use the `{{author}}` or '{{tag}}` helper. The change does create a general parameterized way in core for helpers to specify such a class on any anchors they emit.

The last thing which I wondered about was this part of that comment, "for a use-case which is very vague (nobody has ever requested it before)". I don't understand the characterization of 'vague', you and others I've talked to seem to understand the request very easily as "I would like to style the author and tag anchors." as being pretty clear. I could certainly understand that you don't know what motivated me to want that capability, but would you agree that the request itself was clear? The second part is just a timing thing I suspect. Wordpress has a variety of methods to style author and tag links, perhaps I was the first who brought it to your attention (and certainly the only one who has suggested code to enhance it), this is a capability of other blogging platforms though so I am pretty sure it will come up again.  

I'm totally cool with you not taking the PR, but I am frustrated in my attempts to understand you logic. And I would like to _understand_ the logic so that in the future if I there is something which I've done in my version of the code which I think would be generally helpful, I'll have a better shot at predicting whether or not you guys would want to it.

**Comment by JohnONolan** [comment]
Certainly! No problem. So here's a hypothetical:

A blog has a post, and that post has 1x author and 5x tags. So we have 6 additional classes per post. 

So let's say a blog has 200 posts and paginates at 5 posts per page

We have the classes on posts - 6x200 = 1200
We have classes on posts in index archive = 1200 more classes
We have classes on the same posts in the tag archives = 1200 more classes
Classes on the same posts in author archive = 1200 more classes

So far we're at 4,800 new classes for one blog, now multiply that by the 30,000 blogs we know if in the wild and we're at 144,000,000 new classes in everybody's source code.

If we're going to add *that* many classes - we want at least 60% of all blogs to really desperately need these classes, cause otherwise we're adding a LOT of overhead out there.

So - wherever possible - we *try* to allow themes to define classes rather than Ghost. That way classes are define just for their one use-case, and not for everybody. If anything, we already output too many classes - but we've tried to make it flexible by putting them in dedicated helpers like `{{body_class}}` and `{{post_class}}` so that they can be removed without impacting on any functionality.

Hope that helps clarify

**Comment by ChuckM** [comment]
Thanks @JohnONolan I really appreciate it, I wonder if you could tell me what you call a "class" in your hypothetical. I have been using the term to mean a [CSS selector][selector], which in this case is named `author-link` (or `tag-link`). Using the the selector definition the class name `anchor-link` is put on to every author anchor and the class name `tag-link` is put on to every tag anchor. (well ones that use the standard `{{author}}` and `{{tag}}` built in-helpers. So in your example with 1x author and 5x tags, I would be inclined to say it includes exactly two new classes. The blog author could style them with:
```
a.anchor-link {
    font-family: Modern Script, sans serif;
}
```
For example and the anchors to the author would now all look like a "signature" rather than just text. That would happen through out the blog whether it had 1 post or 20,000 posts. It sounds like you are imagining that the code was creating a new class based on all of the parent container names (like `author-link post meta` or something, which it did not do. Just the two I mentioned. I could certainly see that if the class name were generated algorithmically the numbers would be higher than two. I think you'll agree though that the maximum number of different class selectors you would generate in a blog that way would have been related to the number of containing sections though (post, post-meta, etc) rather than the number of pages / authors / tags on a blog.

[selector]:https://developer.mozilla.org/en-US/docs/Web/CSS/Class_selectors

**Comment by JohnONolan** [comment]
Your PR didn't add CSS. It added HTML. I am talking about the number of HTML classes added across every instance of a tag or author helper across a site. Which is exactly the numbers that I just gave you.

**Comment by ChuckM** [comment]
Ok, I think we're close to the same page, you are correct, my PR changed the HTML, my contention was that the change **enabled** the author and tag anchor links to by styled with CSS.  

You could always change it in your theme of course. I remain convinced that its a nice default for the helper of course. Thanks for taking the time to explain.

**Pull request closed without merging**
