### PR TITLE
fixed redirect to /undefined after authorization in private blogging app

### PR DESCRIPTION
**Pull request by ololoken**
no issue

### CODE REVIEW

**Comment by allouis** [comment]
Thanks for contributing! I'm off for the evening but I'll check this out tomorrow for you :relaxed:

**Comment by kirrg001** [comment]
Did that code change in the last 6 month or so? Or was it always like that?
@allouis

**Comment by kirrg001** [comment]
@allouis

**Comment by allouis** [comment]
Not that exact code, but the module did

**Pull request merged**
