### PR TITLE
🛠  Improve existing gulp tasks

### PR DESCRIPTION
**Pull request by aileen**
refs #7427
- Deleting the `built` or `dist` directory doesn't result in an error, when running `gulp dev`
- Adds default task as `gulp dev`
- Adds abbreviations for the repositories in `gulp setup` task (`--ghost` -> `-g`, `--admin` -> `-a` and `--casper` -> `-c`) to type less 😊
- Installs dependencies on `gulp dev`, if called with `--deps` or `-d`
- Sets `verbose` option nodemon to default (=`false`) to have less unneccessary logging.
- Will do a delete of all dependencies and install them again ('FFS'), if `gulp deps` is called with a force flag.
- Will update submodules not matter what, if `gulp submodules` is called with a force flag. Calling `gulp submodules` without the force flag will only update/initiate the submodules, if the folders don't exist.
- Better logging messages and sequential task handling.
- Removes `gulp-shell` as dependency, as this is on gulp's blacklist
- Refactors code, that used `gulp-shell` to use `child_process.exec` or `spawn` instead.
- Exits properly if node crashes

---

Tasks available after this PR:
- `gulp server`: Starts a nodemon server with livereload of the ghost core only. No client build here.
- `gulp dev`: [ --deps | -d ] Starts development mode for Ghost, incl. client build and livereload for both. Will also update the submodules if the directories are missing. If called with with `--deps` flag, it will install client and core dependencies.
- `gulp submodules`: [ --force | -f ] Will update the submodules, if directories are missing. Will update no matter what, if called with force flag.
- `gulp deps`: [ --force | -f ] Will update client and core dependencies. Does a fresh install of both (delete, cache clear and install) if called with force flag.
- `gulp setup`: </br>[ --ghost | -g 'branch' or 'pr/1234' ]
      [ --admin | -a 'branch' or 'pr/1234' ]
      [ --casper | -c 'branch' or 'pr/1234' ]
      [ --force | -f ]
      Takes various - optional - parameters. If called without parameters, this task will update submodules first (if directory doesn't exist) and then install client and core dependendies.
      If called with branch 'master', submodules will be updated.
      Calling with the force flag will do a clean install of the dependencies.
      There's no autocomplete for branchnames at the moment 😔
      To check out a PR (e. g. `--ghost pr/7444`), it is necessary, that you add an additional fetch line in the `.git/config` file for each repository: `fetch = +refs/pull/*/head:refs/remotes/upstream/pr/*`. See https://dev.ghost.org/easy-git-pr-test/ for further information.

### CODE REVIEW

**Comment by kirrg001** [comment]
Could we exit the gulp process, when node crashes?
Nodemon always tries to restart node.
Example case: your database version is not compatible.

**Comment by kirrg001** [comment]
I can confirm it works now. Having no `built` folder and running `gulp dev` - nice 👍

**Comment by kirrg001** [comment]
One weird thing is: when deleting my `built` folder and then running `gulp dev`, the server starts. i go to `/ghost` and then the server restarts 4 times, then it says `Build successful - 4685ms.`. That is a long time to wait.

**Comment by kevinansfield** [comment]
> One weird thing is: when deleting my built folder and then running gulp dev, the server starts. i go to /ghost and then the server restarts 4 times, then it says Build successful - 4685ms.. That is a long time to wait.

Initial ember build can take a long time, sometimes on my machine it's >1min. Not sure there's much that can be done there although the ember-cli devs are working to reduce the initial build times.

**Comment by AileenCGN** [comment]
Well, this is ready for review and merging 🎉

**Comment by kirrg001** [comment]
Is it possible to improve the output?
`gulp` (or `gulp-util`) prints with timestamp and in between we can find some Ghost logs.
Maybe it's possible to hide all the `gulp` task print outs and enable them if needed with an option.

gulp output

**Comment by kirrg001** [comment]
When you add `CI=false` as env parameter, you can get the ember `Building...` output.
You can pass `env` into `spawn`.

**Comment by kirrg001** [comment]
If the Ghost server dies and an ember build process is active in background, we would like to kill the process, because you see a Ghost error and you read it, then suddenly the big build output of Ember occurs and `nodemon` then restarts Ghost a couple of times. Until the error is printed out again. 

Maybe we can avoid this by calling `ember.kill()` (on the child process) when Ghost crashed.

**Comment by AileenCGN** [comment]
Regarding optimising the output. After a first research, I don't think it's possible.  But I will do some more research and implement it in another PR, if there is a way...

**Pull request merged**
