### PR TITLE
Correct reset passsword screen markup and styles

### LINKED ISSUE #5524: Reset Password screen has incorrect markup/styles
Reached by clicking the link in the Reset Password e-mail.

screen shot 2015-07-07 at 15 13 27

### PR DESCRIPTION
**Pull request by elliotblackburn**
closes #5524
- added styles for reset page, similar to sign in but seperated for easy change further down the line.
- changed markup to reflect added css changes.
- remove html classes that are redundant.

### CODE REVIEW

**Comment by BlueHatbRit** [comment]
Build seems to have failed due to issue #5373. Is there a way to proceed with this before PR before that issue is resolved or will it have to wait until it's resolved and then have a re-build issued?

**Comment by ErisDS** [comment]
@BlueHatbRit it's just a random build failure, you don't really have to worry unless they're all red :wink:. I've restarted the job that failed and it should be ok now.

**Comment by BlueHatbRit** [comment]
@ErisDS Awesome, thought it may be that simple. Thanks :)

**Comment by ikhattab** [comment]
@BlueHatbRit I didn't have the chance to check yet, but can you please rename `reset.css` to something less may be `reset-password.css` the name misleads me I thought it's the reset stylesheet

**Comment by BlueHatbRit** [comment]
@ikhattab That hadn't actually crossed my mind for some reason, good point. I'll sort that this evening.

**Comment by JohnONolan** [comment]
These styles are identical (0 difference) to .gh-signin -- so there's really no sense in duplicating them. The only change needed here is to the HTML file to pull in the correct elements and classes.

**Comment by BlueHatbRit** [comment]
@JohnONolan That makes sense, I was torn between creating a new set for them or not to enable easy change later but you're right. I'll make that change and let it rebuild.

**Comment by JohnONolan** [comment]
Thanks for making those changes :)

**Pull request merged**
