### PR TITLE
Upgrade should.js to version 8.2.1 (Issue #6448)

### LINKED ISSUE #6448: Upgrade should.js dev dep to the latest version
We're currently on version 6.0.3 of [should.js](https://github.com/shouldjs/should.js). 

Version 7.0.0, which is the next version, has [breaking API changes](https://github.com/shouldjs/should.js/blob/master/History.md#700--2015-06-18). 

These mean that all assertions, such as `should.be.true` must now be function calls: `should.be.true()`, this is to prevent false positives.

Instructions on how to upgrade the codebase for 7.0.0 and 8.0.0 can be found [on the should wiki](https://github.com/shouldjs/should.js/wiki/Breaking-changes). (I don't think there are any changes in 8.0.0 that affect us).

The work to check through and make sure all of our tests use the same correct is a fairly big task. The should docs say there's no real need to migrate a live project, but I think we could benefit from the newer version of the API being more consistent.

### PR DESCRIPTION
**Pull request by cameronviner**
This PR upgrades should.js to the latest version (issue #6448), it also introduces the packages should-http and should-sinon. I have gone through all of the tests and updated them to comply with the new version of should.js, I believe I have covered everything but if I have missed something or there are any changes you would like made let me know and ill have a look as soon as I can.

Couple of things to point out here that I am not sure is 100% correct due to my unfamiliarity with the code base:

The test case 'should not be able to get a slug for an unknown type' in core/test/functional/routes/api/slugs_spec.js (line 137) was changed from checking the response does not exist to checking for a errors property on the response. 

In the test core/test/unit/middleware/spam-prevention_spec.js some of the assertions were changed from `error.should.be.a.UnauthorizedError;` to checking for a specific errorType such as `error.errorType.should.eql('TooManyRequestsError');`

closes #6448
-upgraded should.js to the latest version (8.2.1)
-Changed the tests so that they comply with the breaking changes introduced in the new version of should.js
-Installs the package should-http so should.be.json() can be used
-Installs the package should-sinon so that should.be.calledOnce() can be used

### CODE REVIEW

**Comment by ErisDS** [comment]
@cameronviner Woah!!!! Thanks for doing this :grin: :+1: :cake:  You must've been sick of typing parenthesis by the end of it :smile: 

It looks absolutely spot on, and I really appreciate the thorough PR message. It's great that this has already caught some bugs in our tests, and they all look like they've been resolved correctly.

As a result of this change, there are some extra lines which can be removed:
- The first is the jshint declaration which appears at the top of many files ([example](https://github.com/TryGhost/Ghost/pull/6464/files#diff-4fdea5016a3fba533bd0f17df90299bcR2)), which looks like `/*jshint expr:true*/` - this was because the should expressions looked weird & jshint complained. The new syntax solves this, so the declaration isn't needed.
- The second is the `should.equal(true, true);` line ([example](https://github.com/TryGhost/Ghost/pull/6464/files#diff-4fdea5016a3fba533bd0f17df90299bcR8)), which was also another fix for jshint & should's weird syntax.

If you have time to update this PR to also remove those lines where present, that would be awesome.

There's one other minor detail, which is entirely my fault:

When updating a dependency, we have a commit title convention, which you can see in action here: https://github.com/TryGhost/Ghost/commits/master

`deps: packagename@x.x.x`

Just for the first line, so that the message in the changelog is consistent - the rest of the commit message can stay the same, and you can fix this with `git commit --amend` and then a force push.

This isn't actually documented anywhere, I usually put a note in the issue - sorry!

If you only have time in the near future to update the commit message and not make the other changes, that would be just fine too. It'd be good to merge this quickly so it doesn't get conflicts, and the second set of changes can come after.

**Comment by cameronviner** [comment]
Hey @ErisDS , I've changed the commit message now so it doesn't block this PR and introduce conflicts. I'm happy to pick up the rest of the changes though (sometime this weekend), would you like me to raise a issue for that?

**Comment by ErisDS** [comment]
Yes please, raising an issue would be great :+1:

**Comment by ErisDS** [comment]
Note: I've raised the followup issue #6505

**Pull request merged**
