### PR TITLE
[WIP] Removed `post.page` from Content API v2

### PR DESCRIPTION
**Pull request by kirrg001**
refs #10335

[ci skip]

### CODE REVIEW

**Comment by kirrg001** [comment]
@ErisDS _This PR is not fully finished_, but i went over the usages of `post.page` and `this.page` in the code base to eliminate it completely to be able to remove `.page` from the Content API v2.

Maybe if you have some minutes, could you pls double check if i have forgotten a place or/and if you see any problems with this approach? This solution was for me right now the only logical conclusion 😁If you have other ideas, pls share them

We should probably also remove `.page` it from the `pages` endpoint? Otherwise it's inconsistent. Would do in a separate PR.

**Comment by ErisDS** [comment]
>  We should probably also remove .page (and .status) from the pages endpoint? Otherwise it's inconsistent. Would do in a separate PR.

For anyone else reading this, as far as I am able to tell this is already done. Is anyone able to reproduce?

**Comment by allouis** [comment]
@ErisDS Local testing says this is done

**Comment by rishabhgrg** [comment]
Ditto, works well locally!

**Comment by kirrg001** [comment]
Closing. v2 still exposes the _page_ attribute. We might want to return a new type field e.g. `type: page|post` in v3.

**Pull request closed without merging**
