### PR TITLE
[WIP] Updates nodemailer to 1.3.2

### LINKED ISSUE #5095: Cannot send invitation
Cannot send mail from `http://blog.mydomain.com:2368/ghost/settings/users/` to user with newer TLD. (in this case, .rocks)

```
/home/ghost/ghost/core/server/mail.js:95
                if (data.error.errno === 'ENOTFOUND') {
                              ^
TypeError: Cannot read property 'errno' of null
    at EventEmitter.<anonymous> (/home/ghost/ghost/core/server/mail.js:95:31)
    at EventEmitter.g (events.js:180:16)
    at EventEmitter.emit (events.js:95:17)
    at DirectMailer.<anonymous> (/home/ghost/ghost/node_modules/nodemailer/node_modules/directmail/lib/mailer.js:138:30)
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:147:9)
```

### PR DESCRIPTION
**Pull request by javorszky**
Fixes #5095
- Updates nodemailer from 0.7.x to 1.3.2
- Adds `nodemailer-wellknown` for common SMTP configs
- Adds `nodemailer-stub-transport` for development
- Adjusts tests so they work with changes in nodemailer
- (hopefully) fixes the timeouts

### CODE REVIEW

**Comment by javorszky** [comment]
Implemented the updated `stub-transport` and enabled that fix, also rebased on top of https://github.com/TryGhost/Ghost/commit/2165153d97c1d8ec38cedfeb44ecf2b005d9ff74

**Comment by jaswilli** [comment]
> Adds nodemailer-wellknown for common SMTP configs

Is this being used at all?  I'm not against it in principal, it's just I don't see it being used anywhere in the diff and it doesn't look like nodemailer pulls it in implicitly?

**Comment by javorszky** [comment]
Yes. When your config looks like:

```
mail: {
    options: {
        service: "Gmail",
        auth: { ... }
    }
}
```
the standard nodemailer smtp package will try to include the `wellknown` package to look up server settings and whatnot. See https://github.com/andris9/nodemailer-smtp-transport/blob/master/src/smtp-transport.js#L5

`smtp-transport` is part of the package.json for nodemailer, but wellknown isn't.

**Comment by jaswilli** [comment]
Ok, good to know.  I see that `nodemailer-wellknown` is in the package.json for `nodemailer-smtp-transport`.  In that case, do we need to include it in Ghost's package.json?

**Comment by javorszky** [comment]
Huh, missed that. Thanks. Will fix, no, Ghost does not need wellknown then. :)

**Comment by ErisDS** [comment]
Unfortunately, as far as I can see, we [cannot upgrade](https://github.com/andris9/Nodemailer#upgrade-warning) to Nodemailer v1 :disappointed: 

We depend on all of the mail functionality being included in nodemailer directly, and many of our existing users are using configurations for sendmail or amazon SES that would break without warning or explanation if we make this upgrade.

In the future, we could make the upgrade and then automatically install an app which adds SES or sendmail back if that configuration is used, but right now we have no way to manage the upgrade path for those users.

In the meantime, I suggest trying to get major bugs back-ported to the 0.7 branch of nodemailer?

**Comment by javorszky** [comment]
Hm... sadtimes. Okay, the main change then is to allow for the long TLDs. Do you know of any others, or should I go through the commits on the 1.x branch and cherry pick / adopt them?

**Comment by jaswilli** [comment]
Is there anything that can happen here or should we close this for now?

**Comment by javorszky** [comment]
@jaswilli as far as I know, this can be closed (done that just now)

**Pull request closed without merging**
